objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-8429: This field will be used for holding Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2969 Comma separated field to capure all Internal Business segments related to the opportunity product</description>
        <inlineHelpText>This is a calculated field to list all the Internal Business segments for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Internal Business Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <description>SFDC - 1346 field to capture sub business line related to the products</description>
        <inlineHelpText>This is a calculated field to list all the sub business lines for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Sub Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2624 Internal Business Segment field for Sales Product Reporting</description>
        <inlineHelpText>For Sales Product Reporting</inlineHelpText>
        <label>Internal Business Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubBusinessLine__c.object
<CustomObject>
    <description>SFDC1-2170 : This holds Sub Business Line related to Products</description>
    <label>Sub Business Line</label>
    <nameField>
        <label>Sub Business Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestProductSearchControllerLWC.cls
//-----------------------------
// @author: Pankhuri Jain
// @date: 25th Apr 2022
// @description: Test class for ProductSearchControllerLWC 
//------------------- 
@isTest
public class TestProductSearchControllerLWC {
	
    @isTest
    static void testGetProductDetails() {
        //Creating test data
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',true); 
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.DiscountThreshold__c = 10;
        Product2 p2 = TestUtility.createProduct('Test Product 2', false);
        p2.DiscountThreshold__c = 12;
        insert new List<Product2>{p1,p2};
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
        insert new List<PricebookEntry>{pbe1,pbe2};
        
        //Creating product schedules
        String currentFiscalYear = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <= TODAY AND EndDate >= TODAY].FiscalYearSettings.Name;
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, currentFiscalYear, '1 Year', currentFiscalYear, p1.Id, false);
        ProductSchedule__c ps2 = TestUtility.createProductSchedule(2223.23, currentFiscalYear, '3 Years', currentFiscalYear, p2.Id, false);
        ProductSchedule__c ps3 = TestUtility.createProductSchedule(2323.23, currentFiscalYear, '3 Years', String.valueOf(Integer.valueOf(currentFiscalYear)+1), p2.Id, false);
        ProductSchedule__c ps4 = TestUtility.createProductSchedule(2423.23, currentFiscalYear, '3 Years', String.valueOf(Integer.valueOf(currentFiscalYear)+2), p2.Id, false);
        insert new List<ProductSchedule__c>{ps1,ps2,ps3,ps4};
        Test.startTest();      
        List<productSelectorWrapperClass> assertProd = ProductSearchControllerLWC.getProducts ('','Test Product','', '', '','', '', '','','','');     
        System.assertEquals(2, assertProd.size(),'check size');
        OpportunityLineItem oli1 = TestUtility.createOpportunityLineItem(testOppy.id, pbe1,false);
        insert oli1;
        List<string> productId = productSearchControllerLWC.getProductsAlreadyInOppy(testOppy.Id);
        System.assertEquals(1, productId.size(), 'check size');
        System.assertEquals(p1.Id, productId[0],'check recordId');
        Test.stopTest();
     
    }
    
    @isTest
    static void testGetProductDetails2() {
        //Creating test data
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',true); 
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.DiscountThreshold__c = 10;
        Product2 p2 = TestUtility.createProduct('Test Product 2', false);
        p2.DiscountThreshold__c = 12;
        insert new List<Product2>{p1,p2};
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
        insert new List<PricebookEntry>{pbe1,pbe2};
        
        //Creating product schedules
        String currentFiscalYear = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <= TODAY AND EndDate >= TODAY].FiscalYearSettings.Name;
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, currentFiscalYear, '1 Year', currentFiscalYear, p1.Id, false);
        ProductSchedule__c ps2 = TestUtility.createProductSchedule(2223.23, currentFiscalYear, '3 Years', currentFiscalYear, p2.Id, false);
        ProductSchedule__c ps3 = TestUtility.createProductSchedule(2323.23, currentFiscalYear, '3 Years', String.valueOf(Integer.valueOf(currentFiscalYear)+1), p2.Id, false);
        ProductSchedule__c ps4 = TestUtility.createProductSchedule(2423.23, currentFiscalYear, '3 Years', String.valueOf(Integer.valueOf(currentFiscalYear)+2), p2.Id, false);
        insert new List<ProductSchedule__c>{ps1,ps2,ps3,ps4};
        Test.startTest();         
        List<productSelectorWrapperClass> assertProd = ProductSearchControllerLWC.getProducts ('Data Lake Platform/Auto','Test Product','2000040046', 'Automotive Insights', 'Auto: Data Lake','Auto Data Lake Subs', 'Online Access', 'Data Lake Platform/Automotive','Data Lake','Automotive','Subscription');     
        OpportunityLineItem oli1 = TestUtility.createOpportunityLineItem(testOppy.id, pbe1,false);
        insert oli1;
        System.assertNotEquals(null, oli1.id,'Record Id cannot be null');
        List<string> productId = productSearchControllerLWC.getProductsAlreadyInOppy(testOppy.Id);
        Test.stopTest();
     
    }
    
    //-----------------------------
    // @author: Pankhuri Jain
    // @date: 26th Apr 2022
    // @param: null
    // @description:Test method for ProductSearchControllerLWC.getIbsBsSubBsLines 
    //------------------- 
    @isTest
    static void testGetIbsBsSubBsLines() {
        //Creating test data
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1', true);
        BusinessLine__c bl = New BusinessLine__c();
        bl.Name = 'Automative Insights';
        bl.Status__c = 'Active';
        insert bl;
        SubBusinessLine__c sbl = new SubBusinessLine__c();
        sbl.Name = 'Auto: Advisory';
        insert sbl;
        SubBusinessLine__c sbl2 = new SubBusinessLine__c();
        sbl2.Name = 'Auto: Commercial';
        insert sbl2;
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.InternalBusinessSegment__c = 'Automotive';
        p1.BusinessLine2__c = bl.id;
        p1.SubBusinessLine__c = sbl.id;
        insert p1;
        Product2 p2 = TestUtility.createProduct('Test Product 2', false);
        p2.InternalBusinessSegment__c = 'Automotive';
        p2.BusinessLine2__c = bl.id;
        p2.SubBusinessLine__c = sbl2.id;
        insert p2;
        Map<String, Map<String, List<String>>> result = productSearchControllerLWC.getIbsBsSubBsLines();
        System.assertNotEquals(Null, result.size(), 'Size of IBS should not be Null');
    }
    
}