objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-383 This field serves as a lookup to the Country object</description>
        <inlineHelpText>Read-only field, updated indirectly by a change of Company&apos;s Billing Country/Territory</inlineHelpText>
        <label>Account Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country/Territory Code</inlineHelpText>
        <label>Country/Territory Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchUpdateAccountCountry.cls
/**
* @author Tran-Vu Tran
* @date 22nd April 2019
* @description SFDC-1381 test class for BatchUpdateAccountCountry
* @return void
* @companyname IHS Markit
*/
@isTest
private class TestBatchUpdateAccountCountry {
    
    private static testMethod void testBatchUpdateAccountCountryClass() {
        
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);

        Account testAccount = TestUtility.createTestAccountWithAddress('Test Account', '1234 Testing Street', 'Test City', '', country.CountryCode__c, true);

        Test.startTest();
        
        Account assertAccount = [Select Id, AccountCountry__c from Account where Id =: testAccount.Id];
        System.assertNotEquals(null, assertAccount.AccountCountry__c,
                               'Verifying AccountCountry__c lookup value is populated by trigger');
        
        testAccount.AccountCountry__c = null; // set AccountCountry__c = null to simulate when trigger is turned off
        update testAccount;
       
        BatchUpdateAccountCountry batchJob = new BatchUpdateAccountCountry();
        Id batchId = Database.executeBatch(batchJob, 1);
        
        Test.stopTest();
        
        assertAccount = [Select Id, AccountCountry__c from Account where Id =: testAccount.Id];
        System.assertNotEquals(null, assertAccount.AccountCountry__c,
                               'Verifying AccountCountry__c lookup value is populated by BatchUpdateAccountCountry batch job');
    }

}