objects/Account.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-10407 : Creating this field to bypass the validation rule using Apex Code.</description>
        <inlineHelpText>This field will be used to byPass the Validation Rules in Apex.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-8429: This field will be used for holding Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Businessline__c</fullName>
        <description>SFDC-1346 field to store comma separated values of business lines derived from contract line items</description>
        <inlineHelpText>Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6439 This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</description>
        <inlineHelpText>This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentYearTotalFirstYearValueSub__c</fullName>
        <inlineHelpText>Sum of first year value in USD for all active SUBSCRIPTION products (existing + new)</inlineHelpText>
        <label>Current Year total First year value-Sub</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentYearTotalFirstYearValue__c</fullName>
        <inlineHelpText>Sum of first year value in USD for all active products (existing + new)</inlineHelpText>
        <label>Current Year Total First Year Value</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MobilitySalesNew__c</fullName>
        <inlineHelpText>The total first year value of products, with status = new</inlineHelpText>
        <label>Sales New</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MobilitySalesRenewal__c</fullName>
        <inlineHelpText>first year value of all the products = existing</inlineHelpText>
        <label>Sales Renewal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PreviousFiscalYearOpportunityLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will take you to the Last fiscal year or the most recent Oppy link</description>
        <inlineHelpText>This field will take you to the Last fiscal year or the most recent Oppy link</inlineHelpText>
        <label>Previous Fiscal Year Opportunity Link</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Previous Fiscal Year Opportunity Link)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store primary contact name at Opportunity record level.</description>
        <inlineHelpText>To store primary contact name at Opportunity record level.</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorYearTotalFirstYearValueSub__c</fullName>
        <inlineHelpText>Last fiscal year sum of first year value in USD for all active SUBSCRIPTION products (existing + new). Using current FX rate</inlineHelpText>
        <label>Prior Year total First year value-Sub</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PriorYearTotalFirstYearValue__c</fullName>
        <inlineHelpText>Last fiscal year sum of first year value in USD for all active products (existing + new). Using current FX rate.</inlineHelpText>
        <label>Prior Year total First year value</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesLostSubOnly__c</fullName>
        <description>US-5856761 : Opportunity - Mobility Metrics Section - Lost Sales (2 Fields)</description>
        <inlineHelpText>Sum of first year value in USD for all products which were initially up for renewal and which are now showing as lost</inlineHelpText>
        <label>Sales Lost Sub Only</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesLosttransonly__c</fullName>
        <description>US5856761 : Opportunity - Mobility Metrics Section - Lost Sales (2 Fields)</description>
        <inlineHelpText>We want to know the value of what we lost that was up for renewal. This should be the value of all &apos;Transaction&apos; product codes moved to lost that were previously existing (on a prior year opportunity and the value should be the value of the prior year codes at the current year FX rate)</inlineHelpText>
        <label>Sales Lost trans only</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesNewSubscription__c</fullName>
        <inlineHelpText>Sum of the first year value in USD for all new subscription product. We use the product type to define sub vs non recurring</inlineHelpText>
        <label>Sales New Subscription</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesPriceIncreaseDecrease__c</fullName>
        <defaultValue>0.00</defaultValue>
        <inlineHelpText>Sum of the first year value of all existing products - sum of the first year value in USD for all subscription product from last fiscal year (which are not lost in current FY). Using current FX rate.</inlineHelpText>
        <label>Sales Price Increase/Decrease</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/TestBatchUpdateMobilityMatrics.cls
//@author: Arshad Qureshi
// @date: 14th July 2023
// @description: Test Class for TestBatchUpdateMobilityMatrics
//---------------------------------------------------------------------------------------------------------------------------
@isTest
public class TestBatchUpdateMobilityMatrics {
@testSetup
    static void createRecords() {
 
        // CREATE ACCOUNT
        Account acc1 = new Account();
        //acc1.parentid = 'Test Parent'; 
        acc1.Name = 'Test Account';
        acc1.BillingStreet = 'No Lane';
        acc1.BillingCity = 'Hyderabad';
        acc1.BillingState = 'Telangana';
        acc1.BillingCountry = 'India';
        acc1.BillingCountryCode = 'IN';
        acc1.DataGovernanceStatus__c = 'Approved';
        insert acc1;
        
        // CREATE CONTACT
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc1.Id;
        con.Email = 'test-contact@sfdc.com';
        INSERT con;
        
        // CREATE OPPORTUNITY
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = Date.newInstance(2022,12,31);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        opp.AccountId = acc1.Id;
        opp.ContractStartDate__c = Date.newInstance(2021,8,1);
        opp.BusinessLine__c = 'Automotive Insights';
        opp.ByPassValidation__c = true;
        opp.StageName = '1-Sales Qualified';
        opp.PreviousFiscalYearOpportunityLink__c = null ;
        opp.ContractEndDate__c = Date.newInstance(2023,8,1);
        INSERT opp;
        
        // Create Contract 
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id orderFormContractId = ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, opp.Id);
        Contract testContract = new Contract(Id = orderFormContractId);
       
        // CREATE OPPORTUNITY CONTACT ROLE (OPPORTUNITY PRIMARY CONTACT)
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.OpportunityId = opp.Id;
        ocr.ContactId = con.Id;
        ocr.IsPrimary = true;
        ocr.Role = 'Opportunity Primary Contact';
        INSERT ocr;
        
        opp.PrimaryContact__c = ocr.Id;
        Update Opp;
        
        
              
        // Create 1st Renewal Opportunityhttps://ihsmarkit--ea.sandbox.my.salesforce.com/_ui/common/apex/debug/ApexCSIPage#
        Opportunity oppy1 = TestUtility.createRenewalOpportunity(acc1.Id, testContract.Id, true, false, false, true);
        oppy1.ContractStartDate__c = Date.newInstance(Date.today ().year () - 1,8,1);
        oppy1.CurrencyIsoCode = 'USD';
        oppy1.PreviousFiscalYearOpportunityLink__c = opp.Id;
        oppy1.BusinessLine__c='Automotive Insights';
        oppy1.ContractEndDate__c = oppy1.ContractStartDate__c + 1;
        oppy1.MobilitySalesNew__c = 0.0;
        oppy1.MobilitySalesRenewal__c= 0.0;
        oppy1.SalesNewSubscription__c = 0.0;
        oppy1.SalesPriceIncreaseDecrease__c=0.0;
        oppy1.CurrentYearTotalFirstYearValue__c = 0.0;
        oppy1.CurrentYearTotalFirstYearValueSub__c = 0.0;
        oppy1.SalesLostSubOnly__c = 0.0;
        oppy1.SalesLosttransonly__c = 0.0;
        oppy1.PriorYearTotalFirstYearValue__c=0.00;
        oppy1.PriorYearTotalFirstYearValueSub__c=0.00;
        oppy1.LostReasonCode__c='Customer exiting business';
        oppy1.LostReasonDescription__c='test';
        oppy1.StageName = '6W-Renewal Won';
        system.debug('oppy1.ContractStartDate__c'+oppy1.ContractStartDate__c);
        
        // CREATE OPPORTUNITY CONTACT ROLE (OPPORTUNITY PRIMARY CONTACT)
        OpportunityContactRole ocr2 = new OpportunityContactRole();
        ocr2.OpportunityId = oppy1.Id;
        ocr2.ContactId = con.Id;
        ocr2.IsPrimary = true;
        ocr2.Role = 'Opportunity Primary Contact';
        INSERT ocr2;
        
        oppy1.PrimaryContact__c = ocr2.Id;
       // Update oppy1;
       
        Test.startTest();
        // Create 2nd Renewal Opportunity
        Opportunity oppy2 = TestUtility.createRenewalOpportunity(acc1.Id, testContract.Id, true, false, false, true);
        oppy2.ContractStartDate__c = oppy1.ContractStartDate__c.addYears(1);
        oppy2.CurrencyIsoCode = 'USD' ;
        oppy2.PreviousFiscalYearOpportunityLink__c = oppy1.id ;
        oppy2.BusinessLine__c='Automotive Insights';
        oppy2.ContractEndDate__c = oppy2.ContractStartDate__c + 1;
        oppy2.MobilitySalesNew__c = 0.0;
        oppy2.MobilitySalesRenewal__c= 0.0;
        oppy2.SalesNewSubscription__c = 0.0;
        oppy2.SalesPriceIncreaseDecrease__c=0.0;
        oppy2.CurrentYearTotalFirstYearValue__c = 0.0;
        oppy2.CurrentYearTotalFirstYearValueSub__c = 0.0;
        oppy2.SalesLostSubOnly__c = 0.0;
        oppy2.SalesLosttransonly__c = 0.0;
        oppy2.PriorYearTotalFirstYearValue__c=0.00;
        oppy2.PriorYearTotalFirstYearValueSub__c=0.00;
        oppy2.StageName = '6W-Renewal Won';
        system.debug('oppy2.ContractStartDate__c'+oppy2.ContractStartDate__c);
        
        OpportunityContactRole ocr3 = new OpportunityContactRole();
        ocr3.OpportunityId = oppy2.Id;
        ocr3.ContactId = con.Id;
        ocr3.IsPrimary = true;
        ocr3.Role = 'Opportunity Primary Contact';
        INSERT ocr3;
        
        oppy2.PrimaryContact__c = ocr3.Id;
        //Update oppy2;
        
        
        
        List<Opportunity> listOfOpportunities = new List<Opportunity>{oppy1,oppy2};
        UPDATE listOfOpportunities;
        
        
        //CREATE BUSINESS LINE
        BusinessLine__c bsLine = new BusinessLine__c();
        bsLine.Status__c='Active';
        bsLine.CurrencyIsoCode='USD';
        bsLine.Name='Automotive Insights';
        insert bsLine;
        
        //CREATE PROFIT CENTER
        ProfitCenter__c profitCenter1=new ProfitCenter__c();
        profitCenter1.Active__c=true;
        profitCenter1.CurrencyIsoCode='USD';
        profitCenter1.SaleType__c='Subscription';
        insert profitCenter1;
        
        
        
        // CREATE OPPORTUNITY PRODUCT
        Product2 prod = new Product2();
        prod.Name = 'Test Product';
        prod.ProductCode = 'TESTPRODUCT';
        prod.IsActive = true;
        prod.BusinessLine2__c=bsLine.Id;
        prod.AAG__c='Subscription';
        prod.ProfitCenters__c=profitCenter1.Id;
        INSERT prod;
        
        Product2 prod2 = new Product2();
        prod2.Name = 'Test Product2';
        prod2.ProductCode = 'TESTPRODUCT';
        prod2.IsActive = true;
        prod2.AAG__c='Transaction';
        prod2.BusinessLine2__c=bsLine.Id;
        prod2.ProfitCenters__c=profitCenter1.Id;
        INSERT prod2;
        
        Product2 prod3 = new Product2();
        prod3.Name = 'Test Product3';
        prod3.ProductCode = 'TESTPRODUCT';
        prod3.IsActive = true;
        prod3.AAG__c='Subscription';
        prod3.BusinessLine2__c=bsLine.Id;
        prod3.ProfitCenters__c=profitCenter1.Id;
        INSERT prod3;
        
        // CREATE PRICEBOOK ENTRY
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.Product2Id = prod.Id;
        pbe.UnitPrice = 100.00;
        pbe.IsActive = true;
        pbe.CurrencyIsoCode = 'USD';
        INSERT pbe;
        
        PricebookEntry pbe2 = new PricebookEntry();
        pbe2.Pricebook2Id = Test.getStandardPricebookId();
        pbe2.Product2Id = prod2.Id;
        pbe2.UnitPrice = 200.00;
        pbe2.IsActive = true;
        pbe2.CurrencyIsoCode = 'USD';
        INSERT pbe2;
        
        PricebookEntry pbe3 = new PricebookEntry();
        pbe3.Pricebook2Id = Test.getStandardPricebookId();
        pbe3.Product2Id = prod3.Id;
        pbe3.UnitPrice = 300.00;
        pbe3.IsActive = true;
        pbe3.CurrencyIsoCode = 'USD';
        INSERT pbe3;
        
        
        // CREATE OPPORTUNITY PRODUCT / LINE ITEM
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppy1.Id;
        oli.Product2Id=prod.Id;
        oli.Quantity = 2;
        oli.PricebookEntryId = pbe.Id;
        oli.TotalPrice = oli.Quantity * pbe.UnitPrice;
        oli.FirstYear__c = oli.TotalPrice;
        oli.Status__c = 'New';
        
        OpportunityLineItem oli2 = new OpportunityLineItem();
        oli2.OpportunityId = oppy1.Id;
        oli2.Product2Id=prod2.Id;
        oli2.Quantity = 2;
        oli2.PricebookEntryId = pbe2.Id;
        oli2.TotalPrice = oli2.Quantity * pbe2.UnitPrice;
        oli2.FirstYear__c = oli2.TotalPrice;
        oli2.Status__c = 'New';
        
		OpportunityLineItem oli3 = new OpportunityLineItem();
        oli3.OpportunityId = oppy1.Id;
        oli3.Product2Id=prod3.Id;
        oli3.Quantity = 2;
        oli3.PricebookEntryId = pbe3.Id;
        oli3.TotalPrice = oli3.Quantity * pbe3.UnitPrice;
        oli3.FirstYear__c = oli3.TotalPrice;
        oli3.Status__c = 'Lost';
        
        OpportunityLineItem oli4 = new OpportunityLineItem();
        oli4.OpportunityId = oppy2.Id;
        oli4.Product2Id=prod.Id;
        oli4.Quantity = 2;
        oli4.PricebookEntryId = pbe.Id;
        oli4.TotalPrice = oli4.Quantity * pbe.UnitPrice;
        oli4.FirstYear__c = oli4.TotalPrice;
        oli4.Status__c = 'New';
        
        OpportunityLineItem oli5 = new OpportunityLineItem();
        oli5.OpportunityId = oppy2.Id;
        oli5.Quantity = 2;
        oli5.Product2Id=prod2.Id;
        oli5.PricebookEntryId = pbe2.Id;
        oli5.TotalPrice = oli5.Quantity * pbe2.UnitPrice;
        oli5.FirstYear__c = oli5.TotalPrice;
        oli5.Status__c = 'Existing';
        
        OpportunityLineItem oli6 = new OpportunityLineItem();
        oli6.OpportunityId = oppy2.Id;
        oli6.Quantity = 2;
        oli6.Product2Id=prod3.Id;
        oli6.PricebookEntryId = pbe.Id;
        oli6.TotalPrice = oli6.Quantity * pbe3.UnitPrice;
        oli6.FirstYear__c = oli6.TotalPrice;
        oli6.Status__c = 'Existing';
        
        List<OpportunityLineItem> listOfOpportunityLineItems = new List<OpportunityLineItem>{oli,oli2,oli3,oli4,oli5,oli6};
        INSERT listOfOpportunityLineItems;
        Test.stopTest();   
    }
  
     @isTest
    static void unitTest() {
        List<Opportunity> listOfRenewalOpportunity = new List<Opportunity>();
        Map<Id, List<OpportunityLineItem>> mapOfOpportunityLineItems = new Map<Id, List<OpportunityLineItem>>();
        for (Opportunity oppty : [SELECT Id, Name,CurrencyIsoCode,BusinessLine__c,CurrentYearTotalFirstYearValue__c,MobilitySalesRenewal__c,CurrentYearTotalFirstYearValueSub__c,MobilitySalesNew__c,SalesNewSubscription__c,SalesPriceIncreaseDecrease__c,SalesLostSubOnly__c,SalesLosttransonly__c,PriorYearTotalFirstYearValue__c,PriorYearTotalFirstYearValueSub__c,PreviousFiscalYearOpportunityLink__c,ContractStartDate__c,ContractEndDate__c, (SELECT Id, Status__c,product2.BusinessLine2__r.name,FirstYear__c,ProductType__c FROM OpportunityLineItems where FirstYear__c != null) FROM Opportunity])
		{
  			mapOfOpportunityLineItems.put(oppty.Id, oppty.OpportunityLineItems);
            system.debug('oppty==>'+oppty);
            listOfRenewalOpportunity.add(oppty);
            system.debug('listOfRenewalOpportunity'+listOfRenewalOpportunity);
            system.debug('listOfRenewalOpportunity.size()'+listOfRenewalOpportunity.size());
         }
       
        system.debug('OpportunityLineItem-->oppLineItem'+mapOfOpportunityLineItems);
        system.debug('listOfRenewalOpportunity'+listOfRenewalOpportunity);
        Test.startTest();
        Database.executeBatch(new BatchUpdateMobilityMatrics());
        //system.assertEquals(oppy2.PreviousFiscalYearOpportunityLink__c, oppy1.Id);
        Test.stopTest();
    }
}