objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of Product Group record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisibleInLiveChat__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5540 Check if the Product Group is visible in LiveChat.</description>
        <label>Visible in LiveChat</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestLiveChatPreChatController.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: SFDC1-834 TestLiveChatOfflineFormController - test class for LiveChatPreChatController
// @return: NA
//-----------------------------
@isTest(seealldata=false)
private class TestLiveChatPreChatController {
    // ensure Chat_Survey__c inserted and redirection to confirmation page occurs
    @isTest
    static void test1() {
        
        Account ac = TestUtility.createTestAccount('Test Pre Chat',true);

        //START - Insert Product Group
        String groupName = 'Active Live Chat';
        ProductGroup__c objProductGroup = TestUtility.createProductGroup(groupName, false);
        objProductGroup.VisibleInLiveChat__c = true;
        objProductGroup.Status__c = 'Active';
        insert objProductGroup;
        //END
        
        Contact myContact1 = TestUtility.createContact(ac.Id, 'uttam.arya@test.ihsmarkit.com',true, 'Uttam', 'Arya');
        
        PageReference pageRef = Page.LiveChatPreChat;
        
        Test.setCurrentPage(pageRef);

        LiveChatPreChatController controller = new LiveChatPreChatController();
        
        controller.suppliedemail = 'uttam.arya@test.ihsmarkit.com';
        
        Contact assertCon = LiveChatPreChatController.getContact(controller.suppliedemail);
        
        System.assertEquals(myContact1.Id, assertCon.Id);
        
        //START - Assert Product ID
        controller.SelectedProduct = groupName;
        controller.productIdSecuritiesFinance = objProductGroup.id;
        String pId = LiveChatPreChatController.getProductId(groupName);
        System.assert(string.isNotBlank(pId));
        //END
    }
    
}