objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC-5711 : field created for better reporting.</description>
        <label>AAG</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-6735: New Record Type Created for SOW/Consulting Usage</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountPercentage__c</fullName>
        <description>SFDC1-173 Denotes the discount percentage to be applied to the UnitPrice. Used in the pricing calculation customization.</description>
        <inlineHelpText>Please specify the discount percentage to be applied to the Updated List Price. Only required when the Discount Type is set to &quot;Percentage&quot;.</inlineHelpText>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <description>Specify what, if any, type of discount to be applied to the sales price.</description>
        <inlineHelpText>This field denotes the type of discount that is being applied.</inlineHelpText>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Discount</fullName>
                    <default>true</default>
                    <label>No Discount</label>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnitListPrice__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>SFDC1-173 Currency field that displays the intial value pre discount as entered by the rep</description>
        <inlineHelpText>List Price for the product populated by sales from pricing tools or through renewal process</inlineHelpText>
        <label>Updated List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/OpportunityToContractLineItemMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDC1-380 This mapping applies to contract creation wizard</description>
    <fields>
        <fullName>ContractLineItemField__c</fullName>
        <description>SFDC1-380 This field will hold contract line item field API Names</description>
        <inlineHelpText>Contract Line Item Field</inlineHelpText>
        <label>Contract Line Item Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityLineItemField__c</fullName>
        <description>SFDC1-380 This field will hold opportunity field API Names</description>
        <inlineHelpText>Opportunity Field API Name</inlineHelpText>
        <label>Opportunity Line Item Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpportunityToContract-LineItemMapping</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductswithTermsConditions__c.object
<CustomObject>
    <description>SFDC-1954</description>
    <fields>
        <fullName>TermsConditions__c</fullName>
        <description>SFDC-1954</description>
        <label>Terms &amp; Conditions</label>
        <referenceTo>TermsConditions__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductswithTermsConditions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Products with Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>PTC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products with Terms &amp; Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TermsConditions__c.object
<CustomObject>
    <description>SFDC-1954 New custom objects: Terms &amp; Conditions</description>
    <label>Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>TC-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestOrderFormData.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 18 Oct 2019
// @param: NA
// @description: SFDC-2007 Test Class for OrderFormData class
// @return: NA
//----------------------------
@isTest
private class TestOrderFormData {
    @testSetup
    static void createTestData() {
        //Create Account
        Account testAccount = TestUtility.createTestAccount('Account TestBatchCurrentAnnualValue', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
		//Create Contact        
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',true, 'Test', 'Contact');
        
        //Create Opportunity
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',true);
        
        //Create Opportunity Contact Role
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId = testOppy.Id, ContactId = testContact.Id, IsPrimary=false);
        insert ocr;
        
        //Create Products
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.AAG__c='Subscription';
        p1.DiscountThreshold__c = 10;
        Product2 p2 = TestUtility.createProduct('Test Product 2', false);
        p2.DiscountThreshold__c = 12;
        p1.AAG__c='Consulting';
        insert new List<Product2>{p1,p2};
        
        //Create Terms And Conditions
        TermsConditions__c testTnc1 = TestUtility.createTermsNCondition('Test Tnc 1 - Text',false);
        TermsConditions__c testTnc2 = TestUtility.createTermsNCondition('Test Tnc 2 - Text',false);
        insert new List<TermsConditions__c>{testTnc1, testTnc2};
        
        //Create Product Specific Terms And Conditions
        ProductswithTermsConditions__c ptnc1 = TestUtility.createProductTnC(p1.Id, testTnc1.Id, false);
        ProductswithTermsConditions__c ptnc2 = TestUtility.createProductTnC(p1.Id, testTnc2.Id, false);
        ProductswithTermsConditions__c ptnc3 = TestUtility.createProductTnC(p2.Id, testTnc1.Id, false);
        insert new List<ProductswithTermsConditions__c>{ptnc1, ptnc2, ptnc3};
            
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
        insert new List<PricebookEntry>{pbe1,pbe2};
            
        //Create OLIs
        OpportunityLineItem oli1 = TestUtility.createOpportunityLineItem(testOppy.id, pbe1,false);
        OpportunityLineItem oli2 = TestUtility.createOpportunityLineItem(testOppy.id, pbe2,false);
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>{oli1,oli2};
        insert new List<OpportunityLineItem>{oli1,oli2};
            
        //Create mapping custom setting records for - Opp Product to Contract Line Item setting
        List<OpportunityToContractLineItemMapping__c> oppProdToContractLineItemMapping = new List<OpportunityToContractLineItemMapping__c>();
        //oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='',OpportunityLineItemField__c='',ContractLineItemField__c=''));
        
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='Status',OpportunityLineItemField__c='Status__c',ContractLineItemField__c='Status__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='Discount',OpportunityLineItemField__c='DiscountPercentage__c',ContractLineItemField__c='Discount__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='DiscountType',OpportunityLineItemField__c='DiscountType__c',ContractLineItemField__c='DiscountType__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='OppProductId',OpportunityLineItemField__c='Id',ContractLineItemField__c='OpportunityProductId__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='Quantity',OpportunityLineItemField__c='Quantity',ContractLineItemField__c='Quantity__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='MaterialCode',OpportunityLineItemField__c='MaterialCode__c',ContractLineItemField__c='MaterialCode__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='UpdatedListPrice',OpportunityLineItemField__c='UnitListPrice__c',ContractLineItemField__c='UnitListPriceNew__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='ContractStartDate',OpportunityLineItemField__c='ContractStartDate__c',ContractLineItemField__c='StartDate__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='ContractEndDate',OpportunityLineItemField__c='ContractEndDate__c',ContractLineItemField__c='EndDate__c'));
        oppProdToContractLineItemMapping.add(new OpportunityToContractLineItemMapping__c(Name='TotalPrice',OpportunityLineItemField__c='TotalPrice',ContractLineItemField__c='TotalPriceFromOpportunityLineItem__c'));
               
        insert oppProdToContractLineItemMapping;
    }
    
    @isTest
    static void createOFContractRunOrderFormDataClass() {
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id orderFormContractRecId;
        Test.startTest();
        //Query Opportunity
        List<Opportunity> testOppList = [Select Id From Opportunity WHERE Name ='Test Opportunity 1'];
        for(Opportunity testOpp:testOppList) {
            //Create Order Form Contract
            orderFormContractRecId = ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, testOpp.Id);            
        }
        //Setup docgen related parameters
        OrderFormData ofmydApexObj = new OrderFormData();
        Loop.ExternalData.QueryRequestInfo requestInfo = new Loop.ExternalData.QueryRequestInfo();
        requestInfo.RecordId = orderFormContractRecId;
        
        Set<String> gd = ofmydApexObj.getGlobalDescribe();
        System.debug('gd='+gd);
		System.assertEquals(1, gd.size());
        ofmydApexObj.describeObjects(new List<String>(gd));
        
        List<Loop.ExternalData.Relationship> relationships = new List<Loop.ExternalData.Relationship>();
        for(String str: gd) {
            Loop.ExternalData.Relationship relationship = new Loop.ExternalData.Relationship();
            relationship.Name = str;
            relationships.add(relationship);
        }
        requestInfo.Relationships = relationships;        
               
        Loop.ExternalData.QueryResultSet queryRS = ofmydApexObj.query(requestInfo);
        System.debug('queryRS.results='+queryRS.results);
        System.debug('queryRS.results.size()='+queryRS.results.size());
        System.assert(queryRS.results.size()>0);

        Test.stopTest();
    }

}