objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Wrapper</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NotesCompleted__c</fullName>
        <description>SFDC-2752 If meeting outcome is populated on related meeting note, mark Notes Completed on event as true.</description>
        <formula>MeetingNote__r.NotesCompleted__c ||  IF(ISBLANK(CommentsPreview__c),False,True)</formula>
        <label>Notes Completed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Create an event record to log interactions with a customer</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NotesCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-2752 True if meeting outcome is populated on Meeting Note.</description>
        <label>Notes Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MISActivityAdded__c</fullName>
        <description>SFDC1-2243 Whenever an activity is created for an opportunity,  MISActivityAdded field is auto populated with the current timestamp.</description>
        <inlineHelpText>System Managed Field: This field is used for MIS pipeline reporting. Whenever an activity is created for an opportunity,  MISActivityAdded field is auto populated with the current timestamp.</inlineHelpText>
        <label>MIS Activity Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Only open opportunities can be linked to a meeting.</errorMessage>
            <filterItems>
                <field>Opportunity.IsClosed</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTaskMethods.cls
// @author: Uttam Arya
// @date: 31 Aug 2017
// @param: NA
// @description: Test class for Task trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestTaskMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 31 Aug 2017
    // @param: NA
    // @description: SFDC1-2243 Test method for Task trigger methods populateTaskAddedInOpportunityWhenTaskIsInserted on insert
    // @return: NA
    // 
    // @Updated by: Harshit Singhal
    // @Updated date: 15 Jun 2018
    // @Updated description: Updated to cover code changes made for SFDC1-8540 in populateTaskAddedInOpportunityWhenTaskIsInserted() method
    //-----------------------------
    @isTest
    private static void testpopulateTaskAddedInOpportunityWhenTaskIsInserted() {
        
        Account acct = TestUtility.createTestAccount('Test populateAdditionalFiledsLookupInAccount', true);
        Opportunity oppt = TestUtility.createOpportunity(acct.Id, 'Test Oppy Task', true);
        
        Task t = new Task(Account__c = acct.Id, Subject = 'Test Task', WhatId = oppt.Id);
        
        insert t;
        
        //Assert if MIS is inserted
        Opportunity opp = [select MISActivityAdded__c,ActivityCreated__c from Opportunity where Id =: oppt.Id];
        
        System.assertNotEquals(opp.MISActivityAdded__c,null,'MISActivityAdded__c should not be null');
        System.assertEquals(true,opp.ActivityCreated__c,'ActivityCreated__c should be true');
        
        acct.DataGovernanceStatus__c = 'Unapproved';
        update acct;
        
        t = new Task(Account__c = acct.Id, Subject = 'Test Task2', WhatId = oppt.Id);
        try { 
            insert t;
            Throw new AssertException ('Expected to fail, account is unapproved');
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Opportunities can only be created for or associated with accounts that have been approved by Customer Master Data Team.');
            System.AssertEquals(expectedExceptionThrown, true,'Expected Exception is thrown');
        }
        
    }
    
    //-----------------------------
    // @author: Mohit Modi
    // @date: 17 Jan 2018
    // @param: NA
    // @description: SFDC1-5027 Test method for Task trigger methods updateOpportunityActivityCheckOnTaskDeletion on Delete
    // @return: NA
    // @modified by: Priyanka Vyas
    // @date: 26 Aug 2020
    // @description: Commented and rewrote the method below against SFDC-3133. 
    //-----------------------------
    /*private static testMethod void testupdateOpportunityActivityCheckOnTaskDeletion() {
        
        Account acct = TestUtility.createTestAccount('Test populateAdditionalFiledsLookupInAccount', true);
        
        Opportunity oppt1 = TestUtility.createOpportunity(acct.Id, 'Test Oppy Task', false);
        oppt1.ActivityCreated__c = true;
        Opportunity oppt2 = TestUtility.createOpportunity(acct.Id, 'Test Oppy Task', false);
        oppt2.ActivityCreated__c = true;
        insert new list<opportunity> {oppt1,oppt2};
        
        test.startTest();
        
        Task t1 = new Task(Account__c = acct.Id, Subject = 'Test Task', WhatId = oppt1.Id);
        Task t2 = new Task(Account__c = acct.Id, Subject = 'Test Task', WhatId = oppt1.Id);
        Task t3 = new Task(Account__c = acct.Id, Subject = 'Test Task', WhatId = oppt2.Id);
        insert new List<Task>{t1,t2,t3};
        
        set<id> setOppID = new set<id>{oppt1.Id,oppt2.Id};
        
        List<Opportunity> opp = [select ActivityCreated__c from Opportunity where Id in : setOppID ];
        System.assertEquals(opp[0].ActivityCreated__c ,true);
        System.assertEquals(opp[1].ActivityCreated__c ,true);
        
        delete new list<task>{t1,t3};
        
        // Assert that the opportunity's ActivityCreated__c should be false if the last task is deleted, else it should be true.
        opp = [select ActivityCreated__c from Opportunity where Id in : setOppID ];
        System.assertEquals(opp[0].ActivityCreated__c ,true);
        System.assertEquals(opp[1].ActivityCreated__c ,false);
        
        test.stopTest();
    }*/
    //-----------------------------
    // @author: Priyanka Vyas
    // @date: 26 Aug 2020
    // @description: SFDC-3133 Test method for changeActivityCreatedOppyOnUpdate and updateOpportunityActivityCheckOnTaskDeletion methods to update ActivityCreated__c on Opportunity .
    // @param: 
    // @return: void
    //-----------------------------
    @isTest
    private static void testChangeActivityCreatedCheckboxOnOpportunity() {
        Set<ID> oppIDSet=new Set<ID>();
        //test.startTest();
        Account acc = TestUtility.createTestAccount('Test', true);
        Opportunity testOpp1 = TestUtility.createOpportunity(acc.id, 'Test Opp1', false);
        Opportunity testOpp2 = TestUtility.createOpportunity(acc.id, 'Test Opp2', false);
        Opportunity testOpp3 = TestUtility.createOpportunity(acc.id, 'Test Opp3', false);
        Opportunity testOpp4 = TestUtility.createOpportunity(acc.id, 'Test Opp4', false);
        Opportunity testOpp5 = TestUtility.createOpportunity(acc.id, 'Test Opp5', false);
        
        List<Opportunity> oppList = new List<Opportunity> {testOpp1, testOpp2, testOpp3, testOpp4,testOpp5};
            insert oppList;
			for(Opportunity opp:oppList) {
                oppIDSet.add(opp.id);
            }
            Event testEvt1 = new Event(Subject='Test1', WhatId=testOpp1.id,StartDateTime=System.now(),EndDateTime=System.now()+1);
            insert testEvt1;
        	Event insertedEvent = [Select id, MeetingNote__c from event where id=:testEvt1.id];
        	Task t = new Task(WhatId=testOpp2.id, subject='test', Priority='Normal', Status='Open');
            insert t;
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            
            Contact markitContact = TestUtility.createContact(acc.Id,uniqueName + '@test' + orgId + '.org',true, 'FirstName', 'LastName');
            RelatedOpportunity__c testRO1 = new RelatedOpportunity__c(MeetingNote__c=insertedEvent.MeetingNote__c,Opportunity__c=testOpp3.Id);
            insert testRO1;
        	Task tsk1 = new Task(Type='Call', Subject='Meeting1', WhatId=testOpp1.id);
            Task tsk2 = new Task(Type='Call', Subject='Meeting2', WhatId=testOpp2.id);
            Task tsk3 = new Task(Type='Call', Subject='Meeting3', WhatId=testOpp3.id);
            Task tsk4 = new Task(Type='Call', Subject='Meeting4', WhatId=testOpp4.id);
            List<task> tskList=new List<task>{tsk1,tsk2,tsk3,tsk4};
                insert tskList;
            tsk4.WhatId=testOpp5.id;
            update tsk4;
        	Product2 prod = TestUtility.createProduct('Test Product', true);
        	Id stdPricebookId = Test.getStandardPricebookId();
        	PriceBook2 standardPB = new PriceBook2(Id = stdPricebookId, Name = 'Standard Price Book', isActive = true);
        	update standardPB;
        	test.startTest();
        	PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, prod.Id, true);

        	OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpp5.Id, pbe1, true);
        	OpportunityContactRole ocr = TestUtility.createOpportunityContactRole(markitContact.id, testOpp5.id, true, 'Business User', true);
        	testOpp5.StageName = '5-Contracting';
        	testOpp5.ContractStartDate__c = Date.Today();
        	testOpp5.ContractEndDate__c = Date.Today() + 1;
        	update testOpp5;
        	try{
            List<task> taskDeletionList=new List<task>{tsk1,tsk2,tsk3,tsk4};
                delete taskDeletionList;
            }
        	catch (Exception e) {
            	Boolean expectedExceptionThrown =  e.getMessage().contains('On Stage 5-Contracting opportunity must have an activity referenced to it.');
            	System.AssertEquals(expectedExceptionThrown, true, 'expectedExceptionThrown should be true');
        	}
        List<Opportunity> oppyListFinal=[Select id,name,ActivityCreated__c from Opportunity where id in:oppIDSet];
        For(Opportunity O: oppyListFinal) {
            if(o.id==testOpp1.id) {
                System.assertEquals(o.ActivityCreated__c,true,'testOpp1 has ActivityCreated__c as true');
            }
            if(o.id==testOpp2.id) {
                System.assertEquals(o.ActivityCreated__c,true,'testOpp2 has ActivityCreated__c as true');
            }
            if(o.id==testOpp3.Id) {
               System.assertEquals(o.ActivityCreated__c,true,'testOpp3 has ActivityCreated__c as true');
            }
            if(o.id==testOpp4.Id) {
                System.assertEquals(o.ActivityCreated__c,false,'testOpp4 has ActivityCreated__c as false');
            }
            if(o.id==testOpp5.Id) {
                //System.assertEquals(o.ActivityCreated__c,false,'testOpp5 has ActivityCreated__c as false');
                System.assertEquals(o.ActivityCreated__c,true,'testOpp5 has ActivityCreated__c as true');
            }
        }
        test.stopTest();
    }
    //-----------------------------
    // @author: Akshay Dogra
    // @date: 11 June 2021
    // @description: SFDC-3979: Test method for notesCheckbox methods to  Notes / Comments Added Checkbox on Tasks.
    // @param: 
    // @return: void
    //-----------------------------
    @isTest
    private static void testnotesCheckbox() {
        test.startTest();
        Account acc = TestUtility.createTestAccount('Test', true);
        Opportunity testOpp1 = TestUtility.createOpportunity(acc.id, 'Test Opp1', false);
        insert testOpp1;
        
        Task t = new Task(WhatId=testOpp1.id, subject='test', Priority='Normal', Status='Open', Description='ABCTest');
        Task t1 = new Task(WhatId=testOpp1.id, subject='test', Priority='Normal', Status='Open');
        List<task> tskList=new List<task>{t,t1};
        insert tskList;
        List<Task> t2 = [Select Id, NotesCompleted__c from Task Where Id in : tskList];
        System.assertEquals(True, t2[0].NotesCompleted__c,'Comments Checkbox should be checked');
        System.assertEquals(False, t2[1].NotesCompleted__c, 'Comments Checkbox should be unchecked');
    
        test.stopTest();
    }
}