objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-309 Lookup to Accounts
SFDC1-8156: Relabeling related list label to &quot; Internal Cases&quot;</description>
        <inlineHelpText>Salesforce will populate when the case is spawned from an Account</inlineHelpText>
        <label>Account Reference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Internal Cases</relationshipLabel>
        <relationshipName>AccountReferenceCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryTeam__c</fullName>
        <description>SFDC1-6148: This field will hold the Delivery Team values
SFDC1-6944: Reorder the picklist values
SFDC1-6995: Configure field dependencies - if Team Select = Retail, only RETAIL values are available in Delivery Team</description>
        <label>Delivery Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TeamSelect__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agri Connect</fullName>
                </value>
                <value>
                    <fullName>Agri SAM</fullName>
                </value>
                <value>
                    <fullName>Auto Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Calgary Licensing</fullName>
                </value>
                <value>
                    <fullName>CD Distribution</fullName>
                </value>
                <value>
                    <fullName>Chemical Deliverables</fullName>
                </value>
                <value>
                    <fullName>CI Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Delivery Technical</fullName>
                </value>
                <value>
                    <fullName>EMEA Physical Delivery</fullName>
                </value>
                <value>
                    <fullName>Englewood Physical Delivery</fullName>
                </value>
                <value>
                    <fullName>Erights</fullName>
                </value>
                <value>
                    <fullName>Experts Portal</fullName>
                </value>
                <value>
                    <fullName>Fekete Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>GIS Delivery</fullName>
                </value>
                <value>
                    <fullName>Global Delivery EMEA ADandM</fullName>
                </value>
                <value>
                    <fullName>Global Delivery Help Desk</fullName>
                </value>
                <value>
                    <fullName>Global Insight Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Goldfire Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>GTA Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>JOC Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Kingdom Licensing</fullName>
                </value>
                <value>
                    <fullName>Macro Economic Advisors</fullName>
                </value>
                <value>
                    <fullName>ODSP Orders</fullName>
                </value>
                <value>
                    <fullName>Online Delivery</fullName>
                </value>
                <value>
                    <fullName>OPIS Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Entitlements EM</fullName>
                </value>
                <value>
                    <fullName>Order Entitlements UK</fullName>
                </value>
                <value>
                    <fullName>PETRA Licensing</fullName>
                </value>
                <value>
                    <fullName>Premier Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Product Design</fullName>
                </value>
                <value>
                    <fullName>RETAIL-SDM1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoadingGroupOnboarding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7137: Creating lookup field for Implementation record type. Since there exists another field as Loading group, creating new field with same label, but different API</description>
        <label>Loading Group</label>
        <referenceTo>LoadingGroup__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderManagementRegion__c</fullName>
        <description>SFDC1-6148 : This field will hold Order Management Region</description>
        <label>Order Management Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGRI</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Markit</fullName>
                    <label>Financial Services</label>
                </value>
                <value>
                    <fullName>INFORMA</fullName>
                </value>
                <value>
                    <fullName>IPREO</fullName>
                </value>
                <value>
                    <fullName>IPREO-Noida</fullName>
                </value>
                <value>
                    <fullName>JANES</fullName>
                </value>
                <value>
                    <fullName>POLK</fullName>
                </value>
                <value>
                    <fullName>UKSUP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SingleSignOnSAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-8685 SAM SSO Inquiry Checkbox field</description>
        <label>Single Sign On (SAM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamSelect__c</fullName>
        <description>SFDC1-6148 : This field will hold the value of Team</description>
        <label>Team Select</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Management</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CaseProducts__c.object
<CustomObject>
    <description>SFDC1-593 - Junction object between Case and Products</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>SFDC1-593 - Master Detail relationship to Case</description>
        <inlineHelpText>Select the Case you wish to relate to additional Products</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-593 - Lookup to Product</description>
        <inlineHelpText>Select a Product (if known).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Products</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LoadingGroup__c.object
<CustomObject>
    <description>SFDC1-2462 Loading Group related to product. To be maintained by Vanguard product management process</description>
    <fields>
        <fullName>DeliveryTeam__c</fullName>
        <description>SFDC1-6249 This field is to carry loading group so cases get sent to the correct Delivery teams when an opportunity is closed</description>
        <label>Delivery Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Loading Group</label>
    <nameField>
        <label>Loading Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loading Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>SFDC-1103 This field captures the budget range for the opportunity</description>
        <inlineHelpText>Please provide the Budget Range.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>100,000 - 500,000</fullName>
                </value>
                <value>
                    <fullName>500,000 - 1,000,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 1,000,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LoadingGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2462 Lookup field to capture loading group on product</description>
        <inlineHelpText>Loading Group Managed by Vanguard Product Management Process</inlineHelpText>
        <label>Loading Group</label>
        <referenceTo>LoadingGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LoadingGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCreateOMDHCaseController.cls
//-----------------------------
// @author: Vishnu Vardhan Chowdary Andra
// @date: 08 Oct 2018
// @param: NA
// @description: Test class for CreateOMDHCaseController methods 
// @return: NA
//-----------------------------
@isTest
public class TestCreateOMDHCaseController {

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 08 Oct 2018
    // @description: Method to create test data.
    // @param: 
    // @return: void
    //-----------------------------
    @testSetup 
    static void dataSetup() {
        Account acc = TestUtility.createTestAccount('Account testAccount', false);
        acc.DataGovernanceStatus__c = 'Approved';
        insert acc;

        List<LoadingGroup__c> lgList = new List<LoadingGroup__c> ();
        lgList.add(TestUtility.createLoadingGroup('IHS', 'IHS Lg1', false));
        lgList.add(TestUtility.createLoadingGroup('IHS', 'Markit Lg2', false));
        lgList.add(TestUtility.createLoadingGroup('Markit', 'Markit Lg3', false));
        lgList.get(0).deliveryTeam__c = 'Erights';
        lgList.get(0).deliveryTeam__c = 'Erights2';
        insert lgList;

        Id standardId = Test.getStandardPricebookId();
        List<Product2> productList = new List<Product2>();
        productList.add(TestUtility.createProductWithLoadingGroup('Test Product1', lgList.get(0).id, false));
        productList.add(TestUtility.createProductWithLoadingGroup('Test Product2', lgList.get(0).id, false));
        productList.add(TestUtility.createProductWithLoadingGroup('Test Product3', lgList.get(1).id, false));
        productList.add(TestUtility.createProductWithLoadingGroup('Test Product4', lgList.get(1).id, false));
        productList.add(TestUtility.createProductWithLoadingGroup('Test Product5', lgList.get(2).id, false));
        insert productList;

        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        pbeList.add(TestUtility.createPriceBookEntry(standardId, productList.get(0).id, false));
        pbeList.add(TestUtility.createPriceBookEntry(standardId, productList.get(1).id, false));
        pbeList.add(TestUtility.createPriceBookEntry(standardId, productList.get(2).id, false));
        pbeList.add(TestUtility.createPriceBookEntry(standardId, productList.get(3).id, false));
        pbeList.add(TestUtility.createPriceBookEntry(standardId, productList.get(4).id, false));
        insert pbeList;

        Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', false);
        testOpportunity.BudgetRange__c = '< 25,000';
        testOpportunity.ActivityCreated__c = true;
        testOpportunity.CloseDate = System.today() + 180;
        insert testOpportunity;

        Contact testContact = TestUtility.createContact(acc.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId = testOpportunity.Id, ContactId = testContact.Id, IsPrimary=true);
        insert ocr;

        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        oliList.add(TestUtility.createOpportunityLineItem(testOpportunity.Id, pbeList.get(0), false));
        oliList.add(TestUtility.createOpportunityLineItem(testOpportunity.Id, pbeList.get(1), false));
        oliList.add(TestUtility.createOpportunityLineItem(testOpportunity.Id, pbeList.get(2), false));
        oliList.add(TestUtility.createOpportunityLineItem(testOpportunity.Id, pbeList.get(3), false));
        insert oliList;
        
        Id ofRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(ofRecordTypeId, testOpportunity.Id);
    }

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 08 Oct 2018
    // @description: Test method to test if Retail/OM case is created or not.
    // @param: 
    // @return: void
    //-----------------------------
    @isTest
    public static void testRetailAndOMCaseCreation() {
        Id testContractId = [SELECT Id FROM Contract LIMIT 1].Id;
        System.assert(testContractId!=null);
		Test.startTest();
        Case cas = CreateOMDHCaseController.getOMDHRecord();
        Contract ctrct = CreateOMDHCaseController.getContractDetails(testContractId);
        cas.Subject = 'Retail Case';
        cas.Description = 'Retail Case Description';
        cas.TeamSelect__c = 'Retail';
        cas.Contract__c = ctrct.Id;
        cas.DeliveryTeam__c = 'RETAIL-SDM1';
        cas.OrderManagementRegion__c = 'EMEA';
        cas.SingleSignOnSAM__c = false;
        cas.AccountId = ctrct.AccountId;
        cas.AccountReference__c =ctrct.AccountId;
        String successMessage = CreateOMDHCaseController.saveOMDHCase(cas);
        System.assertEquals('Case record created', successMessage);
        cas = [SELECT Id, Contract__c, AccountReference__c, TeamSelect__c FROM case where Contract__c = :testContractId  LIMIT 1];
        System.assertNotEquals(cas, null);
        System.assertEquals(cas.Contract__c, testContractId);
        System.assertEquals(cas.AccountReference__c, ctrct.AccountId);
        Test.stopTest();
    }

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 08 Oct 2018
    // @description: Test method to test if Delivrey cases are created or not, with correct case products..
    // @param: 
    // @return: void
    //-----------------------------
    @isTest
    public static void testDeliveryCaseCreation() {
        Id testContractId = [SELECT Id FROM Contract LIMIT 1].Id;
        System.assert(testContractId!=null);
        Set<String> delTeams = new Set<String>{'Erights','Global Delivery EMEA ADandM','Global Delivery Help Desk','Delivery Technical'};
        Test.startTest();
        
        Contract ctrct = CreateOMDHCaseController.getContractDetails(testContractId);
        List<ProductSelectorWrapperClass> lstProductWrapper = CreateOMDHCaseController.getAvailableProductsForContract(testContractId);
        System.assertEquals(4, lstProductWrapper.size());//Markit category products are not to be included.
        //remove the last one, and create case. Since we have 2 products for loading group, we will have 2 Cases created.
        lstProductWrapper.remove(3);
        
        Case cas = CreateOMDHCaseController.getOMDHRecord();
        cas.Subject = 'Delivery Case';
        cas.Description = 'Delivery Case Description';
        cas.TeamSelect__c = 'Delivery';
        cas.Contract__c = ctrct.Id;
        cas.OrderManagementRegion__c = 'EMEA';
        //cas.SingleSignOnSAM__c = true;
        cas.AccountId = ctrct.AccountId;
        cas.AccountReference__c =ctrct.AccountId;
        
        String successMessage = CreateOMDHCaseController.createDeliveryCases(cas, Json.serialize(lstProductWrapper));
        System.assertEquals('Cases are Created!', successMessage);

        List<Case> caseList = [SELECT Id, LoadingGroupOnboarding__c, DeliveryTeam__C, (select id, Product__c from CaseProducts__r) 
               FROM case where Contract__c = :testContractId and TeamSelect__c = 'Delivery' and isClosed=false];
        System.assertNotEquals(caseList, null);
        System.assertEquals(caseList.size(), 2);
        //One will have default value, another will have default value
        System.assert(delTeams.contains(caseList.get(0).deliveryTeam__c));
        System.assert(delTeams.contains(caseList.get(1).deliveryTeam__c));
        
        //Again get the products, all 4 should be returned. Earlier only products 
        //for which delivery case is not created, was returned.
        lstProductWrapper = CreateOMDHCaseController.getAvailableProductsForContract(testContractId);
        System.assertEquals(4, lstProductWrapper.size());
        cas.SingleSignOnSAM__c = true;
        successMessage = CreateOMDHCaseController.createDeliveryCases(cas, Json.serialize(lstProductWrapper));
        System.assertEquals('Cases are Created!', successMessage);

        caseList = [SELECT Id, LoadingGroupOnboarding__c, DeliveryTeam__c, (select id, Product__c from CaseProducts__r) 
               FROM case where Contract__c = :testContractId and TeamSelect__c = 'Delivery' and isClosed=false];
        System.assertNotEquals(caseList, null);
        //New cases are added in the above step, making a total of 4
        System.assertEquals(caseList.size(), 4);
        for(case c: caseList) {
            System.assert(delTeams.contains(c.deliveryTeam__c));
        }
        
        //Again get the products for which delivery case is to be created. All products should be returned.
        lstProductWrapper = CreateOMDHCaseController.getAvailableProductsForContract(testContractId);
        System.assertEquals(lstProductWrapper.size(), 4);
        Test.stopTest();
    }
}