objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>SFDC-1103 This field captures the budget range for the opportunity</description>
        <inlineHelpText>Please provide the Budget Range.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>100,000 - 500,000</fullName>
                </value>
                <value>
                    <fullName>500,000 - 1,000,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 1,000,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestQuickRecordCreationController.cls
//------------------------------------------------
// @author: Priyanka Vyas
// @date: 14 Apr 2020
// @description:  SFDC-2565, SFDC-2699 Creation of Contact & Opportunity from utility bar
//------------------------------------------------
@isTest
public class TestQuickRecordCreationController {
    public static testMethod void testQuickRecordCreation() {
        test.startTest();
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        SObject acc = QuickRecordCreationController.fetchSObjectfields(testAccount.id);
        String orgId = UserInfo.getOrganizationId();
        String userId = UserInfo.getUserId();
        User user=QuickRecordCreationController.fetchCurrentUser(userId);
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        Contact newContact1;
        Contact newContact2;
        Opportunity opp1;
        Opportunity opp2;
        Opportunity opp3;
        Event newEvent1;
        Task newTask1;
        String accId=String.valueOf(acc.Id);
        String contactEmail=uniqueName + '@test' + orgId + '.com';
        newContact1 = QuickRecordCreationController.createContact('TestFirstName','TestMiddleName','TestLastName','999-888-1234',contactEmail,accId, 'test','FinTech','Analyst','Advisor','Accounting');
        try{		
            newContact2 = QuickRecordCreationController.createContact('TestFirstName','TestMiddleName','TestLastName','999-888-1234',null,accId, 'test','FinTech','Analyst','Advisor','Accounting');
        }Catch(Exception ex){
            System.debug('::: Error on quick create contact in test context: '+ex);
        }
        QuickRecordCreationController.fetchPickListValues('Opportunity', 'BudgetRange__c');
        opp1 = QuickRecordCreationController.createOpportunity('Opp1',accId, Date.newInstance(2016, 12, 9) ,'< 25,000');
        opp2 = QuickRecordCreationController.createOpportunity('Opp1',accId, Date.newInstance(2016, 12, 9) ,'--None--');
        String eventJSON='{"eventType": "Meeting", "eventSubject": "Call", "eventWhoId":"'+ newContact1.Id +'", "eventWhatId":"'+ opp1.Id+'", "StartDateTime":"'+Datetime.now()+'", "EndDateTime":"'+ DateTime.Now().AddDays(1)+'", "OwnerId":"'+UserInfo.getUserId()+'", "Location":"Test"}';
    	Event newEvent = QuickRecordCreationController.createEvent(eventJSON);
        String taskJSON='{"taskType": "Task", "taskSubject": "Call", "taskWhoId":"'+newContact1.Id+'", "taskWhatId":"'+ opp1.Id+'", "OwnerId":"'+ UserInfo.getUserId()+'", "ActivityDate":"'+Date.today()+'", "Priority": "Normal", "Status": "Open" }';
     	Task newTask = QuickRecordCreationController.createTask(taskJSON);
        String eWhoId=QuickRecordCreationController.fetchEventWhatId(newEvent.Id);
        String tWhoId=QuickRecordCreationController.fetchTaskWhatId(newTask.Id);
        String eventJSON1='{"eventType": "Call", "eventSubject": "Call", "eventWhoId":"'+ newContact1.Id +'", "eventWhatId":"'+ opp1.Id+'", "StartDateTime":"'+Datetime.now()+'", "EndDateTime":"'+ DateTime.Now().AddDays(1)+'", "OwnerId":"null"}';
        try{
            newEvent1 = QuickRecordCreationController.createEvent(eventJSON1);
        }
        catch(Exception ex){
            System.debug('::: Error on quick create event in test context: '+ex);
        }
        String taskJSON1='{"taskType": "Task", "taskSubject": "Call", "taskWhoId":"'+newContact1.Id+'", "taskWhatId":"'+ opp1.Id+'", "OwnerId":"null", "ActivityDate":"'+Date.today()+'", "Priority": "Normal"}';
        try{
            newTask1 = QuickRecordCreationController.createTask(taskJSON1);
        }
        catch(Exception ex){
            System.debug('::: Error on quick create task in test context: '+ex);
        }
        testAccount.DataGovernanceStatus__c ='Unapproved';
        update testAccount;
        try{		
            opp3 = QuickRecordCreationController.createOpportunity('Opp1',accId, Date.newInstance(2016, 12, 9) ,'--None--');
        }Catch(Exception ex){
            System.debug('::: Error on quick create opportunity in test context: '+ex);
        }
        test.stopTest(); 
        QuickRecordCreationController.checkCreationPermission('Contact');
        List<Profile> readOnlyProfiles = [select id, Name from Profile where Name = 'IHSMarkit: Read Only Profile'];
		User u = new User(FirstName='Test', Alias = 'standt', Email=uniqueName + '@test' + orgId + '.org', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = readOnlyProfiles[0].Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=uniqueName + '@test' + orgId + '.org', HRManager__c ='TestHR', ADID__c=uniqueName + '@test' + orgId + '.org', EmployeeNumber__c='123');
        System.runAs(u) {
        	QuickRecordCreationController.checkCreationPermission('Opportunity');
        }
        System.assert(newContact1!=null);
        System.assert(opp1!=null);
		System.assert(newTask!=null);
        System.assert(newEvent!=null);
        
    }
    
}