objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesIncentiveApproval__c.object
<CustomObject>
    <description>SFDC-1908 Sales Incentives</description>
    <fields>
        <fullName>CommissionStatus__c</fullName>
        <description>SFDC-1908 Sales Incentive Approvals</description>
        <inlineHelpText>Picklist field for commission team</inlineHelpText>
        <label>Commission Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Opportunity Lost</fullName>
                </value>
                <value>
                    <fullName>Waiting on Finance Info</fullName>
                </value>
                <value>
                    <fullName>Waiting on Rep Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IncentiveOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-1908 Sales Incentive Approvals</description>
        <inlineHelpText>Lookup to user, when users are creating for others</inlineHelpText>
        <label>Incentive Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SalesIncentiveApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-1908 Sales Incentive Approvals</description>
        <inlineHelpText>Lookup to Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Incentive Approvals</relationshipLabel>
        <relationshipName>SalesIncentiveApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_for_Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US-5103087 : Edit access remain unlocked for &quot;New Sales Incentive Approval &quot;related object under &quot;Opportunity&quot; object until &quot;Commission&quot; status is open.</description>
        <inlineHelpText>Check this field to submit this record for approval.</inlineHelpText>
        <label>Ready for Submission</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Incentive Approval</label>
    <nameField>
        <displayFormat>SIA-{000000}</displayFormat>
        <label>Sales Incentive Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Incentive Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSalesIncentiveApprovalMethod.cls
//-----------------------------
// @author: Sushma Yadav
// @date: 10 Feb 2020
// @param: NA
// @description: Test class for Sales Incentive Approval trigger methods 
// @date: 27 Feb 2020: SFDC-2680 Req update so achieving the result via custom button URL hacking
// @return: NA
//-----------------------------

@isTest
public class TestSalesIncentiveApprovalMethod {
    	/* private static testMethod void testpopulateIncentiveOwnerLookupSalesIncentive() {
        test.startTest();
        Account a = TestUtility.createTestAccount('Account testSetRenewalRiskOptysObject', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;      
              
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName= '1-Sales Qualified';
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.AccountId = a.id;
        insert opp;       
        
        SalesIncentiveApproval__c sIA=new SalesIncentiveApproval__c();
        sIA.Opportunity__c=opp.id;
        sIA.CommissionStatus__c='Open';
        insert sIA;
        //Updated on 12th Feb2020
        List<SalesIncentiveApproval__c> lstSIA=[Select IncentiveOwner__c from SalesIncentiveApproval__c where Id=:sIA.Id];  
        System.assertEquals(UserInfo.getUserId(), lstSIA[0].IncentiveOwner__c); 

        test.stopTest();
        
    } */

    	//-----------------------------
   		// @author: Dev Aggarwal
   		// @date: 9 March 2020
  		// @param: TriggerParameters
   		// @description: SFDC-2681 - Create Data for Testing.
   	@testSetup
    private static void CreateTestDate() {
        Account a = TestUtility.createTestAccount('Account testSetRenewalRiskOptysObject', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;      
              
        
        Id NewBusRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity(name='Test Opp', StageName= '1-Sales Qualified', RecordTypeId = NewBusRecordTypeId,
                                         CloseDate = System.today()+2, Amount = 123, AccountId = a.id);
        insert opp;  
    }

    	//-----------------------------
   		// @author: Dev Aggarwal
   		// @date: 9 March 2020
  		// @param: TriggerParameters
   		// @description: SFDC-2681 - Test SubmitForApprovalMethod.
        // BUG-5241405: to avoid getting records locked upon save.
    	@isTest private static void testSubmitForApproval() {
        List<Opportunity> oppties = [Select id from Opportunity where name = 'Test Opp'];
        test.startTest();
        SalesIncentiveApproval__c sIA=new SalesIncentiveApproval__c();
        sIA.Opportunity__c=oppties[0].id;
        sIA.CommissionStatus__c='Open';
        sIA.Ready_for_Submission__c = true;
        insert sIA;
        test.stopTest();
        
        List<ProcessInstance> approvals = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE TargetObjectId = :sia.id];
        system.assertEquals(0,approvals.size(),'Record is not submitted for approval');

    } 
}