objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <description>SFDC1-2060 Contract Status fields
SFDC1-7222: Adding picklist value &quot;Waiting on PO&quot;</description>
        <inlineHelpText>Please select from dropdown menu</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Signed By Customer</fullName>
                    <label>Signed by Customer</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validated PO Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-POD Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-BSI Pending</fullName>
                </value>
                <value>
                    <fullName>Validated by ConsOps</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Sent to Delivery</fullName>
                </value>
                <value>
                    <fullName>Sent to OM/Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered to Customer</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved &amp; Processed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Unscheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                    <isActive>false</isActive>
                    <label>Received</label>
                </value>
                <value>
                    <fullName>Sent To OM</fullName>
                    <isActive>false</isActive>
                    <label>Sent To OM</label>
                </value>
                <value>
                    <fullName>Sent for Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Sent for Delivery</label>
                </value>
                <value>
                    <fullName>Waiting on PO</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on PO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fastrack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5851 Checkbox on &quot;Order From&quot; contracts
SFDC1-10429:Update Fastrack to Fast Track</description>
        <inlineHelpText>Use Fast Track terms and conditions if under $100k</inlineHelpText>
        <label>Fast Track</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>AssociatedProduct__r.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ContractProductAlliancePartner__c.object
<CustomObject>
    <description>SFDC-4235: Alliances Validation Tracking - to check whether the customer has a license or not to use IHS data via partners</description>
    <fields>
        <fullName>AlliancePartnerApprovalDate__c</fullName>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Alliance Partner Approval Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AlliancePartner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Alliance Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Global Alliance - Core, Global Alliance - HSP, Global Alliance - Prospect</value>
            </filterItems>
            <filterItems>
                <field>Account.DataGovernanceStatus__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Product Alliance Partners</relationshipLabel>
        <relationshipName>ContractProductAlliancePartners</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Product Alliance Partners</relationshipLabel>
        <relationshipName>ContractProductAlliancePartners</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroupText__c</fullName>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Product Group</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contract Product Alliance Partner</label>
    <nameField>
        <displayFormat>CPAP-{000000}</displayFormat>
        <label>Contract Product Alliance Partner Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Alliance Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestmultiSelectPicklist.cls
//-----------------------------
// @author: Neelam Agrawal
// @date: 09 Mar 2022
// @param: NA
// @description: Test class for multiSelectPicklist class 
// @return: NA
//-----------------------------

@isTest(SeeAllData=false)
private class TestmultiSelectPicklist {
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test setup
    
    @testSetup static void setup() {
        User u1 = TestUtility.createAdminUser('adminuser@sfdc.test',true);
        User u2= TestUtility.createTestUser('IHSMarkit Customer Care','customercaretest@sfdc.test',true);
        User u3= TestUtility.createTestUser('Contract Manager','salescordinator@sfdc.test',true);
        ProductGroup__c pg = new ProductGroup__c();
        pg.Name = 'NRG';
        insert pg;
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
        a.Type = 'Global Alliance - Core';
        a.DataGovernanceStatus__c = 'Approved';
        insert a;
        Contact c = TestUtility.createContact(a.Id,'1test.2test@3test.com' ,true,'Test', 'testSetCaseAdditionalFieldsObject');
        
        //creating contract
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        testProd.ProductGroup__c=pg.Id;
        update testProd;
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract1.RecordTypeId = orderFormRecordTypeId;
        contract1.Fastrack__c = TRUE;
        Contract1.Status = 'Creation';
        contract1.ContractStatus__c = 'Open';
        insert contract1;
        
        ContractLineItem__c  cli= TestUtility.createContractLineItem('cli1',contract1.Id,testProd.Id,true);
        ContractProductAlliancePartner__c cpap = new ContractProductAlliancePartner__c();
        cpap.AlliancePartner__c = a.Id;
        cpap.ProductGroupText__c = pg.Id;
        cpap.Contract__c = contract1.Id;
        cpap.AlliancePartnerApprovalDate__c = System.today();
        insert cpap;
        
        ContractProductAlliancePartner__c cpap1 = new ContractProductAlliancePartner__c();
        cpap1.AlliancePartner__c = a.Id;
        cpap1.ProductGroupText__c = pg.Id;
        cpap1.Contract__c = contract1.Id;
        cpap1.AlliancePartnerApprovalDate__c = System.today();
    }
    
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test method for getProductGroup method
	// 
    static testmethod void testgetProductGroup(){
        test.startTest();
        Contract con= [Select Id from Contract Limit 1];
        List<String> productname = multiSelectPicklist.getProductGroup(con.Id);
        System.assertEquals(productname, new List<String>{'NRG'});
        test.stopTest();
    }
    
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test method for getProductGroupAlliance method
	// 
    static testmethod void testgetProductGroupAlliance(){
        test.startTest();
        ContractProductAlliancePartner__c conProductAlliance= [SELECT Id, ProductGroupText__c from ContractProductAlliancePartner__c Limit 1];
        List<String> ProductGroupName=multiSelectPicklist.getProductGroupAlliance(conProductAlliance.Id);
        System.assertEquals(ProductGroupName, new List<String>{conProductAlliance.ProductGroupText__c});
        List<String> ProductGroupName2=multiSelectPicklist.getProductGroupAll(conProductAlliance.Id);
        System.assertEquals(ProductGroupName2, new List<String>{'NRG'});    
        test.stopTest();
    }
    
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test method for getProfile method
	// 
    static testmethod void testgetProfile1(){
        test.startTest();
        User testUser1 = [SELECT Id,Username FROM User where username='customercaretest@sfdc.test'];
        System.runAs(testUser1) { 
        Boolean profiletype=multiSelectPicklist.getProfile();
        System.assertEquals(profiletype, true);
        }
        test.stopTest();
    }
    
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test method for getProfile method
	// 
    static testmethod void testgetProfile2() {              
		test.startTest();
        User testUser2 = [SELECT Id,Username FROM User where Email='adminuser@sfdc.test'];
        system.debug('testUser2' + testUser2);
        System.runAs(testUser2) { 
        Boolean profiletype=multiSelectPicklist.getProfile();
        System.assertEquals(profiletype, true);
        }
        test.stopTest();  
    }
    
    //-----------------------------
	// @author: Neelam Agrawal
	// @date: 09 Mar 2022
	// @param: NA
	// @description: Test method for getProfile method
	// 
    static testmethod void testgetProfile3() {      
        test.startTest();
        User testUser3 = [SELECT Id,Username FROM User where username='salescordinator@sfdc.test'];
        System.runAs(testUser3) { 
        Boolean profiletype=multiSelectPicklist.getProfile();
        System.assertEquals(profiletype, false);
        }
        test.stopTest();  
    }
}