objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <description>SFDC1-7046: related to Legacy ID and Legacy system, this field is a concatenation of those two fields to create a unique legacy UD that can be used as an external key for updates by the migration team, will not be visible to sales profiles to avoid confusion with related legacy ids object.
This field store the concatenation of the source system name and a source system record id to ensure the record is uniquely identified.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field store the concatenation of the source system name and a source system record id to ensure the record is uniquely identified.</inlineHelpText>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/FieldServiceActivityProduct__c.object
<CustomObject>
    <description>SFDC1-166.
Tracks products behind the Field Service Activities.</description>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-166.
Reference to the field service activity.</description>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <description>SFDC1-8596:Add Legacy Fields to the Fields Service Activity Product</description>
        <externalId>true</externalId>
        <inlineHelpText>This field stores the concatenation of the source system name and a source system record id to ensure the record is uniquely identified.</inlineHelpText>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6381: Changing the lookup from Product to Product group</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Service Activity Product</label>
    <nameField>
        <displayFormat>FSAPRD-{00000}</displayFormat>
        <label>Field Service Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <description>SFDC1-7046: Legacy ID Unique field is a concatenation of the source system name and a source system record id to ensure record is uniquely identified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Concatenation of the source system name and a source system record id to ensure the record is uniquely identified.</inlineHelpText>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestFieldServiceActivityProductDispatch.cls
@isTest
public class TestFieldServiceActivityProductDispatch {
    
     @isTest 
    static void testAfterInsertAndUpdate(){
        test.startTest();
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'test@test.com', true, 'test','data');
        ProductGroup__c pg = TestUtility.createProductGroup('MRO',false,false);
        WorkOrder workOrder = testUtility.createFieldServiceActivity(testContact.Id,true);
        FieldServiceActivityProduct__c fap = testUtility.createFSAProduct(workOrder.Id, pg.Id,true);     
        fap.LegacyIDUnique__c ='tEsTDaTa';
        update fap;
        test.stopTest();  
        FieldServiceActivityProductDispatcher.isAfterInsertProcessing = true;
        FieldServiceActivityProduct__c fap2 = testUtility.createFSAProduct(workOrder.Id, pg.Id,true);     
        FieldServiceActivityProductDispatcher.isAfterUpdateProcessing = true;
        fap2.LegacyIDUnique__c ='testDatefap2';
        update fap2;           
        system.assertEquals(fap.FieldServiceActivity__c, workOrder.Id);
        system.assertEquals(fap2.FieldServiceActivity__c, workOrder.Id);
        system.assertEquals(fap.LegacyIDUnique__c, 'tEsTDaTa');
    }
   
}