objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CMRelationship__c.object
<CustomObject>
    <description>SFDC1-2455 CM Relationships is used to track the Live CM Brokers on the Account Additional fields object</description>
    <fields>
        <fullName>BrokerContract__c</fullName>
        <description>SFDC1-2455 CM Relationships&apos; Broker Contract</description>
        <label>Broker Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CM Clients</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CM Relationship</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CM #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC-5711 : field created for better reporting.</description>
        <label>AAG</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InvoiceRemarks__c</fullName>
        <description>SFDC1-2252  This field will have information related to Invoice Remarks</description>
        <label>Invoice Remarks</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>AssociatedProduct__r.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestContractLineItemMethods.cls
@isTest
private class TestContractLineItemMethods {
    
    @isTest
    private static void testRollupProductInfoToContract() {
        
        TestBatchUpdateRollUpFieldOnParent.createTestCustomRollUpCustomSettings();
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount ;
        
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
        Test.startTest();
        ProductGroup__C pg1 = new ProductGroup__C(name = 'Test PG1');
        insert pg1;
         
        Product2 testProd = TestUtility.createProduct('Test Product', false);
        testProd.ProductGroup__c = pg1.Id;
        testProd.AAG__c = 'Subscription';
        
        insert testProd;
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id ofContractRecId = ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, testOpportunity.Id);
        List<Contract> ctList = [Select ProductGroup__c,AAG__c FROM Contract WHERE Id =:ofContractRecId];
        System.assertEquals('Test PG1', ctList.get(0).ProductGroup__c);
        List<ContractLineItem__c> cliList = [Select Id FROM ContractLineItem__c WHERE Contract__c =: ofContractRecId];
        delete cliList;
        Test.stopTest();
     }
	
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 06 Oct 2020
    // @description: SFDC-3403: Test method for lockCLIForCompletedContracts() method
    // @param: None
    // @return: None
    //-----------------------------
    @isTest
    private static void testLockCLIForCompletedContracts() {                        
        //Create Sales User
        Profile testSalesProfile = [SELECT Id ,name FROM Profile WHERE Name like '%Sales: General%' limit 1];        
        User testSalesUser = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = testSalesProfile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihsihs.com',ADID__c='adIdtest'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*123456)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*1324567)));
        insert testSalesUser;
        //Create Account
        Account testAcc = TestUtility.createTestAccount('Test 3403 Account', false);
        testAcc.DataGovernanceStatus__c = 'Approved';
        insert testAcc;
        //Create contact
        Contact testContact = TestUtility.createContact(testAcc.Id,'con1@externalorg.com',true,'Contact1','Test 3403 Account');
        //Create product and pricebook entry
        Product2 p1 = TestUtility.createProduct('Test SubProduct 1', true);
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        pbe1.CurrencyIsoCode = 'USD';
        insert pbe1;
        //Create opprtunity
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        Opportunity testOpportunity = TestUtility.createOpportunity(testAcc.Id, '3403 NewBiz Opp1', false);
		testOpportunity.ContractStartDate__c = date.newinstance(currentFY, 03, 20);
		testOpportunity.ContractEndDate__c = date.newinstance(currentFY+3, 03, 19);
        testOpportunity.OwnerId = testSalesUser.Id;
        testOpportunity.ActivityCreated__c = true;
        insert testOpportunity;        
        //Create opportunity line item
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, pbe1, true);
        //Create primary opportunity contact
        OpportunityContactRole primaryOCR = new OpportunityContactRole(OpportunityId=testOpportunity.Id,ContactId=testContact.Id,IsPrimary=true);
        insert primaryOCR;
                
        Test.startTest();
        Id orderFormRecordTypeId =  Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        //Create contract
        Id contractOrderformRecId =  ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, testOpportunity.Id);
        
        //Mark Contract as complete
        Contract testContract = new Contract(Id=contractOrderformRecId);
        TestUtility.createContractAttachment(testContract.id);        
        TestUtility.markContractAsComplete(testContract, true);
        
        //Query CLI
        ContractLineItem__c testCLI = [SELECT Id,Name,Contract__r.Status FROM ContractLineItem__c WHERE Contract__c=:testContract.Id LIMIT 1];
        
        UtilityClass.LoggedInUserProfileName = null;
        System.runAs(testSalesUser) {
            try {
                //Update a non-calculated field on CLI as Sales General user
                testCLI.InvoiceRemarks__c = 'test';
                update testCLI;
                System.assert(false,'Control should not reach here. CLI Lock validation exception not thrown.');
            }
            catch(DMLException ex) {
                System.assertEquals('Contract Line Items are locked for editing after stage is completed',ex.getDmlMessage(0),'Contract Line Items locked validation exception should have occurred.');
            }            
        }
        Test.stopTest();
     }
    //-----------------------------
    // @author: Digvijay Singh
    // @date: 3 May 2021
    // @description: SFDC-4069: Test method for preventContractLineItemDeletion() method
    // @param: None
    // @return: None
    //-----------------------------
    @isTest
    private static void testCLIDeletion() {
        //Create Sales User
       Profile testSalesProfile = [SELECT Id ,name FROM Profile WHERE Name like '%Sales: General%' limit 1];        
       User testSalesUser = new User(Alias = 'standt', Email='standarduser@testorg.com', 
           EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
           LocaleSidKey='en_US', ProfileId = testSalesProfile.Id, 
           TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihsihs.com',ADID__c='adIdtest'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*123456)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*1324567)));
       insert testSalesUser;
       
      
       //Create Account
       Account testAcc = TestUtility.createTestAccount('Test 3403 Account', false);
       testAcc.DataGovernanceStatus__c = 'Approved';
       insert testAcc;
       //Create contact
       Contact testContact = TestUtility.createContact(testAcc.Id,'con1@externalorg.com',true,'Contact1','Test 3403 Account');
       //Create product and pricebook entry
       Product2 p1 = TestUtility.createProduct('Test SubProduct 1', true);
       Id stdPricebookId = Test.getStandardPricebookId();
       PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
       pbe1.CurrencyIsoCode = 'USD';
       insert pbe1;
       //Create opprtunity
       Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
       Opportunity testOpportunity = TestUtility.createOpportunity(testAcc.Id, '3403 NewBiz Opp1', false);
       testOpportunity.ContractStartDate__c = date.newinstance(currentFY, 03, 20);
       testOpportunity.ContractEndDate__c = date.newinstance(currentFY+3, 03, 19);
       testOpportunity.OwnerId = testSalesUser.Id;
       testOpportunity.ActivityCreated__c = true;
       insert testOpportunity;        
       //Create opportunity line item
       OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, pbe1, true);
       //Create primary opportunity contact
       OpportunityContactRole primaryOCR = new OpportunityContactRole(OpportunityId=testOpportunity.Id,ContactId=testContact.Id,IsPrimary=true);
       insert primaryOCR;
               
       Test.startTest();
       Id orderFormRecordTypeId =  Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
       //Create contract
       Id contractOrderformRecId =  ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, testOpportunity.Id);
       
       //Mark Contract as complete
       Contract testContract = new Contract(Id=contractOrderformRecId);
       TestUtility.createContractAttachment(testContract.id);  
       TestUtility.markContractAsComplete(testContract, true);
       
       //Query CLI
       ContractLineItem__c testCLI = [SELECT Id,Name,Contract__r.Status FROM ContractLineItem__c WHERE Contract__c=:testContract.Id LIMIT 1];
       
       UtilityClass.LoggedInUserProfileName = null;
       System.runAs(testSalesUser) {
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name =: System.Label.ContractLineItemEditAccessPermissionSet];
        insert new PermissionSetAssignment(AssigneeId = testSalesUser.id, PermissionSetId = ps.Id);
        
           try {
               //Update a non-calculated field on CLI as Sales General user
               delete  testCLI;
           }
           catch(DMLException ex) {
               System.assertEquals('You are not authorized to Delete a Contract Line Item.',ex.getDmlMessage(0));
           }            
       }
       Test.stopTest();
    }
}