objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC-5711 : field created for better reporting.</description>
        <label>AAG</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-718;Only on Contract Type = Order Form</description>
        <label>PO Required</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-662- End date of the Contract to which this contact attachment is associated</description>
        <formula>Contract__r.EndDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Read-only field: End date of the Contract to which this contact attachment is associated</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-662- Start date of the Contract to which this contact attachment is associated</description>
        <formula>Contract__r.StartDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Read-only field: Start date of the Contract to which this contact attachment is associated</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1- 535 ;Checkbox fields on opportunity which is automatically populated from Account, SFDC1-959 : Added &apos;?&apos; to the Label.</description>
        <label>PO Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store primary contact name at Opportunity record level.</description>
        <inlineHelpText>To store primary contact name at Opportunity record level.</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>SFDC1-6958: Global Segment field will be populated from the SAP Product Master and incorporated with the load to keep products in sync.</description>
        <inlineHelpText>Reporting Global Segment</inlineHelpText>
        <label>Global Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchToCreatePOContractAttachment.cls
@isTest
public class TestBatchToCreatePOContractAttachment {
    //-----------------------------
    // @author: Sharique
    // @date: 24 May 2021
    // @description: SFDC-3186 Setup test data for the  batch class
    // @param: none
    // @return: void
    //-----------------------------
    @testSetup 
    public static void createTestData() {
                
        //Account
        Account testAcc = TestUtility.createTestAccount('Test 3186 Account', false);
        testAcc.DataGovernanceStatus__c = 'Approved';
        insert testAcc;
                
        //Contact
        List<Contact> contactList = new List<Contact>();
        Contact testCon1 = TestUtility.createContact(testAcc.Id,'con1@externalorg.com',false,'Contact1','Test 3186 Account');
        contactList.add(testCon1);
        Contact testCon2 = TestUtility.createContact(testAcc.Id,'con2@externalorg.com',false,'Contact2','Test 3186 Account');
        contactList.add(testCon2);
        insert contactList;
        
        //Users
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u1 = new User(Alias = 'adm1', Email='admin1user3186@test.com', 
                          EmailEncodingKey='UTF-8', firstName='test1',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admin1user3186@test.com',ADID__c='test1'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        
        User u2 = new User(Alias = 'adm2', Email='admin2user3186@test.com', 
                          EmailEncodingKey='UTF-8', firstName='test2',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admin2user3186@test.com',ADID__c='test2'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert new List<User> {u1,u2};
                
        //Legal Entity
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHSM test legalEntity', 'USD'); 
                
        //Products - Set Global Segment and AAG
        Product2 p1 = TestUtility.createProduct('Test SubProduct 1', false);
        p1.DiscountThreshold__c = 10;
        p1.LegalEntity__c = testLegalEntity.Id;
        p1.AAG__c = 'Subscription';
        p1.Division__c = 'Financial Svcs-Info';
        Product2 p2 = TestUtility.createProduct('Test SubProduct 2', false);
        p2.DiscountThreshold__c = 12;
        p2.LegalEntity__c = testLegalEntity.Id;
        p2.AAG__c = 'SubscriptionVar';
        p2.Division__c = 'Financial Svcs-Info';
        Product2 p3 = TestUtility.createProduct('Test NonFin Product 3', false);
        p3.DiscountThreshold__c = 12;
        p3.LegalEntity__c = testLegalEntity.Id;
        p3.AAG__c = 'SubscriptionVar';
        p3.Division__c = 'Resources';        
        insert new List<Product2>{p1,p2,p3};
                    
        //Price Book Entry        
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
        PricebookEntry pbe3 = TestUtility.createPriceBookEntry(stdPricebookId, p3.Id, false);
        pbe1.CurrencyIsoCode = 'USD';
        pbe2.CurrencyIsoCode = 'USD';
        pbe3.CurrencyIsoCode = 'USD';
        insert new List<PricebookEntry>{pbe1,pbe2,pbe3};
        
        //Create New Business Opp        
        List<Opportunity> testOppList = new List<Opportunity>();
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        Opportunity testOpp1 = TestUtility.createOpportunity(testAcc.Id, '3186+ NewBiz Opp1', false);
        testOpp1.ContractStartDate__c = system.today();//date.newinstance(currentFY, 03, 20);
        testOpp1.ContractEndDate__c = date.newinstance(currentFY+3, 03, 19);
        testOpp1.PrimaryContact__c = 'test1 HS';
        testOppList.add(testOpp1);
        Opportunity testOpp2 = TestUtility.createOpportunity(testAcc.Id, '3186+ NewBiz Opp2', false);
        testOpp2.ContractStartDate__c = system.today();//date.newinstance(currentFY, 03, 20);
        testOpp2.ContractEndDate__c = date.newinstance(currentFY+3, 03, 19);
        testOpp2.PrimaryContact__c = 'test1 HS';
        testOppList.add(testOpp2);
        insert testOppList;
        
        //Add opp products
        OpportunityLineItem opp1testOLI1 = TestUtility.createOpportunityLineItem(testOpp1.Id, pbe1, false);
        opp1testOLI1.Product2Id = p1.Id;
        OpportunityLineItem opp1testOLI2 = TestUtility.createOpportunityLineItem(testOpp1.Id, pbe2, false);
        opp1testOLI2.Product2Id = p2.Id;
        OpportunityLineItem opp2testOLI1 = TestUtility.createOpportunityLineItem(testOpp2.Id, pbe1, false);
        opp2testOLI1.Product2Id = p1.Id;
        OpportunityLineItem opp2testOLI2 = TestUtility.createOpportunityLineItem(testOpp2.Id, pbe2, false);
        opp2testOLI2.Product2Id = p2.Id;
        OpportunityLineItem opp2testOLI3 = TestUtility.createOpportunityLineItem(testOpp2.Id, pbe3, false);
        opp2testOLI3.Product2Id = p3.Id;
        List<OpportunityLineItem> testOliList = new List<OpportunityLineItem> {opp1testOLI1,opp1testOLI2,opp2testOLI1,opp2testOLI2,opp2testOLI3};
        insert testOliList;
                       
        //Add Splits, Team, OCR to opp
        List<OpportunityContactRole> ocrList = new List<OpportunityContactRole>();
        OpportunityContactRole primaryOCROpp1 = new OpportunityContactRole(OpportunityId=testOpp1.Id,ContactId=testCon1.Id,IsPrimary=true);
        ocrList.add(primaryOCROpp1);
        OpportunityContactRole primaryOCROpp2 = new OpportunityContactRole(OpportunityId=testOpp2.Id,ContactId=testCon2.Id,IsPrimary=true);
        ocrList.add(primaryOCROpp2);
        insert ocrList;
                
        //Create contract
        Id ofRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId(); 
        Contract testContractOpp1 = TestUtility.createContractWithInsertOptional(testAcc.Id, testLegalEntity.Id, null, stdPricebookId,false );
        testContractOpp1.Opportunity__c = testOpp1.Id;
        testContractOpp1.PORequired__c = true;
        testContractOpp1.status = 'Draft';
        testContractOpp1.ContractStatus__c = 'Open';
        testContractOpp1.Startdate =  System.today().addMonths(1);
        testContractOpp1.EffectiveDate__c = System.today().addMonths(1); //System.today().addMonths(-11);
        testContractOpp1.Enddate = System.today().addMonths(13);
        testContractOpp1.RecordTypeId = ofRecordTypeId;
        
        Contract testContractOpp11 = TestUtility.createContractWithInsertOptional(testAcc.Id, testLegalEntity.Id, null, stdPricebookId,false );
        testContractOpp11.Opportunity__c = testOpp1.Id;
        testContractOpp11.PORequired__c = true;
        testContractOpp11.status = 'Draft';
        testContractOpp11.ContractStatus__c = 'Open';
        testContractOpp11.Startdate =  System.today().addYears(-2).addMonths(1);
        testContractOpp11.EffectiveDate__c =  System.today().addYears(-2).addMonths(1);
        testContractOpp11.Enddate = System.today().addYears(-1).addMonths(1);
        testContractOpp11.RecordTypeId = ofRecordTypeId;
        
        Contract testContractOpp2 = TestUtility.createContractWithInsertOptional(testAcc.Id, testLegalEntity.Id, null, stdPricebookId,false );
        testContractOpp2.Opportunity__c = testOpp1.Id;
        testContractOpp2.PORequired__c = true;
        testContractOpp2.status = 'Draft';
        testContractOpp2.ContractStatus__c = 'Open';
        testContractOpp2.Startdate =  System.today().addYears(-2).addMonths(1);
        testContractOpp2.EffectiveDate__c = System.today().addYears(-2).addMonths(1);
        testContractOpp2.Enddate = System.today().addYears(2).addMonths(1);
        testContractOpp2.RecordTypeId = ofRecordTypeId;
        
        Contract testContractOpp3 = TestUtility.createContractWithInsertOptional(testAcc.Id, testLegalEntity.Id, null, stdPricebookId,false );
        testContractOpp3.Opportunity__c = testOpp1.Id;
        testContractOpp3.PORequired__c = true;
        testContractOpp3.status = 'Draft';
        testContractOpp3.ContractStatus__c = 'Open';
        testContractOpp3.Startdate =  System.today().addYears(-1);
        testContractOpp3.EffectiveDate__c =  System.today().addYears(-1);
        testContractOpp3.Enddate = System.today().addYears(2);
        testContractOpp3.CACreationDate__c = System.today();
        testContractOpp3.RecordTypeId = ofRecordTypeId;
        
        insert new List<Contract> {testContractOpp1,testContractOpp11,testContractOpp2,testContractOpp3};
    }
    
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 26 May 2021
    // @description: SFDC-2539 Main test method for the batch class
    // @param: none
    // @return: void
    //-----------------------------
    @isTest
    private static void testMethodGenerateContractAttach() {
       
        List <Contract> testContractList = new List <Contract>();
        for(Contract crt : [SELECT Id,Recordtype.Name,ContractStatus__c,status,PORequired__c, StartDate, EndDate, Renewaldate__c, CACreationDate__c, POAttached__c, Active__c,Account.Name FROM Contract]) {
          crt.ContractStatus__c = 'Validated';
          crt.OrderReason__c = 'New';
          crt.BillingFrequency__c = 'Annual';
          crt.UsageReportsRequired__c = 'No';
          crt.RenewalTerm__c = '1 Year';
          crt.RenewalDate__c = System.today().addYears(4);
          testContractList.add(crt);
        } 
        TestUtility.createMultiContractAttachment(testContractList);
        Test.startTest();
        update testContractList;
        
        //Execute Batch
        BatchToCreateContractAttachment obj=new BatchToCreateContractAttachment();
        Id batchJobId=Database.executeBatch(obj);
        System.debug('batch Id='+batchJobId);
        List <ContractAttachment__c> contractAtt = [Select id from ContractAttachment__c];
        Test.stopTest();
        System.assertEquals(True, contractAtt.size() > 0, 'No Contract Attachment was created');
       
    }
}