objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Opportunity</description>
        <inlineHelpText>Opportunity number of the publication fee to which this claim is related</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Businessline__c</fullName>
        <description>SFDC-1346 field to store comma separated values of business lines derived from contract line items</description>
        <inlineHelpText>Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <description>SFDC1-2060 Contract Status fields
SFDC1-7222: Adding picklist value &quot;Waiting on PO&quot;</description>
        <inlineHelpText>Please select from dropdown menu</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Signed By Customer</fullName>
                    <label>Signed by Customer</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validated PO Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-POD Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-BSI Pending</fullName>
                </value>
                <value>
                    <fullName>Validated by ConsOps</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Sent to Delivery</fullName>
                </value>
                <value>
                    <fullName>Sent to OM/Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered to Customer</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved &amp; Processed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Unscheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                    <isActive>false</isActive>
                    <label>Received</label>
                </value>
                <value>
                    <fullName>Sent To OM</fullName>
                    <isActive>false</isActive>
                    <label>Sent To OM</label>
                </value>
                <value>
                    <fullName>Sent for Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Sent for Delivery</label>
                </value>
                <value>
                    <fullName>Waiting on PO</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on PO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AverageDiscountPercentage__c</fullName>
        <description>SFDC1-4275 Average discount percent rolled up from Opportunity product</description>
        <inlineHelpText>Average Discount Percentage on all products</inlineHelpText>
        <label>Average Discount Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CompetitorName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-3965 When an opportunity is marked as lost with Lost Reason Code as Competition, make this field mandatory</description>
        <inlineHelpText>Who did we lose this opportunity to?  Select from dropdown or enter if missing</inlineHelpText>
        <label>Competitor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Competitor Name)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.
SFDC-1896 Updated filter criteria for Consulting record type</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountOverThreshold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4275 Checkbox to indicate if any of the products related to opportunity have crossed discount threshold</description>
        <inlineHelpText>Checked if product(s) are discounted over threshold</inlineHelpText>
        <label>Discount Over Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstYearValue__c</fullName>
        <description>SFDC1-4275 First year total price value rolled up from Opportunity Products</description>
        <inlineHelpText>First Year Contract Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MultiYear__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-54 field to track if opportunity has multi-year schedules.</description>
        <inlineHelpText>Populates from the Products if term of contract is greater than or equal to 2 years</inlineHelpText>
        <label>MultiYear</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousFiscalYearOpportunityLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will take you to the Last fiscal year or the most recent Oppy link</description>
        <inlineHelpText>This field will take you to the Last fiscal year or the most recent Oppy link</inlineHelpText>
        <label>Previous Fiscal Year Opportunity Link</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Previous Fiscal Year Opportunity Link)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReplacementOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-2439 Field to hold the Replacement Opportunity when Closed Lost Reason is Duplicated/Replaced</description>
        <inlineHelpText>Replacement Opportunity field for closed lost opportunities where the Lost Code is &quot;Duplicate/Existing Opp&quot;</inlineHelpText>
        <label>Replacement Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Replacement Opportunity)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchUpdatePriorYearOppyLink.cls
//@author: Kanika Miglani
// @date: 25th April 2023
// @description: Batch apex to update the Prior Year Oppy Link on opportunity reporting since FY 2021.
//---------------------------------------------------------------------------------------------------------------------------
global class BatchUpdatePriorYearOppyLink implements Database.Batchable<sobject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {   
        DateTime testingStartDate = DateTime.ValueofGmt('2022-09-01 00:02:00'); 
        DateTime testingEndDate = DateTime.ValueofGmt('2022-09-02 00:00:00'); 
        //String query = 'SELECT Id, BusinessLine__c, AverageDiscountPercentage__c,AccountId,CreatedDate,CloseDate,ContractStartDate__c,ContractBeingRenewed__c,PreviousFiscalYearOpportunityLink__c,FirstYearValue__c, DiscountOverThreshold__c, MultiYear__c,ContractBeingRenewed__r.Opportunity__c,Account.DataGovernanceStatus__c FROM Opportunity where PreviousFiscalYearOpportunityLink__c = null AND ( RecordType.name = \'Renewal\' OR RecordType.name = \'Inner Year\') AND createdDate = LAST_N_MONTHS:12';
        String query = 'SELECT Id, BusinessLine__c,AccountId,CreatedDate,CloseDate,ContractStartDate__c,ContractBeingRenewed__c,PreviousFiscalYearOpportunityLink__c,FirstYearValue__c FROM Opportunity where ( RecordType.name = \'Renewal\' OR RecordType.name = \'Inner Year\') AND ContractStartDate__c >= LAST_N_YEARS:2 AND PreviousFiscalYearOpportunityLink__c=null AND ContractBeingRenewed__c!=null';
        return Database.getQueryLocator(query);  
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope)  {  
        try{
            Map<Id,Map<Date,Opportunity>> contractOpportunityMap = new Map<Id,Map<Date,Opportunity>>();
            Map<id,contract> oppyInContract=new Map<id,contract>();
            list<Opportunity> listOpportunityToUpdate = new List<Opportunity>();
            set<Id> setOfOriginatingContract = new set<Id>();
             List<Contract> contractWithOpportunities = new List<Contract>();
            system.debug('scope->'+scope); 
            
            for(Opportunity opp : scope) {
                //Process only Automotive Insights Oppies
                if(opp.BusinessLine__c!=null){
                if(opp.BusinessLine__c.contains('Automotive Insights')) {
                	setOfOriginatingContract.add(opp.ContractBeingRenewed__c);
                }
                }
            }
      //      system.debug('setOfOriginatingContract---'+setOfOriginatingContract);
            if(setOfOriginatingContract!=null){    
            for(Contract lstCon : [Select Id,StartDate,ContractStatus__c,Opportunity__c,Opportunity__r.ContractStartDate__c,
                                                          (Select id,BusinessLine__c,ContractBeingRenewed__r.Opportunity__c,AverageDiscountPercentage__c,AccountId,CloseDate,ContractStartDate__c,ContractBeingRenewed__c,PreviousFiscalYearOpportunityLink__c from Opportunities2__r order by ContractStartDate__c)
                                                          from contract where ID IN:setOfOriginatingContract])
            {
            //   Contract con = new Contract(lstCon);
                 contractWithOpportunities.add(lstCon);                
                
            }
           //     system.debug('inside-->contractWithOpportunities'+contractWithOpportunities);
                if(contractWithOpportunities!=null && !contractWithOpportunities.isEmpty()){
                    for(Contract con : contractWithOpportunities){
                        if(!contractOpportunityMap.containsKey(con.Id)){
                            Map<Date,Opportunity> opportunityStartDateMap= new Map<Date,Opportunity>();
                            if(!oppyInContract.containsKey(con.Id)){
                            	oppyInContract.put(con.id,con);
                                system.debug('oppyInContract'+oppyInContract);
                            }
                            if(con.Opportunities2__r != null) {
                                system.debug('con.Opportunities2__r'+con.Opportunities2__r);
                                for(Opportunity renewalOppy : con.Opportunities2__r){
                                    if(renewalOppy.ContractStartDate__c!=null){
                                        opportunityStartDateMap.put(renewalOppy.ContractStartDate__c,renewalOppy);
                                        system.debug('opportunityStartDateMap'+opportunityStartDateMap);
                                        system.debug('renewalOppy.ContractStartDate__c'+renewalOppy.ContractStartDate__c);
                                        system.debug('renewalOppy'+renewalOppy);
                                    } 
                                }
                                if(opportunityStartDateMap!=null){
                                    contractOpportunityMap.put(con.Id,opportunityStartDateMap);
                                    system.debug('contractOpportunityMap'+contractOpportunityMap);
                                }
                            }
                        }
                        
                    }
                    
                    if(contractOpportunityMap!=null){
                      //  System.debug('inside-->contractOpportunityMap'+contractOpportunityMap);
                        for(Opportunity oppy: scope) {
                            if(oppy.BusinessLine__c!=null){
                            if(oppy.BusinessLine__c.contains('Automotive Insights')) {
                                if(oppy.PreviousFiscalYearOpportunityLink__c==null) {
                             //       system.debug('contractOpportunityMap.containsKey(oppy.ContractBeingRenewed__c)'+contractOpportunityMap.containsKey(oppy.ContractBeingRenewed__c));
                             //       system.debug('oppy.ContractBeingRenewed__c'+oppy.ContractBeingRenewed__c);
                                    if(contractOpportunityMap.containsKey(oppy.ContractBeingRenewed__c))
                                    {
                                        system.debug('inside-->contractBeingRenewed__c');
                                        Map<Date,Opportunity> opportunityContractStartDateMap= new Map<Date,Opportunity>();
                                        
                                        //wrapper list
                                         List<OppyDetailsWrapper> lstOppyDetailWrap=new List<OppyDetailsWrapper>();
                                        
                                        opportunityContractStartDateMap=contractOpportunityMap.get(oppy.ContractBeingRenewed__c);
                                        if(opportunityContractStartDateMap!=null){
                                         //   system.debug('inside-->opportunityContractStartDateMap');
                                         //   Date minDate=oppy.ContractStartDate__c;
                                          //  String OppyIdInContract='';
                                            for(Date oppyContractStartDate: opportunityContractStartDateMap.keySet()){
                                                OppyDetailsWrapper objOppyDetailWrap = new OppyDetailsWrapper(opportunityContractStartDateMap.get(oppyContractStartDate).Id,oppyContractStartDate);                               
                                                    lstOppyDetailWrap.add(objOppyDetailWrap);
         
                                            }
                                            if(oppyInContract.containsKey(oppy.ContractBeingRenewed__c) && (oppy.Id!=oppyInContract.get(oppy.ContractBeingRenewed__c).id))
                                            {
                                                OppyDetailsWrapper objOppyDetailWrap1 = new OppyDetailsWrapper(oppyInContract.get(oppy.ContractBeingRenewed__c).Opportunity__c,oppyInContract.get(oppy.ContractBeingRenewed__c).Opportunity__r.ContractStartDate__c);                               
                                                lstOppyDetailWrap.add(objOppyDetailWrap1); 
                                            }
                                            
                                              //Sorting and updating previous fiscal year oppy link
                                            
                                            if(lstOppyDetailWrap != null && !lstOppyDetailWrap.isEmpty()){
                                                lstOppyDetailWrap.sort();
                                                System.debug('wrapper-->'+lstOppyDetailWrap);
                                                integer i=0;
                                                ID previousOppyLink=null;
                                                for(OppyDetailsWrapper wrapper : lstOppyDetailWrap)
                                                {
                                                    if(i==0)
                                                    {
                                                        previousOppyLink=wrapper.oppyId;
                                                        i++;
                                                    }
                                                    else{
                                                        if(wrapper.oppyId==oppy.Id)
                                                        {
                                                            oppy.PreviousFiscalYearOpportunityLink__c=previousOppyLink;
                                                            break;
                                                        }
                                                        previousOppyLink=wrapper.oppyId;
                                                    }       
                                                }
                                            }
                                        }
                                    }
                                }
                                if(oppy.PreviousFiscalYearOpportunityLink__c!=null){
                                    listOpportunityToUpdate.add(oppy);  
                                }
                            }
                            }
                        }
                    }
                }
        }
             if(listOpportunityToUpdate!=null && !listOpportunityToUpdate.isEmpty()) {
                    Database.update(listOpportunityToUpdate,false);
                }
            }
        catch(Exception ex) {
            System.debug('Exception caught in batch' + ex.getMessage());
            UtilityClass.createApexLogRecord(ex, 'BatchUpdatePriorYearOppyLink', 'Execute');       
        }

    }
    
    global void finish(Database.BatchableContext bc) {
        System.debug(LoggingLevel.INFO, 'BatchUpdatePriorYearOppyLink batch completed');
     }
  }