objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AssociatedwithResponseManagementTeam__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4476 : this field shows if Opportunity is Associated with Response Management Team</description>
        <label>Associated with Response Management Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SystemMutedTriggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SFDC1-405 This Custom Settings is used by Trigger Framework to switch trigger on/off for individual user/whole org.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-405 To switch opportunity object triggers on/off</description>
        <inlineHelpText>Check to switch opportunity object triggers on</inlineHelpText>
        <label>Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <label>System Muted Triggers</label>
</CustomObject>

objects/SystemMutedValidationRules__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <label>System Muted Validation Rules</label>
</CustomObject>

classes/TestAccessToResponseMgmtTeamController.cls
//-----------------------------
// @author: Sharique Iqbal
// @date: 4th Fev 2022
// @param: NA
// @description: Test Class for AccessToResponseManagementTeamController

@isTest
public class TestAccessToResponseMgmtTeamController {
     
    @isTest
     static void testupdateAssociatedWithResMmtTeam() { 
		
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
    	Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Oppy', false);
        testOpportunity.ContractStartDate__c = 	date.newinstance(currentFY, 03,21 );
        testOpportunity.ContractEndDate__c = date.newinstance(currentFY+2, 10, 21);
        insert testOpportunity;
        
        Test.startTest(); 
        AccessToResponseManagementTeamController.updateAssociatedWithResMmtTeam (testOpportunity.Id, True);
        Test.stopTest();
         
        Opportunity  oppy = [Select Id,AssociatedwithResponseManagementTeam__c from Opportunity where Name= 'test Oppy']; 
        System.assertEquals(True, oppy.AssociatedwithResponseManagementTeam__c, 'Opportunity was not updated!!');  
     }
    
    @isTest
     static void testupdateAssociatedWithResMmtTeamWithCSRec() { 
		  
        Id currentUserId = UserInfo.getUserId();
        SystemMutedValidationRules__c smve = SystemMutedValidationRules__c.getInstance(currentUserId);
        smve.Opportunity__c = false;//SFDC-5428
        insert smve; 
        SystemMutedTriggers__c smt = SystemMutedTriggers__c.getInstance(currentUserId);
        smt.Opportunity__c = false;//SFDC-5428
        insert smt;

        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
    	Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Oppy', false);
        testOpportunity.ContractStartDate__c = 	date.newinstance(currentFY, 03,21 );
        testOpportunity.ContractEndDate__c = date.newinstance(currentFY+2, 10, 21);
        insert testOpportunity;
        
        Test.startTest(); 
        AccessToResponseManagementTeamController.updateAssociatedWithResMmtTeam (testOpportunity.Id, True);
        Test.stopTest();
        
        Opportunity  oppy = [Select Id,AssociatedwithResponseManagementTeam__c from Opportunity where Name= 'test Oppy']; 
        System.assertEquals(True, oppy.AssociatedwithResponseManagementTeam__c, 'Opportunity was not updated!!'); 
     }     
}