objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Fastrack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5851 Checkbox on &quot;Order From&quot; contracts
SFDC1-10429:Update Fastrack to Fast Track</description>
        <inlineHelpText>Use Fast Track terms and conditions if under $100k</inlineHelpText>
        <label>Fast Track</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DocuSignEnvelopeId__c</fullName>
        <description>SFDC1-662 DocuSign envelope ID if the contract  attachment is of DocuSign type</description>
        <externalId>true</externalId>
        <inlineHelpText>System managed: DocuSign envelope ID if the contract  attachment is of DocuSign type</inlineHelpText>
        <label>DocuSign Envelope Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/dsfs__DocuSign_Recipient_Status__c.object
<CustomObject>
    <description>Information about a Recipient on a DocuSign Envelope. This is a child object of DocuSign Status</description>
    <fields>
        <fullName>dsfs__DocuSign_Recipient_Email__c</fullName>
        <description>The email address that the recipient used in the DocuSign System.</description>
        <label>DocuSign Recipient Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>dsfs__DocuSign_Recipient_Id__c</fullName>
        <externalId>true</externalId>
        <label>DocuSign Recipient Id</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Envelope_Id__c</fullName>
        <description>The DocuSign EnvelopeId that this Recipient is related to</description>
        <label>Envelope Id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Parent_Status_Record__c</fullName>
        <label>DocuSign Status Record</label>
        <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
        <relationshipLabel>DocuSign Recipient Status</relationshipLabel>
        <relationshipName>R00NS0000000WUO2MAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>dsfs__Recipient_Status__c</fullName>
        <description>The last status reported by the DocuSign System for this recipient</description>
        <label>Recipient Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Recipient Status</label>
    <nameField>
        <label>DocuSign Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>dsfs__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>R00N80000002eb1GEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>R00N80000002vvynEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__DocuSign_Envelope_ID__c</fullName>
        <label>DocuSign Envelope ID</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Sender__c</fullName>
        <label>Sender</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestdsfsDocuSignRecipientStatusMethods.cls
//-----------------------------
// @author: Ankita Singh
// @date: 11 April 2018
// @param: NA
// @description: Test class for Docu Sign Recipient Status trigger methods 
// @return: NA
// @Last Modified By: Harshit Singhal
// @Last Modified Date: 13 Nov 2019
// @Description: SFDC-2037 Cleaned up test class as per valid scenarios in DocusignRecipientStatus trigger code
//-----------------------------

@isTest
private class TestdsfsDocuSignRecipientStatusMethods{
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 13 Nov 2019
    // @param: NA
    // @description:SFDC-2037 Test coverage for updateContractAttachmentType() and createContractAttachmentFilesFromDocusignStatus() methods in dsfsDocuSignRecipientStatusMethods class. Testing by Continuation Letter contract.
    //-----------------------------
    @isTest
    private static void testDocusignFlowForContinuationLetter() {
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id CLRecordTypeId = ContractMethods.continuationLetterRecordTypeId;
        //LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = CLRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        //creating docusign status and docusign Recipient status object record
        Test.startTest();
        
        dsfs__DocuSign_Status__c ds = new dsfs__DocuSign_Status__c();
        ds.dsfs__Subject__c = 'Please sign the document';
        ds.dsfs__Sender__c = 'Sales';
        ds.dsfs__Contract__c = contract.id;
        ds.dsfs__Company__c = testAccount.id;
        ds.dsfs__DocuSign_Envelope_ID__c = 'B1F8E324-D40E-415B-8CCD-185EAF4DWXYZ';
        insert ds;
        
        Attachment testAtt = new Attachment();
        testAtt.Body = Blob.valueOf('This is test attachment');
        testAtt.Name = String.valueOf('TestContinuationAttachment.pdf');
        testAtt.ParentId = ds.Id;
        insert testAtt;
                
        dsfs__DocuSign_Recipient_Status__c drsCustomer = new dsfs__DocuSign_Recipient_Status__c();
        drsCustomer.dsfs__Parent_Status_Record__c = ds.id;
        drsCustomer.Name='Customer';
        drsCustomer.dsfs__DocuSign_Recipient_Email__c = 'test@yahoo.com';
        drsCustomer.dsfs__Recipient_Status__c = 'Sent';
        drsCustomer.dsfs__DocuSign_Recipient_Id__c = 'B1F8E324-D40E-415B-8CCD-185EAF4DWXYZ';
        drsCustomer.dsfs__Envelope_Id__c = ds.dsfs__DocuSign_Envelope_ID__c;
        insert drsCustomer;
        
        ContractAttachment__c sentConAttachment = [SELECT Id, AttachmentType__c FROM ContractAttachment__c WHERE DocuSignEnvelopeId__c=:ds.dsfs__DocuSign_Envelope_ID__c Limit 1];
        String sentContractAttachmentType = sentConAttachment.AttachmentType__c;
        System.assertEquals('Continuation Letter', sentContractAttachmentType, 'Verifying if the Sent Contract Attachment Type is populated correctly');
        
        List<ContentVersion> sentFiles = [Select Id From ContentVersion Where FirstPublishLocationId=:sentConAttachment.Id];
        System.assertEquals(1,sentFiles.size(), 'Verifying if the first file is attached successfully');
        
        //Simulate customer sign by updating dsfs__Recipient_Status__c to 'Completed'
        drsCustomer.dsfs__Recipient_Status__c = 'Completed';
        update drsCustomer;
        
        ContractAttachment__c signedConAttachment = [SELECT Id, AttachmentType__c FROM ContractAttachment__c WHERE DocuSignEnvelopeId__c=:ds.dsfs__DocuSign_Envelope_ID__c Limit 1];
        String signedContractAttachmentType = signedConAttachment.AttachmentType__c;
        System.assertEquals('Signed Continuation Letter', signedContractAttachmentType, 'Verifying if the Signed Contract Attachment Type is populated correctly');
        
        List<ContentVersion> sentAndSignedFiles = [Select Id From ContentVersion Where FirstPublishLocationId=:signedConAttachment.Id];
        System.assertEquals(2,sentAndSignedFiles.size(), 'Verifying if the second file is attached successfully');
        
        Test.stopTest();
    }
	
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 13 Nov 2019
    // @param: NA
    // @description:SFDC-2037 Test coverage for changeContractStatus() and createContractAttachmentFilesFromDocusignStatus() methods in dsfsDocuSignRecipientStatusMethods class. Testing by Order Form contract. 
    //-----------------------------
    @isTest
    private static void testChangeContractStatus() {
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id OFRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = OFRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        //creating docusign status and docusign Recipient status object record
        Test.startTest();
        
        dsfs__DocuSign_Status__c ds = new dsfs__DocuSign_Status__c();
        ds.dsfs__Subject__c = 'Please sign the document';
        ds.dsfs__Sender__c = 'Sales';
        ds.dsfs__Contract__c = contract.id;
        ds.dsfs__Company__c = testAccount.id;
        ds.dsfs__DocuSign_Envelope_ID__c = 'B1F8E324-D40E-415B-8CCD-185EAF4DABCD';
        insert ds;
        
        Attachment testAtt = new Attachment();
        testAtt.Body = Blob.valueOf('This is test OF attachment');
        testAtt.Name = String.valueOf('TestOrderFormAttachment.pdf');
        testAtt.ParentId = ds.Id;
        insert testAtt;
        
        dsfs__DocuSign_Recipient_Status__c drsCustomer = new dsfs__DocuSign_Recipient_Status__c();
        drsCustomer.dsfs__Parent_Status_Record__c = ds.id;
        drsCustomer.Name='Customer';
        drsCustomer.dsfs__DocuSign_Recipient_Email__c = 'test@yahoo.com';
        drsCustomer.dsfs__Recipient_Status__c = 'Sent';
        drsCustomer.dsfs__DocuSign_Recipient_Id__c = 'B1F8E324-D40E-415B-8CCD-185EAF4DABCD';
        drsCustomer.dsfs__Envelope_Id__c = ds.dsfs__DocuSign_Envelope_ID__c;
        insert drsCustomer;
        
        String conStatus= [Select ContractStatus__c from contract where ID=: contract.id].ContractStatus__c;
        System.assertNotEquals('Signed By Customer', conStatus, 'Verifying if the Contract Status is not Signed By Customer');
        
        drsCustomer.dsfs__Recipient_Status__c = 'Completed';
        update drsCustomer;
        
        conStatus= [Select ContractStatus__c from contract where ID=: contract.id].ContractStatus__c;        
        System.assertEquals('Signed By Customer', conStatus, 'Verifying if the Contract Status is Signed By Customer');
        
        ContractAttachment__c conAttachmentOF = [SELECT Id, AttachmentType__c FROM ContractAttachment__c WHERE DocuSignEnvelopeId__c=:ds.dsfs__DocuSign_Envelope_ID__c Limit 1];        
        List<ContentVersion> signedFiles = [Select Id From ContentVersion Where FirstPublishLocationId=:conAttachmentOF.Id];
        System.assertEquals(1,signedFiles.size(), 'Verifying if the signed file is attached successfully');
        
        Test.stopTest();
    }
    
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 16 Sep 2020
    // @param: NA
    // @description:SFDC-3317 Test method to cover changeContractStatus() and createContractAttachmentFilesFromDocusignStatus() methods. 
    // 				This test method covers scenario where Contract Management sends the contract for internal signatures using Docusign portal independent of Salesforce. Once signed, the signed document should be attached under Contract Attachments.
    //-----------------------------
    @isTest
    private static void testExternalDocusignFlow() {
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id OFRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = OFRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        //creating docusign status and docusign Recipient status object record
        Test.startTest();
        
        dsfs__DocuSign_Status__c ds = new dsfs__DocuSign_Status__c();
        ds.dsfs__Subject__c = 'Please sign the document';
        ds.dsfs__Sender__c = 'Sales';
        ds.dsfs__Contract__c = contract.id;
        ds.dsfs__Company__c = testAccount.id;
        ds.dsfs__DocuSign_Envelope_ID__c = 'B1F8E324-D40E-415B-8CCD-185ESFDC3317';
        insert ds;
        
        Attachment testAtt = new Attachment();
        testAtt.Body = Blob.valueOf('This is test OF attachment');
        testAtt.Name = String.valueOf('TestOrderFormAttachment.pdf');
        testAtt.ParentId = ds.Id;
        insert testAtt;
        
        dsfs__DocuSign_Recipient_Status__c drsCustomer = new dsfs__DocuSign_Recipient_Status__c();
        drsCustomer.dsfs__Parent_Status_Record__c = ds.id;
        drsCustomer.Name='Customer';
        drsCustomer.dsfs__DocuSign_Recipient_Email__c = 'test@ihsmarkit.com';
        drsCustomer.dsfs__Recipient_Status__c = 'Completed';
        drsCustomer.dsfs__DocuSign_Recipient_Id__c = 'B1F8E324-D40E-415B-8CCD-185ESFDC3317';
        drsCustomer.dsfs__Envelope_Id__c = ds.dsfs__DocuSign_Envelope_ID__c;
        insert drsCustomer;
                
        ContractAttachment__c conAttachmentOF = [SELECT Id, AttachmentType__c FROM ContractAttachment__c WHERE DocuSignEnvelopeId__c=:ds.dsfs__DocuSign_Envelope_ID__c Limit 1];        
        List<ContentVersion> signedFiles = [Select Id From ContentVersion Where FirstPublishLocationId=:conAttachmentOF.Id];
        System.assertEquals(1,signedFiles.size(), 'Verifying if the signed file is attached successfully');
        
        Test.stopTest();
    }
}