objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/MSFPlatform__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDC1-281 Used for setting Live Agent Product List for MSF</description>
    <fields>
        <fullName>DeliveryMechanism__c</fullName>
        <description>SFDC1-4674 To store the MSF Delivery Mechanism for specific Platform from where the Live Agent Chat originated</description>
        <label>Delivery Mechanism</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <description>SFDC1-4674 To store the MSF Platform from where the Live Agent Chat originated</description>
        <label>Platform</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MSF Platform</label>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of Product Group record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisibleInLiveChat__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5540 Check if the Product Group is visible in LiveChat.</description>
        <label>Visible in LiveChat</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestLiveChatOfflineFormController.cls
/*--------------------------------------------------------------------------------------------------------------------
    Author:        
    Company:       
    Description:   TestLiveChatOfflineFormController - test class for LiveChatOfflineFormController
    History
    07/01/2016     First Release
----------------------------------------------------------------------------------------------------------------------*/
@isTest
private class TestLiveChatOfflineFormController {
    // ensure Case inserted and redirection to confirmation page occurs
    static testMethod void testCaseCreation() {
        
                
        Account ac = TestUtility.createTestAccount('Test Pre Chat',true);
        Contact myContact1 = TestUtility.createContact(ac.Id, 'uttam.arya@test.com',true, 'Uttam', 'Arya');
       	insert new MSFPlatform__c(Name = 'MSF',Platform__c = 'Web Portal', DeliveryMechanism__c = 'Web Application');
        insert new ProductGroup__c(Name = 'MSF',VisibleInLiveChat__c = true, Status__c = 'Active');
        PageReference pageRef = Page.LiveChatOfflineForm;
        Test.setCurrentPage(pageRef);
        System.currentPageReference().getParameters().put('suppliedProduct', 'MSF');
        
        LiveChatOfflineFormController controller = new LiveChatOfflineFormController();
        controller.email = 'uttam.arya@test.com';
        controller.phone = '01234';
        controller.message = 'my comment';
        
        PageReference result = controller.submit();
        Case c = [select id from Case];
        System.assert(c != null);
        // verify that page fails without parameters
        System.assertEquals(Page.LiveChatConfirmation.getURL(), result.getURL().split('\\?')[0]);
        
        System.currentPageReference().getParameters().put('buttonOrigin', 'MSF');
        LiveChatOfflineFormController lcof = new LiveChatOfflineFormController();
        lcof.email = 'test.test@test.com';
        lcof.phone = '01234';
        lcof.message = 'my comment';
        lcof.contactName = 'Test';
        lcof.accountName = 'Test';
        lcof.submit();
        List<Case> lstCase = [Select Id from Case WHERE Suppliedemail = 'test.test@test.com'];
        System.assertEquals(1, lstCase.size(),'Verifying that the case has been created');
    }
}