objects/Account.object
<CustomObject>
    <fields>
        <fullName>LegacyID__c</fullName>
        <description>SFDC1-2445 When the account is created via migration this field will be populated by the migration with the winning ID of the legacy system.  Please note that all 3 legacy fields listed here are from the highest ranking source. Each source can be found in the related table Legacy Account ID - will not be visible to Sales profiles to avoid confusion with related legacy ids object.</description>
        <externalId>true</externalId>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country/Territory Code</inlineHelpText>
        <label>Country/Territory Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>SFDC1-620 Specify Country&apos;s geography</description>
        <inlineHelpText>Please select Country&apos;s geography</inlineHelpText>
        <label>Geography</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia &amp; NZ</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Eastern Europe</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany/Austria/Switzerland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; Africa</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Southern Europe</fullName>
                </value>
                <value>
                    <fullName>UK &amp; Ireland</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-7046: Legacy ID field is the system id (unfriendly) referencing the source record.</description>
        <externalId>true</externalId>
        <inlineHelpText>System ID referencing the source record Populated at Migration</inlineHelpText>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-2445 : Legacy ID field for Legal Entity Object</description>
        <externalId>true</externalId>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionStatus__c</fullName>
        <description>SFDC-4731: Field for exception process status</description>
        <label>Exception Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception Requested</fullName>
                </value>
                <value>
                    <fullName>Exception Request Approved</fullName>
                </value>
                <value>
                    <fullName>Exception Request Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedLegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4731: To store the requested legal entity for offline exception process</description>
        <label>Requested Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities (Requested Legal Entity)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>ProductSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 related product schedule</description>
        <label>Product Schedule</label>
        <referenceTo>ProductSchedule__c</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>SFDC1-6958: Global Segment field will be populated from the SAP Product Master and incorporated with the load to keep products in sync.</description>
        <inlineHelpText>Reporting Global Segment</inlineHelpText>
        <label>Global Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestOpportunityAddProductControllerLWC.cls
/**
* @auhor Ankush Agarwal
* @date 3rd Apr 2022
* @description Test class for OpportunityAddProductControllerLWC
* @company IHS Markit
* */
@isTest
public class TestOpportunityAddProductControllerLWC {

    @isTest
	private static void testAddProducts() {
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHSM test legalEntity', 'USD');
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',false);
        testOppy.CurrencyIsoCode = 'USD';
        testOppy.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
        testOppy.ContractEndDate__c = date.newinstance(currentFY, 10,21 );
        testOppy.ExceptionStatus__c = 'Exception Request Denied';   //Product Selection project change
        testOppy.RequestedLegalEntity__c = testLegalEntity.id;      //Product Selection project change
        insert testOppy;
         
        Test.startTest();    
			Product2 p1 = TestUtility.createProduct('Test Product 1', false);
			p1.DiscountThreshold__c = 10;
			p1.Division__c = 'Financial Services';
			p1.AAG__c = 'Subscription';
			p1.LegalEntity__c = testLegalEntity.Id;
			Product2 p2 = TestUtility.createProduct('Test Product 2', false);
			p2.DiscountThreshold__c = 12;
			p2.Division__c = 'Resources';
			p2.AAG__c = 'Subscription';
			p2.LegalEntity__c = testLegalEntity.Id;
			insert new List<Product2>{p1,p2};
				Id stdPricebookId = Test.getStandardPricebookId();
			PriceBook2 standardPB = new PriceBook2(Id = stdPricebookId, Name = 'Standard Price Book', isActive = true);
			update standardPB;
			
			PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
			PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
			pbe1.CurrencyIsoCode = 'USD';
			pbe2.CurrencyIsoCode = 'USD';
			insert new List<PricebookEntry>{pbe1,pbe2};
			//Now create product schedules
			ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, String.valueOf(currentFY), '1 Year', String.valueOf(currentFY), p1.Id, false);
			ProductSchedule__c ps2 = TestUtility.createProductSchedule(2223.23, String.valueOf(currentFY), '3 Years', String.valueOf(currentFY), p2.Id, false);
			ProductSchedule__c ps3 = TestUtility.createProductSchedule(2323.23, String.valueOf(currentFY), '3 Years', String.valueOf(currentFY + 1), p2.Id, false);
			ProductSchedule__c ps4 = TestUtility.createProductSchedule(2423.23, String.valueOf(currentFY), '3 Years', String.valueOf(currentFY + 2), p2.Id, false);
			insert new List<ProductSchedule__c>{ps1,ps2,ps3,ps4};
            OpportunityAddProductControllerLWC.OppyWrapper lstProdWrapper = OpportunityAddProductControllerLWC.getProductDetails(new List<Id>{p1.Id,p2.Id},testOppy.Id,'IHSM test legalEntity');
        	System.assertEquals(2, lstProdWrapper.lstOPSWrapper.size(), 'Product List Created');
        	//lstProdWrapper.aag = 'Subscription';
        	lstProdWrapper.canBeProRated = true;
        	lstProdWrapper.isProRated = 'Yes';
        	String json = System.JSON.serialize(lstProdWrapper.lstOPSWrapper);
        	OpportunityAddProductControllerLWC.saveProductsOnOpportunity(json, testOppy.Id, testLegalEntity.Id);
        	List<String> licenseTypes = OpportunityAddProductControllerLWC.getLicenseTypes();
            List<OpportunityLineItem> oppyProductList = [Select Id, OpportunityId from OpportunityLineItem where OpportunityId =:testOppy.Id];
            String jsonOLI = System.JSON.serialize(oppyProductList);
        	String msg = OpportunityAddProductControllerLWC.deleteOppyProducts(jsonOLI);
            System.assertEquals('Products deleted successfully from Opportunity', msg, 'Products deleted successfully');
        	Decimal dConvertedVal = OpportunityAddProductControllerLWC.getConvertedCurrencyRate('USD', 'INR', 100.0);
        Test.stopTest();
      }

    @isTest
	private static void testAddProductsIndianLevy() {
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHS Global Pte Ltd', 'USD'); 
        //Country Record
        Country__c indiaCountry = new Country__c(CountryCode__c = 'IN', Region__c = 'APAC', Geography__c = 'Singapore',
                                                 CurrencyIsoCode = 'USD', LegacyID__c = testLegalEntity.Id, Name = 'India');
        insert indiaCountry;
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',false);
        testOppy.CurrencyIsoCode = 'USD';
        testOppy.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
        testOppy.ContractEndDate__c = date.newinstance(currentFY, 10,21 );
        testOppy.OpportunityCountry__c = indiaCountry.Id;
        insert testOppy;
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.DiscountThreshold__c = 10;
        p1.Division__c = 'Resources';
        p1.AAG__c = 'Subscription';
        p1.Mediatype__c = 'Online Access';
        p1.LegalEntity__c = testLegalEntity.Id;
        insert new List<Product2>{p1};
        
        Id stdPricebookId = Test.getStandardPricebookId();
        PriceBook2 standardPB = new PriceBook2(Id = stdPricebookId, Name = 'Standard Price Book', isActive = true);
        update standardPB;
        
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        pbe1.CurrencyIsoCode = 'INR';
        insert new List<PricebookEntry>{pbe1};
        //Now create product schedules
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, String.valueOf(currentFY), '1 Year', String.valueOf(currentFY), p1.Id, false);
        insert new List<ProductSchedule__c>{ps1};
        Test.startTest();    
            OpportunityAddProductControllerLWC oAPCObj = new OpportunityAddProductControllerLWC();
            OpportunityAddProductControllerLWC.OppyWrapper lstProdWrapper = OpportunityAddProductControllerLWC.getProductDetails(new List<Id>{p1.Id},testOppy.Id,'IHS Global Pte Ltd');
        	System.assertEquals(1, lstProdWrapper.lstOPSWrapper.size(), 'Product List Created');
        	String json = System.JSON.serialize(lstProdWrapper.lstOPSWrapper);
        	OpportunityAddProductControllerLWC.saveProductsOnOpportunity(json, testOppy.Id, testLegalEntity.Id);
        Test.stopTest();
      }

	@isTest
    private static void testAddProductsindianLevyCalc() {
        OpportunityLineItemSchedule__c opsObj = new OpportunityLineItemSchedule__c();
        opsObj.ExternalListPrice__c = 1000;
        opsObj.DiscountPercent__c = 0.0;
        opsObj.DiscountAmount__c =200;
        opsObj.SalesPrice__c = 816.53;
        opsObj.Quantity__c = 1;
        opsObj.CurrencyIsoCode = 'USD';
        opsObj.AnnualizedUnitPrice__c = 900;
        opsObj.AnnualizedDiscountAmount__c =200;
        List<OpportunityLineItemSchedule__c> opsList = new List<OpportunityLineItemSchedule__c>();
        opsList.add(opsObj);
        //Formula fields need to be recalculated as record is not yet inserted     
        List<FormulaRecalcResult> results = Formula.recalculateFormulas(opsList);
        Test.startTest();
			Decimal adjustedListPrice=OpportunityAddProductControllerLWC.setUnitPriceasperLevyCharges(opsList[0],1, False);            
			Decimal adjustedListPrice1=OpportunityAddProductControllerLWC.setUnitPriceasperLevyCharges(opsList[0],1, True);            
			System.assertEquals(adjustedListPrice,1016.53, 'Adjusted List Price is calculated');
        Test.stopTest();
	}
}