objects/Account.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-10407 : Creating this field to bypass the validation rule using Apex Code.</description>
        <inlineHelpText>This field will be used to byPass the Validation Rules in Apex.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6439 This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</description>
        <inlineHelpText>This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Placeholder</fullName>
        <active>true</active>
        <businessProcess>Forecasting Placeholder Process</businessProcess>
        <description>For Retail Business</description>
        <label>Forecasting Placeholder</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchCleanupEntitySubscriptions.cls
/**
* @author Paras Dhingra
* @date 17 Sep 2020
* @description SFDC-3387 test Class for batch and scheduler for EntitySubscription cleanup
* @companyname IHS Markit
*/
@isTest(SeeAllData=false)
public class TestBatchCleanupEntitySubscriptions {
    @isTest
    static void testExecute() {
        //create test data
        Account testAccount  = TestUtility.createTestAccount('Test PArent Account', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        Profile salesProfile = [SELECT Id ,name FROM Profile WHERE Name like '%General%' limit 1];
        User testSalesUser = new User(Alias = 'standt', Email='ctcompletedTest@testorg.com', 
        EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = salesProfile.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='ctcompletedTest@ihsihs.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber='test'+String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c='test'+String.valueOf(Math.round(Math.random()*10000)));
        insert testSalesUser;
        //Forecasting placeholder oppy
        Id placeholderOppRecTypeId = Schema.SobjectType.Opportunity.getRecordTypeInfosByName().get('Forecasting Placeholder').getRecordTypeId();
        //create test oppies 5 with closedate less than threshold and 5 under threshold
        List<Opportunity> lstOpportunityToInsert = new List<Opportunity>();
        // close date in today and future
        for(Integer i=0; i<5;i++) {
            Opportunity oppy = TestUtility.createOpportunity(testAccount.Id, 'Test Oppy'+i, false);
            oppy.CloseDate = Date.today()+i;
            oppy.RecordTypeId = placeholderOppRecTypeId;
            oppy.StageName = '1-Open';
            oppy.OwnerId = testSalesUser.Id;
            lstOpportunityToInsert.add(oppy);
        }
        // close date in today and before threshold
        Integer dateThreshold = Integer.valueOf(System.Label.NumberOfDaysThreshold);
        for(Integer i=0; i<5;i++) {
            Opportunity oppy = TestUtility.createOpportunity(testAccount.Id,'Test Oppy old'+i , false);
            oppy.CloseDate = (Date.today()-dateThreshold-i-1);
            oppy.RecordTypeId = placeholderOppRecTypeId;
            oppy.StageName = '1-Open';
            oppy.OwnerId = testSalesUser.Id;
            lstOpportunityToInsert.add(oppy);
        }
        Test.startTest();        
        insert lstOpportunityToInsert;
        //assert Entity Subscriptions
        List<EntitySubscription> assertSubscriptions = [Select Id from EntitySubscription where SubscriberId=:testSalesUser.Id];
        System.assertEquals(10,assertSubscriptions.size(),'Checking size of Subs created');
        //close the oppies and start the batch
        for(Opportunity oppy: lstOpportunityToInsert) {
            oppy.StageName = '6W-Forecasting Placeholder';
            oppy.ByPassValidation__c = true;
        }
        update lstOpportunityToInsert;
        BatchCleanupEntitySubscriptionsScheduler ba = new BatchCleanupEntitySubscriptionsScheduler(); //Schedule apex class name
        ba.query = 'Select Id from User where Id=\''+testSalesUser.Id+'\'';
        String sch = '0 0 8 13 2 ?'; //schedule interval time
        String jobId = System.schedule('Run Job for BatchCleanupEntitySubscriptions', sch, ba); //system method to schedule apex class
        System.assert(jobId!=null);
        BatchCleanupEntitySubscriptions batchObj = new BatchCleanupEntitySubscriptions();
        batchObj.query = 'Select Id from User where Id=\''+testSalesUser.Id+'\'';
        batchObj.batchHasErrors = true;
        Id batchId = Database.executeBatch(batchObj);
        Test.stopTest();
        List<EntitySubscription> assertSubscriptions2 = [Select Id from EntitySubscription where SubscriberId=:testSalesUser.Id];
        System.assertEquals(5,assertSubscriptions2.size(),'Checking size of Subs after batch');
        
        
    }
}