objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipName>Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of family record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <description>SFDC1-7525 Profit center to be rolled up from opportunity product&apos;s related product
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Profit center for related products automatically populated by system</inlineHelpText>
        <label>Profit Center</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>ProductSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 related product schedule</description>
        <label>Product Schedule</label>
        <referenceTo>ProductSchedule__c</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-487 Ghost status field to store status of related opportunity product</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Product Family</inlineHelpText>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormerIPOwner__c</fullName>
        <inlineHelpText>Former Intellectual Property Owner</inlineHelpText>
        <label>Former IP Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenterCode__c</fullName>
        <description>SFDC1-9430 field to establish relationship between product and it&apos;s profit center Code</description>
        <formula>ProfitCenters__r.ProfitCenterCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Profit Center Code</inlineHelpText>
        <label>Profit Center #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of Product Group record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ProfitCenter__c.object
<CustomObject>
    <description>SFDC1-3837 Object to hold data for profit centers related to a product</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6128 to add Deactivate functionality</description>
        <inlineHelpText>Active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProfitCenterCode__c</fullName>
        <description>SFDC1-3837 Field to hold profit center code in alphanumeric format
SFDC-5732.  Field is updated to External and Unique</description>
        <externalId>true</externalId>
        <label>Profit Center Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBatchToUpdateOpportunityStage.cls
//-----------------------------
// @author: Tran-Vu Tran
// @date: 22 March 2019
// @param: NA
// @description: SFDC-1145 Test Class for TestBatchToUpdateOpportunityStage
// @return: NA
//----------------------------
@isTest
private class TestBatchToUpdateOpportunityStage {
    static Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
    static Integer nextFY = currentFY+1;
    
	static Account testAcct;
    static Contact testCont;
    static Opportunity testOppty;
    
    static void DataSetup() {
        testAcct = TestUtility.createTestAccount('Test BatchToUpdateOpportunityStage', true);
        testCont = TestUtility.createContact(testAcct.Id, 'test.contact@ihsmarkit.com', true, 'Test First', 'Test Last');
        
        testOppty = TestUtility.createOpportunity(testAcct.id, 'Test Oppty', null, false);
        testOppty.ContractStartDate__c = date.NewInstance(currentFY, 03, 21);
        testOppty.ContractEndDate__c = date.NewInstance(currentFY+2, 10, 21);
        testOppty.ActivityCreated__c = true;
        insert testOppty;
        
        OpportunityContactRole ocr = new OpportunityContactRole(IsPrimary = true, OpportunityId = testOppty.Id, ContactId = testCont.Id);
        insert ocr;
        
        ProfitCenter__c testProfitCenter = new ProfitCenter__c(Name='UP - Energy', Active__c=true, ProfitCenterCode__c='187');
        insert testProfitCenter;
        
        Family__c testProdFamily = new Family__c(Name='ETC-C&A',Status__c ='Active');
        insert testProdFamily;
        
        ProductGroup__c testProdGroup = TestUtility.createProductGroup('MRO',false,false);
        
        Product2 testProd = TestUtility.createProduct('Test Product', false);
        testProd.FormerIpOwner__c = 'IHS Markit Global Inc.';
        testProd.Family__c = testProdFamily.Id;
        testProd.ProfitCenters__c = testProfitCenter.Id;
        testProd.ProductGroup__c = testProdGroup.Id;
        insert testProd;
        
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOppty.Id, testPBE, true);
        ProductSchedule__c testPS = TestUtility.createProductSchedule(2223.23, String.valueof(currentFY), '1 Year', String.valueof(currentFY), testProd.Id, false);
        insert testPS;
        
        OpportunityLineItemSchedule__c testOLIS = TestUtility.createOpportunityProductSchedule(testOppty.Id, testPS.Id, 2223.23, 2000, 'Amount', 223.23, 0.0,
                                                                                               testProd.Id, '2017', 1, testOLI.Id, false);
        insert testOLIS;
    }
    
    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 22 March 2019
    // @param: NA
    // @description: SFDC-1145 Test method for TestBatchToUpdateOpportunityStage
    // when converting Stage '3-Proposal Development and Delivery' to Stage '3-Proposal Development'
    //-----------------------------
    @isTest
    static void testBatchToUpdateOpportunity_Stage3() {
        DataSetup();

        // Start test for converting Stage '3-Proposal Development and Delivery' to Stage '3-Proposal Development'
        test.startTest();
        testOppty.StageName = '3-Proposal Development and Delivery';
        update testOppty;

        BatchToUpdateOpportunityStage testBatch = new BatchToUpdateOpportunityStage();
        testBatch.query = 'Select Id, StageName, Probability From Opportunity where Id=\'' + testOppty.Id +'\'';
        Database.executeBatch(testBatch, 1);
        
        Test.stopTest();
        testOppty = [Select Id, StageName, Probability from Opportunity where Id =: testOppty.Id];
        System.assertEquals('3-Proposal Development', testOppty.StageName,'Opportunity Stage is not updated to Proposal Development');
    }
    
    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 22 March 2019
    // @param: NA
    // @description: SFDC-1145 Test method for TestBatchToUpdateOpportunityStage
    // when converting Stage '4-Proposal Accepted and Verbal Commit' with Probability = 50% to Stage '4.1-Proposal/Quote Delivery'
    //-----------------------------
    @isTest
    static void testBatchToUpdateOpportunity_Stage4_1() {
        DataSetup();

        // Start test for converting Stage '4-Proposal Accepted and Verbal Commit' with Probability = 50% to Stage '4.1-Proposal/Quote Delivery'
        test.startTest();
        testOppty.StageName = '4-Proposal Accepted and Verbal Commit';
        testOppty.Probability = 50;
        update testOppty;

        BatchToUpdateOpportunityStage testBatch = new BatchToUpdateOpportunityStage();
        testBatch.query = 'Select Id, StageName, Probability From Opportunity where Id=\'' + testOppty.Id +'\'';
        Database.executeBatch(testBatch, 1);
        
        Test.stopTest();
        testOppty = [Select Id, StageName, Probability from Opportunity where Id =: testOppty.Id];
        System.assertEquals('4.1-Proposal/Quote Delivery', testOppty.StageName,'Opportunity Stage is not updated to Proposal Quote Delivery');
    }

    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 22 March 2019
    // @param: NA
    // @description: SFDC-1145 Test method for TestBatchToUpdateOpportunityStage
    // when converting Stage '4-Proposal Accepted and Verbal Commit' with Probability = 75% to Stage '4.2-Verbal Commit'
    //-----------------------------
    @isTest
    static void testBatchToUpdateOpportunity_Stage4_2() {
        DataSetup();

        // Start test for converting Stage '4-Proposal Accepted and Verbal Commit' with Probability = 75% to Stage '4.2-Verbal Commit'
        test.startTest();
        testOppty.StageName = '4-Proposal Accepted and Verbal Commit';
        testOppty.Probability = 75;
        update testOppty;

        BatchToUpdateOpportunityStage testBatch = new BatchToUpdateOpportunityStage();
        testBatch.query = 'Select Id, StageName, Probability From Opportunity where Id=\'' + testOppty.Id +'\'';
        Database.executeBatch(testBatch, 1);
        
        Test.stopTest();
        testOppty = [Select Id, StageName, Probability from Opportunity where Id =: testOppty.Id];
        System.assertEquals('4.2-Verbal Commit', testOppty.StageName,'Opportunity Stage is not updated to Verbal Commit');
    }

}