objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-383 This field serves as a lookup to the Country object</description>
        <inlineHelpText>Read-only field, updated indirectly by a change of Company&apos;s Billing Country/Territory</inlineHelpText>
        <label>Account Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RocketDocs__Proposal_Request__c.object
<CustomObject>
    <description>RocketDocs Salesforce Connector 2.0: Container for the project synced from RocketDocs.</description>
    <fields>
        <fullName>AccountCity__c</fullName>
        <label>Account City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <label>Account Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountState__c</fullName>
        <label>Account State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountStreet__c</fullName>
        <label>Account Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountZip__c</fullName>
        <label>Account Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityOwnerEmail__c</fullName>
        <label>Opportunity Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OpportunityOwnerHRTitle__c</fullName>
        <label>Opportunity Owner HR Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityOwnerMobileNumber__c</fullName>
        <label>Opportunity Owner Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OpportunityOwnerPhoneNumber__c</fullName>
        <label>Opportunity Owner Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Department__c</fullName>
        <label>Opportunity Owner Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContactEmail__c</fullName>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PrimaryContactFirstName__c</fullName>
        <label>Primary Contact First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContactFullName__c</fullName>
        <label>Primary Contact Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContactPhone__c</fullName>
        <label>Primary Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PrimaryContactTitle__c</fullName>
        <label>Primary Contact Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RocketDocs__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RocketDocs Salesforce Connector 2.0: Main proposal request container associated to an Opportunity</description>
        <inlineHelpText>RocketDocs Salesforce Connector 2.0: Lookup to the Opportunity. There should only be one active Proposal Request associated to an Opportunity at any given time.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RocketDocs Requests</relationshipLabel>
        <relationshipName>RocketDocs_Proposal_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RocketDocs Request</label>
    <nameField>
        <displayFormat>RDR-{0000000}</displayFormat>
        <label>RocketDocs Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RocketDocs Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RocketDocsRequestMethods.cls
public class RocketDocsRequestMethods {
    
    public static void prepopulateFieldsValues(TriggerParameters tp) {
        
        Set <Id> oppIds = new Set <Id>();
        for (RocketDocs__Proposal_Request__c rpr : (List<RocketDocs__Proposal_Request__c>)tp.newList) {
          if (rpr.RocketDocs__Opportunity__c != null) {
              oppIds.add(rpr.RocketDocs__Opportunity__c);
          }
        }
   
        Map <Id,Opportunity> OppyMap = new  Map <Id,Opportunity>([Select Id, CurrencyIsoCode, Account.BillingStreet, Account.BillingCity, 
                                                                  Account.BillingState, Account.BillingPostalCode, Account.BillingCountry, 
                                                                  Owner.Email, Owner.HRJobTitle__c,Owner.HRBusinessLine__c,Owner.Phone,Owner.MobilePhone, 
                                                                   (SELECT id, Contact.Name,Contact.FirstName, Contact.Email, Contact.LastName, Contact.Title, Contact.Phone  
                                                                    FROM OpportunityContactRoles where IsPrimary=true LIMIT 1)
                                                                  FROM Opportunity WHERE Id IN : oppIds]);
     
       for (RocketDocs__Proposal_Request__c rpr : (List<RocketDocs__Proposal_Request__c>)tp.newList) {
          if (rpr.RocketDocs__Opportunity__c != null && OppyMap.containsKey(rpr.RocketDocs__Opportunity__c)) {
             Opportunity oppy = OppyMap.get(rpr.RocketDocs__Opportunity__c);
             rpr.OpportunityOwnerEmail__c  = oppy.Owner.Email ;
             rpr.OpportunityOwnerHRTitle__c  = oppy.Owner.HRJobTitle__c ;
             rpr.Opportunity_Owner_Department__c = oppy.Owner.HRBusinessLine__c ;
             rpr.OpportunityOwnerPhoneNumber__c  = oppy.Owner.Phone ;
             rpr.OpportunityOwnerMobileNumber__c = oppy.Owner.MobilePhone;
             rpr.AccountCountry__c  = oppy.Account.BillingCountry ;
             rpr.AccountState__c  = oppy.Account.BillingState  ;
             rpr.AccountStreet__c  = oppy.Account.BillingStreet;
             rpr.AccountCity__c  = oppy.Account.BillingCity ;
             rpr.AccountZip__c  = oppy.Account.BillingPostalCode ;
             rpr.CurrencyIsoCode = oppy.CurrencyIsoCode;
             
             if(oppy.OpportunityContactRoles.size() > 0) {
               rpr.PrimaryContactFullName__c  = oppy.OpportunityContactRoles[0].Contact.Name;
               rpr.PrimaryContactPhone__c  = oppy.OpportunityContactRoles[0].Contact.Phone;
               rpr.PrimaryContactTitle__c  = oppy.OpportunityContactRoles[0].Contact.Title;
               rpr.PrimaryContactEmail__c  = oppy.OpportunityContactRoles[0].Contact.Email;
               rpr.PrimaryContactFirstName__c =  oppy.OpportunityContactRoles[0].Contact.FirstName;
             }
         }
      }
   }    
}