objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-3378 Global Account Manager</description>
        <inlineHelpText>Global Account Manager</inlineHelpText>
        <label>GAM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityName__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning page layout</description>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity Name</inlineHelpText>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>NegotiatedDate__c</fullName>
        <label>Negotiated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderRequestStatus__c</fullName>
        <label>Order Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved without Job</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLCJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>PLC Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>OrderRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Programmer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <label>Programmer&apos;s Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aftersales-Chrysler</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>ESS-Delivery</fullName>
                </value>
                <value>
                    <fullName>Forecasting</fullName>
                </value>
                <value>
                    <fullName>MCM-Analytics</fullName>
                </value>
                <value>
                    <fullName>MCM-Marketing Databases</fullName>
                </value>
                <value>
                    <fullName>MCM-Market Research</fullName>
                </value>
                <value>
                    <fullName>MCM-Target Marketing Services</fullName>
                </value>
                <value>
                    <fullName>MEL-Delivery</fullName>
                </value>
                <value>
                    <fullName>MR-Aftermarket</fullName>
                </value>
                <value>
                    <fullName>MR-Commercial</fullName>
                </value>
                <value>
                    <fullName>MR-Loyalty</fullName>
                </value>
                <value>
                    <fullName>MR-Market Reporting BI</fullName>
                </value>
                <value>
                    <fullName>MR-Network Management</fullName>
                </value>
                <value>
                    <fullName>Planning Solutions</fullName>
                </value>
                <value>
                    <fullName>PolkConnect Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect System</fullName>
                </value>
                <value>
                    <fullName>VIN-Recall</fullName>
                </value>
                <value>
                    <fullName>VIN-VIN Decoders</fullName>
                </value>
                <value>
                    <fullName>VIN-VVS</fullName>
                </value>
                <value>
                    <fullName>Visualization Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>JobType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
                <value>
                    <fullName>Ad-Hoc (non-cyclical)</fullName>
                </value>
                <value>
                    <fullName>Cyclical</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Estimate only</fullName>
                </value>
                <value>
                    <fullName>Internal Ad-Hoc</fullName>
                </value>
                <value>
                    <fullName>Internal Cyclical</fullName>
                </value>
                <value>
                    <fullName>Lights Out Process</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NegotiatedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>If no Negotiated Date was provided, use the date from Requested Due Date to populate this required field</inlineHelpText>
        <label>Negotiated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Order Request</label>
        <referenceTo>OrderRequest__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Programmer&apos;s Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aftersales-Chrysler</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>ESS-Delivery</fullName>
                </value>
                <value>
                    <fullName>Forecasting</fullName>
                </value>
                <value>
                    <fullName>MCM-Analytics</fullName>
                </value>
                <value>
                    <fullName>MCM-Marketing Databases</fullName>
                </value>
                <value>
                    <fullName>MCM-Market Research</fullName>
                </value>
                <value>
                    <fullName>MCM-Target Marketing Services</fullName>
                </value>
                <value>
                    <fullName>MEL-Delivery</fullName>
                </value>
                <value>
                    <fullName>MR-Aftermarket</fullName>
                </value>
                <value>
                    <fullName>MR-Commercial</fullName>
                </value>
                <value>
                    <fullName>MR-Loyalty</fullName>
                </value>
                <value>
                    <fullName>MR-Market Reporting BI</fullName>
                </value>
                <value>
                    <fullName>MR-Network Management</fullName>
                </value>
                <value>
                    <fullName>Planning Solutions</fullName>
                </value>
                <value>
                    <fullName>PolkConnect Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect System</fullName>
                </value>
                <value>
                    <fullName>VIN-Recall</fullName>
                </value>
                <value>
                    <fullName>VIN-VIN Decoders</fullName>
                </value>
                <value>
                    <fullName>VIN-VVS</fullName>
                </value>
                <value>
                    <fullName>Visualization Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestOrderRequestMethods.cls
//--------------------------------------------------------------------
// @author: Anjali
// @date: 05 July 2021
// @description: This is test class for WorkRequestFormController
//--------------------------------------------------------------------
@isTest
private class TestOrderRequestMethods {
    @testSetup static void testData() {
        Account a = TestUtility.createTestAccount('testAccount', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName= '1-Sales Qualified';
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.GAM__c = u.id;
        opp.AccountId = a.id;
        insert opp; 
        Id PASRecordTypeId = Schema.SObjectType.WorkRequestForm__c.getRecordTypeInfosByName().get('PAS').getRecordTypeId();
        WorkRequestForm__c wrf = new WorkRequestForm__c();
        wrf.RecordTypeId = PASRecordTypeId;
        wrf.JobType__c = 'Ad Hoc';
        wrf.RoyaltyVendor__c='No Royalty Data';
        wrf.ReturnToSales__c=true;
        wrf.PrimarySalesContact__c=UserInfo.getUserId();
        wrf.RequestedDueDate__c = System.today() + 7;
        wrf.OutputType__c='Comma Delimited (CSV)';
        wrf.OutputMedium__c='CD ROM/DVD';
        wrf.TLAS__c  = true;
        wrf.JobDescription__c = 'test';
        wrf.RequestStatus__c='Submitted';
        wrf.OpportunityName__c= opp.Id;
        wrf.AccountName__c= a.Id;
        insert wrf;
        List<OrderRequest__c> orderReqLst = new List<OrderRequest__c>();
        OrderRequest__c orderReq = new OrderRequest__c();
        orderReq.WorkRequestForm__c = wrf.Id;
        orderReq.OrderRequestStatus__c = 'Draft';
        orderReqLst.add(orderReq);
        OrderRequest__c orderReq1 = new OrderRequest__c();
        orderReq1.WorkRequestForm__c = wrf.Id;
        orderReq1.OrderRequestStatus__c = 'Submitted';
        orderReqLst.add(orderReq1);
        OrderRequest__c orderReq2 = new OrderRequest__c();
        orderReq2.WorkRequestForm__c = wrf.Id;
        orderReq2.OrderRequestStatus__c = 'Submitted';
        orderReqLst.add(orderReq2);
        insert orderReqLst;
        String testEmail = 'dgtest@testtest1ihsmarkit.com';
        User myTestUser = TestUtility.createAdminUser(testEmail, true);
        TestUtility.addWRApproverPermSet(myTestUser.Id); 
    }
    @isTest
    private static void testUpdateRequestor() {
        User userObj =[Select Id FROM User WHERE Id=:Userinfo.getUserId()];
        OrderRequest__c orderReq;
            Test.StartTest();
            orderReq = [Select Id,Requestor__c FROM OrderRequest__c LIMIT 1];
            Test.StopTest();
        System.assertEquals(orderReq.Requestor__c,userObj.Id , 'Requestor is not updated to Order Request created user');           
    }
    @isTest
    private static void testUpdateonSubmit() { 
        WorkRequestForm__c workReq = [Select Id,ownerId FROM WorkRequestForm__c LIMIT 1];
        OrderRequest__c orderReq = [Select Id,SubmittedDateTime__c,OwnerId FROM OrderRequest__c WHERE OrderRequestStatus__c='Draft' LIMIT 1];
        Test.StartTest();
        orderReq.OrderRequestStatus__c = 'Submitted';
        update orderReq;
        Test.StopTest();
        OrderRequest__c oRObj = [Select Id,OwnerId,SubmittedDateTime__c FROM OrderRequest__c where Id=:orderReq.Id];
        System.assertEquals(workReq.OwnerId,oRObj.OwnerId, 'Owner is not updated to the queue');
        
    }
    @isTest
    private static void testUpdateonApprovalwithoutJob() { 
        OrderRequest__c orderReq = [Select Id,OwnerId FROM OrderRequest__c WHERE OrderRequestStatus__c='Submitted' LIMIT 1];
        User currentUser = [SELECT Id FROM User WHERE Alias = 'testA'];
        System.runAs(currentUser) {
            Test.StartTest();
            orderReq.OrderRequestStatus__c = 'Approved without Job';
            update orderReq;
            Test.StopTest();
            OrderRequest__c oRObj = [Select Id,OwnerId FROM OrderRequest__c where Id=:orderReq.Id];
            System.assertEquals(oRObj.OwnerId,Userinfo.getUserId(), 'Owner is not updated to the current user');
        }
    }
    @isTest
    private static void testUpdateonApprovalwithoutJobwithprogrammer() { 
        OrderRequest__c orderReq = [Select Id,OwnerId FROM OrderRequest__c WHERE OrderRequestStatus__c='Submitted' LIMIT 1];
        User userObj = [Select Id from User where Email='standarduser@testorg.com' LIMIT 1];
        User currentUser = [SELECT Id FROM User WHERE Alias = 'testA'];
        System.runAs(currentUser) {
            Test.StartTest();
            orderReq.OrderRequestStatus__c = 'Approved without Job';
            orderReq.Programmer__c = userObj.Id;
            update orderReq;
            Test.StopTest();
            OrderRequest__c oRObj = [Select Id,OwnerId FROM OrderRequest__c where Id=:orderReq.Id];
            System.assertEquals(oRObj.OwnerId,userObj.Id, 'Owner is not updated to the current user');
        }
    }
    @isTest
    private static void testUpdateonRejected() { 
        OrderRequest__c orderReq = [Select Id,OwnerId FROM OrderRequest__c where OrderRequestStatus__c='Submitted' LIMIT 1];
        User currentUser = [SELECT Id FROM User WHERE Alias = 'testA'];
        System.runAs(currentUser) {
            orderReq.OrderRequestStatus__c='Approval Pending';
            update orderReq;
            Test.StartTest();
            orderReq.OrderRequestStatus__c = 'Rejected';
            update orderReq;
            Test.StopTest();
            OrderRequest__c oRObj = [Select Id,OwnerId,CreatedById FROM OrderRequest__c where Id=:orderReq.Id];
            system.assertEquals(oRObj.ownerID, oRobj.CreatedById, 'Owner and created by are not same users');
        }
    }
    @isTest
    private static void testUpdateonApproval() { 
        OrderRequest__c orderReq = [Select Id,PLCJob__c,OwnerId FROM OrderRequest__c where OrderRequestStatus__c='Submitted' LIMIT 1];
        User userObj = [Select Id from User where Email='standarduser@testorg.com' LIMIT 1];
        Test.StartTest();
        User currentUser = [SELECT Id FROM User WHERE Alias = 'testA'];
        System.runAs(currentUser) {
            orderReq.NegotiatedDate__c =System.today()+10;
            orderReq.Team1__c='MCM-Analytics';
            orderReq.OrderRequestStatus__c = 'Approved';
            orderReq.Programmer__c=userObj.Id;
            update orderReq;
            Test.StopTest();
            PLCJob__c plcJob = [Select Id FROM PLCJob__c WHERE OrderRequest__c =: orderReq.Id];
            OrderRequest__c oRObj = [Select Id,OwnerId,PLCJob__c FROM OrderRequest__c where Id=:orderReq.Id];
            System.assertEquals(oRObj.OwnerId,userObj.Id, 'Owner is not updated to the programmer');
            System.assertEquals(oRObj.PLCJob__c,plcJob.Id, 'PLC job is not created');
        }
    }
}