objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountActiveContractsCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SFDC-3473 Rollup summary field to calculate count of all active contracts.</description>
        <inlineHelpText>Count of all active contracts related to the account</inlineHelpText>
        <label>Account Active Contracts Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AccountContractsCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SFDC-3473 Rollup summary field to calculate count of all contracts.</description>
        <inlineHelpText>Count of all contracts related to the account</inlineHelpText>
        <label>Account Contracts Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>SFDC1-10131 New Contract field: &quot;Active&quot;</description>
        <formula>IF(
OR(text(ContractStatus__c)== &quot;Validated&quot;, text(ContractStatus__c)== &quot;Validated PO Pending&quot;, text(ContractStatus__c)== &quot;Invoiced&quot;, text(ContractStatus__c)== &quot;Executed&quot;, text(ContractStatus__c)== &quot;Delivered to Customer&quot;, text(ContractStatus__c)== &quot;Approved &amp; Processed&quot;,text(ContractStatus__c)== &quot;Validated-POD Pending&quot;),
True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>to quickly see which Contracts on an Account are &quot;Active&quot;</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SetContractCountonAccount__e.object
<CustomObject>
    <description>SFDC-4166.Platform Event to update Active and Total Contract Count on Account.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SetContractCountOnAccount</label>
    <pluralLabel>SetContractCountOnAccounts</pluralLabel>
</CustomObject>

classes/SetContractCountonAccountMethods.cls
//-----------------------------
// @author: Digvijay Singh
// @date: 11 June 2021
// @param: NA
// @description: SFDC-4166 Class to hold SetContractCountonAccount__e platform event trigger methods 
// @return: NA
//-----------------------------
public class SetContractCountonAccountMethods {
      /**
    * @author Digvijay Singh
    * @date 11 June 2021
    * @description SFDC-4166 Update Contract Count on  Account record 
    * @param TriggerParameters
    * @return void
    * @companyname IHS Markit
    */
    public static void calculateContractCountOnAccount(TriggerParameters tp) {
        List<SetContractCountonAccount__e> eventList = (List<SetContractCountonAccount__e>)tp.newList;
        try {
            List<Account> lstAccountToUpdate = new List<Account>();
            List<Id> lstAccountId = new List<Id>();
            for(SetContractCountonAccount__e event : eventList) {
                lstAccountId.add(event.AccountId__c);
            }
            if(!lstAccountId.IsEmpty()) {
                Map<Id,Account> mapIdtoAccount = new Map<Id,Account>([SELECT Id,(SELECT Id, Active__c FROM Contracts) FROM Account WHERE Id In: lstAccountId]);
                for(Account acc: mapIdtoAccount.values()) {
                    Integer count = 0;
                    acc.AccountContractsCount__c = mapIdtoAccount.get(acc.Id).Contracts.Size();
                    for(Contract cont : acc.contracts) {
                        if(cont.Active__c) {
                            count += 1; 
                        }
                    }
                    acc.AccountActiveContractsCount__c = count;
                    lstAccountToUpdate.add(acc);
                }
            }
            
            if(!lstAccountToUpdate.IsEmpty()) {
                update lstAccountToUpdate;
            }
        }
        catch(Exception ex) {
            UtilityClass.createApexLogRecord(ex, 'SetContractCountonAccountMethods', 'calculateContractCountOnAccount');
        } 
    }
}