objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country/Territory Code</inlineHelpText>
        <label>Country/Territory Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>SFDC1-620 Specify Country&apos;s geography</description>
        <inlineHelpText>Please select Country&apos;s geography</inlineHelpText>
        <label>Geography</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia &amp; NZ</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Eastern Europe</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany/Austria/Switzerland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; Africa</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Southern Europe</fullName>
                </value>
                <value>
                    <fullName>UK &amp; Ireland</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExceptionStatus__c</fullName>
        <description>SFDC-4731: Field for exception process status</description>
        <label>Exception Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception Requested</fullName>
                </value>
                <value>
                    <fullName>Exception Request Approved</fullName>
                </value>
                <value>
                    <fullName>Exception Request Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-616 Lookup to Country object</description>
        <label>Opportunity Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedLegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4731: To store the requested legal entity for offline exception process</description>
        <label>Requested Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities (Requested Legal Entity)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1843 Product related to Opportunity product schedule</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-487 Ghost status field to store status of related opportunity product</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductExtensions__c.object
<CustomObject>
    <description>SFDC1-134 : This Object will be used to Track the Product Extensions between Product and Legal Entities</description>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-134 : This field will be used to store the value of Legal Entity</description>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Product Extensions</relationshipLabel>
        <relationshipName>Product_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-134 : This field will be used to store the Product Value</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Extensions</relationshipLabel>
        <relationshipName>Product_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Extensions</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Product Extensions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 Product for which product schedule is created</description>
        <inlineHelpText>Related Product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>ProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ProductSelectionCriteria__c.object
<CustomObject>
    <description>SFDC-4540: This object is to store criteria for identification of Legal Entity under Product Selection framework.</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>SFDC-4540: Store the account region</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Selection Criteria</label>
    <nameField>
        <displayFormat>PSC-{000000}</displayFormat>
        <label>Product Selection Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Selection Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestProductSelectionController.cls
/*
* @Author : Manish Kumar
* @Date : 2nd Dec 2021
* @Description : Test Class for ProductSelectionController
* @company : IHS Markit
*/
@isTest
private class TestProductSelectionController {
    
    @testSetup static void setup() {
        //create test data
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        Account acc = TestUtility.createTestAccount('Test Account for Product Selection', true);
        LegalEntity__c leUS = TestUtility.createLegalEntity('Markit Group Limited US', 'USD');
        LegalEntity__c leIndia = TestUtility.createLegalEntity('IHS Global Pte Ltd', 'USD');
        LegalEntity__c leMarkitSERV = TestUtility.createLegalEntity('MarkitSERV Ltd', 'USD');
        
        Country__c countryUS = New Country__c();
        countryUS.Name = 'United States';
        countryUS.CountryCode__c = 'US';
        countryUS.Geography__c = 'United States';
        countryUS.Region__c = 'Americas';
        insert countryUS;
        Country__c countryIndia = New Country__c();
        countryIndia.Name = 'India';
        countryIndia.CountryCode__c = 'IN';
        countryIndia.Geography__c = 'Singapore';
        countryIndia.Region__c = 'APAC';
        insert countryIndia;
		Country__c countryROW = New Country__c();
		countryROW.Name = 'Rest of the World';
		countryROW.CountryCode__c = 'RT';
		countryROW.Geography__c = '#N/A';
		countryROW.Region__c = 'EMEA';
		insert countryROW;
        
        id newBusinessRecTypeId = UtilityClass.getObjectRecordTypeId('Opportunity','New Business');
        Opportunity oppyUS = TestUtility.createOpportunity(acc.Id, 'Test Opportunity for US', false);
        oppyUS.RecordTypeId = newBusinessRecTypeId;
        oppyUS.ExceptionStatus__c = 'Exception Request Denied';
        oppyUS.RequestedLegalEntity__c = leUS.Id;
        oppyUS.CurrencyIsoCode = 'USD';
        oppyUS.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
        oppyUS.OpportunityCountry__c = countryUS.Id;
        insert oppyUS;
        test.startTest();
        Opportunity oppyIndia = TestUtility.createOpportunity(acc.Id, 'Test Opportunity for India', false);
        oppyIndia.RecordTypeId = newBusinessRecTypeId;
        //oppy.ExceptionStatus__c = 'Exception Request Denied';
        //oppy.RequestedLegalEntity__c = leIndia.Id;
        //oppy.CurrencyIsoCode = 'USD';
        //oppy.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
        oppyIndia.OpportunityCountry__c = countryIndia.Id;
        insert oppyIndia;
        
        Product2 prod1 = TestUtility.createProduct('Test Product1', false);
        prod1.legalEntity__c = leIndia.Id;
        insert prod1;
        Product2 prod2 = TestUtility.createProduct('Test Product2', false);
        prod2.legalEntity__c = leIndia.Id;
        insert prod2;
        ProductExtensions__c pe1 = New ProductExtensions__c();
        pe1.product__c = prod1.Id;
        pe1.Status__c = 'Active';
        pe1.LegalEntity__c = leUS.Id;
        insert pe1;
        
        Id stdPricebookId = Test.getStandardPricebookId();
        PriceBook2 standardPB = new PriceBook2(Id = stdPricebookId, Name = 'Standard Price Book', isActive = true);
        update standardPB;
        
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, prod1.Id, false);
        pbe1.CurrencyIsoCode = oppyUS.CurrencyIsoCode;
        insert pbe1;
        
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, String.valueOf(currentFY), '1 Year', String.valueOf(currentFY), prod1.Id, true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(oppyUS.Id, pbe1, true);
        
        OpportunityLineItemSchedule__c ops1 = TestUtility.createOpportunityProductSchedule(oppyUS.Id,ps1.Id,2223.23,2000,
                                                                                           'Amount', 223.23, 0.0, prod1.Id, '2017', 1, 
                                                                                           testOLI.Id,false);
        ops1.Quantity__c = 1;
        insert ops1;
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 2nd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.productSelectionRuleEngine
    // @return: NA
    //-----------------------------
	@isTest
    static void testProductSelectionRuleEngine(){
        test.startTest();
        
        Opportunity oppyUS = [Select id, OpportunityCountry__r.Region__c from Opportunity where Name = 'Test Opportunity for US' LIMIT 1];
        System.assertEquals('Americas', oppyUS.OpportunityCountry__r.Region__c, 'Region should be Americas');
        
        Opportunity oppyIndia = [Select id, OpportunityCountry__r.Region__c from Opportunity where Name = 'Test Opportunity for India' LIMIT 1];
        System.assertEquals('APAC', oppyIndia.OpportunityCountry__r.Region__c, 'Region should be APAC');
        
        List<Id> listOfProductIds = New List<Id>();
        Product2 prod1 = [Select id, isActive from Product2 where Name = 'Test Product1' LIMIT 1];
        System.assertEquals(true, prod1.isActive, 'Product Status should be Active');
        listOfProductIds.add(prod1.Id);
        
        LegalEntity__c leUS = [Select id, Status__c from LegalEntity__c where Name = 'Markit Group Limited US' LIMIT 1];
        System.assertEquals('Active', leUS.Status__c, 'Status should be Active');
        
        LegalEntity__c leIndia = [Select id, Status__c from LegalEntity__c where Name = 'IHS Global Pte Ltd' LIMIT 1];
        System.assertEquals('Active', leUS.Status__c, 'Status should be Active');
        
        LegalEntity__c leMarkitSERV = [Select id, Status__c from LegalEntity__c where Name = 'MarkitSERV Ltd' LIMIT 1];
        System.assertEquals('Active', leUS.Status__c, 'Status should be Active');
        
        Country__c CountryIndia = [Select id, Name, Region__c from Country__c where Name = 'India' LIMIT 1];
        System.assertEquals('APAC', CountryIndia.Region__c, 'Region should be APAC');
        
        Country__c CountryUS = [Select id, Name, Region__c from Country__c where Name = 'United States' LIMIT 1];
        System.assertEquals('Americas', CountryUS.Region__c, 'Region should be Americas');
        
        Country__c CountryROW = [Select id, Name, Region__c from Country__c where Name = 'Rest of the World' LIMIT 1];
		System.assertEquals('EMEA', CountryROW.Region__c, 'Region should be EMEA');
        
        ProductSelectionCriteria__c psc3 = New ProductSelectionCriteria__c();
        psc3.stepNumber__c = 3;
        psc3.order__c = 1;
        psc3.BillingCountry__c = CountryUS.Id;
        psc3.TargetLegalEntity__c = leUS.Id;
        insert psc3;
        
        ProductSelectionCriteria__c psc4 = New ProductSelectionCriteria__c();
        psc4.stepNumber__c = 4;
        psc4.order__c = 1;
        psc4.TargetLegalEntity__c = leIndia.Id;
        psc4.Region__c = 'APAC';
        insert psc4;
        
        LegalEntityResultWrapper lerw1 = ProductSelectionController.productSelectionRuleEngine(oppyUS.Id, listOfProductIds);
        System.assertEquals('Success', lerw1.result, 'Result should be Success');
        
        ProductSelectionCriteria__c psc2 = New ProductSelectionCriteria__c();
        psc2.stepNumber__c = 2;
        psc2.order__c = 1;
        psc2.ProductLegalEntity__c = leMarkitSERV.Id;
        insert psc2;
        
        ProductSelectionCriteria__c psc1 = New ProductSelectionCriteria__c();
        psc1.stepNumber__c = 1;
        psc1.order__c = 1;
        psc1.BillingCountry__c = CountryIndia.Id;
        psc1.TargetLegalEntity__c = leIndia.Id;
        insert psc1;
        
        LegalEntityResultWrapper lerw2 = ProductSelectionController.productSelectionRuleEngine(oppyIndia.Id, listOfProductIds);
        System.assertEquals('Success', lerw2.result, 'Result should be Success');
        
        ProductSelectionCriteria__c psc0 = New ProductSelectionCriteria__c();
        psc0.stepNumber__c = 0;
        psc0.order__c = 1;
        psc0.FormerIpOwner__c = 'IHS Consulting';
        insert psc0;
        LegalEntityResultWrapper lerw3 = ProductSelectionController.productSelectionRuleEngine(oppyUS.Id, listOfProductIds);
        System.assertEquals('Success', lerw3.result, 'Result should be Success');
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 2nd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.saveProductsOnOpportunity
    // @return: NA
    //-----------------------------
	@isTest
    static void testSaveProductsOnOpportunity(){
        test.startTest();
        Opportunity oppy = [Select id, OpportunityCountry__r.Region__c from Opportunity where Name = 'Test Opportunity for US' LIMIT 1];
        System.assertEquals('Americas', oppy.OpportunityCountry__r.Region__c, 'Region should be Americas');
        LegalEntity__c le = [Select id, Status__c from LegalEntity__c where Name = 'Markit Group Limited US' LIMIT 1];
        System.assertEquals('Active', le.Status__c, 'Status should be Active');
        List<String> listOfProductIds = New List<String>();
        Product2 prod1 = [Select id, isActive from Product2 where Name = 'Test Product1' LIMIT 1];
        System.assertEquals(true, prod1.isActive, 'Product Status should be Active');
        listOfProductIds.add(prod1.Id);
        String result1 = ProductSelectionController.saveProductsOnOpportunity(listOfProductIds, oppy.Id, le.Id, false, false);
        System.assertEquals('Records added successfully', result1, 'Verify if products added successfully');
        String result2 = ProductSelectionController.saveProductsOnOpportunity(listOfProductIds, oppy.Id, le.Id, false, true);
        System.assertEquals('Records updated successfully', result2, 'Verify if products updated successfully');
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 2nd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.getOppCountry
    // @return: NA
    //-----------------------------
	@isTest
    static void testGetOppCountry(){
        test.startTest();
        Opportunity oppy = [Select id, OpportunityCountry__r.Region__c from Opportunity where Name = 'Test Opportunity for US' LIMIT 1];
        System.assertEquals('Americas', oppy.OpportunityCountry__r.Region__c, 'Region should be Americas');
        String oppCountry = ProductSelectionController.getOppCountry(oppy.Id);
        System.assertEquals('United States', oppCountry, 'OppCountry should be United States');
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 3rd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.exceptionApprovalEmail
    // @return: NA
    //-----------------------------
	@isTest
    static void testExceptionApprovalEmail(){
        test.startTest();
        Opportunity oppy = [Select id, OpportunityCountry__r.Region__c, (select id, Status__c from opportunitylineitems) from Opportunity where Name = 'Test Opportunity for US' LIMIT 1];
        System.assertEquals('Americas', oppy.OpportunityCountry__r.Region__c, 'Region should be Americas');
        LegalEntity__c le = [Select id, Status__c from LegalEntity__c where Name = 'Markit Group Limited US' LIMIT 1];
        System.assertEquals('Active', le.Status__c, 'Status should be Active');
        
        Map<String,List<OpportunityLineItemSchedule__c>> mapOppyProductandSchedules = new Map<String,List<OpportunityLineItemSchedule__c>>();
        for(OpportunityLineItemSchedule__c ops : [Select id,opportunityProductID__c,Opportunity__c,ExternalListPrice__c,Quantity__c,discountType__c from OpportunityLineItemSchedule__c]) {
            if(mapOppyProductandSchedules.containsKey(ops.opportunityProductID__c)) {
                mapOppyProductandSchedules.get(ops.opportunityProductID__c).add(ops);
            }
            else {
                mapOppyProductandSchedules.put(ops.opportunityProductID__c,new List<OpportunityLineItemSchedule__c>{ops});
            }
        }
        
        opportunitylineitem oli = oppy.opportunitylineitems[0];
        OPSWrapper opsWrapObj = new OPSWrapper();
		opsWrapObj.Status = oli.Status__c;
		opsWrapObj.oppyProduct = new OpportunityLineItem();
		opsWrapObj.oppyProduct = oli;
		opsWrapObj.mapOPSAll = new Map<String,List<OpportunityLineItemSchedule__c>>();
		opsWrapObj.lstOPS = mapOppyProductandSchedules.get(oli.Id);
		String existingTerm = String.valueOf(opsWrapObj.lstOPS.size());
		opsWrapObj.productTermSelected = existingTerm;
		opsWrapObj.mapOPSAll.put(existingTerm,opsWrapObj.lstOPS);
		opsWrapObj.productQty = 0.0;
        opsWrapObj.isDeleted = false;
        opsWrapObj.productQty = opsWrapObj.lstOPS[0].Quantity__c;
        opsWrapObj.discountType = opsWrapObj.lstOPS[0].discountType__c;
        opsWrapObj.productTermSelected = String.valueOf(opsWrapObj.lstOPS.size());
        opsWrapObj.lstMapOPSIndex = new List<String>();
        String wrapperJSON = '['+JSON.serialize(opsWrapObj)+']';
        
        Boolean result = ProductSelectionController.exceptionApprovalEmail(oppy.Id, 'Testing', le.Id, '1', 'India', '22012212', wrapperJSON);
        System.assertEquals(true, result, 'result should be true');
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 3rd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.getListLegalEntity
    // @return: NA
    //-----------------------------
	@isTest
    static void testGetListLegalEntity(){
        test.startTest();
        List<id> listOfProductIds = New List<id>();
        Product2 prod1 = [Select id, isActive from Product2 where Name = 'Test Product1' LIMIT 1];
        System.assertEquals(true, prod1.isActive, 'Product Status should be Active');
        listOfProductIds.add(prod1.Id);
        //For Single Product
        LegalEntityResultWrapper lerw1 = ProductSelectionController.getListLegalEntity(listOfProductIds);
        System.assertEquals('SUCCESS', lerw1.result, 'Result should be SUCCESS');
        Product2 prod2 = [Select id, isActive from Product2 where Name = 'Test Product2' LIMIT 1];
        System.assertEquals(true, prod2.isActive, 'Product Status should be Active');
        listOfProductIds.add(prod2.Id);
        //For Multiple Products
        LegalEntityResultWrapper lerw2 = ProductSelectionController.getListLegalEntity(listOfProductIds);
        System.assertEquals('SUCCESS', lerw2.result, 'Result should be SUCCESS');
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 3rd Dec 2021
    // @param: NA
    // @description: Test method for ProductSelectionController.updateLegalEntityOnOppy
    // @return: NA
    //-----------------------------
	@isTest
    static void testUpdateLegalEntityOnOppy(){
        test.startTest();
        Opportunity oppy = [Select id, OpportunityCountry__r.Region__c from Opportunity where Name = 'Test Opportunity for US' LIMIT 1];
        System.assertEquals('Americas', oppy.OpportunityCountry__r.Region__c, 'Region should be Americas');
        LegalEntity__c le = [Select id, Status__c from LegalEntity__c where Name = 'Markit Group Limited US' LIMIT 1];
        System.assertEquals('Active', le.Status__c, 'Status should be Active');
        String result = ProductSelectionController.updateLegalEntityOnOppy(oppy.Id, le.Id);
        System.assertEquals('Records updated successfully', result, 'Verify if Legal Entity updated successfully');
        test.stopTest();
    }      
}