objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-3378 Global Account Manager</description>
        <inlineHelpText>Global Account Manager</inlineHelpText>
        <label>GAM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ChangeLog__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all Work Request change log data.</description>
    <fields>
        <fullName>ChangeDescription__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Change Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Programmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Programmer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <description>Picklist value of Status for Work request form</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved without Job</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Change Logs</relationshipLabel>
        <relationshipName>ChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityName__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning page layout</description>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity Name</inlineHelpText>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>OrderRequestStatus__c</fullName>
        <label>Order Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved without Job</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Programmer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Queues__mdt.object
<CustomObject>
    <label>Queue</label>
    <pluralLabel>Queues</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestOperationsQueue.cls
//--------------------------------------------------------------------
// @author: Anjali
// @date: 06 July 2021
// @description: This is test class for WorkRequestFormController
//--------------------------------------------------------------------
@isTest
public class TestOperationsQueue {
    
    @testSetup static void testData() {
        Account a = TestUtility.createTestAccount('testAccount', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName= '1-Sales Qualified';
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.GAM__c = u.id;
        opp.AccountId = a.id;
        insert opp; 
        Id PSRecordTypeId = Schema.SObjectType.WorkRequestForm__c.getRecordTypeInfosByName().get('Planning Solutions').getRecordTypeId();
        WorkRequestForm__c wrf = new WorkRequestForm__c();
        wrf.RecordTypeId = PSRecordTypeId;
        wrf.JobType__c = 'Ad Hoc';
        wrf.RoyaltyVendor__c='No Royalty Data';
        wrf.ReturnToSales__c=true;
        wrf.PrimarySalesContact__c=UserInfo.getUserId();
        wrf.RequestedDueDate__c = System.today() + 7;
        wrf.OutputType__c='Comma Delimited (CSV)';
        wrf.OutputMedium__c='CD ROM/DVD';
        wrf.PlanningSolutions__c = true;
        wrf.PlanningSolutionsProdRegions__c  ='Europe';
        wrf.RequestStatus__c='Submitted';
        wrf.OpportunityName__c= opp.Id;
        wrf.AccountName__c= a.Id;
        wrf.PlanningSolutionsEndDate__c=system.today()+10; 
        wrf.PlanningSolutionsStartDate__c = system.today(); 
        insert wrf;
        List<ChangeLog__c> clList = new List<ChangeLog__c>();
        User userObj =[Select Id,Name FROM User WHERE Id=:Userinfo.getUserId()];
        System.runAs(userObj) {
            ChangeLog__c changeLog = new ChangeLog__c();
            changeLog.ChangeDescription__c = 'Test';
            changeLog.WorkRequestForm__c = wrf.id;
            changeLog.RequestStatus__c='Draft';
            clList.add(changeLog);
            ChangeLog__c changeLog1 = new ChangeLog__c();
            changeLog1.ChangeDescription__c = 'Test';
            changeLog1.WorkRequestForm__c = wrf.id;
            changeLog1.RequestStatus__c='Submitted';
            clList.add(changeLog1);
            ChangeLog__c changeLog2 = new ChangeLog__c();
            changeLog2.ChangeDescription__c = 'Test';
            changeLog2.WorkRequestForm__c = wrf.id;
            changeLog2.RequestStatus__c='Submitted';
            changeLog2.Programmer__c = u.Id;
            clList.add(changeLog2);
            insert clList;
            OrderRequest__c orderReq = new OrderRequest__c();
            orderReq.WorkRequestForm__c = wrf.Id;
            orderReq.OrderRequestStatus__c = 'Submitted';
            insert orderReq;
        }
    }
	@isTest
    public static void testQueueValues(){
        List<Queues__mdt> lstOfQueue;
        Test.startTest();
        lstOfQueue = OperationsQueue.queueValues();
        Test.stopTest();
        system.assertNOTEquals(lstOfQueue.size(), 0, 'queueValues did not return correct no of records' );
    }
	@isTest
    public static void testGetWRFRecords(){
        list<WorkRequestForm__c> lstOfWRF;
        Test.startTest();
        lstOfWRF = OperationsQueue.getWRFRecords('All');
        Test.stopTest();
        system.assertEquals(lstOfWRF.size(), 1, 'getWRFRecords did not return correct no of records' );
    }
    @isTest
    public static void testGetWRFRecordswithsearchId(){
        list<WorkRequestForm__c> lstOfWRF;
        Test.startTest();
        lstOfWRF = OperationsQueue.getWRFRecords('Planning Solutions');
        Test.stopTest();
        system.assertEquals(lstOfWRF.size(), 1, 'getWRFRecords did not return correct no of records' );
    }
	@isTest
    public static void testGetchangeLogRecords(){
        list<changelog__c> clResults;
        Test.startTest();
        clResults = OperationsQueue.getchangeLogRecords('All');
        Test.stopTest();
        system.assertEquals(clResults.size(), 2, 'getchangeLogRecords did not return correct no of records' );
    }
    @isTest
    public static void testGetchangeLogRecordswithsearchId(){
        list<changelog__c> clResults;
        Test.startTest();
        clResults = OperationsQueue.getchangeLogRecords('Planning Solutions');
        clResults = OperationsQueue.getchangeLogRecords('Planning Solutions');
        Test.stopTest();
        system.assertEquals(clResults.size(), 2, 'getchangeLogRecords did not return correct no of records' );
    }
	@isTest
     public static void testGetOrderReqRecords(){
        list<OrderRequest__c> orResults;
        Test.startTest();
        orResults = OperationsQueue.getOrderReqRecords('All');
        Test.stopTest();
        system.assertEquals(orResults.size(), 1, 'getOrderReqRecords did not return correct no of records' );
    }  
	@isTest
    public static void testGetOrderReqRecordswithsearchId(){
        list<OrderRequest__c> orResults;
        Test.startTest();
        orResults = OperationsQueue.getOrderReqRecords('PAS');
        Test.stopTest();
        system.assertEquals(orResults.size(), 0, 'getOrderReqRecords did not return correct no of records' );
    }  

}