objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4728: Create Auto Renewal field on Opportunity that will be updated from Contract.</description>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoesThisAutoRenewalHaveChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field includes renewal details of opportunity. (JIRA story SFDC1-556)</description>
        <inlineHelpText>Specify if Auto Renewal has any changes.</inlineHelpText>
        <label>Does this Auto Renewal Have Changes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <description>SFDC1 -171; Describe source of the lead/opportunity
SFDC1-2219; Rename Source System to External Source System
SFDC1-8491: Updated picklist values
SFDC-2753: Added picklist value for PCM</description>
        <inlineHelpText>Please select a value</inlineHelpText>
        <label>External Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Manually Generated</fullName>
                    <default>true</default>
                    <label>Manually Generated</label>
                </value>
                <value>
                    <fullName>IHS CRM</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Lead Generated</fullName>
                </value>
                <value>
                    <fullName>Third Party System</fullName>
                </value>
                <value>
                    <fullName>Polk Salesforce</fullName>
                </value>
                <value>
                    <fullName>Markit Salesforce</fullName>
                </value>
                <value>
                    <fullName>PCM Salesforce</fullName>
                </value>
                <value>
                    <fullName>IHSM Salesforce</fullName>
                </value>
                <value>
                    <fullName>Market Scan (Dealer Instance)</fullName>
                </value>
                <value>
                    <fullName>Market Scan (API Customer Instance)</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                    <isActive>false</isActive>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>Markit SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Markit SFDC</label>
                </value>
                <value>
                    <fullName>Markit Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Markit Salesforce.com</label>
                </value>
                <value>
                    <fullName>Polk SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Polk SFDC</label>
                </value>
                <value>
                    <fullName>Polk Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Polk Salesforce.com</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestOpportunityUpdateBatchJob.cls
//-----------------------------
// @author: Sushma Yadav
// @date: 24 Jan 2020
// @param: NA
// @description: Test Class for OpportunityUpdateBatchJob class
// @lastmodifiedBy: Neelam Agrawal
// @date: 09 Mar 2022
// @return: NA
//----------------------------
@isTest
private class TestOpportunityUpdateBatchJob {
    
    @isTest
    Private static void createTestData() {
        
        Account testAccount = TestUtility.createTestAccount('Account testSetCaseOpportunityUpdate', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Id renewRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        List<Opportunity> oppList = new List<Opportunity>();
        
        Opportunity opp1 = new Opportunity(Name = 'Test Opp1' , StageName= '3-Renewal Pending', RecordTypeId = renewRecordTypeId, CloseDate = System.today()+2,
                                           AutoRenewal__c = true, SourceSystem__c = 'SAP', DoesThisAutoRenewalHaveChanges__c = false,
                                           AccountId = testAccount.id);
        
        Opportunity Opp2 = new Opportunity(Name = 'Test Opp2' , StageName= '3-Renewal Pending', RecordTypeId = renewRecordTypeId, CloseDate = System.today()+2,
                                           AutoRenewal__c = true, SourceSystem__c = 'Manually Generated', DoesThisAutoRenewalHaveChanges__c = false,
                                           AccountId = testAccount.id);
        oppList.add(opp1);
        oppList.add(opp2);
        insert oppList;
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'test1';
        c.AccountId = testAccount.Id;
        c.Email = 'a@tst123example.com';
        insert c;
        
        List<OpportunityContactRole> ocrList = new List<OpportunityContactRole>();
        OpportunityContactRole ocr = new OpportunityContactRole(ContactId = c.Id, OpportunityId = opp1.Id, IsPrimary = TRUE, Role = 'Decision Maker');
        
        OpportunityContactRole ocr1 = new OpportunityContactRole(ContactId = c.Id, Isprimary = True, OpportunityId = opp2.Id, Role = 'Decision maker');
        ocrList.add(ocr);
        ocrList.add(ocr1);
        insert ocrList;  
        
        for(Opportunity oppty: oppList) {
            oppty.stageName = '6W-Renewal Won';
        }
        update oppList;
        
        Test.startTest();
        OpportunityUpdateBacthJobScheduled sh1= new OpportunityUpdateBacthJobScheduled();
        String sch1 = '0 0 23 * * ?';
        System.schedule('test oppyupdate batch', sch1,sh1 );
        Id batchJobId = Database.executeBatch(new OpportunityUpdateBatchJob(), 1);
        system.debug('batchJobId='+batchJobId);		
        Test.stopTest();
        
        List<Opportunity> Oppties = [SELECT Id FROM Opportunity where id in :OppList and stageName = '6WP-Closed Won/Order Processed'];
        System.assertEquals(1, Oppties.size(),'Check Oppties size is 1');
        
    }
}