objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>SFDC-1103 This field captures the budget range for the opportunity</description>
        <inlineHelpText>Please provide the Budget Range.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>100,000 - 500,000</fullName>
                </value>
                <value>
                    <fullName>500,000 - 1,000,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 1,000,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContinuationEndDate__c</fullName>
        <description>SFDC1-8989 &quot;Continuation End Date&quot; on the &apos;Renewal&apos; opportunity record type.</description>
        <inlineHelpText>Continuation End Date</inlineHelpText>
        <label>Continuation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quota__c.object
<CustomObject>
    <description>SFDC-4105:  Quota Import &amp; Assignment</description>
    <fields>
        <fullName>GlobalVertical__c</fullName>
        <label>Global Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CMS</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GlobalVertical__c</fullName>
        <label>Global Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consolidated Markets &amp; Solutions</fullName>
                </value>
                <value>
                    <fullName>Financial Markets</fullName>
                </value>
                <value>
                    <fullName>Financial Services: Financial Markets</fullName>
                </value>
                <value>
                    <fullName>Financial Services: Financial Market Technologies</fullName>
                </value>
                <value>
                    <fullName>Resources</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Above All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchCreateRenewalQuota.cls
//-----------------------------
// @author: Neelam Agrawal
// @date: 05 July 2021
// @param: NA
// @description: Test Class for BatchCreateRenewalQuota
// @return: NA
//----------------------------
@isTest
private class TestBatchCreateRenewalQuota {
    @isTest
    static void testCreateRenewalQuota() {
        Profile p = [SELECT Id FROM Profile WHERE Name ='IHSMarkit Data Governance'];
        
        User testUser = new User(Alias = 'standt', Email='testUSer.testuser123@ihsmarkit.com.user', 
                                 EmailEncodingKey='UTF-8', firstName='testFirstName', HRManager__c='testManager', LastName='testLastName',
                                 LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id,GlobalVertical__c='Financial Markets',
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testUSer.testuser123@ihsmarkit.com.user', ADID__c='test'+String.valueOf(Math.round(Math.random()*10000))+system.now().millisecond(),
                                 EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert testUser;
        System.runAs(testUser){
            Test.startTest();           
            List<Account> accList = new List<Account>();
            Account acc = TestUtility.createTestAccount('Account testCreateRenewalQuota Summary1', false);
            acc.DataGovernanceStatus__c = 'Approved';
            accList.add(acc);
            Account acc2 = TestUtility.createTestAccount('Account testCreateRenewalQuota Summary2', false);
            acc2.DataGovernanceStatus__c = 'Approved';
            accList.add(acc2);
            insert accList;
            Contact con = TestUtility.createContact(acc.Id,'oppty.primary@ihsmarkit.com',true,'TestOppty','TestPrimary');
            Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', false);
            insert testOpportunity;
            OpportunityContactRole ocr = new OpportunityContactRole(IsPrimary = true, OpportunityId = testOpportunity.Id, ContactId=con.Id);
            insert ocr;
            testOpportunity.BudgetRange__c = '< 25,000';
            testOpportunity.ActivityCreated__c = true;
            testOpportunity.ContractStartDate__c = System.today()-30;
            testOpportunity.ContinuationEndDate__c=System.today()-30;
            Id RenewalOppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
            testOpportunity.RecordTypeId=RenewalOppRecordTypeId;
            update testOpportunity;
            String batchId = Database.executeBatch(new BatchCreateRenewalQuota(),200);
            Test.stopTest();
            List<Quota__c> quota = [Select id from Quota__c];
            System.assertEquals(true, quota.size()>0, 'Quota records are not created');
            
        }
    }
}