objects/Account.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-10407 : Creating this field to bypass the validation rule using Apex Code.</description>
        <inlineHelpText>This field will be used to byPass the Validation Rules in Apex.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <description>SFDC1-965 and SFDC1-683 Field to hold account name which will be used to create new Account
SFDC1-10142 change label to &quot;Requested Account Name&quot;</description>
        <inlineHelpText>Legal Entity Name of the requested account</inlineHelpText>
        <label>Requested Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-10251: Field used to bypass validation rules. OMDH case created from lightning component in Contract has to be bypassed</description>
        <inlineHelpText>Field used to bypass validation rules</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryTeam__c</fullName>
        <description>SFDC1-6148: This field will hold the Delivery Team values
SFDC1-6944: Reorder the picklist values
SFDC1-6995: Configure field dependencies - if Team Select = Retail, only RETAIL values are available in Delivery Team</description>
        <label>Delivery Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TeamSelect__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agri Connect</fullName>
                </value>
                <value>
                    <fullName>Agri SAM</fullName>
                </value>
                <value>
                    <fullName>Auto Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Calgary Licensing</fullName>
                </value>
                <value>
                    <fullName>CD Distribution</fullName>
                </value>
                <value>
                    <fullName>Chemical Deliverables</fullName>
                </value>
                <value>
                    <fullName>CI Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Delivery Technical</fullName>
                </value>
                <value>
                    <fullName>EMEA Physical Delivery</fullName>
                </value>
                <value>
                    <fullName>Englewood Physical Delivery</fullName>
                </value>
                <value>
                    <fullName>Erights</fullName>
                </value>
                <value>
                    <fullName>Experts Portal</fullName>
                </value>
                <value>
                    <fullName>Fekete Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>GIS Delivery</fullName>
                </value>
                <value>
                    <fullName>Global Delivery EMEA ADandM</fullName>
                </value>
                <value>
                    <fullName>Global Delivery Help Desk</fullName>
                </value>
                <value>
                    <fullName>Global Insight Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Goldfire Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>GTA Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>JOC Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Kingdom Licensing</fullName>
                </value>
                <value>
                    <fullName>Macro Economic Advisors</fullName>
                </value>
                <value>
                    <fullName>ODSP Orders</fullName>
                </value>
                <value>
                    <fullName>Online Delivery</fullName>
                </value>
                <value>
                    <fullName>OPIS Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Entitlements EM</fullName>
                </value>
                <value>
                    <fullName>Order Entitlements UK</fullName>
                </value>
                <value>
                    <fullName>PETRA Licensing</fullName>
                </value>
                <value>
                    <fullName>Premier Order Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Product Design</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoadingGroupOnboarding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7137: Creating lookup field for Implementation record type. Since there exists another field as Loading group, creating new field with same label, but different API</description>
        <label>Loading Group</label>
        <referenceTo>LoadingGroup__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMDStatus__c</fullName>
        <description>SFDC1-6250 Dependent picklist (controlling field is &quot;Team Select&quot;)</description>
        <label>OMD Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TeamSelect__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Re-Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Clarification</fullName>
                </value>
                <value>
                    <fullName>Pending Documentation</fullName>
                </value>
                <value>
                    <fullName>Waiting on Information - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Waiting on Information - Customer</fullName>
                </value>
                <value>
                    <fullName>Waiting on Information - Internal</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Resolved - No Delivery Action Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SingleSignOnSAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-8685 SAM SSO Inquiry Checkbox field</description>
        <label>Single Sign On (SAM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamSelect__c</fullName>
        <description>SFDC1-6148 : This field will hold the value of Team</description>
        <label>Team Select</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Management</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CaseProducts__c.object
<CustomObject>
    <description>SFDC1-593 - Junction object between Case and Products</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>SFDC1-593 - Master Detail relationship to Case</description>
        <inlineHelpText>Select the Case you wish to relate to additional Products</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-593 - Lookup to Product</description>
        <inlineHelpText>Select a Product (if known).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Products</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>AssociatedProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4324 This field holds the product associated with &apos;Opportunity Line Item&apos;, to which contract line item is related.</description>
        <inlineHelpText>Product related to Opportunity Line Item</inlineHelpText>
        <label>Associated Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items (Associated Product)</relationshipLabel>
        <relationshipName>ContractLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LoadingGroup__c</fullName>
        <formula>AssociatedProduct__r.LoadingGroup__r.Name</formula>
        <label>Loading Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2298;Product Lookup field on Contract Line Item
SFDC-99 Duplicate for AssociatedProduct__c marking this as zz to delete in future</description>
        <label>zzzProduct</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LoadingGroup__c.object
<CustomObject>
    <description>SFDC1-2462 Loading Group related to product. To be maintained by Vanguard product management process</description>
    <fields>
        <fullName>DeliveryTeam__c</fullName>
        <description>SFDC1-6249 This field is to carry loading group so cases get sent to the correct Delivery teams when an opportunity is closed</description>
        <label>Delivery Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoadingGroupCategory__c</fullName>
        <description>SFDC1-6976: A new field to store Loading Group Category</description>
        <label>Loading Group Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Loading Group</label>
    <nameField>
        <label>Loading Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loading Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LoadingGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2462 Lookup field to capture loading group on product</description>
        <inlineHelpText>Loading Group Managed by Vanguard Product Management Process</inlineHelpText>
        <label>Loading Group</label>
        <referenceTo>LoadingGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LoadingGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateOMDHCaseController.cls
////--------------------------------------
// @Author : Vishnu Vardhan Chowdary 
// @date: 08th Oct 2018
// @description : SFDC1-9003 Controller to create Order Management Delivery Helpdesk cases 
// 					from lightning quick action on Contract. 
// @company : Vertiba
//--------------------------------------
public without sharing class CreateOMDHCaseController {

    private static Id omdhRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Order Management/Delivery Help Desk').getRecordTypeId();
    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 8 Oct 2018
    // @param: NA
    // @description: SFDC1- 9003 : The earlier requirement of creating Order Management delivery helpdesk 
    // 		case has been moved to lightning component. Accordingly moving all predefined values in existing
    // 		lightning quick action into Code.
    // @return: Case
    // @company: VERTIBA
    //------------------------------
    @AuraEnabled
    public static Case getOMDHRecord() {
        Case cas = new Case();
        cas.RecordTypeId = omdhRecordTypeId;
        //Values are not displayed in UI, but are stored in case. Moving values 
        //exactly as in existing quick actions. 
        cas.Origin = 'Contract';
        cas.Status = 'In Progress';
        cas.OMDStatus__c = 'New';
        cas.AccountName__c = System.Label.NewUserContactAccount;
        cas.ByPassValidation__c = true;
        return cas;
    }

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 8 Oct 2018
    // @param: Id - ContractId for which OMDH case is about to be created
    // @description: SFDC1-9003: Create and return contract details to UI. Few details of 
    // 				contract are required to be shown on UI, add to case for persisting. 
    // @return: Contract - Few details of contract record
    // @company: VERTIBA
    //------------------------------
    @AuraEnabled
    public static Contract getContractDetails(Id contractId){
        Contract ctrct = [select Id, AccountId, ContractNumber from contract where id = :contractId];
        return ctrct;
    }

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 8 Oct 2018
    // @param: Case - OMDH Case that will be created with teamselect as 'Order Management' or 'Retail'.  
    // @description: SFDC1-9003: OMDH Case will be created with teamselect as 'Order Management'
    // 				    or 'Retail' as selected in the lightning component.
    // @return: String - Success or error Message to be displayed in UI.
    // @company: VERTIBA
    //------------------------------
    @AuraEnabled
    public static String saveOMDHCase (Case cas) {
        String msg = 'Case record created';
        try {
            insert cas;
            //reverting by pass validation, so that next time when it is edited, validation should trigger
            //Internally when case is inserted Account is set to IHS Markit account, If cas is updated directly,  
            //then account the earlier set IHS Markit is reset with account from Contract and validation error 
            //is thrown. To avoid that creating a new case variable and updating here.
            Case c = new Case(id=cas.Id, ByPassValidation__c = false);
            update c;
        } catch (Exception e) {
            if(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                msg = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',':');  
            } else {
                msg = e.getMessage();
            }
        }
        return msg;
    } 

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 8 Oct 2018
    // @param: Id - ContractId for which cases are to be created.  
    // @description: SFDC1-9003: Once user selects the Delivery as team select and continue, following steps occur:
    // 		1. Get products from the contract line items.
    // 		2. Get all the OM cases for contract with team select as delivery, and collect the related products.
    // 		3. Remove all the products in step 1, that are already part of OMDH cases in step 2.
    // 		4. Create a wrapper class for each product and return the list.
    // @return: List<ProductSelectorWrapperClass> - List to be displayed in the second screen for user to select.
    // @company: VERTIBA
    //------------------------------
    @AuraEnabled
    public static List<ProductSelectorWrapperClass> getAvailableProductsForContract(Id ContractId) {
        List<ProductSelectorWrapperClass> lstProductsToReturn = new List<ProductSelectorWrapperClass>();
        List<ContractLineItem__c> cliList = [Select id, associatedProduct__r.Name, associatedProduct__r.loadingGroup__r.name, 
                                     		associatedProduct__r.loadingGroup__r.DeliveryTeam__c, associatedProduct__r.Id 
                                             From ContractLineItem__c where Contract__c = :ContractId and 
                                            AssociatedProduct__r.LoadingGroup__r.LoadingGroupCategory__c = 'IHS'];
        Map<Id, ContractLineItem__c> cliMap = new Map<Id, ContractLineItem__c>();
        for(ContractLineItem__c clitem : cliList) {
            cliMap.put(clitem.AssociatedProduct__c, clitem);
        }
        if(cliMap.isEmpty()) {
            //No contract line items, we are displaing blank screen by returning empty list
            return lstProductsToReturn;
        }
        //Get all the OMDH cases for contract with team select as delivery, and collect the related products
        /**List<CaseProducts__c> cpList = [select id, Product__c from CaseProducts__c where Case__r.Contract__c = :ContractId
                                       and Case__r.recordTypeId = :omdhRecordTypeId and Case__r.TeamSelect__c = 'Delivery' 
                                       and Case__r.isClosed=false];
        //remove the products for which cases are already created. 
        for(CaseProducts__c caseProduct : cpList ) {
            cliMap.remove(caseProduct.product__c);
        }
        if(cliMap.isEmpty()) {
            //No new products to select we are displaing blank screen by returning empty list
            return lstProductsToReturn;
        }*/
        //create a wrapper and send to UI. Need Id, Product Name and Loading Group ID (to group)
        for(ContractLineItem__c clitem : cliMap.values()) {
            productSelectorWrapperClass wrapper = new productSelectorWrapperClass();
            wrapper.isSelected = false;
            wrapper.productName = clitem.associatedProduct__r.Name;
            wrapper.loadingGroupId = clitem.associatedProduct__r.loadingGroup__c;
            wrapper.productid = clitem.associatedProduct__r.Id;
            wrapper.deliveryTeam = clitem.associatedProduct__r.loadingGroup__r.DeliveryTeam__c;
            lstProductsToReturn.add(wrapper);
        }
        return lstProductsToReturn;
    }

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 8 Oct 2018
    // @param: cas - Case record, according to which delivery cases will be created. 
    // 			WrapperJson- List of productSelectorWrapperClass that are selected in the UI to create products.  
    // @description: SFDC1-9003: Once user selects the products and submits following steps occur:
    // 		1. Group products based on loading group. For each loading group clone cas and create a case.
    // 		2. Insert cases. If SSO is selected, then set Delivery technical as Delivery team, else set
    // 				from loading group. If value is not there in case picklist, then set default value
    // 		3. Get inserted case Ids and based on loading groups, create Case products and insert it.
    // @return: String - Success or error Message to be displayed in UI.
    // @company: VERTIBA
    //------------------------------
    @AuraEnabled
    public static String createDeliveryCases(Case cas, String wrapperJson) {
        List<productSelectorWrapperClass> products = 
            (List<productSelectorWrapperClass>)JSON.deserialize(wrapperJson, List<productSelectorWrapperClass>.class);
        Map<Id, List<productSelectorWrapperClass>> loadingMap = new Map<Id, List<productSelectorWrapperClass>>();
        for(productSelectorWrapperClass product : products) {
            List<productSelectorWrapperClass> lst = new List<productSelectorWrapperClass>();
            //Once case is inserted, this map will be used to insert case product junction record.
            if(loadingMap.containsKey(product.loadingGroupId)) {
                lst = loadingMap.get(product.loadingGroupId);
            }
            lst.add(product);
            loadingMap.put(product.loadingGroupId, lst);
        }
        if(loadingMap.isEmpty()) {
            //Ideally we should never be here.
            return 'Selected Products dont have loading groups. Didnt create cases';
        }
        Set<String> delTeams = DependentPicklistUtil.getDependentOptionsImpl(Case.DeliveryTeam__c, case.TeamSelect__c).get('Delivery');
        Savepoint sp = Database.setSavepoint();
        try {
            List<Case> casesToInsert = new List<Case>();
            //Group selected products based on their loading group id. and create case for each group
            for(Id loadingGroupId : loadingMap.keySet()) {
                Case c = cas.clone();
                c.LoadingGroupOnboarding__c = loadingGroupId;
                productSelectorWrapperClass wclass = loadingMap.get(loadingGroupId).get(0);
                if(cas.SingleSignOnSAM__c) {
                    c.DeliveryTeam__c = 'Delivery Technical';
                } else if (delTeams.contains(wclass.deliveryTeam)) {
                    c.DeliveryTeam__c = wclass.deliveryTeam;
                } else {
                    c.DeliveryTeam__c = 'Global Delivery Help Desk'; //Set default value
                }
                casesToInsert.add(c);
            }
            //Insert list of cases.
            insert casesToInsert;
            //After inserting case, insert case products.
            List<CaseProducts__c> caseProductList = new List<CaseProducts__c>();
            for(Case c: casesToInsert) {
                List<productSelectorWrapperClass> prodList = loadingMap.get(c.LoadingGroupOnboarding__c);
                for(productSelectorWrapperClass wrapper : prodList) {
                    CaseProducts__c cp = new CaseProducts__c(Case__c = c.id, Product__c = wrapper.productid);
                    caseProductList.add(cp);
                }
            }
            insert caseProductList;
            //reverting by pass validation, so that next time when it is edited, validation should trigger
            //Internally when case is inserted Account is set to IHS Markit account, If cas is updated directly,  
            //then account the earlier set IHS Markit is reset with account from Contract and validation error 
            //is thrown. To avoid that creating a new case variable and updating here.
            List<Case> casesToUpdate = new List<Case>();
            for(Case ca: casesToInsert) {
                casesToUpdate.add(new Case(id=ca.Id, ByPassValidation__c = false));
            }
            update casesToUpdate;
        } catch(Exception e) {
            Database.rollback(sp);
            System.debug('Error, method createDeliveryCases, class CreateOMDHCaseController ');
            ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='CreateOMDHCaseController ',ErrorDescription__c='Error: '+e.getMessage(),FunctionName__c='createDeliveryCases');
            insert apexLogRecord;
            if(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                return e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',':');  
            } else {
                return e.getMessage();
            }
        } 
        return 'Cases are Created!';
    }
}