objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CMRelationship__c.object
<CustomObject>
    <description>SFDC1-2455 CM Relationships is used to track the Live CM Brokers on the Account Additional fields object</description>
    <fields>
        <fullName>BrokerContract__c</fullName>
        <description>SFDC1-2455 CM Relationships&apos; Broker Contract</description>
        <label>Broker Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CM Clients</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CM Relationship</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CM #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <description>SFDC1-2060 Contract Status fields
SFDC1-7222: Adding picklist value &quot;Waiting on PO&quot;</description>
        <inlineHelpText>Please select from dropdown menu</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Signed By Customer</fullName>
                    <label>Signed by Customer</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validated PO Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-POD Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-BSI Pending</fullName>
                </value>
                <value>
                    <fullName>Validated by ConsOps</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Sent to Delivery</fullName>
                </value>
                <value>
                    <fullName>Sent to OM/Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered to Customer</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved &amp; Processed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Unscheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                    <isActive>false</isActive>
                    <label>Received</label>
                </value>
                <value>
                    <fullName>Sent To OM</fullName>
                    <isActive>false</isActive>
                    <label>Sent To OM</label>
                </value>
                <value>
                    <fullName>Sent for Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Sent for Delivery</label>
                </value>
                <value>
                    <fullName>Waiting on PO</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on PO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fastrack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5851 Checkbox on &quot;Order From&quot; contracts
SFDC1-10429:Update Fastrack to Fast Track</description>
        <inlineHelpText>Use Fast Track terms and conditions if under $100k</inlineHelpText>
        <label>Fast Track</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestContractAttachmentMethods.cls
//-----------------------------
// @author: Ankita Singh
// @date: 19 June 2018
// @param: NA
// @description: Test class for ContractAttachment trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestContractAttachmentMethods {
    
    //-----------------------------
    // @author: Ankita Singh
    // @date: 18 June 2018
    // @param: NA
    // @description: SFDC1-8559.Test method for ContactAttachment trigger methods updateFieldOnContract on insert and delete
    // @return: NA
    //-----------------------------
    /*
	@isTest
    private static void testupdateFieldOnContract() {
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id OFRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = OFRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        //Creating ContractAttachment
        Test.startTest();
        ContractAttachment__c ca = new ContractAttachment__c();
        ca.Name = 'Contract Attachment PO 1';
        ca.Contract__c = contract.id;
        ca.AttachmentType__c = 'Purchase Order';
        insert ca;
        // Assert output
        String c1 = [Select POAttached__c from contract where id=:contract.id][0].POAttached__c;
        system.assertEquals('Yes', c1);
        // deleting Contract Attachment 
        delete ca;
        // Assert Output
        String c2 = [Select POAttached__c from contract where id=:contract.id][0].POAttached__c;
        system.assertEquals('No', c2);
        Test.stopTest();
    }*/
    
    //-----------------------------
    // @author: Dev Aggarwal
    // @date: 08 November 2019
    // @param: NA
    // @description: SFDC1-2037.Test method for ContactAttachment trigger methods setRecordTypeFromContract on insert 
    // @return: NA
    //-----------------------------
	@isTest
    private static void testSetRecordTypeFromContract() {
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id OFRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = OFRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        //Creating ContractAttachment
        Test.startTest();
        ContractAttachment__c ca = new ContractAttachment__c();
        ca.Name = 'Contract Attachment PO 1';
        ca.Contract__c = contract.id;
        ca.AttachmentType__c = 'Purchase Order';
        insert ca;
        Test.stopTest();
        
        List<ContractAttachment__c> ListCA = [select name, recordType.name from contractAttachment__c where id = :ca.id];
        system.assertEquals('Order Form', ListCA[0].recordType.name, 'Record type should be Order Form');
    }
    //-----------------------------
    // @author: Dev Aggarwal
    // @date: 08 November 2019
    // @param: NA
    // @description: SFDC1-2037.Test method for ContactAttachment trigger methods updateContinuationContracts (Signed By Customer) on insert. 
    // @return: NA
    //-----------------------------
	@isTest
    private static void testupdateContinuationContractsForSigned() {
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id CLRecordTypeId = ContractMethods.continuationLetterRecordTypeId;
        //LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = CLRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        ContractAttachment__c ca = new ContractAttachment__c();
        ca.Name = 'Contract Attachment PO 1';
        ca.Contract__c = contract.id;
        ca.AttachmentType__c = 'Purchase Order';
        insert ca;
        //Creating ContractAttachment
        Test.startTest();
			ca.AttachmentType__c = 'Signed Continuation Letter';
        	update ca;
        Test.stopTest();
        
        List<ContractAttachment__c> ListCA = [select name, contract__r.ContractStatus__c from contractAttachment__c where id = :ca.id];
        system.assertEquals('Signed By Customer', ListCA[0].contract__r.contractStatus__c,'Contract status should be Signed By Customer');
    }
    //-----------------------------
    // @author: Dev Aggarwal
    // @date: 08 November 2019
    // @param: NA
    // @description: SFDC1-2037.Test method for ContactAttachment trigger methods updateContinuationContracts (Sent to Customer) on insert. 
    // @return: NA
    //-----------------------------
	@isTest
    private static void testupdateContinuationContractsForSent() {
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id CLRecordTypeId = ContractMethods.continuationLetterRecordTypeId;
        //LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = CLRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        
        ContractAttachment__c ca = new ContractAttachment__c();
        ca.Name = 'Contract Attachment PO 1';
        ca.Contract__c = contract.id;
        ca.AttachmentType__c = 'Purchase Order';
        insert ca;
        //Creating ContractAttachment
        Test.startTest();
			ca.AttachmentType__c = 'Continuation Letter';
        	update ca;
        Test.stopTest();
        
        List<ContractAttachment__c> ListCA = [select name, contract__r.ContractStatus__c from contractAttachment__c where id = :ca.id];
        system.assertEquals('Sent to Customer', ListCA[0].contract__r.contractStatus__c,'Contract status should be Sent to Customer');
    }
    //-----------------------------
    // @author: Sharique
    // @date: 12 Oct 2021
    // @param: NA
    // @description: SFDC-4568.Test method for ContactAttachment trigger methods deletionRestrictedWhenContractStage11 
    // @return: NA
    //-----------------------------
	@isTest
    private static void TestDeletionRestrictedWhenContractStage11() {
        
        Profile p = [SELECT Id ,name FROM Profile WHERE Name like '%Sales Coordinator%' limit 1];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id CLRecordTypeId = ContractMethods.continuationLetterRecordTypeId;
        //LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        
        Test.startTest();
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = CLRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        Test.stopTest();
         ContractAttachment__c ca = new ContractAttachment__c();
        System.runAs(u) {
         System.debug('$$$ userid--'+UserInfo.getUserId());
         System.debug('$$$ userName--'+UserInfo.getName()); 
       
        ca.Name = 'Contract Attachment PO 1';
        ca.Contract__c = contract.id;
        ca.AttachmentType__c = 'Purchase Order';
        insert ca;
             ContractAttachment__c caa= [select id,createdbyid,createdby.name from ContractAttachment__c limit 1];
             system.debug('$$$ ca---'+caa.createdby.name);
         
        try {
            delete ca;
           }
           catch (exception ex) {
                  Boolean errorexist = ex.getmessage().contains(System.Label.ContractAttachmentRestrictionError) ? true : false;
                  System.assertEquals(errorexist ,true, ex.getMessage());
              }
            
        }
        
     }
       //-----------------------------
    // @author: Sharique
    // @date: 12 Oct 2021
    // @param: NA
    // @description: SFDC-4568.Test method for ContactAttachment trigger methods updateRestrictionOnContractStage11 
    // @return: NA
    //-----------------------------
	@isTest
    private static void TestupdateRestrictionOnContractStage11() {
        
        Profile p = [SELECT Id ,name FROM Profile WHERE Name like '%Sales Coordinator%' limit 1];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        //Creating Contract
        Id CLRecordTypeId = ContractMethods.continuationLetterRecordTypeId;
        //LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        
        Test.startTest();
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        contract.recordtypeid = CLRecordTypeId;
        contract.POAttached__c = 'No';
        contract.Fastrack__c = true;
        insert contract;
        Test.stopTest();
         ContractAttachment__c ca = new ContractAttachment__c();
        System.runAs(u) {
            ca.Name = 'Contract Attachment PO 1';
            ca.Contract__c = contract.id;
            ca.AttachmentType__c = 'Purchase Order';
            insert ca;
         
            try {
                delete ca;
            }
            catch (exception ex) {
                Boolean errorexist = ex.getmessage().contains(System.Label.ContractAttachmentRestrictionError) ? true : false;
                System.assertEquals(errorexist ,true, ex.getMessage());
            }
            
        }
        
     }
}