objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-383 This field serves as a lookup to the Country object</description>
        <inlineHelpText>Read-only field, updated indirectly by a change of Company&apos;s Billing Country/Territory</inlineHelpText>
        <label>Account Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ClientLegalEntityCountryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7542 This lookup refers to country mentioned in Client Legal Entity: Country (text)</description>
        <inlineHelpText>Client Legal Entity: Country/Territory</inlineHelpText>
        <label>Client Legal Entity: Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientLegalEntityLookUp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-905 Client Legal Entity</description>
        <inlineHelpText>Client&apos;s Legal Entity</inlineHelpText>
        <label>Client Legal Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ClientLegalEntity</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country/Territory Code</inlineHelpText>
        <label>Country/Territory Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBatchUpdateContractClientLECountry.cls
/**
* @author Tran-Vu Tran
* @date 22nd April 2019
* @description SFDC-1381 test class for BatchUpdateAccountCountry
* @return void
* @companyname IHS Markit
*/
@isTest
private class TestBatchUpdateContractClientLECountry {
    @isTest
    private static void TestBatchUpdateContractClientLECountryClass() {
        
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);

        // creating test account
        Account testAccount = TestUtility.createTestAccountWithAddress('Test Account', '1234 Testing Street', 'Test City', '', country.CountryCode__c, true);

        Test.startTest();
        
        Account assertAccount = [Select Id, AccountCountry__c from Account where Id =: testAccount.Id];
        System.assertNotEquals(null, assertAccount.AccountCountry__c, 'Verifying AccountCountry__c lookup value is populated by trigger');
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        Contact testContact = TestUtility.createContact(testAccount.Id, 'test@ihsmarkit.com', true, 'Test', 'Contact');
                                                                                     
        // creating test opportunity                                                                                     
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = true;
        ocr.Role = 'Decision Maker';
        insert ocr;
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity', 'USD', true, 
                                                                                     'No', 'No', 'Yes', 'No', 'No', 'No', 'No');
        // creating test opportunity
        Contract testContract = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        testContract.ClientLegalEntityLookUp__c = testAccount.Id;
        update testContract;
        
        Contract assertContract = [Select Id, ClientLegalEntityCountryLookup__c from Contract where Id =: testContract.Id];
        System.assertNotEquals(null, assertContract.ClientLegalEntityCountryLookup__c, 'Verifying ClientLegalEntityCountry__c lookup value is populated by trigger');
        
        testContract.ClientLegalEntityCountryLookup__c = null;  // set ClientLegalEntityCountryLookup__c = null to simulate when trigger is turned off
        update testContract;
            
        BatchUpdateContractClientLECountry batchJob = new BatchUpdateContractClientLECountry();
        Id batchId = Database.executeBatch(batchJob, 1);
        
        Test.stopTest();
        
        assertContract = [Select Id, ClientLegalEntityCountryLookup__c from Contract where Id =: testContract.Id];
        System.assertNotEquals(null, assertContract.ClientLegalEntityCountryLookup__c,
                               'Verifying ClientLegalEntityCountry__c lookup value is populated by BatchUpdateContractClientLECountry');
    }

}