objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCCES__c</fullName>
        <inlineHelpText>This roll-up field calculates the average Customer Effort Score (CES) across ALL Transactional Survey Responses for any Contact(s) who submitted a Survey Response under this Account, on a scale of 1 (Extremely difficult) - 7 (Extremely easy).</inlineHelpText>
        <label>CC – CES</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCCSAT__c</fullName>
        <inlineHelpText>This roll-up field calculates the average Customer Satisfaction (CSAT) Score across ALL Transactional Survey Responses for any Contact(s) who submitted a Survey Response under this Account, on a scale of 1 (Extremely unsatisfied) - 7 (Extremely satisfied).</inlineHelpText>
        <label>CC – CSAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CorporateNPS__c</fullName>
        <inlineHelpText>This roll-up field calculates the average Net Promoter Score (NPS) across ALL Corporate Survey Responses for any Contact(s) who submitted a Survey Response under this Account, on a scale of 0 (Not at all likely) - 10 (Extremely likely).</inlineHelpText>
        <label>Corporate – NPS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingNPS__c</fullName>
        <description>SFDC-5347: This field calculates the average Net Promoter Score (NPS) across all the Training Survey Responses under this Account.</description>
        <label>Training – NPS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingTrainingMetNeeds__c</fullName>
        <inlineHelpText>This roll-up field calculates the average score of whether the training expectations were met across ALL Training Survey Responses for any Contact(s) who submitted a Survey Response under this Account, on a scale of 1 (Strongly disagree) - 7 (Strongly agree).</inlineHelpText>
        <label>Training – Training Met Needs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TransactionalNPS__c</fullName>
        <description>SFDC-5347: This field calculates the average Net Promoter Score (NPS) across all the transactional Survey Responses under this Account.</description>
        <label>Transactional – NPS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>SurveyResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4998 Customer Experience project</description>
        <label>Survey Response</label>
        <referenceTo>SurveyResponse__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CustomerCare</fullName>
        <active>true</active>
        <businessProcess>Customer Care</businessProcess>
        <description>Used to track standard customer care support requests.</description>
        <label>Customer Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SurveyResponse__c.object
<CustomObject>
    <description>SFDC1-254: Customer Care - Survey Response Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-6010: account id of responded</description>
        <inlineHelpText>Account Name of the Customer who submitted the Survey Response.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AlertStatus__c</fullName>
        <description>SFDC1-6010: If alert type is not null then status is required. Should be populated as new on create when alert type is not null</description>
        <inlineHelpText>Current status of the Survey Response.</inlineHelpText>
        <label>Alert Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AlertType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved with Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - No Action Required</fullName>
                </value>
                <value>
                    <fullName>Closed - Unable to Reach Customer</fullName>
                </value>
                <value>
                    <fullName>Inprogress</fullName>
                    <isActive>false</isActive>
                    <label>Inprogress</label>
                </value>
                <value>
                    <fullName>Null</fullName>
                    <isActive>false</isActive>
                    <label>Null</label>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                    <isActive>false</isActive>
                    <label>Resolved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AlertType__c</fullName>
        <description>SFDC1-6010: Hot Alert, Commendation, can be null. The survey team can decide what triggers this and we can build workflows on this value. A workflow will trigger an email based on this value. For Phase 1 we are only expecting this value to be sent as hot alert or null</description>
        <inlineHelpText>The type of Alert that has been generated based on the Survey Response: Commendation, Neutral or Hot Alert.</inlineHelpText>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot Alert</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Commendation</fullName>
                </value>
                <value>
                    <fullName>Null</fullName>
                    <isActive>false</isActive>
                    <label>Null</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CESScore__c</fullName>
        <description>SFDC1-6010: Carlos&apos; team to calculate and present as a whole number</description>
        <inlineHelpText>Customer Effort Score (CES) defining the level of effort required by the customer to request support, on a scale of 1 (Extremely difficult) - 7 (Extremely easy).</inlineHelpText>
        <label>CES Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSATScore__c</fullName>
        <formula>(TESScore__c +  CESScore__c  +  RSSScore__c) / 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Customer Satisfaction Score (CSAT) defines overall satisfaction, calculated as a simple average of CES, RSS &amp; TES, on a scale of 1 (Extremely unsatisfied) - 7 (Extremely satisfied). Note: Hot Alert triggers are not enabled on this formula field.</inlineHelpText>
        <label>CSAT Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseOwnerId__c</fullName>
        <formula>Case__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CaseOwnerId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-254: contactid of responded</description>
        <inlineHelpText>Customer Contact who submitted the Survey Response.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExperienceQuestion__c</fullName>
        <inlineHelpText>Overall customer Experience score based on interacting and doing business with IHS Markit, on a scale of 1 (Extremely negative) - 7 (Extremely positive).</inlineHelpText>
        <label>Experience Question</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FSAOwnerId__c</fullName>
        <description>SFDC-4091: Backend field for FSA Owner Id</description>
        <formula>CASESAFEID(Training__r.OwnerId)</formula>
        <label>FSA Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LikelihoodToRenew__c</fullName>
        <inlineHelpText>Customer&apos;s likelihood to renew their contract with IHS Markit on a scale of  1 (Extremely unlikely) - 7 (Extremely likely).</inlineHelpText>
        <label>Likelihood To Renew</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPSScore__c</fullName>
        <description>Calculated Net Promoter Score. This score is provided by the survey team on a scale from 0-10.</description>
        <inlineHelpText>Net Promoter Score (NPS) measures the likelihood of the customer to recommend IHS Markit to a colleague or industry contact, on a scale of 0 (Not at all likely) - 10 (Extremely likely).</inlineHelpText>
        <label>NPS Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductsServicesMeetNeed__c</fullName>
        <inlineHelpText>A measure of the customer&apos;s overall needs met by IHS Markit&apos;s product(s) and/or service(s), on a scale of 1 (Strongly disagree) - 7 (Strongly agree).</inlineHelpText>
        <label>Products/Services Meet Need</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSSScore__c</fullName>
        <description>Calculated Rep Satisfaction Score. This score is provided by the survey team on a scale from 1-7.</description>
        <inlineHelpText>Rep Satisfaction Score (RSS) measures the customer&apos;s satisfaction level, based on the service provided by the Case owner, on a scale of 1 (Extremely dissatisfied) - 7 (Extremely satisfied).</inlineHelpText>
        <label>RSS Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecipientEmail__c</fullName>
        <inlineHelpText>The customer&apos;s email address to which the Corporate Survey was sent.</inlineHelpText>
        <label>Recipient Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>RecipientFirstName__c</fullName>
        <description>SFDC-4091: First Name of the responded</description>
        <inlineHelpText>The customer&apos;s first name as on the corporate survey mailing list.</inlineHelpText>
        <label>Recipient First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecipientLastName__c</fullName>
        <description>SFDC-4091: Last name of the responded</description>
        <inlineHelpText>The customer&apos;s last name as on the corporate survey mailing list.</inlineHelpText>
        <label>Recipient Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <inlineHelpText>Version of the survey questions that the customer responded to, when the feedback was received.</inlineHelpText>
        <label>Survey Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TESScore__c</fullName>
        <description>Calculated Time Expectation Score. This score is provided by the survey team on a scale from 1-7.</description>
        <inlineHelpText>Time Expectation Score (TES) measures the customer&apos;s satisfaction level, based on the time taken to respond to the Case, on a scale of 1 (Extremely dissatisfied) - 7 (Extremely satisfied).</inlineHelpText>
        <label>TES Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingMetNeeds__c</fullName>
        <inlineHelpText>Measure of whether the customer&apos;s training expectations were met, on a scale of 1 (Strongly disagree) - 7 (Strongly agree).</inlineHelpText>
        <label>Training Met Needs</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <label>Corporate</label>
    </recordTypes>
    <recordTypes>
        <fullName>CustomerCare</fullName>
        <active>true</active>
        <label>Transactional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SurveyResponseMethods.cls
//-----------------------------
// @author: Manish Kumar
// @date: 29 July 2021
// @param: NA
// @description: SFDC-4232  Class to hold trigger methods 
// @return: NA
//-----------------------------
public class SurveyResponseMethods {
    // Static reference to "Corporate" Survey Response Record Type Id
    public static Id corporateRecordTypeId {
        get {
            if (corporateRecordTypeId == null) {
                corporateRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
            }
            return corporateRecordTypeId;
        }
        
        set;
    }
    // Static reference to "Transactional" Survey Response Record Type Id
    public static Id TransactionalRecordTypeId {
        get {
            if (TransactionalRecordTypeId == null) {
                TransactionalRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('CustomerCare').getRecordTypeId();
            }
            return TransactionalRecordTypeId;
        }
        
        set;
    }
    // Static reference to "Training" Survey Response Record Type Id
    public static Id TrainingRecordTypeId {
        get {
            if (TrainingRecordTypeId == null) {
                TrainingRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Training').getRecordTypeId();
            }
            return TrainingRecordTypeId;
        }
        
        set;
    }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 29 July 2021
    // @param: TriggerParameters tp
    // @description: SFDC-4232 SurveyResponse__c BEFORE INSERT - called from SurveyResponseTrigger
    //               if the Recipient Email field has been populated on the SurveyResponse__c then populate the Account 
    //               and Contact Lookup fields on Survey Response record.
    // @return: None
    //------------------------------
    
        public static void populateExistingAccountAndContactLookup(TriggerParameters tp) {
            List<string> emailOfRecipients = New List<string>();
            Id srCorpRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
            for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist){
                if(sr.RecordTypeId == srCorpRecordTypeId && sr.RecipientEmail__c != Null && (sr.Account__c == Null || sr.Contact__c == Null)){
                    string recipientEmail = string.valueOf(sr.RecipientEmail__c);
                    emailOfRecipients.add(recipientEmail);
                }
            }
            if(!emailofRecipients.isEmpty()){
                List<Contact> listOfContacts = [Select id, AccountId, Email from Contact where email in :emailOfRecipients];
                if(!listOfContacts.isEmpty()){
                    for(Contact contactObj : listOfContacts){
                        for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist){
                            if(sr.RecipientEmail__c == contactObj.Email){
                                sr.Contact__c = contactObj.id;
                                sr.Account__c = contactObj.AccountId;
                            }
                        }     
                    }
                }
            }        
        }
    
    //-----------------------------
    // @author: Manish Kumar
    // @date: 29 July 2021
    // @param: TriggerParameters tp
    // @description: SFDC-4232 SurveyResponse__c AFTER INSERT - called from SurveyResponseTrigger
    //               if the Contact record not present for Recipient Email then create a new contact record and populate 
    //               the Account and Contact Lookup fields on Survey Response record.
    // @LastModifiedby: Neelam Agrawal	
    // @ModifiedDate: 08 Oct 2021
    // @description: SFDC-4888 Moved logic from afterinsert to beforeinsert trigger and updated logic
    // @return: None
    //------------------------------
        public static void populateNewAccountAndContactLookup(TriggerParameters tp) {
            List<Contact> contactsToInsert = New List<Contact>();
            List<string> emailOfRecipients = New list<String>();
            Map<String,Id> mapContactEmailandId = new Map<String,Id>();
            List<SurveyResponse__c> surveyResponseToUpdate = New list<SurveyResponse__c>();
            Id srCorpRecordTypeId = SurveyResponseMethods.corporateRecordTypeId;
            for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist){
                if(sr.RecordTypeId == srCorpRecordTypeId && sr.RecipientEmail__c != Null && (sr.Account__c == Null || sr.Contact__c == Null)){
                    string recipientEmail = string.valueOf(sr.RecipientEmail__c);
                    emailOfRecipients.add(recipientEmail);
                }
            }
            List<Contact> listOfContacts = [Select id, AccountId, Email from Contact where email in :emailOfRecipients];
            for(Contact con:listOfContacts){
                mapContactEmailandId.put(con.Email,con.Id);
            }
            for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist){
                if(sr.RecordTypeId == srCorpRecordTypeId && sr.RecipientEmail__c != Null && (sr.Account__c == Null || sr.Contact__c == Null) && !mapContactEmailandId.containskey(sr.RecipientEmail__c)){
                    contact contactObj = New Contact();
                    contactObj.AccountId = System.Label.AccountIdForContact;
                    contactObj.Email = sr.RecipientEmail__c;
                    contactObj.FirstName = sr.RecipientFirstName__c;
                    contactObj.LastName = sr.RecipientLastName__c;
                    contactsToInsert.add(contactObj);
                }
            }
            //Insert new Contact record based on Recipient Email if not present
            if(!contactsToInsert.isEmpty()){
                insert contactsToInsert;
            }
        }

    //-----------------------------
    // @author: Vaishali Jain
    // @date: 04 Aug 2021
    // @param: TriggerParameters tp
    // @description: SFDC#4339: IHSM CEP - New Rollup summary fields required for reporting on Contact and Account
    // @return: None
    // @Modified By: Neelam Agrawal
    // @Modified Date: 25 Oct 2021
    // @Modifief description: Fixing bug SFDC-4821 Update Rollup summary field on Account/Contact Change
    // @Modified By: Neelam Agrawal
    // @Modified Date: 09 Nov 2021
    // @Modifief description: SFDC-4884 IHSM CEP - Amendments to Rollups calculations
    //------------------------------
   
    public static void updateRollupFields(TriggerParameters tp) {

        List<Account> updateAccountList = new List<Account>();
        List<Contact> updateContactList = new List<Contact>();
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> contactIdSet= new Set<Id>();

            if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert || tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                for(SurveyResponse__c sr:(List<SurveyResponse__c>) tp.newList) {  
                    System.debug('checkvalue' + sr.Account__c +sr.Contact__C);
                    if(!String.isBlank(sr.Account__c)) 
                       {
                          accountIdSet.add(sr.Account__c);
                       } 
                       if(!String.isBlank(sr.Contact__C)){                        
                           contactIdSet.add(sr.Contact__C);
                       }
                    }
                }
             
            if(tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate){
                for(SurveyResponse__c sr:(List<SurveyResponse__c>) tp.oldList) {                
                    if(!String.isBlank(sr.Account__c)) 
                       {
                          accountIdSet.add(sr.Account__c);
                       } 
                       if(!String.isBlank(sr.Contact__C)){                        
                           contactIdSet.add(sr.Contact__C);
                       }
                    }
            }

            if(accountIdSet != Null && accountIdSet.size()>0) {
                updateAccountList=SurveyResponseMethods.updateAccountRollupFields(accountIdSet);
            }
           
            try {
                if(updateAccountList != Null && updateAccountList.size() > 0){
                    update updateAccountList;
                }
            }
            catch (DMLException ex) {
                ApexLogger.logError(new LogMessage('SurveyResponseMethods','updateRollupFields',ex,tp.newList.get(0),null));
            }

            if(contactIdSet != Null && contactIdSet.size()>0) {
                updateContactList=SurveyResponseMethods.updateContactRollupFields(contactIdSet);
            }
            try {
                if(updateContactList != Null && updateContactList.size() > 0){
                    update updateContactList;
                }
            }
            catch (DMLException ex) {
                ApexLogger.logError(new LogMessage('SurveyResponseMethods','updateRollupFields',ex,tp.newList.get(0),null));
            }
            
        }

    
    //-----------------------------
    // @author: Vaishali Jain
    // @date: 09 Aug 2021
    // @param: TriggerParameters tp
    // @description: AlertType based on score calculation
    // @return: None
    //------------------------------
    
        public static void scoreAlertType(TriggerParameters tp) {
            Id srCorpRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
            Id srTransRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('CustomerCare').getRecordTypeId();
            Id srTrainingRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Training').getRecordTypeId();  
        
            for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist) {
                if(sr.RecordTypeId == srCorpRecordTypeId) {
                    if((sr.NPSScore__c >=0 && sr.NPSScore__c <=4) || (sr.LikelihoodToRenew__c >=1 && sr.LikelihoodToRenew__c <=3)|| (sr.ExperienceQuestion__c>=1 && sr.ExperienceQuestion__c <=3)|| (sr.ProductsServicesMeetNeed__c >=1 && sr.ProductsServicesMeetNeed__c <=3)) {
                        sr.AlertType__c = 'Hot Alert';
                        sr.AlertStatus__c = 'New';
                        break;
                    }
                    if((sr.NPSScore__c >=5 && sr.NPSScore__c <=8) || (sr.LikelihoodToRenew__c >=4 && sr.LikelihoodToRenew__c <=5)|| (sr.ExperienceQuestion__c >=4 && sr.ExperienceQuestion__c <=5)|| (sr.ProductsServicesMeetNeed__c >=4 && sr.ProductsServicesMeetNeed__c <=5)) {
                        sr.AlertType__c = 'Neutral';
                        sr.AlertStatus__c = 'New';
                        break;
                    }
                    if((sr.NPSScore__c >=9 && sr.NPSScore__c <=10)|| (sr.LikelihoodToRenew__c >=6 && sr.LikelihoodToRenew__c <=7)|| (sr.ExperienceQuestion__c >=6 && sr.ExperienceQuestion__c<=7)|| (sr.ProductsServicesMeetNeed__c >=6 && sr.ProductsServicesMeetNeed__c <=7)) {
                        sr.AlertType__c = 'Commendation';
                        sr.AlertStatus__c = 'New';
                        break;
                    }
                }
                else if(sr.RecordTypeId == srTransRecordTypeId) {
                    if((sr.NPSScore__c >=0 && sr.NPSScore__c <=4) || (sr.CESScore__c >=1 && sr.CESScore__c <=3) || (sr.RSSScore__c >=1 && sr.RSSScore__c <=3) || (sr.TESScore__c >=1 && sr.TESScore__c <=3) || (sr.LikelihoodToRenew__c >=1 && sr.LikelihoodToRenew__c <=3)) {
                        sr.AlertType__c = 'Hot Alert';
                        sr.AlertStatus__c = 'New';
                        break;
                    }
                    if((sr.NPSScore__c >=5 && sr.NPSScore__c <=8) || (sr.CESScore__c >=4 && sr.CESScore__c <=5) || (sr.RSSScore__c >=4 && sr.RSSScore__c <=5) || (sr.TESScore__c >=4 && sr.TESScore__c <=5) || (sr.LikelihoodToRenew__c >=4 && sr.LikelihoodToRenew__c <=5)) {
                        sr.AlertType__c = 'Neutral';
                        break;
                    }
                    if((sr.NPSScore__c >=9 && sr.NPSScore__c <=10) || (sr.CESScore__c >=6 && sr.CESScore__c <=7) || (sr.RSSScore__c >=6 && sr.RSSScore__c <=7) || (sr.TESScore__c >=6 && sr.TESScore__c <=7) || (sr.LikelihoodToRenew__c >=6 && sr.LikelihoodToRenew__c <=7)) {
                        sr.AlertType__c = 'Commendation';
                        break;
                    }
                }
                else if(sr.RecordTypeId == srTrainingRecordTypeId) {
                    if((sr.NPSScore__c >=0 && sr.NPSScore__c <=4) || (sr.TrainingMetNeeds__c >=1 && sr.TrainingMetNeeds__c <=3)) {
                        sr.AlertType__c = 'Hot Alert';
                        sr.AlertStatus__c = 'New';
                        break;
                    }
                    if((sr.NPSScore__c >=5 && sr.NPSScore__c <=8) || (sr.TrainingMetNeeds__c >=4 && sr.TrainingMetNeeds__c <=5)) {
                        sr.AlertType__c = 'Neutral';
                        break;
                    }
                    if((sr.NPSScore__c >=9 && sr.NPSScore__c <=10)|| (sr.TrainingMetNeeds__c >=6 && sr.TrainingMetNeeds__c <=7)) {
                        sr.AlertType__c = 'Commendation';
                        break;
                    }
                }
            }
        }
    
    //------------------------------
    // @author: Vaishali Jain
    // @date: 18th Aug 2021
    // @param: TriggerParameters tp
    // @description: SFDC-4232 SurveyResponse__c Before Insert - called from SurveyResponseTrigger
    //               Update the Owner of Survey Response
    // @return: None
	// @Modified By: Neelam Agrawal
    // @Modified Date: 25 Oct 2021
    // @Modified description: Fixing bug SFDC-5074 Update owner when case/fsa owner is not user
    //------------------------------
        public static void updateSurveyResponseOwner(TriggerParameters tp) { 
            Id srTransRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('CustomerCare').getRecordTypeId();
            Id srTrainingRecordTypeId = Schema.Sobjecttype.SurveyResponse__c.getRecordTypeInfosByDeveloperName().get('Training').getRecordTypeId();
            for(SurveyResponse__c sr : (List<SurveyResponse__c>)tp.newlist) {
                if(sr.RecordTypeId == srTransRecordTypeId && (sr.AlertType__c == 'Neutral' || sr.AlertType__c == 'Commendation')) {
                    if(string.valueOf(sr.CaseOwnerId__c).startsWith('005')) {
                    	sr.OwnerId = sr.CaseOwnerId__c;   
                    }
                    else if(string.valueOf(sr.CaseOwnerId__c).startsWith('00G')) {
                        sr.OwnerId = System.label.CustomerExperienceTeam;
                    }
                }
                if(sr.RecordTypeId == srTrainingRecordTypeId && (sr.AlertType__c == 'Neutral' || sr.AlertType__c == 'Commendation')) {
                    if(string.valueOf(sr.FSAOwnerId__c).startsWith('005')) {
                    	sr.OwnerId = sr.FSAOwnerId__c;   
                    }
                    else if(string.valueOf(sr.FSAOwnerId__c).startsWith('00G')) {
                        sr.OwnerId = System.label.CustomerExperienceTeam;
                    }
                }
            }
        }

    //-----------------------------
    // @author: Neelam Agrawal
    // @date: 20 Oct 2021
    // @param: Contact Id
    // @description: SFDC#4821: IHSM CEP - Calulates rollup field for Contacts
    // @return: List<Contact>
    //------------------------------
        public static List<Contact> updateContactRollupFields(Set<Id> contactIdSet){
            Map<Id,List<SurveyResponse__c>> conSurveyMap = New Map <Id,List<SurveyResponse__c>>();
            List<Contact> updatedContactList = new List<Contact>();
            Set<Id> contactIdWithoutSR= contactIdSet;
            Id srCorpRecordTypeId = SurveyResponseMethods.corporateRecordTypeId;
            Id srTransRecordTypeId = SurveyResponseMethods.TransactionalRecordTypeId;
            Id srTrainingRecordTypeId = SurveyResponseMethods.TrainingRecordTypeId;
            List<SurveyResponse__c> surveyList = [SELECT Id,Contact__c,RecordTypeId, CESScore__c,CSATScore__c,TrainingMetNeeds__c,NPSScore__c, SurveyVersion__c FROM SurveyResponse__c WHERE Contact__c IN: contactIdSet];
            for(SurveyResponse__c sr : surveyList) {
                If (!conSurveyMap.keyset().contains(sr.Contact__c) && sr.Contact__c != Null) {
                    conSurveyMap.put(sr.Contact__c, New List<SurveyResponse__c>());
                }
                conSurveyMap.get(sr.Contact__c).add(sr);
            }
            contactIdWithoutSR.removeAll(conSurveyMap.keySet());
            for(Id contactId: conSurveyMap.keySet()) {
                Contact con=new Contact();
                con.Id=contactId;
                Double averageCES = 0;    
                Double averageCSAT = 0;  
                Double averageTrainingMetNeeds = 0; 
                Double averageNPS = 0;
                //SFDC-5347 Change Start
            	Double corporateDetractors = 0;
            	Double corporatePromoters = 0;
	    		Double transactionalDetractors = 0;
            	Double transactionalPromoters = 0;
	    		Double trainingDetractors = 0;
            	Double trainingPromoters = 0;
            	//SFDC-5347 Change End
                Double NumberOfRespondents = 0;
                Integer totalCESTransactionalSurveyRecords = 0;
                Integer totalCSATransactionalSurveyRecords = 0;
                Integer totalTrainingSurveyRecords = 0;
                Integer totalCorporateSurveyRecords = 0;
                //SFDC-5347 Change Start
            	Integer totalNPSTrainingSurveyRecords = 0;
            	Integer totalNPSTransactionalSurveyRecords = 0;
            	//SFDC-5347 Change End
                //Integer totalSurveyRecords = conSurveyMap.get(con.Id).size();
                If (conSurveyMap.get(con.Id) != null) {
                    for(SurveyResponse__c sr: conSurveyMap.get(con.Id)) {
                        if(sr.RecordTypeId == srTransRecordTypeId){
                            totalCESTransactionalSurveyRecords += 1;
                            if(sr.CESScore__c != null) {
                                averageCES = averageCES + sr.CESScore__c;
                            }
                            //SFDC-5347 Change Start
							if(sr.NPSScore__c != null && sr.SurveyVersion__c != null){
                            	if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                	transactionalDetractors += 1;
                                	totalNPSTransactionalSurveyRecords += 1;
                            	}
                            	if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                	transactionalPromoters += 1;
                                	totalNPSTransactionalSurveyRecords += 1;
                            	}
                        	}
                        	//SFDC-5347 Change End
                        }
                        if(sr.CSATScore__c != null && sr.RecordTypeId == srTransRecordTypeId){
                            averageCSAT = averageCSAT + sr.CSATScore__c;
                            totalCSATransactionalSurveyRecords += 1;
                        }
                        if(sr.RecordTypeId == srTrainingRecordTypeId){
                            totalTrainingSurveyRecords += 1;
                            if(sr.TrainingMetNeeds__c != null){
                                averageTrainingMetNeeds = averageTrainingMetNeeds + sr.TrainingMetNeeds__c;
                            }
                            //SFDC-5347 Change Start
							if(sr.NPSScore__c != null && sr.SurveyVersion__c != null){
                            	if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                	trainingDetractors += 1;
                                	totalNPSTrainingSurveyRecords += 1;
                            	}
                            	if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                	trainingPromoters += 1;
                                	totalNPSTrainingSurveyRecords += 1;
                            	}
                        	}
                        	//SFDC-5347 Change End
                        }
                        if(sr.RecordTypeId == srCorpRecordTypeId){
                            if(sr.NPSScore__c != null){
                                if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                    corporateDetractors += 1;
                                    totalCorporateSurveyRecords += 1;
                                }
                                if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                    corporatePromoters += 1;
                                    totalCorporateSurveyRecords += 1;
                                }
                            }
                            //totalCorporateSurveyRecords += 1;
                        }
                    }    
                }
                con.CCCES__c = totalCESTransactionalSurveyRecords==0?0:(averageCES/totalCESTransactionalSurveyRecords); 
                if(con.CCCES__c == 0){
                    con.CCCES__c = null;
                }
                con.CCCSAT__c = totalCSATransactionalSurveyRecords==0?0:(averageCSAT/totalCSATransactionalSurveyRecords); 
                if(con.CCCSAT__c == 0){
                    con.CCCSAT__c = null;
                }
                con.TrainingTrainingMetNeeds__c = totalTrainingSurveyRecords==0?0:(averageTrainingMetNeeds/totalTrainingSurveyRecords); 
                if(con.TrainingTrainingMetNeeds__c == 0){
                    con.TrainingTrainingMetNeeds__c = null;
                }
                if(totalCorporateSurveyRecords != 0){
                    con.CorporateNPS__c = totalCorporateSurveyRecords==0?0:((corporatePromoters - corporateDetractors)/totalCorporateSurveyRecords*100);
                }
                else{
                    con.CorporateNPS__c = null;
                }
                //SFDC-5347 Change Start
	    		if(totalNPSTransactionalSurveyRecords != 0){
                	con.TransactionalNPS__c = totalNPSTransactionalSurveyRecords==0?0:((TransactionalPromoters - TransactionalDetractors)/totalNPSTransactionalSurveyRecords*100);
            	}
            	else{
                	con.TransactionalNPS__c = null;
            	}
	    		if(totalNPSTrainingSurveyRecords != 0){
                	con.TrainingNPS__c = totalNPSTrainingSurveyRecords==0?0:((TrainingPromoters - TrainingDetractors)/totalNPSTrainingSurveyRecords*100);
            	}
            	else{
                	con.TrainingNPS__c = null;
            	}
            	//SFDC-5347 Change End
                updatedContactList.add(con);
            }
            if(!contactIdWithoutSR.isEmpty()){
                for(Id contactId:contactIdWithoutSR){
                    Contact con=new Contact();
                    con.Id=contactId;
                    con.CCCES__c = null;
                    con.CCCSAT__c = null;
                    con.TrainingTrainingMetNeeds__c = null;
                    con.CorporateNPS__c = null;
                    //SFDC-5347 Change Start
					con.TransactionalNPS__c = null;
					con.TrainingNPS__c = null;
                	//SFDC-5347 Change End
                    updatedContactList.add(con);
                }
            }
            return updatedContactList;
            
        }
    
    //-----------------------------
    // @author: Neelam Agrawal
    // @date: 20 Oct 2021
    // @param: Account Id
    // @description: SFDC#4821: IHSM CEP - Calulates rollup field for Accounts
    // @return: List<Account>
    //------------------------------
    	
    public static List<Account> updateAccountRollupFields(Set<Id> accountIdSet){
        Map<Id,List<SurveyResponse__c>> conSurveyMap = New Map <Id,List<SurveyResponse__c>>();
        List<Account> updatedAccountList = new List<Account>();
        Set<Id> accountIdWithoutSR= accountIdSet;
        Id srCorpRecordTypeId = SurveyResponseMethods.corporateRecordTypeId;
        Id srTransRecordTypeId = SurveyResponseMethods.TransactionalRecordTypeId;
        Id srTrainingRecordTypeId = SurveyResponseMethods.TrainingRecordTypeId;
        List<SurveyResponse__c> surveyList = [SELECT Id,Account__c,RecordTypeId, CESScore__c,CSATScore__c,TrainingMetNeeds__c,NPSScore__c FROM SurveyResponse__c WHERE Account__c IN: accountIdSet];
        for(SurveyResponse__c sr : surveyList) {
            If (!conSurveyMap.keyset().contains(sr.Account__c) && sr.Account__c != Null) {
                conSurveyMap.put(sr.Account__c, New List<SurveyResponse__c>());
            }
            conSurveyMap.get(sr.Account__c).add(sr);
        }
        accountIdWithoutSR.removeAll(conSurveyMap.keySet());
        for(Id accountId: conSurveyMap.keySet()) {
            Account acc= new Account();
            acc.Id=accountId;
            Double averageCES = 0;    
            Double averageCSAT = 0;  
            Double averageTrainingMetNeeds = 0; 
            Double averageNPS = 0;
            //SFDC-5347 Change Start
            Double corporateDetractors = 0;
            Double corporatePromoters = 0;
	    	Double transactionalDetractors = 0;
            Double transactionalPromoters = 0;
	    	Double trainingDetractors = 0;
            Double trainingPromoters = 0;
            //SFDC-5347 Change End
            Double NumberOfRespondents = 0;
            Integer totalCESTransactionalSurveyRecords = 0;
            Integer totalCSATransactionalSurveyRecords = 0;
            Integer totalTrainingSurveyRecords = 0;
            Integer totalCorporateSurveyRecords = 0;
            //SFDC-5347 Change Start
            Integer totalNPSTrainingSurveyRecords = 0;
            Integer totalNPSTransactionalSurveyRecords = 0;
            //SFDC-5347 Change End
            //Integer totalSurveyRecords = conSurveyMap.get(acc.Id).size();
            If (conSurveyMap.get(acc.Id) != null) {
                for(SurveyResponse__c sr: conSurveyMap.get(acc.Id)) {
                    if(sr.RecordTypeId == srTransRecordTypeId){
                        totalCESTransactionalSurveyRecords += 1;
                        if(sr.CESScore__c != null) {
                            averageCES = averageCES + sr.CESScore__c;
                        }
                        //SFDC-5347 Change Start
						if(sr.NPSScore__c != null){
                            if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                transactionalDetractors += 1;
                                totalNPSTransactionalSurveyRecords += 1;
                            }
                            if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                transactionalPromoters += 1;
                                totalNPSTransactionalSurveyRecords += 1;
                            }
                        }
                        //SFDC-5347 Change End
                    }
                    if(sr.CSATScore__c != null && sr.RecordTypeId == srTransRecordTypeId){
                        averageCSAT = averageCSAT + sr.CSATScore__c;
                        totalCSATransactionalSurveyRecords += 1;
                    }
                    if(sr.RecordTypeId == srTrainingRecordTypeId){
                        totalTrainingSurveyRecords += 1;
                        if(sr.TrainingMetNeeds__c != null){
                            averageTrainingMetNeeds = averageTrainingMetNeeds + sr.TrainingMetNeeds__c;
                        }
                        //SFDC-5347 Change Start
						if(sr.NPSScore__c != null){
                            if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                trainingDetractors += 1;
                                totalNPSTrainingSurveyRecords += 1;
                            }
                            if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                trainingPromoters += 1;
                                totalNPSTrainingSurveyRecords += 1;
                            }
                        }
                        //SFDC-5347 Change End
                    }
                    if(sr.RecordTypeId == srCorpRecordTypeId){
                        if(sr.NPSScore__c != null){
                            if(sr.NPSScore__c >=0 && sr.NPSScore__c <7){
                                corporateDetractors += 1;
                                totalCorporateSurveyRecords += 1;
                            }
                            if(sr.NPSScore__c > 8 && sr.NPSScore__c <=10){
                                corporatePromoters += 1;
                                totalCorporateSurveyRecords += 1;
                            }
                        }
                        //totalCorporateSurveyRecords += 1;
                    }
                }    
            }
            acc.CCCES__c = totalCESTransactionalSurveyRecords==0?0:(averageCES/totalCESTransactionalSurveyRecords); 
            if(acc.CCCES__c == 0){
                acc.CCCES__c = null;
            }
            acc.CCCSAT__c = totalCSATransactionalSurveyRecords==0?0:(averageCSAT/totalCSATransactionalSurveyRecords); 
            if(acc.CCCSAT__c == 0){
                acc.CCCSAT__c = null;
            } 
            acc.TrainingTrainingMetNeeds__c = totalTrainingSurveyRecords==0?0:(averageTrainingMetNeeds/totalTrainingSurveyRecords);
            if(acc.TrainingTrainingMetNeeds__c == 0){
                acc.TrainingTrainingMetNeeds__c = null;
            }
            if(totalCorporateSurveyRecords != 0){
                acc.CorporateNPS__c = totalCorporateSurveyRecords==0?0:((corporatePromoters - corporateDetractors)/totalCorporateSurveyRecords*100);
            }
            else{
                acc.CorporateNPS__c = null;
            }
            //SFDC-5347 Change Start
	    	if(totalNPSTransactionalSurveyRecords != 0){
                acc.TransactionalNPS__c = totalNPSTransactionalSurveyRecords==0?0:((TransactionalPromoters - TransactionalDetractors)/totalNPSTransactionalSurveyRecords*100);
            }
            else{
                acc.TransactionalNPS__c = null;
            }
	    	if(totalNPSTrainingSurveyRecords != 0){
                acc.TrainingNPS__c = totalNPSTrainingSurveyRecords==0?0:((TrainingPromoters - TrainingDetractors)/totalNPSTrainingSurveyRecords*100);
            }
            else{
                acc.TrainingNPS__c = null;
            }
            //SFDC-5347 Change End
            updatedAccountList.add(acc);
        }
        if(!accountIdWithoutSR.isEmpty()){
            for(Id accountId:accountIdWithoutSR){
                Account acc=new Account();
                acc.Id=accountId;
                acc.CCCES__c = null;
                acc.CCCSAT__c = null;
                acc.TrainingTrainingMetNeeds__c = null;
                acc.CorporateNPS__c = null;
                //SFDC-5347 Change Start
				acc.TransactionalNPS__c = null;
				acc.TrainingNPS__c = null;
                //SFDC-5347 Change End
                updatedAccountList.add(acc);
            }
        }
        return updatedAccountList;
    }
}