objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>SFDC-2548 Global Alliance</description>
        <inlineHelpText>Provide information about the deal motivation / objective.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/S1_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>S1 Requests</relationshipLabel>
        <relationshipName>S1_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client Activity (External)</fullName>
                </value>
                <value>
                    <fullName>Education (Internal)</fullName>
                </value>
                <value>
                    <fullName>Expert Insights &amp; Idea Generation (Internal)</fullName>
                </value>
                <value>
                    <fullName>Marketing Events</fullName>
                </value>
                <value>
                    <fullName>Resource/Materials (External)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <description>US 5450464: store the close date of S1 request</description>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <inlineHelpText>Please select the division for which the request is being created.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                </value>
                <value>
                    <fullName>Engineering Solutions</fullName>
                </value>
                <value>
                    <fullName>Commodity Insights</fullName>
                    <isActive>false</isActive>
                    <label>Commodity Insights</label>
                </value>
                <value>
                    <fullName>MI</fullName>
                    <isActive>false</isActive>
                    <label>MI</label>
                </value>
                <value>
                    <fullName>Ratings</fullName>
                    <isActive>false</isActive>
                    <label>Ratings</label>
                </value>
                <value>
                    <fullName>SPDJI</fullName>
                    <isActive>false</isActive>
                    <label>SPDJI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <description>Industry related to the S1 request</description>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Communication Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Discretionary</fullName>
                </value>
                <value>
                    <fullName>Consumer Staples</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Financials</fullName>
                </value>
                <value>
                    <fullName>Health Care</fullName>
                </value>
                <value>
                    <fullName>Industrials</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Utilities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select an opportunity related to the account.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>S1 Requests</relationshipLabel>
        <relationshipName>S1_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Push_Updates__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Push Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>S1 Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/S1_Response__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>User Story 5306779: External Id to map records from Hub and divisions</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Owner_Email__c</fullName>
        <label>Owner Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Push_Updates__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Push Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S1_Request__c</fullName>
        <label>S1 Request</label>
        <referenceTo>S1_Request__c</referenceTo>
        <relationshipName>S1_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Response</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>S1 Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/S1_RFA_Configurations__mdt.object
<CustomObject>
    <description>US 5496291: Custom Metadata to Store Configurational Changes for RFA apex classes</description>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>Field to store the name of the division i.e. division sent from field</description>
        <label>Division Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body_Prefix__c</fullName>
        <description>Define the email body to be appended before response</description>
        <label>Email Body Prefix</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <description>define the subject of email to be sent</description>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_String__c</fullName>
        <description>Filter applied to Request and response objects when querying the data to sync</description>
        <label>Filter String</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Fields__c</fullName>
        <description>Field to store all the fields to be synced with hub (existing fields can be removed but to add new fields wrapper needs to be updated)</description>
        <label>Request Fields</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Object_API__c</fullName>
        <description>Field to store the API name for request Object</description>
        <label>Request Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Child_API__c</fullName>
        <description>Field to store the API name of the child relationship response</description>
        <label>Response Child API</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response_Fields__c</fullName>
        <description>Field to store all the fields to be synced with the hub (existing fields can be removed but to add new fields wrapper needs to be updated)</description>
        <label>Response Fields</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Object_API__c</fullName>
        <description>Field to store Response object API name</description>
        <label>Response Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, Email notifications will be sent on Rest API execution</description>
        <label>Send Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Divisions__c</fullName>
        <label>Sub Divisions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <description>Email address to send the notifications in case of success and failure</description>
        <label>To Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S1 RFA Configuration</label>
    <pluralLabel>S1 RFA Configurations</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>SFDC1-7841 This field holds insight about the user and why the user was created</description>
        <inlineHelpText>Please enter contextual notes about the user and why the user was created</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RfaPullRecords.cls
/*  @author: Pankhuri Jain
*   @date: 21 Nov 2022
*   @description: Class to pull request/response records from hub org to source org
*/
public with Sharing class RfaPullRecords implements Queueable, Database.AllowsCallouts{
    Schema.SObjectField reqExternalId = S1_Request__c.Fields.Id;
    Schema.SObjectField resExternalId = S1_Response__c.Fields.Id;
    Map<string,string> mapIdToExternalID = new Map<string,string>();
    List<RfaWrapper.RfaRestResponse> restResponse = new List<RfaWrapper.RfaRestResponse>();    
    String sourceDivision;
    String subDivisions; // only in IHS
    static string[] toAddresses = new string[]{};
    boolean sendStatusEmails = false;
    String emailSubject;
    String emailBody;
    
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Method to populate variables from custom metadata
    */
    public void setConfigurations() {       
        S1_RFA_Configurations__mdt config = [SELECT    id, Request_Fields__c, Response_Fields__c, Request_Object_API__c, Response_Object_API__c,
                                                    Response_Child_API__c, Filter_String__c, Sub_Divisions__c, Division_Name__c, To_Email_Address__c, Send_Email_Notification__c, 
                                                    Email_Body_Prefix__c, Email_Subject__c
                                            FROM    S1_RFA_Configurations__mdt WHERE DeveloperName  = 'Default'];
        sourceDivision = config.Division_Name__c;
        subDivisions = config.Sub_Divisions__c; 
        toAddresses.addAll(config?.To_Email_Address__c?.split(','));
        sendStatusEmails = config.Send_Email_Notification__c;
        emailBody = config.Email_Body_Prefix__c;
        emailSubject = config.Email_Subject__c;       
    }

    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Method to make callout to pull changes from Hub
    */
    public void pullRecordsFromHub(){
          try{
              setConfigurations();
              string response;
              response = makeCallout('getRecords');
              upsertRecords(response);                          
              string reqBody = serializeResponse(); 
              if(reqBody != ''){
                  makeCalloutToC360Update('updateRecords',reqBody); 
              }
          }catch (Exception ex) {
                System.debug('Exception '+Ex.getMessage()+'--'+ex.getStackTraceString());    
                if(sendStatusEmails) {
                    sendNotification(Ex.getMessage()+'--'+ex.getStackTraceString());
                }        
          }   
    }
     
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: method to serialize and url encode Success/Failure response message after upsert of Request/Response Records
    */  
    public string serializeResponse() {
          String responseStr = JSON.serialize(restResponse);
          String decodedStr = EncodingUtil.urlEncode(responseStr, 'UTF-8');          
          return decodedStr; 
    }

    /*  @author: Pankhuri Jain
    *   @date: 28 Nov 2022
    *   @description: Send a notification email to notify about the job status (failure/success)
    *   @param: Additional description to be sent 
    */
    public void sendNotification(string description) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);
        mail.setSubject(emailSubject);
        emailBody = emailBody.replace('{{jobname}}', 'pullRecordsFromHub');
        emailBody = emailBody.replace('{{mailContent}}', description);
        mail.setPlainTextBody(emailBody);
        Messaging.sendEmail(new Messaging.Email[] { mail });
    }
      
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Update Request and response records in Division based on Rest Callout response from Hub 
    *   @param: Rest Callout response
    */
    public void upsertRecords(string resBody){
          List<sObject> recToUpdate = new List<sObject>();
          String decodedStr = EncodingUtil.urlDecode(resBody, 'UTF-8');
          decodedStr = decodedStr.replaceAll('__c','').replaceAll('__r','').replaceAll('_','');
          decodedStr = decodedStr.substring(1, decodedStr.length()-1);
          List<RfaWrapper.RecordData> listS1Request = (List<RfaWrapper.RecordData>) JSON.deserialize(decodedStr, List<RfaWrapper.RecordData>.class);
          system.debug('RequestList** ' + listS1Request);
          upsertRequestRecords(listS1Request);
          upsertResponseRecords(listS1Request);
    }
    
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Upsert data to request object
    */
    public void upsertRequestRecords(List<RfaWrapper.RecordData> listS1Request) {
          List<S1_Request__c> listToUpsert = new List<S1_Request__c>();
          for(RfaWrapper.RecordData s1Request : listS1Request) {
              if(subDivisions.contains(s1Request.division) && s1Request.divisionSentFrom != sourceDivision){ 
                 listToUpsert.add(createS1Request(s1Request));
              }
          }
          System.debug('RequestlistToUpsert** ' + listToUpsert);      
          system.debug('RequestlistToUpsertSize** ' + listToUpsert.size());            
          List<Database.upsertResult> uResults = database.upsert(listToUpsert, reqExternalId, false);  
          updateResponseMessage(uResults,'S1_Request__c');
  
    }
     
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Upsert data to response object
    */
    public void upsertResponseRecords(List<RfaWrapper.RecordData> listS1Request) {
          List<S1_Response__c> listToUpsert = new List<S1_Response__c>();
          for(RfaWrapper.RecordData s1Request : listS1Request) {
              if(s1Request.s1Response != null && subDivisions.contains(s1Request.division)) {   
                  listToUpsert.addAll(createS1Response(s1Request));
              }
          }
          System.debug('ResponselistToUpsert** ' + listToUpsert);
          system.debug('ResponselistToUpsertSize** ' + listToUpsert.size());         
          List<Database.upsertResult> uResults = database.upsert(listToUpsert, resExternalId, false);
          updateResponseMessage(uResults,'S1_Response__c');
  
    }
      
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Create an object instance of S1Request
    */ 
    public S1_Request__c createS1Request(RfaWrapper.RecordData s1Request) {        
          S1_Request__c newS1Req = new S1_Request__c();              
          newS1Req.Id = s1Request.externalId;
          newS1Req.External_Id__c = s1Request.externalId;        
          newS1Req.Account__c = s1Request.Account;    
          newS1Req.Opportunity__c = s1Request.Opportunity; 
          newS1Req.Category__c = s1Request.Category;
          newS1Req.Industry__c = s1Request.Industry;
          newS1Req.Division__c = s1Request.Division; 
          newS1Req.Description__c = s1Request.Description; 
          if(s1Request.completedDate != null) {
            newS1Req.Completed_Date__c = Date.ValueOf(s1Request.completedDate);
          }           
          newS1Req.Status__c = s1Request.Status;  
          newS1Req.Push_Updates__c = false;             
                    
          return newS1Req;
    }
     
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Create an object instance of S1Response
    */ 
    public List<S1_response__c> createS1Response(RfaWrapper.RecordData s1Request) {
          list<S1_Response__c> listRes = new List<S1_Response__c>();               
          for(RfaWrapper.RecordData s1Response : s1Request.s1Response.records) {
            if(!subDivisions.contains(s1Response.Division)){// Response has come from S1 user
                S1_Response__c newS1Res = new S1_Response__c();
                newS1Res.External_Id__c = s1Response.externalId;
                newS1Res.Description__c = s1Response.Description;
                newS1Res.Push_Updates__c = false;             
                newS1Res.Status__c = 'Received';
                newS1Res.Owner__c = s1Response.Owner;
                newS1Res.Owner_Email__c = s1Response.OwnerEmail;
                newS1Res.Type__c = 'Incoming';              
                newS1Res.S1_Request__c = s1Request.externalId; 
                listRes.add(newS1Res);
              }
          }
          return listRes;
    }
    
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: method to generate a response wrapper and get record Ids
    */
    public void updateResponseMessage(List<Database.UpsertResult> uResults, string sObjectType) {       
          createIdMap(uResults,sObjectType);
          for(Database.upsertResult result:uResults) {
              if (!result.isSuccess()) {
                  restResponse.add(new RfaWrapper.RfaRestResponse(mapIdToExternalID.get(result.getId()),'Failure',JSON.serialize(result.getErrors()),sObjectType));
              }else {
                  restResponse.add(new RfaWrapper.RfaRestResponse(mapIdToExternalID.get(result.getId()),'Success','Record Upserted',sObjectType));
              }
          }
    }
    
    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: method to generate a Id to external Id map
    */
    public void createIdMap(List<Database.UpsertResult> uResults, string sObjectType) {
          List<sobject> listRecords = new List<sObject>();
          Set<Id> idsToQuery = new Set<Id>();
          for(Database.upsertResult result:uResults) {
              if (result.isSuccess()) {
                  idsToQuery.add(result.getId());
              }
          }
          listRecords = Database.query('SELECT id, external_id__c FROM '+sObjectType+' WHERE id in:idsToQuery');
          for(sobject obj : listRecords) {
              if(obj.get('external_id__c') != null){
                 mapIdToExternalID.put(String.valueOf(obj.get('id')),String.valueOf(obj.get('external_id__c')));
              }
              else 
                 mapIdToExternalID.put(String.valueOf(obj.get('id')),String.valueOf(obj.get('id')));
          }
          system.debug('mapIdToExternalID** ' + mapIdToExternalID);
    }
      
    /*  @author: Pankhuri Jain
    *   @date: 21 Nov 2022
    *   @description: Method to make callout to the Hub org to pull records
    *   @param: Rest Webservice Method to call
    */
    public string makeCallout(string serviceMethod) {
          HttpRequest req = new HttpRequest();
          req.setEndpoint('callout:RFAHubConnect/services/apexrest/rfa_pull/'+serviceMethod);
          req.setMethod('GET');
          req.setHeader('Content-Type', 'application/json');         
          req.setTimeout(120000);
          Http http = new Http();
          HTTPResponse res = http.send(req);
          system.debug('body** ' + res.getBody());
          return res.getBody();
    }

    /*  @author: Pankhuri Jain
    *   @date: 25 Nov 2022
    *   @description: Method to make callout to the Hub org to make updates in Hub with encoded Request body(Division Success/Failure response message)
    *   @param: Rest Webservice Method to call,Request body for the webservice method
    */
    @future(callout = true)
    public static void makeCalloutToC360Update(string serviceMethod, string reqBody) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:RFAHubConnect/services/apexrest/rfa_pull/'+serviceMethod);
        req.setMethod('PUT');
        req.setHeader('Content-Type', 'application/json');
        req.setBody('{"reqBody" : "'+reqBody+'"}');
        req.setTimeout(120000);
        Http http = new Http();
        HTTPResponse res = http.send(req);
        system.debug('resbody** ' + res.getBody());
    }

    /*  @author: Pankhuri Jain
    *   @date: 15 Dec 2022
    *   @description: Method to queue pull updates in a async call
    *   @param: Rest Callout response
    */
    public void execute(QueueableContext context) {
        pullRecordsFromHub();
    }
}