objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-8429: This field will be used for holding Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC-5711 : field created for better reporting.</description>
        <label>AAG</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Businessline__c</fullName>
        <description>SFDC-1346 field to store comma separated values of business lines derived from contract line items</description>
        <inlineHelpText>Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AverageDiscountPercentage__c</fullName>
        <description>SFDC1-4275 Average discount percent rolled up from Opportunity product</description>
        <inlineHelpText>Average Discount Percentage on all products</inlineHelpText>
        <label>Average Discount Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.
SFDC-1896 Updated filter criteria for Consulting record type</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountOverThreshold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4275 Checkbox to indicate if any of the products related to opportunity have crossed discount threshold</description>
        <inlineHelpText>Checked if product(s) are discounted over threshold</inlineHelpText>
        <label>Discount Over Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstYearValue__c</fullName>
        <description>SFDC1-4275 First year total price value rolled up from Opportunity Products</description>
        <inlineHelpText>First Year Contract Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MultiYear__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-54 field to track if opportunity has multi-year schedules.</description>
        <inlineHelpText>Populates from the Products if term of contract is greater than or equal to 2 years</inlineHelpText>
        <label>MultiYear</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousFiscalYearOpportunityLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will take you to the Last fiscal year or the most recent Oppy link</description>
        <inlineHelpText>This field will take you to the Last fiscal year or the most recent Oppy link</inlineHelpText>
        <label>Previous Fiscal Year Opportunity Link</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Previous Fiscal Year Opportunity Link)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DiscountOverThreshold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4275 Indicates whether the opportunity product has been discounted over threshold</description>
        <inlineHelpText>Checked when product has been discounted over threshold</inlineHelpText>
        <label>Discount Over Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscountPercentage__c</fullName>
        <description>SFDC1-173 Denotes the discount percentage to be applied to the UnitPrice. Used in the pricing calculation customization.</description>
        <inlineHelpText>Please specify the discount percentage to be applied to the Updated List Price. Only required when the Discount Type is set to &quot;Percentage&quot;.</inlineHelpText>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchUpdateMobilityMatrics.cls
//@author: Arshad Qureshi
// @date: 5th May 2023
// @description: Batch apex to update the Mobility Matrices on opportunity reporting since FY 2021.
global class BatchUpdateMobilityMatrics implements Database.Batchable<sobject>, Database.Stateful{
    
    //Failed List
 //   List<Database.Error> err = new List<Database.Error>();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {   
        
        String query = 'SELECT id,StageName,BusinessLine__c,CurrencyIsoCode,AverageDiscountPercentage__c,AccountId,CreatedDate,CloseDate,ContractStartDate__c,FirstYearValue__c, DiscountOverThreshold__c, MultiYear__c,ContractBeingRenewed__c,ContractBeingRenewed__r.Opportunity__c,PreviousFiscalYearOpportunityLink__c,Account.DataGovernanceStatus__c,(select Id,Name,Product2Id,OpportunityId,Product2.AAG__c,product2.BusinessLine2__r.name, Status__c, ProductType__c, FirstYear__c, DiscountPercentage__c, DiscountOverThreshold__c,IsProRated__c from OpportunityLineItems where product2.BusinessLine2__r.name=\'Automotive Insights\') FROM Opportunity where PreviousFiscalYearOpportunityLink__c!=null AND (ContractStartDate__c = LAST_N_YEARS:2 OR ContractStartDate__c = THIS_YEAR)';
        return Database.getQueryLocator(query);   
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope)  {  
        try{
            system.debug('scope->'+scope);  
            Map<Id,List<OpportunityLineItem>> previousFiscalOppyWithOLI= new Map<Id,List<OpportunityLineItem>>();
          //  List<Database.Error> err = new List<Database.Error>();
            
            Set<Id> setOppyID = new Set<Id>();
            list<Opportunity> listOpportunityToUpdate = new List<Opportunity>();
            Map<String,List<DatedConversionRate>> mapOfDatedConversionrate = UtilityClass.isoCurrencyDatedConversionRate;
            Decimal conversionRateYearly;
            Decimal conversionRateYearlyForPriorYearPricingCalculation;
            set<Id> setPreviousOppyId= new set<ID>();
            Map<String, List<Id>> previousOppyProduct = new Map<String, List<Id>>();
          //  Decimal PriorYearTotalFirstYearValue = 0.0;
          //  Decimal PriorYearTotalFirstYearValueSub = 0.0;
            Map<Id,Decimal> oppIdPriorYearValueSum = new Map<Id, Decimal>();
            Map<Id,Decimal> oppIdPriorYearValueSumSub = new Map<Id, Decimal>();
            Map<Id, Map<Id, String>> prvOppyProductsStatusMap = new Map<Id, Map<Id, String>>();
            Map<Id, Map<Id,Decimal>> prvOppyProductsFirstYearValueMap = new Map<Id, Map<Id, Decimal>>();
            Map<Id, String> previousOppyProductStatus = new Map<Id, String>();
            Map<Id,Decimal> previousOppyProductFirstYearValue = new Map<Id, Decimal>();
            List<String> lstExcludedProductNames = New List<String>();
            Map<Id, String> previousOppyProductType = new Map<Id, String>();
            Map<Id, Map<Id,String>> prvOppyProductsTypeMap = new Map<Id, Map<Id, String>>();
            
            for(Mobility_Metrics_Excluded_Product_Name__mdt excludedProductName : Mobility_Metrics_Excluded_Product_Name__mdt.getAll().values()){
                lstExcludedProductNames.add('%' + excludedProductName.MasterLabel + '%');
            }
            
            for(Opportunity oppy : Scope){
                if(oppy.BusinessLine__c!=null){
                if((oppy.BusinessLine__c).contains('Automotive Insights')){
                setPreviousOppyId.add(oppy.PreviousFiscalYearOpportunityLink__c);
                setOppyID.add(oppy.Id);
                }
                }
            }
          //  system.debug('setPreviousOppyId-->'+setPreviousOppyId);
            
            List<Opportunity> lstOppyToUpdate = [Select id,PreviousFiscalYearOpportunityLink__c,AverageDiscountPercentage__c,FirstYearValue__c, DiscountOverThreshold__c, MultiYear__c,SalesNewSubscription__c, SalesLostSubOnly__c,MobilitySalesRenewal__c,MobilitySalesNew__c, CurrencyIsoCode,ContractStartDate__c,SalesLosttransonly__c,
                                                 StageName, (select Id,Name,Product2Id,OpportunityId,Product2.AAG__c,product2.BusinessLine2__r.name, Status__c, ProductType__c, FirstYear__c, DiscountPercentage__c, DiscountOverThreshold__c,IsProRated__c
                                                             from OpportunityLineItems)
                                                 from Opportunity where ID IN:setOppyID OR PreviousFiscalYearOpportunityLink__c IN : setOppyID];
            
      //      System.debug('--lstOppyToUpdate--'+lstOppyToUpdate[0].Id);
       //     System.debug('--lstOppyToUpdate--'+lstOppyToUpdate[0].OpportunityLineItems);
            
            //Create previous fiscal year Map
            
            List<Opportunity> lstPreviousFiscalOppy = [Select id,StageName,CurrencyIsoCode,PreviousFiscalYearOpportunityLink__c,AverageDiscountPercentage__c,FirstYearValue__c, DiscountOverThreshold__c, MultiYear__c,ContractBeingRenewed__c,ContractBeingRenewed__r.Opportunity__c,
                                                               (select Id,Name,OpportunityId,FirstYear__c,product2.BusinessLine2__r.name,Product2Id,Product2.AAG__c,DiscountPercentage__c, DiscountOverThreshold__c,IsProRated__c,Status__c, ProductType__c
                                                                from OpportunityLineItems)
                                                               from Opportunity where ID IN:setPreviousOppyId];
                    
            
           // system.debug('lstPreviousFiscalOppy-->'+lstPreviousFiscalOppy);
            if(lstPreviousFiscalOppy!=null && !lstPreviousFiscalOppy.isEmpty()){
                for(Opportunity oppy : lstPreviousFiscalOppy){
                    
                    Decimal PriorYearTotalFirstYearValue = 0.0;
                    Decimal PriorYearTotalFirstYearValueSub = 0.0;
                    previousOppyProductStatus = new Map<Id, String>();
                    previousOppyProductType = new Map<Id, String>();
                    previousOppyProductFirstYearValue = new Map<Id, Decimal>();
                    
                    for(OpportunityLineItem oli: oppy.opportunityLineItems){
                        if(previousFiscalOppyWithOLI.containsKey(oppy.Id)){
                            previousFiscalOppyWithOLI.get(oppy.Id).add(oli);
                            system.debug('previousFiscalOppyWithOLI'+previousFiscalOppyWithOLI);
                            
                        }
                        else{                       
                            List<OpportunityLineItem> lstOppyLineItem = new List<OpportunityLineItem>();
                            lstOppyLineItem.add(oli);
                            previousFiscalOppyWithOLI.put(oppy.id,lstOppyLineItem);
                            
                        }
                   
                        //US: 856599 - Prior Year Pricing Story
                                if(!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights'){
                                    if(oli.Status__c!= 'Lost'){
                                        PriorYearTotalFirstYearValue = PriorYearTotalFirstYearValue + oli.FirstYear__c;
                                        if(oli.ProductType__c == 'Subscription'){
                                            PriorYearTotalFirstYearValueSub = PriorYearTotalFirstYearValueSub + oli.FirstYear__c;
                                        }
                                    }
                                }
                                oppIdPriorYearValueSum.put(oli.OpportunityId, PriorYearTotalFirstYearValue);
                                oppIdPriorYearValueSumSub.put(oli.OpportunityId, PriorYearTotalFirstYearValueSub);
                                
                                previousOppyProductStatus.put(oli.Product2Id, oli.Status__c);
                                previousOppyProductType.put(oli.Product2Id, oli.ProductType__c);
                                previousOppyProductFirstYearValue.put(oli.Product2Id, oli.FirstYear__c);
                                
                                prvOppyProductsStatusMap.put(oppy.Id, previousOppyProductStatus);
                                prvOppyProductsTypeMap.put(oppy.Id, previousOppyProductType);
                                prvOppyProductsFirstYearValueMap.put(oppy.Id, previousOppyProductFirstYearValue);
                        
                    }
                    
                }
                system.debug('previousFiscalOppyWithOLI'+previousFiscalOppyWithOLI);
            }				
            
            //----
            
            //Rolling up Line items
            
            for(Opportunity oppy : lstOppyToUpdate) {
                Opportunity oppyToUpdate = new Opportunity(Id=oppy.Id);
               
                oppyToUpdate.MobilitySalesNew__c = 0.0;
               	oppyToUpdate.MobilitySalesRenewal__c= 0.0;
                oppyToUpdate.SalesNewSubscription__c = 0.0;
                oppyToUpdate.SalesPriceIncreaseDecrease__c=0.0;
                oppyToUpdate.CurrentYearTotalFirstYearValue__c = 0.0;
                oppyToUpdate.CurrentYearTotalFirstYearValueSub__c = 0.0;
                oppyToUpdate.SalesLostSubOnly__c = 0.0;
                oppyToUpdate.SalesLosttransonly__c = 0.0;
                oppyToUpdate.PriorYearTotalFirstYearValue__c=0.00;
                oppyToUpdate.PriorYearTotalFirstYearValueSub__c=0.00;
                oppyToUpdate.StageName = oppy.StageName;
                boolean hasExistingStatusProduct = FALSE;
                
                // Fetch Conversion Rate Yearly  
                if(mapOfDatedConversionrate!= null){
                    if(mapOfDatedConversionrate.keySet().contains(oppy.CurrencyIsoCode)){
                        List<DatedConversionRate> listOfMatchedOppyCurrency = mapOfDatedConversionrate.get(oppy.CurrencyIsoCode);
                        //  system.debug('listOfMatchedOppyCurrency'+listOfMatchedOppyCurrency);
                        for(DatedConversionRate checkMultiYear : listOfMatchedOppyCurrency){
                            if(checkMultiYear != null && oppy.ContractStartDate__c != null && checkMultiYear.StartDate <= oppy.ContractStartDate__c){
                                conversionRateYearly = checkMultiYear.ConversionRate;
                                break;
                            }
                            else{
                                conversionRateYearly = listOfMatchedOppyCurrency[0].ConversionRate;
                            }
                        }
                    }
                }
            
              //Update Previous Fiscal Year Values based on previous Year oppy link
                    if(oppy.PreviousFiscalYearOpportunityLink__c != null && oppIdPriorYearValueSum.containsKey(oppy.PreviousFiscalYearOpportunityLink__c) && prvOppyProductsFirstYearValueMap.containsKey(oppy.PreviousFiscalYearOpportunityLink__c) && prvOppyProductsStatusMap.containsKey(oppy.PreviousFiscalYearOpportunityLink__c)) {
                        previousOppyProductStatus = prvOppyProductsStatusMap.get(oppy.PreviousFiscalYearOpportunityLink__c);
                        previousOppyProductType = prvOppyProductsTypeMap.get(oppy.PreviousFiscalYearOpportunityLink__c);
                        previousOppyProductFirstYearValue = prvOppyProductsFirstYearValueMap.get(oppy.PreviousFiscalYearOpportunityLink__c);
                        //US: 856599 - Prior Year Pricing Story
                        oppyToUpdate.PriorYearTotalFirstYearValue__c = oppIdPriorYearValueSum.get(oppy.PreviousFiscalYearOpportunityLink__c)/conversionRateYearly;
                        oppyToUpdate.PriorYearTotalFirstYearValueSub__c = oppIdPriorYearValueSumSub.get(oppy.PreviousFiscalYearOpportunityLink__c)/conversionRateYearly;
                        system.debug('previousOppyProductStatus'+previousOppyProductStatus);
                        system.debug('previousOppyProductFirstYearValue'+previousOppyProductFirstYearValue);
                        system.debug('PriorYearTotalFirstYearValue__c'+oppyToUpdate.PriorYearTotalFirstYearValue__c);                        
                    }
                
                for(OpportunityLineItem oli: oppy.OpportunityLineItems) {
                   
                    if( oli.Status__c == 'Lost' && (!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights')){
                        if(previousOppyProductStatus != null && previousOppyProductFirstYearValue!= null && previousOppyProductFirstYearValue.containsKey(oli.Product2Id) && previousOppyProductStatus.containsKey(oli.Product2Id) && previousOppyProductStatus.get(oli.Product2Id) != 'Lost') {
                            if(oli.ProductType__c == 'Subscription'){
                                oppyToUpdate.SalesLostSubOnly__c += (previousOppyProductFirstYearValue.get(oli.Product2Id))/conversionRateYearly;
                            }
                            if(oli.ProductType__c == 'Transaction'){
                                oppyToUpdate.SalesLosttransonly__c += (previousOppyProductFirstYearValue.get(oli.Product2Id))/conversionRateYearly;
                            }
                        }
                    }
                    else{
                            if(oli.FirstYear__c!=null ) {
                                //Calculating values for CurrentYearTotalFirstYearValue and CurrentYearTotalFirstYearValueSub fields.
                                if(!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights'){
                                oppyToUpdate.CurrentYearTotalFirstYearValue__c += oli.FirstYear__c/conversionRateYearly;
                                if(oli.ProductType__c == 'Subscription'){
                                        oppyToUpdate.CurrentYearTotalFirstYearValueSub__c += oli.FirstYear__c/conversionRateYearly;
                                    }
                                }
                            }                          
                            //US: 5856776 - Sales price increase decrease
                            if(oli.Status__c=='Existing' && (!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights')){
                                hasExistingStatusProduct = TRUE;
                                oppyToUpdate.MobilitySalesRenewal__c += oli.FirstYear__c/conversionRateYearly;
                                if(previousFiscalOppyWithOLI!=null && previousFiscalOppyWithOLI.containsKey(oppy.PreviousFiscalYearOpportunityLink__c)){
                                    if(oli.FirstYear__c!=null){
                                        oppyToUpdate.SalesPriceIncreaseDecrease__c+=oli.FirstYear__c/conversionRateYearly;
                                    }
                                    if(previousOppyProductStatus != null && previousOppyProductFirstYearValue!= null && previousOppyProductFirstYearValue.containsKey(oli.Product2Id) && previousOppyProductStatus.containsKey(oli.Product2Id) && (previousOppyProductStatus.get(oli.Product2Id) == 'New' || previousOppyProductStatus.get(oli.Product2Id) == 'Existing')){
                                        oppyToUpdate.SalesPriceIncreaseDecrease__c-=(previousOppyProductFirstYearValue.get(oli.Product2Id))/conversionRateYearly;
                                    }
                                    system.debug('oppyToUpdate.SalesPriceIncreaseDecrease__c '+oppyToUpdate.SalesPriceIncreaseDecrease__c);
                                }
                            }
                            // US: 5856692 - SalesNew and SalesRenewal fields
                        if(oli.Status__c=='New' && (!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights')) {
                            oppyToUpdate.MobilitySalesNew__c += oli.FirstYear__c/conversionRateYearly;
                            if(oli.ProductType__c == 'Subscription') {
                                oppyToUpdate.SalesNewSubscription__c += oli.FirstYear__c/conversionRateYearly;
                            }
                        }
                    }
                
                }
                if(oppyToUpdate.StageName.contains('6L')){
                    oppyToUpdate.SalesLostSubOnly__c = 0.0;
                    oppyToUpdate.SalesLosttransonly__c = 0.0;
                    for(OpportunityLineItem oli: oppy.OpportunityLineItems) {
                          if(!lstExcludedProductNames.contains(oli.Name) && oli.product2.BusinessLine2__r.name== 'Automotive Insights'){
                        if(oli.ProductType__c == 'Subscription' && previousOppyProductFirstYearValue.ContainsKey(oli.Product2Id)){
                            oppyToUpdate.SalesLostSubOnly__c += (previousOppyProductFirstYearValue.get(oli.Product2Id))/conversionRateYearly;
                            }
                            if(oli.ProductType__c == 'Transaction' && previousOppyProductFirstYearValue.ContainsKey(oli.Product2Id)){
                                oppyToUpdate.SalesLosttransonly__c += (previousOppyProductFirstYearValue.get(oli.Product2Id))/conversionRateYearly;
                            }
                    }
                    }
                }
                
                //Updating fields to 0 when the opp is Lost.
                   if(oppyToUpdate.StageName.contains('6L')){
                        oppyToUpdate.CurrentYearTotalFirstYearValue__c = 0;
                        oppyToUpdate.CurrentYearTotalFirstYearValueSub__c = 0;
                        oppyToUpdate.MobilitySalesRenewal__c = 0;
                        oppyToUpdate.SalesPriceIncreaseDecrease__c = 0;
                        oppyToUpdate.MobilitySalesNew__c=0;
                        oppyToUpdate.SalesNewSubscription__c=0;
                    }
                    if(!hasExistingStatusProduct){
                        oppyToUpdate.SalesPriceIncreaseDecrease__c = 0;
                    } 
                
                listOpportunityToUpdate.add(oppyToUpdate);
                System.debug('oppyToUpdate-->'+oppyToUpdate);
            }
         
            
            if(listOpportunityToUpdate != null && !listOpportunityToUpdate.isEmpty()){
                Database.SaveResult[] srList = Database.update(listOpportunityToUpdate,false);
                // Iterate through each returned result
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                        System.debug('Successfully inserted' );
                    }
                    else {
                        // Operation failed, so get all errors  
                  //  err.addAll(sr.getErrors());    
                    System.debug('Error Caught'+sr.getErrors());    
                    }
                }
            }
            
        }
        catch(Exception ex) {
            System.debug('Exception caught in batch' + ex.getMessage());
           // System.debug('Error List-->'+err);
            UtilityClass.createApexLogRecord(ex, 'BatchUpdateMobilityMatrics', 'Execute');       
        }
        
    }
    
    global void finish(Database.BatchableContext bc) {
     //   System.debug('Error List-->'+err);
        System.debug(LoggingLevel.INFO, 'BatchUpdateMobilityMatrics batch completed');
    }
    
    
}