objects/Account.object
<CustomObject>
    <fields>
        <fullName>ComplianceRestrictionException__c</fullName>
        <description>SFDC1-8049 Setting this designation at the Ultimate Parent will cascade the value in the Compliance Restriction field through the hierarchy to all accounts except those designated with a different exception value</description>
        <inlineHelpText>When set at the Ultimate Parent level, this restriction will then display as the Compliance Restriction for all child accounts.  Otherwise, when a child record has a different restriction than the parent, this field allows for that difference to be set.</inlineHelpText>
        <label>Compliance Restriction Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ComplianceRestrictions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ComplianceRestriction__c</fullName>
        <description>SFDC1-8049 if the Compliance Restriction Exception on the account is null, then set to the Compliance Restriction Exception value of the Ultimate Parent, else set to Compliance Restriction Exception value.</description>
        <formula>IF(!ISBLANK(TEXT(ComplianceRestrictionException__c)), TEXT(ComplianceRestrictionException__c),
   IF(!ISNULL(GlobalUltimateAccount__c), TEXT(GlobalUltimateAccount__r.ComplianceRestrictionException__c), &apos;&apos;)
)</formula>
        <inlineHelpText>Calculated field. If the Compliance Restriction Exception on the account is null, then the Compliance Restriction Exception value of the Ultimate Parent, if any, will display.</inlineHelpText>
        <label>Compliance Restriction</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SetComplianceException__e.object
<CustomObject>
    <description>SFDC-3123 Platform events to cascade Compliance Restriction Exception to child Account Records</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ComplianceRestriction__c</fullName>
        <label>Compliance Restriction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SetComplianceExceptionEvent</label>
    <pluralLabel>SetComplianceExceptionEvents</pluralLabel>
</CustomObject>

globalValueSets/ComplianceRestrictions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Entity List</fullName>
    </customValue>
    <customValue>
        <fullName>Russia Directive 1; Payment terms not &gt; 14 days</fullName>
    </customValue>
    <customValue>
        <fullName>Russia Directive 2; Payment terms not &gt; 60 days</fullName>
    </customValue>
    <customValue>
        <fullName>Russia Directive 2 and 4; Payment terms cannot exceed 60 days, and end use certificate or due diligence questionnaire required</fullName>
    </customValue>
    <customValue>
        <fullName>Russia Directive 3; Payment terms not &gt; 30 days</fullName>
    </customValue>
    <customValue>
        <fullName>Russia Directive 4; End use certificate or due diligence questionnaire required </fullName>
    </customValue>
    <customValue>
        <fullName>Sanctioned Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Unverified List</fullName>
    </customValue>
    <customValue>
        <fullName>Venezuela; Payment terms not &gt; 90 days</fullName>
        <isActive>false</isActive>
        <label>Venezuela; Payment terms not &gt; 90 days</label>
    </customValue>
    <customValue>
        <fullName>Venezuela; Payment terms not &gt; 30 days</fullName>
        <isActive>false</isActive>
        <label>Venezuela; Payment terms not &gt; 30 days</label>
    </customValue>
    <customValue>
        <fullName>Prohibited Customer</fullName>
        <isActive>false</isActive>
        <label>Prohibited Customer</label>
    </customValue>
    <masterLabel>Compliance Restrictions</masterLabel>
</GlobalValueSet>

classes/SetComplianceExceptionMethods.cls
//-----------------------------
// @author: Priyanka Vyas
// @date: 22 Oct 2020
// @param: NA
// @description: SFDC-3123 Class to hold SetComplianceException__e platform event trigger methods 
// @return: NA
//-----------------------------
public class SetComplianceExceptionMethods {
    public static void cascadeComplianceRestrictionToChildAccounts(TriggerParameters tp) {
        List<SetComplianceException__e> eventList = (List<SetComplianceException__e>)tp.newList;
        if(!AccountMethods.continueComplianceCascade) {
            AccountMethods.continueComplianceCascade=true;
        }
        List<Account> accountsToUpdate = new List<Account>();
        List<Account> childAccounts = new List<Account>();
        Map<Id,String> complianceRestrictionOnAccountMap = new Map<Id,String>();
        for (SetComplianceException__e event: eventList) {
            complianceRestrictionOnAccountMap.put(event.AccountId__c, event.ComplianceRestriction__c);
        }
        childAccounts = [Select id, parentid, ComplianceRestrictionException__c, parent.ComplianceRestrictionException__c from Account WHERE ParentId in:complianceRestrictionOnAccountMap.keyset()];
        for(Account childAcc : childAccounts) {
            childAcc.ComplianceRestrictionException__c=complianceRestrictionOnAccountMap.get(childAcc.ParentId);
            accountsToUpdate.add(childAcc);
        }
        if(accountsToUpdate.size()>0) {
            update accountsToUpdate;
        }
    }
}