objects/Account.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-10407 : Creating this field to bypass the validation rule using Apex Code.</description>
        <inlineHelpText>This field will be used to byPass the Validation Rules in Apex.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                    <label>Inactive - Out of Business</label>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                    <label>Inactive - Invalid</label>
                </value>
                <value>
                    <fullName>InactiveLifecycle</fullName>
                    <label>Inactive - Lifecycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-8429: This field will be used for holding Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Businessline__c</fullName>
        <description>SFDC-1346 field to store comma separated values of business lines derived from contract line items</description>
        <inlineHelpText>Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6439 This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</description>
        <inlineHelpText>This field will be used to by pass the opportunity validations that are executed when opportunity line items are deleted while changing currency.</inlineHelpText>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PreviousFiscalYearOpportunityLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will take you to the Last fiscal year or the most recent Oppy link</description>
        <inlineHelpText>This field will take you to the Last fiscal year or the most recent Oppy link</inlineHelpText>
        <label>Previous Fiscal Year Opportunity Link</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Previous Fiscal Year Opportunity Link)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store primary contact name at Opportunity record level.</description>
        <inlineHelpText>To store primary contact name at Opportunity record level.</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstYear__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>SFDC1-905 This fields holds the first year price for opportunity line items</description>
        <inlineHelpText>First Year Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/TestBatchUpdatePriorYearOppyLink.cls
//@author: Kanika Miglani
// @date: 30th May 2023
// @description: Test Class for BatchUpdatePriorYearOppyLink
//---------------------------------------------------------------------------------------------------------------------------
@isTest
public class TestBatchUpdatePriorYearOppyLink {
@testSetup
    static void createRecords() {
 
        // CREATE ACCOUNT
        Account acc1 = new Account();
        //acc1.parentid = 'Test Parent'; 
        acc1.Name = 'Test Account';
        acc1.BillingStreet = 'No Lane';
        acc1.BillingCity = 'Hyderabad';
        acc1.BillingState = 'Telangana';
        acc1.BillingCountry = 'India';
        acc1.BillingCountryCode = 'IN';
        acc1.DataGovernanceStatus__c = 'Approved';
        insert acc1;
        
        // CREATE CONTACT
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc1.Id;
        con.Email = 'test-contact@sfdc.com';
        INSERT con;
        
        // CREATE OPPORTUNITY
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = Date.newInstance(2022,12,31);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        opp.AccountId = acc1.Id;
        opp.ContractStartDate__c = Date.newInstance(2022,8,1);
        opp.BusinessLine__c = 'Automotive Insights';
        opp.ByPassValidation__c = true;
        opp.StageName = '1-Sales Qualified';
        opp.PreviousFiscalYearOpportunityLink__c = null ;
        opp.ContractEndDate__c = Date.newInstance(2023,8,1);
        INSERT opp;
        
        // Create Contract 
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id orderFormContractId = ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, opp.Id);
        Contract testContract = new Contract(Id = orderFormContractId);
       
        // CREATE OPPORTUNITY CONTACT ROLE (OPPORTUNITY PRIMARY CONTACT)
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.OpportunityId = opp.Id;
        ocr.ContactId = con.Id;
        ocr.IsPrimary = true;
        ocr.Role = 'Opportunity Primary Contact';
        INSERT ocr;
        
        opp.PrimaryContact__c = ocr.Id;
        Update Opp;
        
        
              
        // Create 1st Renewal Opportunity
        Opportunity oppy1 = TestUtility.createRenewalOpportunity(acc1.Id, testContract.Id, true, false, false, true);
        oppy1.ContractStartDate__c = system.today();
        oppy1.CurrencyIsoCode = 'USD';
        oppy1.PreviousFiscalYearOpportunityLink__c = null ;
        oppy1.ContractEndDate__c = system.today() + 1;
        system.debug('oppy1.ContractStartDate__c'+oppy1.ContractStartDate__c);
        Test.startTest();
        // Create 2nd Renewal Opportunity
        Opportunity oppy2 = TestUtility.createRenewalOpportunity(acc1.Id, testContract.Id, true, false, false, true);
        oppy2.ContractStartDate__c = oppy1.ContractStartDate__c.addYears(1);
        oppy2.CurrencyIsoCode = 'USD' ;
        oppy2.PreviousFiscalYearOpportunityLink__c = null ;
        oppy2.ContractEndDate__c = oppy2.ContractStartDate__c + 1;
        system.debug('oppy2.ContractStartDate__c'+oppy2.ContractStartDate__c);
        
        List<Opportunity> listOfOpportunities = new List<Opportunity>{oppy1,oppy2};
        UPDATE listOfOpportunities;
        
        // CREATE OPPORTUNITY PRODUCT
        Product2 prod = new Product2();
        prod.Name = 'Test Product';
        prod.ProductCode = 'TESTPRODUCT';
        prod.IsActive = true;
        INSERT prod;
        
        // CREATE PRICEBOOK ENTRY
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.Product2Id = prod.Id;
        pbe.UnitPrice = 100.00;
        pbe.IsActive = true;
        pbe.CurrencyIsoCode = 'USD';
        INSERT pbe;
        
        // CREATE OPPORTUNITY PRODUCT / LINE ITEM
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppy1.Id;
        oli.Quantity = 2;
        oli.PricebookEntryId = pbe.Id;
        oli.TotalPrice = oli.Quantity * pbe.UnitPrice;
        oli.FirstYear__c = oli.TotalPrice;
        oli.Status__c = 'New';
        
        OpportunityLineItem oli2 = new OpportunityLineItem();
        oli2.OpportunityId = oppy1.Id;
        oli2.Quantity = 2;
        oli2.PricebookEntryId = pbe.Id;
        oli2.TotalPrice = oli2.Quantity * pbe.UnitPrice;
        oli2.FirstYear__c = oli2.TotalPrice;
        oli2.Status__c = 'Lost';
        
		OpportunityLineItem oli3 = new OpportunityLineItem();
        oli3.OpportunityId = oppy1.Id;
        oli3.Quantity = 2;
        oli3.PricebookEntryId = pbe.Id;
        oli3.TotalPrice = oli3.Quantity * pbe.UnitPrice;
        oli3.FirstYear__c = oli3.TotalPrice;
        oli3.Status__c = 'Lost';
        
        OpportunityLineItem oli4 = new OpportunityLineItem();
        oli4.OpportunityId = oppy2.Id;
        oli4.Quantity = 2;
        oli4.PricebookEntryId = pbe.Id;
        oli4.TotalPrice = oli4.Quantity * pbe.UnitPrice;
        oli4.FirstYear__c = oli4.TotalPrice;
        oli4.Status__c = 'New';
        
        OpportunityLineItem oli5 = new OpportunityLineItem();
        oli5.OpportunityId = oppy2.Id;
        oli5.Quantity = 2;
        oli5.PricebookEntryId = pbe.Id;
        oli5.TotalPrice = oli5.Quantity * pbe.UnitPrice;
        oli5.FirstYear__c = oli5.TotalPrice;
        oli5.Status__c = 'Lost';
        
        OpportunityLineItem oli6 = new OpportunityLineItem();
        oli6.OpportunityId = oppy2.Id;
        oli6.Quantity = 2;
        oli6.PricebookEntryId = pbe.Id;
        oli6.TotalPrice = oli6.Quantity * pbe.UnitPrice;
        oli6.FirstYear__c = oli6.TotalPrice;
        oli6.Status__c = 'Lost';
        
        List<OpportunityLineItem> listOfOpportunityLineItems = new List<OpportunityLineItem>{oli,oli2,oli3,oli4,oli5,oli6};
        INSERT listOfOpportunityLineItems;
        Test.stopTest();   
    }
    
     @isTest
    static void unitTest() {
        List<Opportunity> listOfRenewalOpportunity = new List<Opportunity>();
        Map<Id, List<OpportunityLineItem>> mapOfOpportunityLineItems = new Map<Id, List<OpportunityLineItem>>();
        for (Opportunity oppty : [SELECT Id, Name,PreviousFiscalYearOpportunityLink__c,ContractStartDate__c,ContractEndDate__c, (SELECT Id, Status__c,FirstYear__c FROM OpportunityLineItems where FirstYear__c != null) FROM Opportunity WHERE PreviousFiscalYearOpportunityLink__c = null])
		{
  			mapOfOpportunityLineItems.put(oppty.Id, oppty.OpportunityLineItems);
            system.debug('oppty==>'+oppty);
            listOfRenewalOpportunity.add(oppty);
            system.debug('listOfRenewalOpportunity'+listOfRenewalOpportunity);
            system.debug('listOfRenewalOpportunity.size()'+listOfRenewalOpportunity.size());
         }
       
        system.debug('OpportunityLineItem-->oppLineItem'+mapOfOpportunityLineItems);
        system.debug('listOfRenewalOpportunity'+listOfRenewalOpportunity);
        Test.startTest();
        Database.executeBatch(new BatchUpdatePriorYearOppyLink());
        //system.assertEquals(oppy2.PreviousFiscalYearOpportunityLink__c, oppy1.Id);
        Test.stopTest();
    }
}