objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Customer Master Data Team.</inlineHelpText>
        <label>Customer Master Data Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                    <label>Under Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-3378 Global Account Manager</description>
        <inlineHelpText>Global Account Manager</inlineHelpText>
        <label>GAM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RocketDocs__Proposal_Request__c.object
<CustomObject>
    <description>RocketDocs Salesforce Connector 2.0: Container for the project synced from RocketDocs.</description>
    <fields>
        <fullName>RocketDocs__Due_Date__c</fullName>
        <description>RocketDocs Salesforce Connector 2.0: Indicates when the user expects a response from the proposal team.</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RocketDocs__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RocketDocs Salesforce Connector 2.0: Main proposal request container associated to an Opportunity</description>
        <inlineHelpText>RocketDocs Salesforce Connector 2.0: Lookup to the Opportunity. There should only be one active Proposal Request associated to an Opportunity at any given time.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RocketDocs Requests</relationshipLabel>
        <relationshipName>RocketDocs_Proposal_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RocketDocs Request</label>
    <nameField>
        <displayFormat>RDR-{0000000}</displayFormat>
        <label>RocketDocs Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RocketDocs Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestRocketDocsRequestMethods.cls
@isTest
private class TestRocketDocsRequestMethods {

    //-----------------------------
    // @author: Sharique
    // @date: 20 June 2022
    // @param: NA
    // @description: Test method for RocketDocs Request trigger methods
    // @return: NA
    //-----------------------------
    @testSetup static void testSetup() {
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;
        c.Phone = '12345';
        c.EmailUnknown__c = true;
        insert c;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName= '1-Sales Qualified';
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.GAM__c = u.id;
        opp.AccountId = a.id;
        insert opp;    
        
        OpportunityContactRole oppContactRole = new OpportunityContactRole();
        oppContactRole.OpportunityID = opp.id;
        oppContactRole.ContactId = c.id;
        oppContactRole.IsPrimary = true;
        insert oppContactRole;
    }
    
    @isTest private static void testPrepopulateFieldsValues() {
        
        Opportunity oppy = [Select Id, AccountId FROM Opportunity Where Name= 'Test Opp' LIMIT 1];
        RocketDocs__Proposal_Request__c req = new RocketDocs__Proposal_Request__c();
        req.RocketDocs__Opportunity__c = oppy.Id;
        req.RocketDocs__Due_Date__c = System.today()+30;
        insert req;
           
        
    }
    
}