objects/Account.object
<CustomObject>
    <fields>
        <fullName>ComplianceRestriction__c</fullName>
        <description>SFDC1-8049 if the Compliance Restriction Exception on the account is null, then set to the Compliance Restriction Exception value of the Ultimate Parent, else set to Compliance Restriction Exception value.</description>
        <formula>IF(!ISBLANK(TEXT(ComplianceRestrictionException__c)), TEXT(ComplianceRestrictionException__c),
   IF(!ISNULL(GlobalUltimateAccount__c), TEXT(GlobalUltimateAccount__r.ComplianceRestrictionException__c), &apos;&apos;)
)</formula>
        <inlineHelpText>Calculated field. If the Compliance Restriction Exception on the account is null, then the Compliance Restriction Exception value of the Ultimate Parent, if any, will display.</inlineHelpText>
        <label>Compliance Restriction</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SetComplianceException__e.object
<CustomObject>
    <description>SFDC-3123 Platform events to cascade Compliance Restriction Exception to child Account Records</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ComplianceRestriction__c</fullName>
        <label>Compliance Restriction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SetComplianceExceptionEvent</label>
    <pluralLabel>SetComplianceExceptionEvents</pluralLabel>
</CustomObject>

classes/TestSetComplianceExceptionMethods.cls
//-----------------------------
// @author: Sathish Edla
// @date: 30 Mar 2022
// @description: SFDC-5375 Extend the trigger framework to handle platform events.
//-----------------------------
@isTest
private class TestSetComplianceExceptionMethods {
    @isTest static void SetComplianceExceptionMethods() {
        Account parentAccount = TestUtility.createTestAccount('Test Account', true);
        Account childAccount = TestUtility.createTestAccount('Child Test Account', false);
        childAccount.ParentId = parentAccount.Id;
        insert childAccount;
        // Create a test event instance
        SetComplianceException__e objPlatformEvent = new SetComplianceException__e(AccountId__c = parentAccount.Id,
                                                                                   ComplianceRestriction__c = 'Test');
        Test.startTest();
        // Publish test event
        Database.SaveResult sr = EventBus.publish(objPlatformEvent);
        Test.stopTest();
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
    }
    @isTest static void SetComplianceExceptionDispatcher() {
        Account parentAccount = TestUtility.createTestAccount('Test Account', true);
        // Create a test event instance
        SetComplianceException__e objPlatformEvent = new SetComplianceException__e(AccountId__c = parentAccount.Id,
                                                                                   ComplianceRestriction__c = 'Test');
        Test.startTest();
        SetComplianceExceptionDispatcher.isAfterInsertProcessing = TRUE;
        // Publish test event
        Database.SaveResult sr = EventBus.publish(objPlatformEvent);
        Test.stopTest();
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
    }
}