objects/Account.object
<CustomObject>
    <fields>
        <fullName>LegacyID__c</fullName>
        <description>SFDC1-2445 When the account is created via migration this field will be populated by the migration with the winning ID of the legacy system.  Please note that all 3 legacy fields listed here are from the highest ranking source. Each source can be found in the related table Legacy Account ID - will not be visible to Sales profiles to avoid confusion with related legacy ids object.</description>
        <externalId>true</externalId>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AdditionalProductLoginFields__c.object
<CustomObject>
    <description>SFDC1-7972 This is a separate object created for capturing additional product login fields which are more specific to the product requirement. Many of these fields are originated from L-Markit.</description>
    <fields>
        <fullName>LegacyID__c</fullName>
        <description>Legacy Id field for Additional product login fields. It will be same as parent product login . Creating as part of migration exercise</description>
        <externalId>true</externalId>
        <inlineHelpText>Legacy Id field from source system</inlineHelpText>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-6347: Parent of Additional Product Login Information.</description>
        <inlineHelpText>Parent of Additional Product Login Information.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Additional Product Login Fields</relationshipLabel>
        <relationshipName>AdditionalProductLoginFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>SFDC1-6785 Username or Login name for this user. This is copied over from Product Login via workflow</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique username or login name for this user automatically copied over from Product Login via workflow</inlineHelpText>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Additional Product Login Fields</label>
    <nameField>
        <label>Additional Product Login Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Product Login Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>AdditionalProductLoginFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6785 Required for the Additional Product Login Fields Setup</description>
        <inlineHelpText>Additional Product Login Fields record gets auto-generated whenever the user record is created. This object holds more product specific fields.</inlineHelpText>
        <label>Additional Product Login Fields</label>
        <referenceTo>AdditionalProductLoginFields__c</referenceTo>
        <relationshipLabel>Product Logins</relationshipLabel>
        <relationshipName>ProductLogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-6785 Email of the user used for Product Login.</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user used for Product Login.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>SFDC1-6785 First Name of the user used for Product Login.</description>
        <inlineHelpText>First Name of the user used for Product Login.</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>SFDC1-6785 Last Name of the user used for Product Login.</description>
        <inlineHelpText>Last Name of the user used for Product Login.</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <description>SFDC1-6785: Legacy ID field is the system id (unfriendly) referencing the source record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the system id (unfriendly) referencing the source record and is populated via migrating system</inlineHelpText>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>SFDC1-6785 Username or Login name for this user</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the unique username or login name for this user.</inlineHelpText>
        <label>Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductLoginContactAssociation__c.object
<CustomObject>
    <description>SFDC1-7972 This object links the Product Login to the related contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-4386 Contact related to this Product Login</description>
        <inlineHelpText>Link the related Contact to this Product Login</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-4386 Product Login related to this Contact</description>
        <inlineHelpText>Link the related to Product Login to this Contact</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Login Contact Association</label>
    <nameField>
        <displayFormat>PLContact-{000000}</displayFormat>
        <label>Product Login Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Login Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LegacyID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-2445 : Legacy ID field for User Object</description>
        <externalId>true</externalId>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProductLoginMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 13 April 2018
// @param: NA
// @description: Class to hold Product Login Fields trigger methods 
// @return: NA
//-----------------------------

public class ProductLoginMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 13 April 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-6347 Whenever an Product Login is created, whether through an integration/data migration or manually by a user an "Additional Product Login Fields" 
    //                          record belonging to the Product Login is automatically created and a link to the record is populated in the "Additional Product Login Fields" field on the Product Login record. 
    //                          This field should not be editable by anyone excluding the System Admin.
    //                          This function create an Additional User Fields lookup related to an Product Login.
    // 
    // @return: None
    //------------------------------
    public static void setProductLoginAdditionalFieldsObject(TriggerParameters tp) {
        
        try {
            
            // List of Additional Product Login Fields thats needs to be inserted 
            List<AdditionalProductLoginFields__c> additionalProductLoginFieldsToInsert = new List<AdditionalProductLoginFields__c>();
            
            // Map of old values and new values
            Map<Id,ProductLogin__c> mapNewProductLogin = (Map<Id,ProductLogin__c>) tp.newMap;
            Map<Id,ProductLogin__c> mapOldProductLogin = (Map<Id,ProductLogin__c>) tp.oldMap;
            
            for(ProductLogin__c newProductLogin: mapNewProductLogin.values()) {
                if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert) {
                    if(newProductLogin.AdditionalProductLoginFields__c == null) {
                        additionalProductLoginFieldsToInsert.add(new AdditionalProductLoginFields__c(Name = newProductLogin.Username__c, Username__c = newProductLogin.Username__c, 
                                                        ProductLogin__c = newProductLogin.Id, LegacyID__c = newProductLogin.LegacyID__c));  
                    }
                }
            }
            
            // insert if list has any records
            if(additionalProductLoginFieldsToInsert != null && additionalProductLoginFieldsToInsert.size() > 0) {
                insert additionalProductLoginFieldsToInsert;
            }
            
        } catch(Exception ex) {
            //this will happen if any exception apart from DML exception has occurred
            //UtilityClass.createApexLogRecord(ex, 'ProductLoginMethods', 'setProductLoginAdditionalFieldsObject');
            ApexLogger.logError(new LogMessage('ProductLoginMethods','setProductLoginAdditionalFieldsObject',ex,tp.newList.get(0),null ));
        }
    }
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 13 April 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-6347 Whenever an Product Login is created, whether through an integration/data migration or manually created by a user an "Additional Product Login Fields" 
    //                          record belonging to the Product Login is automatically created and a link to the record is populated in the "Additional Product Login Fields" field. 
    //                          This function populate the Additional Fields lookup in Product Login.
    //                          This function change Account User Additional Fields Object Name When username changes in Product Login Object
    // 
    // @return: None
    //------------------------------
    public static void changeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges(TriggerParameters tp) {
        
        try {
            
            // List of Additional Product Login Fields thats needs to be updated 
            List<AdditionalProductLoginFields__c> additionalProductLoginFieldsToUpdate = new List<AdditionalProductLoginFields__c>();
            
            // Map of old values and new values
            Map<Id,ProductLogin__c> mapNewProductLogin = (Map<Id,ProductLogin__c>) tp.newMap;
            Map<Id,ProductLogin__c> mapOldProductLogin = (Map<Id,ProductLogin__c>) tp.oldMap;
            
            for(ProductLogin__c newProductLogin: mapNewProductLogin.values()) {
                if(tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                    if(newProductLogin.AdditionalProductLoginFields__c != null && newProductLogin.Username__c != mapOldProductLogin.get(newProductLogin.Id).Username__c) {
                        additionalProductLoginFieldsToUpdate.add(new AdditionalProductLoginFields__c(Name = newProductLogin.Username__c, Username__c = newProductLogin.Username__c, Id = newProductLogin.AdditionalProductLoginFields__c));
                    }
                }
            }
            
            // insert if list has any records
            if(additionalProductLoginFieldsToUpdate != null && additionalProductLoginFieldsToUpdate.size() > 0) {
                update additionalProductLoginFieldsToUpdate;
            }
            
        } catch(Exception ex) {
            //this will happen if any exception apart from DML exception has occurred
            //UtilityClass.createApexLogRecord(ex, 'ProductLoginMethods', 'changeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges');
        	ApexLogger.logError(new LogMessage('ProductLoginMethods','changeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges',ex,tp.newList.get(0),null ));
        }
    }
    //-----------------------------
    // @author: Jagadesh Kumar
    // @date: 06 Aug 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-9572 Whenever Changes to Product Login email trigger relinking to Contact Record via (Product Login Contact Association)
    // If the Email Changes has contact exists in DB then it creates the Product Login Contact Association,
    // If the Email Changes has contact NOT exists in DB then it first create Contact and then creates the Product Login Contact Association
    // @lastModifiedBy: Vishnu Vardhan Chowdary
    // @lastModifiedDate: 11 Dec 2018
    // @LastModifiedDescription: SFDC1-10703, Earlier this method was called only when Product login is updated with different email. 
    // 		Now we are calling it when product login is created. 
    // @lastModifiedBy: Vishnu Vardhan Chowdary
    // @lastModifiedDate: 17 Dec 2018
    // @LastModifiedDescription: SFDC1-10703, Removing the Contact creation logic and changing the methods name.
    // @return: None
    //------------------------------
    public static void insertPLContactAssociation(TriggerParameters tp) {
        try {
            // Map of old values and new values
            Map<Id,ProductLogin__c> mapNewProductLogin = (Map<Id,ProductLogin__c>) tp.newMap;
            Map<Id,ProductLogin__c> mapOldProductLogin = (Map<Id,ProductLogin__c>) tp.oldMap;
            Map<String,Contact> emailContactMap = new Map<String,Contact>();
            Map<String,ProductLoginContactAssociation__c> associationMap = new Map<String,ProductLoginContactAssociation__c>();
            Set<Id> emailChangeprodLoginIds = new Set<Id>();
            Set<String> emailChangeSet = new Set<String>();
            
            for(ProductLogin__c newProductLogin: mapNewProductLogin.values()) {
                ProductLogin__c oldProductLogin = new ProductLogin__c();
                if(tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                    oldProductLogin = mapOldProductLogin.get(newProductLogin.Id);
                }
                if(newProductLogin.Email__c != null && newProductLogin.Email__c != oldProductLogin.Email__c) {
                    emailChangeprodLoginIds.add(newProductLogin.Id);
                    emailChangeSet.add(newProductLogin.Email__c);
                }
            }
            if(emailChangeprodLoginIds.size() > 0) {
                //Check whether updated Email Address has Contact exists in DB or not
                for(Contact con : [SELECT Id,Email,lastName from Contact where Email IN : emailChangeSet]) {
                    emailContactMap.put(con.Email,con);
                }
                //For Email Update Product Login's Loop through to Validate PLContactAsociation
                //Check If Updated Email Address Contact existis in DB then
                //   Check Product Login and Contact has PLContactAsociation exists or not,If not exists will 
                //   insert PLContactAsociation.
                List<ProductLogin__c> productloginList = [SELECT Id,Email__c,FirstName__c,LastName__c,
                                                          (SELECT Contact__c,ProductLogin__c FROM ProductLoginContactAssociations1__r) 
                                                          FROM ProductLogin__c WHERE ID IN : emailChangeprodLoginIds];
                for(ProductLogin__c login : productloginList) {
                    if(emailContactMap.get(login.Email__c) != null) { //Contact exists for the Email
                        checkPLContactAssociation(login, emailContactMap, associationMap);
                        System.debug('--------associationMap---------****'+associationMap);
                    } 
                }
            }
            System.debug('-----final associationMap ---'+associationMap);
            if(associationMap.size() > 0) {
                insert associationMap.values();
            }
        } catch(Exception ex) {
            //this will happen if any exception apart from DML exception has occurred
            //UtilityClass.createApexLogRecord(ex, 'ProductLoginMethods', 'insertPLContactAssociationWhenEmailChanges');
        	ApexLogger.logError(new LogMessage('ProductLoginMethods','insertPLContactAssociationWhenEmailChanges',ex,tp.newList.get(0),null ));
        }
    }
    
    //Check for Product login and Contact association exists or not.
    private static void checkPLContactAssociation(ProductLogin__c login, Map<String,Contact> emailContactMap, Map<String,ProductLoginContactAssociation__c> associationMap) {
        boolean existsAsso = false;
        if(login.ProductLoginContactAssociations1__r != null && login.ProductLoginContactAssociations1__r.size() > 0) {
            for(ProductLoginContactAssociation__c plcAsso : login.ProductLoginContactAssociations1__r) {
                if(login.Id == plcAsso.ProductLogin__c && emailContactMap.get(login.Email__c).Id == plcAsso.Contact__c) {
                    existsAsso = true;
                }  
            }
        }
        if(!existsAsso) {
            ProductLoginContactAssociation__c lcAsso = new ProductLoginContactAssociation__c();
            lcAsso.ProductLogin__c = login.Id;
            lcAsso.Contact__c = emailContactMap.get(login.Email__c).Id;
            String key = login.Id + ':' + emailContactMap.get(login.Email__c).Id;
            associationMap.put(key,lcAsso);
        }
    }
}