objects/Activity_Status__mdt.object
<CustomObject>
    <fields>
        <fullName>Filter_Name__c</fullName>
        <label>Filter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Value__c</fullName>
        <label>Filter Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity Status</label>
    <pluralLabel>Activity_Status</pluralLabel>
</CustomObject>

objects/Division_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>ACV_Color_Field__c</fullName>
        <description>US 3537066: Includes the name of the divisional field that has the ACV scale color conditional formatting.</description>
        <inlineHelpText>Enter the API name of the formula field that includes the division&apos;s ACV scale color conditional formatting.</inlineHelpText>
        <label>ACV Color Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACV_Field_Name__c</fullName>
        <description>US 3537066: Includes the divisional field name for ACV Scale.</description>
        <inlineHelpText>Enter the API name of the divisional scale ACV field that should be displayed.</inlineHelpText>
        <label>ACV Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Chart__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US-US-4880704: If checked, division custom metadata record does not appear on the pipeline or activity chart.</description>
        <label>Disable Chart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>US 3537066: Name of the division as it should be displayed on the divisional view.</description>
        <inlineHelpText>Enter the division name as it should be displayed.</inlineHelpText>
        <label>Display Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESG_Amount_Field__c</fullName>
        <label>ESG Amount Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Field_Name__c</fullName>
        <description>US 3537066: Includes the Lookup field to account manager for the division.</description>
        <inlineHelpText>Enter the API name of the field that links the divisional account manager to the account.</inlineHelpText>
        <label>Manager Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Color_Field__c</fullName>
        <description>US 3537066: Includes the name of the divisional field that has the nps color conditional formatting.</description>
        <inlineHelpText>Enter the API name of the formula field for the division&apos;s NPS color conditional formatting.</inlineHelpText>
        <label>NPS Color Field</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Field_Name__c</fullName>
        <description>US 3537066: Includes the divisonal field name for NPS Score.</description>
        <inlineHelpText>Enter the API name of the divisional NPS score field.</inlineHelpText>
        <label>NPS Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_Field__c</fullName>
        <description>US-4637975: For the pipeline tab, the opportunity amount field differs for IHS divisions. The field referenced will be used in the code to calculate opportunity amount for pipeline chart.</description>
        <label>Opportunity Amount Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>US 3537066: Indicates the order in which each division should appear.</description>
        <inlineHelpText>Enter the order number. The number controls where the divisional card is displayed in ascending order.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_ID__c</fullName>
        <description>US 3537066: Salesforce organization ID of the division.</description>
        <inlineHelpText>Enter the division&apos;s Salesforce organization ID.</inlineHelpText>
        <label>Org ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Color__c</fullName>
        <description>US 3537066: Includes the color for the divisional stack.</description>
        <inlineHelpText>Enter the hex code for the stack. Ex: FF0000.</inlineHelpText>
        <label>Stack Color</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Division Settings</label>
    <pluralLabel>Division Settings</pluralLabel>
</CustomObject>

objects/Hierarchy_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Column_Number__c</fullName>
        <description>US 3537066: Represents the order in which the columns will appear from left to right. Column number cant be greater than 13</description>
        <inlineHelpText>Represents the order in which the columns will appear from left (1) to right (13).</inlineHelpText>
        <label>Column Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>US 3537066: Column header text that appears in the divisional view.</description>
        <inlineHelpText>Enter the text that should appear as the column header.</inlineHelpText>
        <label>Field Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>US 3537066: Include the API name of the field that should be included in the hierarchy table.</description>
        <inlineHelpText>Enter the API name of the field that should be in the hierarchy table.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hierarchy Settings</label>
    <pluralLabel>Hierarchy Settings</pluralLabel>
</CustomObject>

objects/Product_Family_Filter__mdt.object
<CustomObject>
    <fields>
        <fullName>ESG_Amount_Field__c</fullName>
        <description>US-4880704: If Sustainable1/ESG filter is selected on pipeline chart, the amount displayed will be based on this field.</description>
        <label>ESG Amount Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Display_Name__c</fullName>
        <label>Filter Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Name__c</fullName>
        <label>Filter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Value__c</fullName>
        <label>Filter Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_Field__c</fullName>
        <description>US-4637975: For the pipeline tab, the opportunity amount field differs for IHS divisions. The field referenced will be used in the code to calculate opportunity amount for pipeline chart.</description>
        <label>Opportunity Amount Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Product Family Filter</label>
    <pluralLabel>Product Family Filter</pluralLabel>
</CustomObject>

classes/CreateAndUpdateCustomMetadataTypes.cls
global class CreateAndUpdateCustomMetadataTypes  Implements Schedulable
    {
    public static  Metadata.DeployContainer dmContainer;
    public static boolean performDeployment = false;
    
       global void execute(SchedulableContext sc)
        {
            performUpdates();
        }
        
        @future(callout=true)
        public static void performUpdates(){
             updateDivisionCustomDataTypes();
             updateHierarchyCustomDataTypes();
             updateproductFilterCustomTypes();
             updateActivityStatus();
              if(performDeployment == true && !Test.isRunningTest())
             Id jobId = Metadata.Operations.enqueueDeployment(dmContainer, null);
        }
   
    public static void updateDivisionCustomDataTypes(){
          dmContainer = new Metadata.DeployContainer();
        String query = 'select Active__c,masterLabel,Id,developerName,ACV_Color_Field__c,'
            			+ 'ACV_Field_Name__c,Display_Name__c,Manager_Field_Name__c,'
                        +'NPS_Color_Field__c,NPS_Field_Name__c,Order__c,'
                        +'Org_ID__c,Stack_Color__c,Disable_Chart__c,' +
                'ESG_Amount_Field__c, Label from Division_Settings__mdt';
        List<object> objectResponse = CreateAndUpdateCustomMetadataTypes.performCallout(query);
        if(objectResponse != NULL){
           List<string> fieldsList = new List<String>{'Active__c', 'ACV_Color_Field__c',
                						'ACV_Field_Name__c', 'Display_Name__c',
                                        'Manager_Field_Name__c', 'NPS_Color_Field__c',
                                        'NPS_Field_Name__c', 'Order__c',
                                        'Org_ID__c','Stack_Color__c', 'Disable_Chart__c',
                                        'ESG_Amount_Field__c', 'Label'};
            parseResponse(objectResponse,fieldsList ,'Division_Settings__mdt', query);
            system.debug('--dm--'+dmContainer);
           
             
           
        }
    }
    
     public static void updateHierarchyCustomDataTypes(){
      
        String query = 'select masterLabel,Id,developerName,Column_Number__c,Field_Label__c,'
                        +'Field_Name__c from Hierarchy_Settings__mdt';
        List<object> objectResponse = CreateAndUpdateCustomMetadataTypes.performCallout(query);
        if(objectResponse != NULL){
           List<string> fieldsList = new List<String>{'Field_Label__c', 'Field_Name__c',
                						'Column_Number__c'};
            parseResponse(objectResponse,fieldsList ,'Hierarchy_Settings__mdt', query);
          
        
        }
    }
    
       public static void updateproductFilterCustomTypes(){

           String query = 'select masterLabel,Id,developerName,Order__c,Filter_Value__c, Opportunity_Amount_Field__c, Filter_Display_Name__c, '
                        +'Filter_Name__c, Label, ESG_Amount_Field__c from Product_Family_Filter__mdt';
        List<object> objectResponse = CreateAndUpdateCustomMetadataTypes.performCallout(query);
        if(objectResponse != NULL){
           List<string> fieldsList = new List<String>{'Filter_Value__c', 'Filter_Name__c',
                						'Order__c', 'Opportunity_Amount_Field__c', 'Filter_Display_Name__c', 'ESG_Amount_Field__c', 'Label'};
            parseResponse(objectResponse,fieldsList ,'Product_Family_Filter__mdt', query);
          
        }
    }
        
        
       public static void updateActivityStatus(){

        String query = 'select masterLabel,Id,developerName,Filter_Value__c,'
                        +'Filter_Name__c from Activity_Status__mdt';
        List<object> objectResponse = CreateAndUpdateCustomMetadataTypes.performCallout(query);
        if(objectResponse != NULL){
           List<string> fieldsList = new List<String>{'Filter_Value__c', 'Filter_Name__c'
                				};
            parseResponse(objectResponse,fieldsList ,'Activity_Status__mdt', query);
          
        }
    }
        
        
    
    
    public static List<object> performCallout(string query){
        HttpRequest req = new HttpRequest();
        query = EncodingUtil.urlEncode(query, 'UTF-8');
        req.setEndpoint('callout:Hub_Org/services/data/v51.0/query?q='+query);
        req.setMethod('GET');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        system.debug(res.getBody());
        if(res.getStatusCode() == 200){
            Map<string,object> metadataMap = (Map<string,object>)JSON.deserializeUntyped(res.getBody());
            List<object> metadataRecords = (list<object>)metadataMap.get('records');
            return metadataRecords;
        }
        else{
            return null;
        }
    }
    
    public static void parseResponse(List<object> metadataRecords, List<String> fieldsList, String metadataName, String query ){
        Map<String,sObject> localRecordMap =  new Map<String,sObject>();
        List<sObject> localOrgRecords = (List<sObject>)database.query(query);
        for(sObject o : localOrgRecords)    {
            localRecordMap.put(String.valueOf(o.get('DeveloperName')),o);
        }  
        Boolean isUpdate = false;
        SObjectType objType = ((sobject)(Type.forName('Schema.'+metadataName).newInstance())).getSObjectType();
        DescribeSobjectResult rd = objType.getDescribe();
        for(object externalObj : metadataRecords){
            Map<String,object> externalRecordMap = (Map<String,object>)externalObj;
            if(externalRecordMap != NULL){
                
                Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();
                sObject localRecord = null;
                if(localRecordMap.containsKey(String.valueof(externalRecordMap.get('DeveloperName')))){
                    localRecord = localRecordMap.get(String.valueof(externalRecordMap.get('DeveloperName')));
                    customMetadata.fullName = metadataName+'.'+localRecord.get('DeveloperName');
                    customMetadata.label = String.valueOf(externalRecordMap.get('MasterLabel'));
                }
                else{
                    customMetadata.fullName = metadataName+'.'+String.valueOf(externalRecordMap.get('DeveloperName'));
                    customMetadata.label = String.valueOf(externalRecordMap.get('MasterLabel'));
                }
                
                for(String fieldName : fieldsList){
                    Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
                    if(localRecord == null || (localRecord != null
                        && String.valueOf(localRecord.get(fieldName)) !=  String.valueOf(externalRecordMap.get(fieldName))) ){
                            String fieldType = String.valueOf(rd.fields.getMap().get(fieldName).getDescribe().getType());
                            customField.field = fieldName;
                            if(!externalRecordMap.containsKey(fieldName)){
                                continue;
                            }
                            If(fieldType == 'Boolean'){
                                  customField.value = Boolean.valueOf(externalRecordMap.get(fieldName));
                            }
                            else{
                                  customField.value = String.valueOf(externalRecordMap.get(fieldName));
                            }
                   		  
                            customMetadata.values.add(customField);
                            isUpdate = true;
                     }
                }  
                if(isUpdate == true){
                 	dmContainer.addMetadata(customMetadata);
                    performDeployment = true;
                }
            }
        }        
    }
}