objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Opportunity</description>
        <inlineHelpText>Opportunity number of the publication fee to which this claim is related</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/FieldServiceActivityOpportunity__c.object
<CustomObject>
    <description>SFDC1-10104 : Tracks Opportunity for the Field Service Activities.</description>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-10104 : This field will hold the value of Field Service Activity</description>
        <inlineHelpText>Please enter Field Service Activity.</inlineHelpText>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Opportunities</relationshipLabel>
        <relationshipName>FieldServiceActivityOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-10104 : This field will hold the value of Opportunity</description>
        <inlineHelpText>Please enter Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Field Service Activity Opportunities</relationshipLabel>
        <relationshipName>FieldServiceActivityOpportunities1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Field Service Activity Opportunity</label>
    <nameField>
        <displayFormat>FSAOPP-{00000}</displayFormat>
        <label>Field Service Activity Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FirstYearValue__c</fullName>
        <description>SFDC1-4275 First year total price value rolled up from Opportunity Products</description>
        <inlineHelpText>First Year Contract Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-166.
Associated opportunity for this Field Service Activity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryOpportunityName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5786 Add Primary Opportunity Name to FSA Records</description>
        <inlineHelpText>It reflects the highest value opportunity (using first year value converted) from the list of opportunities added in the related section under field service activity opportunities</inlineHelpText>
        <label>Primary Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Field Service Activities (Primary Opportunity Name)</relationshipLabel>
        <relationshipName>FieldServiceActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FieldServiceActivityOpportunityMethods.cls
public class FieldServiceActivityOpportunityMethods {

    /*-----------------------------
    @Author: Shikhar Singh
    @Date: 03 June 2022
    @Description: FDC-5786 Update Opportunity on FSA based on linked FSAOpportunity with highest value
    @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    @return: Void
    -----------------------------*/
    public static void updateOpportunityOnFsa(TriggerParameters tp) {
        Set<Id> fsaIds = new Set<Id>();
        for(FieldServiceActivityOpportunity__c fsao: (List<FieldServiceActivityOpportunity__c>)tp.newList) {
            fsaIds.add(fsao.FieldServiceActivity__c);
        }
        
        // Get all FSA records idenitified above and fetch their highest value oppy
        List<WorkOrder> listOfFsaRecords = [Select Id,(SELECT Id,Opportunity__c from FieldServiceActivityOpportunities__r ORDER BY Opportunity__r.FirstYearValue__c DESC LIMIT 1)
                                            FROM WorkOrder WHERE ID IN: fsaIds];
        
        System.debug(listOfFsaRecords);
        
        //Create a Map of ID,ID with FSAId and OppyID
        Map<Id,Id> mapOfFsaFsao = new Map<Id,Id>();
        for(WorkOrder wo: listOfFsaRecords) {
            mapOfFsaFsao.put(wo.Id,wo.FieldServiceActivityOpportunities__r[0].Opportunity__c);
        }
  
        //Iterate over that map and update FSA record with highest value oppy
        List<WorkOrder> listOfWorkOrders = new List<WorkOrder>();
        for(Id mapIt1: mapOfFsaFsao.keySet()) {
        		listOfWorkOrders.add((new WorkOrder(Id= mapIt1,PrimaryOpportunityName__c=mapOfFsaFsao.get(mapIt1))));    
        }
        
        if(listOfWorkOrders.size()>0) {
            update listOfWorkOrders;
        }        
    }
    
    /*-----------------------------
    @Author: Shikhar Singh
    @Date: 03 June 2022
    @Description: SFDC-5786 Update Opportunity on FSA based on linked FSAOpportunity with highest value after deletion of FSAO Record
    @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    @return: Void
    -----------------------------*/
    public static void deleteOpportunityOnFsa(TriggerParameters tp) {
        Set<Id> fsaIds = new Set<Id>();
        for(FieldServiceActivityOpportunity__c fsao: (List<FieldServiceActivityOpportunity__c>)tp.oldList) {
            fsaIds.add(fsao.FieldServiceActivity__c);
        }
        
        // Get all FSA records idenitified above and fetch their highest value oppy
        List<WorkOrder> listOfFsaRecords = [Select Id,(SELECT Id,Opportunity__c from FieldServiceActivityOpportunities__r ORDER BY Opportunity__r.FirstYearValue__c DESC LIMIT 1)
                                            FROM WorkOrder WHERE ID IN: fsaIds];
        
        System.debug(listOfFsaRecords);
        
        //Create a Map of ID,ID with FSAId and OppyID
        Map<Id,Id> mapOfFsaFsao = new Map<Id,Id>();
        //Create a List to capture records with 0 FSAO left
        List<Id> blankWorkOrders = new List<Id>();
   		
        //Iterate over list of records and add to map or list accordingly as per above mentioned criteria
        for(WorkOrder wo: listOfFsaRecords) {
           	if(wo.FieldServiceActivityOpportunities__r.size()>0) {
            	mapOfFsaFsao.put(wo.Id,wo.FieldServiceActivityOpportunities__r[0].Opportunity__c);
            } else if (wo.FieldServiceActivityOpportunities__r.size() == 0) {
				blankWorkOrders.add(wo.Id);                
            }
        }    
  
        //Iterate over that map and update FSA record with highest value oppy
        List<WorkOrder> listOfWorkOrders = new List<WorkOrder>();
        for(Id mapIt1: mapOfFsaFsao.keySet()) {
        		listOfWorkOrders.add((new WorkOrder(Id= mapIt1,PrimaryOpportunityName__c=mapOfFsaFsao.get(mapIt1))));    
        }
        
        //Iterate over the list of blank records and update FSA record with blank oppy
        for(Id workO: blankWorkOrders) {
        		listOfWorkOrders.add((new WorkOrder(Id= workO,PrimaryOpportunityName__c=null)));    
        }
       
        if(listOfWorkOrders.size()>0) {
            update listOfWorkOrders;
        }        
    }

}