objects/AdditionalCaseTypeLinking__c.object
<CustomObject>
    <description>SFDC1-6246 Used in Additional Case Fields object process to identify the record type of additional case fields</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6246: Additional case fields record should get spawned based on Product Group record</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Additional Case Type Linkings</relationshipLabel>
        <relationshipName>AdditionalCaseTypeLinkings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Case Type Linking</label>
    <nameField>
        <displayFormat>ACTL-{0000}</displayFormat>
        <label>Additional Case Type Linking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Case Type Linkings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>Case.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MSFPlatform__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDC1-281 Used for setting Live Agent Product List for MSF</description>
    <label>MSF Platform</label>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestLiveChatPostChatController.cls
/*--------------------------------------------------------------------------------------------------------------------
    Author:        Akshay Dogra
    Company:       
    Description:   TestLiveChatPostChatController - test class for LiveChatPostChatFormController
    History
    21/03/2022    First Release
----------------------------------------------------------------------------------------------------------------------*/
@IsTest
private class TestLiveChatPostChatController {
    
    /*
    * @author: Akshay Dogra
    * @date: 15 March 2022
    * @description: SFDC1-834, SFDC1-281 LiveChatPostChatController - visualforce controller for LiveChatPostChat page.
    * @companyname:
    */ 
    @IsTest
    private static void liveChatPostChat() {
        
        LiveChatPostChatController.LiveAgentInput lAI = new LiveChatPostChatController.LiveAgentInput('contactEmail',null,null,null,null,null);
        
        String str = '[{"label": "contactEmail","value": "jon@example.com","LiveAgentInput": [{"label": "contactEmail","value": "contactEmail","contactEmail": "abc@abc.com","msfProductCode": "123","isExactMatchable": true}],"transcriptFields": [ "c__EmailAddress"],"displayToAgent": true},{"label": "msfProductCode","value": "jon@example.com","LiveAgentInput": [{"label": "contactEmail","value": "contactEmail","contactEmail": "abc@abc.com","msfProductCode": "123","isExactMatchable": true}],"transcriptFields": [ "c__EmailAddress"],"displayToAgent": true},{"label": "buttonOrigin","value": "jon@example.com","LiveAgentInput": [{"label": "contactEmail","value": "contactEmail","contactEmail": "abc@abc.com","msfProductCode": "123","isExactMatchable": true}],"transcriptFields": [ "c__EmailAddress"],"displayToAgent": true}]';
        String ck = 'TEST123';
        String body = '<p align="center">Chat Started: Tuesday, July 25, 2017, 01:44:14 (+0530)</p><p align="center">Chat Origin: IHSMarkitSupportMCS</p><p align="center">Agent Uttam A</p>( 2s ) Uttam A: Hello Uttam Arya, welcome to IHS Markit live chat support, my name is Uttam how can I help you today?<br>';
        
        Account ac = TestUtility.createTestAccount('Test Post Chat',true);
        Contact myContact1 = TestUtility.createContact(ac.Id, 'akshay.dogra@test.com',true, 'Akshay', 'Dogra');
 		ProductGroup__c pg = TestUtility.createProductGroup('Delivery', true);
        
        AdditionalCaseTypeLinking__c aCaseTypeLinkingNRG = TestUtility.createAdditionalCaseTypeLinking('Customer Care','NRG',false);
        aCaseTypeLinkingNRG.ProductGroup__c = pg.Id;
        insert aCaseTypeLinkingNRG;
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        
        Case testCase = TestUtility.createCase(caseRecordTypeId, ac.Id, myContact1.Id,  userInfo.getUserId(), 'Test subject Live Chat Test', false);
        testCase.ProductGroup__c = pg.Id;
        insert testCase;
        
        PageReference pageRef = Page.LiveChatPostChat;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('chatKey','Thank you');
        pageRef.getParameters().put('chatDetails',str);
        
        LiveChatPostChatController controller = new LiveChatPostChatController();
        controller.email = 'akshay.dogra@test.com';
        controller.emailExist = false;
        controller.chatKey = ck;
        controller.sendTranscript = 'Yes';
        controller.buttonOrigin = 'MSF';
        controller.msfProductCode = 'SFP';
        
        PageReference result1 = controller.redirect();
        
        LiveChatVisitor v = new LiveChatVisitor();
        insert v;
        LiveChatTranscript t = new LiveChatTranscript(ChatKey = ck, LiveChatVisitorId = v.Id, body = body);
        t.CaseId = testCase.Id;
        insert t;

        MSFPlatform__c c1= TestUtility.createMSFPlatform('SFT', 'API', ' Excel Toolkit', true);
        MSFPlatform__c c2= TestUtility.createMSFPlatform('SFP', 'Web Application', ' Web Portal', true);
        
        PageReference result = controller.submit();
        
        controller.sendTranscript = 'No';
        controller.submit();
        
        // verify that page fails without parameters
        System.assertEquals(Page.livechatpostchat.getURL(), result.getURL().split('\\?')[0]); 
    }  
}