objects/AdditionalOpportunityFields__c.object
<CustomObject>
    <description>SFDC1-6937:  This custom object is needed to hold fields for the Opportunity.</description>
    <fields>
        <fullName>OpportunityReference__c</fullName>
        <description>SFDC1-6937 This field will link back this Additional Opportunity Fields to the Opportunity its associated.</description>
        <inlineHelpText>Please select the Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Additional Opportunity Fields</relationshipLabel>
        <relationshipName>AdditionalOpportunityFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Opportunity Fields</label>
    <nameField>
        <label>Additional Opportunity Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Opportunity Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AdditionalOpportunityFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6937: Additional Opportunity Fields record associated to the Opportunity</description>
        <inlineHelpText>This field holds the Additional Opportunity Fields</inlineHelpText>
        <label>Additional Opportunity Fields</label>
        <referenceTo>AdditionalOpportunityFields__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>SFDC-1103 This field captures the budget range for the opportunity</description>
        <inlineHelpText>Please provide the Budget Range.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>100,000 - 500,000</fullName>
                </value>
                <value>
                    <fullName>500,000 - 1,000,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 1,000,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadyForProcessingContractExist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5701, this will be set to true by the process builder on Contract whenever Contract Status changes to &quot;Ready For Processing&quot;.</description>
        <label>Ready For Processing Contract Exist?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestAdditionalOpportunityFieldsMethods.cls
//-----------------------------
// @author: Sonam Raju
// @date: 8 Mar 2018
// @param: NA
// @description: Test class for Additional Opportunity Fields trigger methods 
// @return: NA
// @Last Modified By : Sruti Srivastava
// @Last Modified Description : SFDC1-8090- Added test method testpopulateAdditionalFieldsLookupInOpportunityExceptionScenario
// @Last Modified Date : 27-Apr-2018
//-----------------------------

@isTest
private class TestAdditionalOpportunityFieldsMethods {

    //-----------------------------
    // @author: Sonam Raju
    // @date: 8 Mar 2018
    // @param: NA
    // @description: Test method for Additional Opportunity Fields trigger methods populateAdditionalFieldsLookupInOpportunity on insert.This also covers the functionality available in method setOpportunityAdditionalFieldsObject in OpportunityMethods Class.
    // @return: NA
    //-----------------------------
    @isTest private static void testpopulateAdditionalFieldsLookupInOpportunity() {
        
        Account a = TestUtility.createTestAccount('Account populateAdditionalFieldsLookupInOpportunity', true);
        Contact c = TestUtility.createContact(a.Id,'testaof@aof.com',true,'Test','populateAdditionalFieldsLookupInOpportunity');
        
        Test.Starttest();
        Opportunity opp = TestUtility.createOpportunity(a.Id, 'Testing AoF Creation',true);
        
        // Checking If New business Opportunity creation creates Additional Opportunity Field record
        list <AdditionalOpportunityFields__c> testAOFResult = [Select Id from AdditionalOpportunityFields__c where OpportunityReference__c= :opp.Id];
        System.assertEquals(1, testAOFResult.size());
        
        //Check If Additional Opportunity Field Record is updated in the AdditionalOpportunityFields__c on Opportunity
        list <Opportunity> testOpptyResult = [Select Id, AdditionalOpportunityFields__c from Opportunity where Id= :opp.Id];
        System.assertEquals(testAOFResult[0].Id,testOpptyResult[0].AdditionalOpportunityFields__c);
        
        Test.Stoptest();
    }
    
    //-----------------------------
    // @author: Sruti Srivastava
    // @date: 27th April 2018
    // @param: NA
    // @description: Test method for covering exception scenario
    // @return: NA
    //-----------------------------
    @isTest private static void testpopulateAdditionalFieldsLookupInOpportunityExceptionScenario() {
        
        //Creating test data
        User salesRepUser = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testContact123@ihsmarkit.com',true);
        Account testAccount = TestUtility.createTestAccount('Account populateAdditionalFieldsLookupInOpportunity', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit1@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        Id standardId = Test.getStandardPricebookId();
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity','USD', true,
                                                                  'No', 'No', 'Yes', 'No', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        //start test 
        
        System.runAs(salesRepUser) {
            Opportunity opp = TestUtility.createOpportunity(testAccount.Id, 'Testing AoF Creation', true);
            OpportunityContactRole ocr = new OpportunityContactRole();
            ocr.ContactId = testContact.Id;
            ocr.OpportunityId = opp.Id;
            ocr.IsPrimary = TRUE;
            ocr.Role = 'Decision Maker';
            insert ocr;
            
            OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(opp.Id, testPBE, true);
            
            // Checking If New business Opportunity creation creates Additional Opportunity Field record
            System.assertEquals(1, [Select count() from AdditionalOpportunityFields__c ]);
            Test.Starttest();            
                //Updating Opportunity to closed status, so it doesn't allow any modification
                opp.StageName = '5-Contracting';
                opp.ContractId = contract1.id;
                opp.ContractStartDate__c = System.today();
                opp.ContractEndDate__c = System.today();
                opp.ActivityCreated__c = true;
                opp.ReadyForProcessingContractExist__c = true;
                opp.CloseDate = System.today()-30;
                opp.BudgetRange__c = '25,000-50,000';
                
                update opp;
                    
                // Deleting the Contact Role to get Error on Opportuntiy update
                List<OpportunityContactRole> listOppContactRole = [select ID from OpportunityContactRole where OpportunityId = :Opp.Id];
                delete listOppContactRole;
                System.assertEquals(0, [Select count() from OpportunityContactRole Where OpportunityId =: opp.Id ]);
                
                try {                
                    list<AdditionalOpportunityFields__c> testAOFResult = new list <AdditionalOpportunityFields__c> {new AdditionalOpportunityFields__c(Name = 'Test', OpportunityReference__c = opp.Id)};
                    insert testAOFResult;
                }
                catch (Exception e) {
                    System.assertEquals(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'), true);    
                }
                
            Test.Stoptest();
            //Check If Additional Opportunity Field Record has failed, count should be one 
            System.assertEquals(2, [Select count() from AdditionalOpportunityFields__c where OpportunityReference__c= :opp.Id]);
        }
    }
}