objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordId__c</fullName>
        <description>SFDC-1763: Id of record that resulted in error</description>
        <inlineHelpText>Id of record that resulted in error</inlineHelpText>
        <label>Log Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordName__c</fullName>
        <description>SFDC-1763: Name of record that resulted in error</description>
        <label>Log Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Auto-Renewal</inlineHelpText>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Contract Start Date</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4728: Create Auto Renewal field on Opportunity that will be updated from Contract.</description>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoesThisAutoRenewalHaveChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field includes renewal details of opportunity. (JIRA story SFDC1-556)</description>
        <inlineHelpText>Specify if Auto Renewal has any changes.</inlineHelpText>
        <label>Does this Auto Renewal Have Changes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstYearValue__c</fullName>
        <description>SFDC1-4275 First year total price value rolled up from Opportunity Products</description>
        <inlineHelpText>First Year Contract Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsThisRenewalAutoClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6811 This checkbox is set to true automatically when an auto renewal opportunity is auto closed</description>
        <inlineHelpText>This checkbox is checked automatically when an auto renewal opportunity is auto closed</inlineHelpText>
        <label>Is this Renewal Auto-Closed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store primary contact name at Opportunity record level.</description>
        <inlineHelpText>To store primary contact name at Opportunity record level.</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchAutoRenewalAutoClose.cls
//-----------------------------
// @author: Paras Dhingra
// @date: 22 April 2020
// @description: SFDC-2877 Decommision the workflow and move the Autorenewals Auto close logic to batch to prevent any gaps
// @Last Modified By : Harshit Singhal
// @Last Modified Date : 07 Sep 2020
// @Last Modified Description: SFDC-3352 Added code to set boolean variable isExecutingBatchAutoRenewalAutoClose to true/false in execute method. This is done so that OM case creation logic in opp trigger is not skipped due to partial DML success in batch.
//------
global  class BatchAutoRenewalAutoClose implements Database.Batchable<sObject>,Database.Stateful {
    public Boolean batchHasErrors = false;
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id renewalRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        if (String.isBlank(query)) {
            query = 'SELECT Id, StageName, Name,CloseDate  FROM Opportunity '+ 
                    'WHERE AutoRenewal__c=true '+
                    'AND isClosed=false '+
                    'AND DoesThisAutoRenewalHaveChanges__c=false '+
                    'AND RecordtypeID=:renewalRecordTypeId '+
                    'AND PrimaryContact__c!=null '+
                    'AND ContractStartDate__c!=null '+
                    'AND (FirstYearValue__c=null OR FirstYearValue__c<USD100000) '+
                    'AND (ContractStartDate__c = NEXT_N_DAYS:14 OR ContractStartDate__c <= Today) ' ;
        }
            
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Opportunity> scope) {        
        try {
            GlobalVariables.isExecutingBatchAutoRenewalAutoClose = true;
            System.debug('--Opportunity scope--'+scope);
            List<Opportunity> lstOpportunityToUpdate = new List<Opportunity>();
            for(Opportunity oppy: scope) {//check converted currency <100,000
                    oppy.stageName = '6W-Renewal Won';
                    oppy.IsThisRenewalAutoClosed__c = true;
                    oppy.CloseDate = Date.today();
                    lstOpportunityToUpdate.add(oppy);
            }
            if(lstOpportunityToUpdate!=null && !lstOpportunityToUpdate.isEmpty()) {
                System.debug('--Opportunity list to update--'+lstOpportunityToUpdate);
                //update lstOpportunityToUpdate;
                Database.SaveResult[] srList = Database.update(lstOpportunityToUpdate, false);
                List<ApexLogger__c> logRecList = new List<ApexLogger__c>();                
                Integer counter = 0;
                for (Database.SaveResult sr : srList) {                    
                    if (!sr.isSuccess()) {                        
                        for(Database.Error err : sr.getErrors()) {
                            logRecList.add(new ApexLogger__c(ClassName__c='BatchAutoRenewalAutoClose', FunctionName__c='Execute', LogRecordId__c=lstOpportunityToUpdate[counter].Id, LogRecordName__c=lstOpportunityToUpdate[counter].Name, ErrorDescription__c=err.getMessage()));
                        }
                    }
                    counter++;
                }
                //Insert Error Log records
                if(logRecList.size() > 0) {
                    batchHasErrors = true;
                    insert logRecList;
                }
            }

            
        } catch(Exception ex) {
            System.debug('--Exception caught in batch--'+ex.getMessage());
            batchHasErrors = true;
            UtilityClass.createApexLogRecord(ex, 'BatchAutoRenewalAutoClose', 'Execute');       
        }
        finally {
            GlobalVariables.isExecutingBatchAutoRenewalAutoClose = false;
        }
    }
    global void finish(Database.BatchableContext BC) { 
        System.debug(LoggingLevel.INFO, 'BatchAutoRenewalAutoClose BATCH FINISH()');
        //Send Email if Errors in batch processing
        if(batchHasErrors) {            
            String[] toAddresses = new String[] {'paras.dhingra@ihsmarkit.com'};
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddresses);
            mail.setReplyTo(System.Label.OpptyPrimaryContactBatchEmail);            
            mail.setSubject('paras.dhingra@ihsmarkit.com');
            mail.setPlainTextBody('Please see Apex Log records to view errors of BatchAutoRenewalAutoClose batch class job in detail.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}