objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Stores the Error Message which is either passed by developer  else derived from Exception.</description>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LogRecordJson__c</fullName>
        <description>Details about Object on which is passed to Exception Framework</description>
        <label>Log Record Json</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2624 Internal Business Segment field for Sales Product Reporting</description>
        <inlineHelpText>For Sales Product Reporting</inlineHelpText>
        <label>Internal Business Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesPlan__c.object
<CustomObject>
    <description>SFDC-5363 The object is created to store the Sales Plan details in Salesforce</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SFDC-5363 Field to store the plan amount for the product</description>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Businessline associated with the Plan</description>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-5363 Field to store the Internal business Segment associated with the plan</description>
        <label>Internal Business Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlySalesPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Sales Plan</label>
        <referenceTo>SalesPlan__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <description>SFDC-5363 Field to store the plan start date</description>
        <label>Sales Plan Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroupName__c</fullName>
        <label>Product Group Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Product Group associated with the Plan</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Sub business line associated with the plan</description>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Non-Recurring</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Lo</fullName>
                    <isActive>false</isActive>
                    <label>Lo</label>
                </value>
                <value>
                    <fullName>NR</fullName>
                    <isActive>false</isActive>
                    <label>NR</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <isActive>false</isActive>
                    <label>R</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Plan</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Sales Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubBusinessLine__c.object
<CustomObject>
    <description>SFDC1-2170 : This holds Sub Business Line related to Products</description>
    <label>Sub Business Line</label>
    <nameField>
        <label>Sub Business Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchCreateDailySalesPlan.cls
/*  @author: Akash Punera
*   @date: 07 Mar 2022
*   @description: Batch class to Create daily Sales Plan records from monthly data
*/
public class BatchCreateDailySalesPlan implements Database.Batchable<sObject>,Database.Stateful {
    public boolean batchHasErrors = false;
    public map<String, set<String>> mapErrorRecord= new map<String, set<String>>();
    public set<String> errorLog= new set<String>();
    public String query;
    public Map<integer,integer> mapMonthToNumberOfDays;
    public Map<string,product2> mapProductGroupToProduct;
    public string subBusinesslineToExclude = system.label.SubBusinessLinesToExclude;
    
    /*  @author: Akash Punera
	*   @date: 7 Mar 2022
	*   @description: Initiate batch with Sales plan query and product map to populate hierarchy
	*/
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Map product group to product
        mapProductGroupToProduct = new map<String,product2>();
        set<String> setProductGroupsMapped = new Set<String>();
        for(Product2 objPro : [SELECT 	id, productGroup__r.name, businessLine2__r.name, SubBusinessLine__r.name, InternalBusinessSegment__c
                               FROM 	Product2
                               WHERE	isActive = true AND subbusinessline__c != null AND businessline2__c != null AND productgroup__c != null
                               ORDER BY createdDate Desc
                               LIMIT 50000]) {
                                   if(objPro.productGroup__c != null && !setProductGroupsMapped.contains(objPro.productGroup__r.name.toLowerCase()) && !subBusinesslineToExclude.containsIgnoreCase(objPro.SubBusinessLine__r.name)) {
                                       setProductGroupsMapped.add(objPro.productGroup__r.name.toLowerCase());
                                       mapProductGroupToProduct.put(objPro.productGroup__r.name.toLowerCase(), objPro);
                                   }
                               }
        //Populate MonthToNumberOfDays Map
        mapMonthToNumberOfDays = new Map<integer,integer>{ 1=>31, 2=>28, 3=>31, 4=>30, 5=>31, 6=>30, 7=>31, 8=>31, 9=>30, 10=>31, 11=>30, 12=>31};
        if(Date.isLeapYear(system.now().year())) {
           mapMonthToNumberOfDays.put(2, 29);
        }
        //Query all Sales Plan Records
        query = 'SELECT Id, Type__c, SubBusinessLine__c, Region__c, ProductGroup__c, ProductGroupName__c, Period__c, InternalBusinessSegment__c, ExternalId__c, BusinessLine__c, Amount__c FROM SalesPlan__c where MonthlySalesPlan__c = null';
        
        return Database.getQueryLocator(query);
    }
    
    /*  @author: Akash Punera
	*   @date: 7 Mar 2022
	*   @description: Batch execute to iterate on Sales plan records and process and update hierarchy
	*	@param: List of Sales Plan records to be updated
	*/
    public void execute(Database.BatchableContext BC, List<SalesPlan__c> scope) {
        try {
            List<SalesPlan__c> lstSalesPlanToUpsert = new List<SalesPlan__c>();
            for(SalesPlan__c objSp : scope) {
                lstSalesPlanToUpsert.add(updateSalesPlanFields(objSp));
                lstSalesPlanToUpsert.addAll(createDailyPlan(objSp));
            }
            
            upsertSalesPlan(lstSalesPlanToUpsert);

            
        } catch(Exception ex) {
            System.debug('Exception caught in batch'+ex.getMessage());
            UtilityClass.createApexLogRecord(ex, 'BatchCreateDailySalesPlan', 'Execute');       
        }
        
    }
    
    /*  @author: Akash Punera
	*   @date: 14 Mar 2022
	*   @description: Batch finish method to log errors if any during execution
	*/
    public void finish(Database.BatchableContext BC) { 
        System.debug(LoggingLevel.INFO, 'BatchCreateDailySalesPlan batch completed');
        if(batchHasErrors) {
            List<ApexLogger__c> apexloggerList= new List<ApexLogger__c>();
            for(String err:mapErrorRecord.keySet()) {
                List<String> errorvalues= new List<String>(mapErrorRecord.get(err));
                String recordIds=String.join(errorvalues,',').trim();
                Integer size= mapErrorRecord.get(err).size();
                String errormessage= 'Total records failed: '+size;
                ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='BatchCreateDailySalesPlan',ErrorDescription__c=err,LogRecordJson__c=recordIds,ErrorMessage__c=errormessage);
                apexloggerList.add(apexLogRecord);
            }
            insert apexloggerList;
            
        }
    }
    
    /*  @author: Akash Punera
	*   @date: 14 Mar 2022
	*   @description: Method to update hierarchy in Sales plan record based on hierarchy from active Product
	*	@param: Sales Plan Object to be updated with product hierarchy
	*/
    public SalesPlan__c updateSalesPlanFields(SalesPlan__c objSP) {
        if(mapProductGroupToProduct.containsKey(objSp.ProductGroupName__c.toLowerCase())) {
            Product2 pro = mapProductGroupToProduct.get(objSp.ProductGroupName__c.toLowerCase());
            objSp.BusinessLine__c = pro.businessline2__c;
            objSp.subBusinessLine__c = pro.subbusinessline__c;
            objSp.InternalBusinessSegment__c = pro.InternalBusinessSegment__c;
            objSp.ProductGroup__c = pro.ProductGroup__c;
        }
        return objSp;
    }
    
    /*  @author: Akash Punera
	*   @date: 14 Mar 2022
	*   @description: Method to Create daily sales plan from monthly plan data
	*	@param: Monthly Sales Plan Object
	*/
    public list<SalesPLan__c> createDailyPlan(SalesPlan__c objSp) {
        List<SalesPlan__c> lstSalesPlanToUpsert = new List<SalesPlan__c>();
        if(objSp.Period__c != null) {
            integer numberOfDays = mapMonthToNumberOfDays.get(objSp.Period__c.month());
            for(integer i = 1; i <= mapMonthToNumberOfDays.get(objSp.Period__c.month()) ; i++) {
                SalesPlan__c dailyPlan = new SalesPlan__c();
                dailyPlan.Type__c = objSp.type__c;
                dailyPlan.SubBusinessLine__c = objSp.SubBusinessLine__c;
                dailyPlan.Region__c = objSp.Region__c;
                dailyPlan.ProductGroup__c = objSp.ProductGroup__c;
                dailyPlan.ProductGroupName__c = objSp.ProductGroupName__c;
                dailyPlan.Period__c = Date.newInstance(objSp.Period__c.year(), objSp.Period__c.month(), i);
                dailyPlan.InternalBusinessSegment__c = objSp.InternalBusinessSegment__c;
                dailyPlan.ExternalId__c = objSp.ExternalId__c+'_'+i;
                dailyPlan.BusinessLine__c = objSp.BusinessLine__c;
                dailyPlan.Amount__c = objSp.Amount__c/numberOfDays;     
                dailyPlan.MonthlySalesPlan__c = objSp.id;
                lstSalesPlanToUpsert.add(dailyPlan);
            }
        }
        return lstSalesPlanToUpsert;
    }
    
    /*  @author: Akash Punera
	*   @date: 14 Mar 2022
	*   @description: Method to upsert Sales Plan records
	*	@param: List of Sales plan records to be upserted
	*/
    public void upsertSalesPlan(List<SalesPlan__c> lstSalesPlanToUpsert) {
        if(lstSalesPlanToUpsert.size() > 0) {
                Database.upsertResult[] urList = database.upsert(lstSalesPlanToUpsert, salesPlan__c.ExternalId__c, false);
                Integer counter=0;
                for (Database.upsertResult ur : urList) {                    
                    if (!ur.isSuccess()) {                        
                        for(Database.Error err : ur.getErrors()) {
                            String error= err.getMessage();
                            batchHasErrors = true;
                            errorLog.add(err.getMessage());
                            if(!mapErrorRecord.containsKey(error)) {
                                mapErrorRecord.put(error, new set<String>());
                            }
                            mapErrorRecord.get(error).add(lstSalesPlanToUpsert[counter].Id);
                        }
                    }
                    counter++;
                }
            }
    }
}