objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordId__c</fullName>
        <description>SFDC-1763: Id of record that resulted in error</description>
        <inlineHelpText>Id of record that resulted in error</inlineHelpText>
        <label>Log Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordName__c</fullName>
        <description>SFDC-1763: Name of record that resulted in error</description>
        <label>Log Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Id of Logged in User.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Apex_Logger</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quota__c.object
<CustomObject>
    <description>SFDC-4105:  Quota Import &amp; Assignment</description>
    <fields>
        <fullName>AllManagers__c</fullName>
        <label>All Managers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SharedHierarchy__c</fullName>
        <description>SFDC-4930 Hierarchy of users manually shared via shared quota object</description>
        <label>Shared Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quota Database</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SharedQuota__c.object
<CustomObject>
    <description>SFDC-4930 Share managers quota outside of quota hierarchy</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>SFDC-4930 flag to mark sharing record as valid and active</description>
        <inlineHelpText>Only active records will be considered for quota sharing.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShareWithUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who will be able to see the additional quota and actual records</description>
        <label>Share with User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SharedQuotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserQuota</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shared Quota</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Shared Quota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchUpdateQuotaHierarchy.cls
/*  @author: Akash Punera
*   @date: 04 Jul 2021
*   @description: Batch class to update All Managers field on Quota records with latest user info
*/
global class BatchUpdateQuotaHierarchy implements Database.Batchable<sObject>,Database.Stateful {
    public String query;
    public Map<String,String> mapEmployeeIdToName;
    public Map<String,List<String>> mapQuotaToShare;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        mapEmployeeIdToName = new Map<String,String>();
        mapQuotaToShare = new Map<String, List<String>>();
        
        //Get all users and create employeeNumber to Name map
        for(User uObj : [SELECT employeeNumber__c, Name 
                         FROM User
                         WHERE employeeNumber__c != '' ]) {
                             mapEmployeeIdToName.put(uObj.employeeNumber__c,uObj.Name);
                         }
        //SFDC-4930 create shared quota map
        createSharedQuotaMap();
        //Query all Quota Records
        query = 'SELECT Id, Name, AllManagers__c, hierarchy__c, SharedHierarchy__c FROM Quota__c where source__c = \'Quota Database\' ';

        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Quota__c> scope) {
        try {
            List<Quota__c> lstQuotaToUpdate = new List<Quota__c>();
            
            //Update manager names based on hierarchy
            for(Quota__c qObj : scope) {
                //SFDC-4930 check and update custom hierarchy
                qObj = updateCustomHierarchy(qObj);
                
                String managerNames = '';
                if(qObj.hierarchy__c != null){
                    for(String mId : qObj.hierarchy__c.split(';')) {
                        if(String.isNotBlank(mId)){
                            managerNames += mapEmployeeIdToName.get(mId)+';';
                        }
                    }
                    qObj.AllManagers__c = managerNames;
                    lstQuotaToUpdate.add(qObj);
                } 
            }
            if(lstQuotaToUpdate!=null && !lstQuotaToUpdate.isEmpty()) {
                Database.SaveResult[] srList = Database.update(lstQuotaToUpdate, false);
                List<ApexLogger__c> logRecList = new List<ApexLogger__c>();                
                Integer counter = 0;
                for (Database.SaveResult sr : srList) {                    
                    if (!sr.isSuccess()) {                        
                        for(Database.Error err : sr.getErrors()) {
                            logRecList.add(new ApexLogger__c(ClassName__c='BatchUpdateQuotaHierarchy', FunctionName__c='Execute', LogRecordId__c=lstQuotaToUpdate[counter].Id, LogRecordName__c=lstQuotaToUpdate[counter].Name, ErrorDescription__c=err.getMessage()));
                        }
                    }
                    counter++;
                }
                //Insert Error Log records
                if(logRecList.size() > 0) {
                    insert logRecList;
                }
            }

            
        } catch(Exception ex) {
            System.debug('Exception caught in batch'+ex.getMessage());
            UtilityClass.createApexLogRecord(ex, 'BatchUpdateQuotaHierarchy', 'Execute');       
        }
        
    }
    global void finish(Database.BatchableContext BC) { 
        System.debug(LoggingLevel.INFO, 'BatchUpdateQuotaHierarchy batch completed');
    }
    
    /*  @author: Akash Punera
    *   @date: 05 Apr 2022
    *   @description: SFDC-4930 Method to create map of users to share quota records with
    */
    public void createSharedQuotaMap() {
        //Get all Shared Quota records
        for(SharedQuota__c sQuota : [SELECT user__r.employeeNumber__c, shareWithUser__r.employeeNumber__c 
                                     FROM 	SharedQuota__c
                                     WHERE 	active__c = true]) {
            if(mapQuotaToShare.containsKey(sQuota.user__r.employeeNumber__c)) {
                mapQuotaToShare.get(sQuota.user__r.employeeNumber__c).add(sQuota.shareWithUser__r.employeeNumber__c);
            }else {
                mapQuotaToShare.put(sQuota.user__r.employeeNumber__c, new list<STring>{sQuota.shareWithUser__r.employeeNumber__c});
            }            
        }
        system.debug('mapQuotaToShare '+mapQuotaToShare);
    }
    
     
    /*  @author: Akash Punera
    *   @date: 05 Apr 2022
    *   @description: SFDC-4930 Method to update custom hierarchy on quota
    */
    public quota__c updateCustomHierarchy(quota__c qObj) {
        //clear existing sharings if any
        if(String.isnotblank(qObj.SharedHierarchy__c)) {
            for(string employeeToRemove : qObj.sharedHierarchy__c.split(';')) {
                qObj.Hierarchy__c = qObj.Hierarchy__c.replace(employeeToRemove,'').replace(';;',';');
            }
            qObj.SharedHierarchy__c = '';
        }
        
        //iterate on all shared quota records
        for(String mId : mapQuotaToShare.keySet()) {
            if(qObj.hierarchy__c.contains(mId) && (String.isblank(qObj.SharedHierarchy__c) || !qObj.SharedHierarchy__c.contains(mId))) {
                for(String userId : mapQuotaToShare.get(mId)) {
                    if(String.isblank(qObj.SharedHierarchy__c)) {
                    	qObj.SharedHierarchy__c = userId+';';    
                    }else {
                        qObj.SharedHierarchy__c += userId+';';
                    }
                	qObj.Hierarchy__c += userId+';';   
                }
            }
        }
        return qObj;
    }
}