objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordId__c</fullName>
        <description>SFDC-1763: Id of record that resulted in error</description>
        <inlineHelpText>Id of record that resulted in error</inlineHelpText>
        <label>Log Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordName__c</fullName>
        <description>SFDC-1763: Name of record that resulted in error</description>
        <label>Log Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>SFDC1-10131 New Contract field: &quot;Active&quot;</description>
        <formula>IF(
OR(text(ContractStatus__c)== &quot;Validated&quot;, text(ContractStatus__c)== &quot;Validated PO Pending&quot;, text(ContractStatus__c)== &quot;Invoiced&quot;, text(ContractStatus__c)== &quot;Executed&quot;, text(ContractStatus__c)== &quot;Delivered to Customer&quot;, text(ContractStatus__c)== &quot;Approved &amp; Processed&quot;,text(ContractStatus__c)== &quot;Validated-POD Pending&quot;),
True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>to quickly see which Contracts on an Account are &quot;Active&quot;</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <description>SFDC1-2060 Contract Status fields
SFDC1-7222: Adding picklist value &quot;Waiting on PO&quot;</description>
        <inlineHelpText>Please select from dropdown menu</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Signed By Customer</fullName>
                    <label>Signed by Customer</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validated PO Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-POD Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-BSI Pending</fullName>
                </value>
                <value>
                    <fullName>Validated by ConsOps</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Sent to Delivery</fullName>
                </value>
                <value>
                    <fullName>Sent to OM/Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered to Customer</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved &amp; Processed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Unscheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                    <isActive>false</isActive>
                    <label>Received</label>
                </value>
                <value>
                    <fullName>Sent To OM</fullName>
                    <isActive>false</isActive>
                    <label>Sent To OM</label>
                </value>
                <value>
                    <fullName>Sent for Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Sent for Delivery</label>
                </value>
                <value>
                    <fullName>Waiting on PO</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on PO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchUpdateTrialContractStatus.cls
/*  @author: Paras Dhingra
*   @date: 04 Jun 2020
*   @description: SFDC-2003 Batch class to update Active trial contracts past contract end date
*/
global class BatchUpdateTrialContractStatus implements Database.Batchable<sObject>,Database.Stateful {
    public Boolean batchHasErrors = false;
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id trialRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Trial').getRecordTypeId();
        if (String.isBlank(query)) {
            query = 'SELECT Id, Name,ContractStatus__c, EndDate FROM Contract '+ 
                    'WHERE EndDate < today '+
                    'AND RecordtypeID=:trialRecordTypeId '+
                    'AND Active__c=true';
        }
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
        try {
            System.debug('--Contract scope--'+scope);
            List<Contract> lstContractToUpdate = new List<Contract>();
            for(Contract cont: scope) {//check converted currency <100,000
                cont.ContractStatus__c = 'Expired';
                lstContractToUpdate.add(cont);
            }
            if(lstContractToUpdate!=null && !lstContractToUpdate.isEmpty()) {
                System.debug('--Contract list to update--'+lstContractToUpdate);
                //update lstContractToUpdate;
                Database.SaveResult[] srList = Database.update(lstContractToUpdate, false);
                List<ApexLogger__c> logRecList = new List<ApexLogger__c>();                
                Integer counter = 0;
                for (Database.SaveResult sr : srList) {                    
                    if (!sr.isSuccess()) {                        
                        for(Database.Error err : sr.getErrors()) {
                            logRecList.add(new ApexLogger__c(ClassName__c='BatchUpdateTrialContractStatus', FunctionName__c='Execute', LogRecordId__c=lstContractToUpdate[counter].Id, LogRecordName__c=lstContractToUpdate[counter].Name, ErrorDescription__c=err.getMessage()));
                        }
                    }
                    counter++;
                }
                //Insert Error Log records
                if(logRecList.size() > 0) {
                    batchHasErrors = true;
                    insert logRecList;
                }
            }

            
        } catch(Exception ex) {
            System.debug('--Exception caught in batch--'+ex.getMessage());
            batchHasErrors = true;
            UtilityClass.createApexLogRecord(ex, 'BatchUpdateTrialContractStatus', 'Execute');       
        }
        
    }
    global void finish(Database.BatchableContext BC) { 
        System.debug(LoggingLevel.INFO, 'BatchUpdateTrialContractStatus BATCH FINISH()');
        //Send Email if Errors in batch processing
        if(batchHasErrors) {            
            String[] toAddresses = new String[] {};
            toAddresses.addAll(System.Label.BatchErrorRecepient.split(','));
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddresses);
            mail.setReplyTo(System.Label.OpptyPrimaryContactBatchEmail);            
            mail.setSubject('BatchUpdateTrialContractStatus batch errors');
            mail.setPlainTextBody('Please see Apex Log records to view errors of BatchUpdateTrialContractStatus batch class job in detail.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}