objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Create an event record to log interactions with a customer</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>PrivacyLevel__c</fullName>
        <description>SFDC-2748 Syncs to PrivacyLevel__c field in related Event(Activity) record.</description>
        <label>Privacy Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personal appointment</fullName>
                </value>
                <value>
                    <fullName>Internal meeting</fullName>
                </value>
                <value>
                    <fullName>Customer-facing meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelatedEventId__c</fullName>
        <description>SFDC-2748 Store related event id in a text field. This is a backend field created to save recursive trigger invocation.</description>
        <label>Related Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchCreateMeetingNoteForEvent.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 05 May 2020
// @description: SFDC-2761 Batch to create automated meeting notes for events that pass the critria - AccountId!=null AND IsChild=false AND RecordType=Standard AND MeetingNote__c=null
// -----------------------------
public class BatchCreateMeetingNoteForEvent implements Database.Batchable<sObject>, Database.Stateful {
    public static Boolean isExecutingBatchCreateMeetingNoteForEvent = false;		//Variable to help fire platform events in EventMethods trigger helper if PrivacyLevel__c needs to be updated or MeetingNote__Share records need to be checked.
    public Set<Id> errorLogIdSet = new Set<Id>();
    public Integer batchCount = 0;
    public Integer recordCount = 0;
    public String query = '';
    public String emailId = '';
    
    public BatchCreateMeetingNoteForEvent(String q, String email) {
        query = String.isNotBlank(q) ? q : 'SELECT Id, AccountId, MeetingNote__c, MeetingNote__r.RelatedEventId__c, RecordType.Name, RecordTypeId, WhatId, IsChild, DurationInMinutes, StartDateTime, ShowAs, EndDateTime, IsReminderSet, PrivacyLevel__c, IsPrivate, ActivityDateTime, Location, Subject, IsAllDayEvent, Type, Description, IsRecurrence2, OwnerId FROM Event WHERE (AccountId!=null AND RecordType.Name=\'Standard\' AND IsChild=false AND MeetingNote__c=null AND IsRecurrence2=false)';
        emailId = String.isNotBlank(email) ? email : Label.OpptyPrimaryContactBatchEmail;        
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {  
        System.debug('START() METHOD');
        System.debug('query='+query);
        return Database.getQueryLocator(query);        
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        isExecutingBatchCreateMeetingNoteForEvent = true;
        batchCount++;
        List<MeetingNote__c> upsertMeetingNoteList = new List<MeetingNote__c>();
        for(Event evt: (List<Event>)scope) {
            //Create meeting note if it does not exist on relevant event
            if(EventMeetingNoteSyncUtility.shouldEventHaveMeetingNote(evt)) {
                Map<String,String> evtToMtngNoteCreationMap = EventMeetingNoteSyncUtility.EventMeetingNoteSyncFieldsMap;
                MeetingNote__c mtngNote = EventMeetingNoteSyncUtility.createMeetingNoteFromEvent(evt, evtToMtngNoteCreationMap);
                upsertMeetingNoteList.add(mtngNote);
            }
        }
        try {
            if(upsertMeetingNoteList.size() > 0) {
                recordCount += upsertMeetingNoteList.size();
                upsert upsertMeetingNoteList;
            }
        }
        catch(Exception ex) {
            System.debug('Exception in BatchCreateMeetingNoteForEvent. ex.getMessage()='+ex.getMessage());            
            
            String description = '\n Cause: '+ex.getCause()+'\n Line number : '+ ex.getLineNumber()+ '\n Message: '+ ex.getMessage()+ '\n stackTrace: '+ex.getStackTraceString();
            ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='BatchCreateMeetingNoteForEvent',ErrorDescription__c=description,FunctionName__c='execute');
            insert apexLogRecord;
            errorLogIdSet.add(apexLogRecord.Id);
        }
        finally {
            isExecutingBatchCreateMeetingNoteForEvent = false;
        }
        System.debug('EXECUTE() METHOD ENDS');
    }
    
    public void finish(Database.BatchableContext bc) {
        System.debug('FINISH() METHOD');
        if(String.isNotBlank(emailId)) {            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String status = 'BatchCreateMeetingNoteForEvent Batch Completed.';
            String[] toAddresses = new String[] {emailId};
            mail.setToAddresses(toAddresses);
            String mailBody = ' Meeting Notes Count: ' + String.valueOf(recordCount) + '\n'
                + ' Total Batches Executed: ' + String.valueOf(batchCount) + '\n';
                
            if(errorLogIdSet!=null && errorLogIdSet.size()>0) {
                mail.setSubject('FAILED: ' + status);
                mailBody += ' Batches Failed: '+ errorLogIdSet.size() + '\n\n Check Apex Logger records for details.';
                mail.setPlainTextBody(mailBody);
            }
            else {
                mail.setSubject('SUCCESS: ' + status);
                mail.setPlainTextBody(mailBody);
            }
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

}