objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordId__c</fullName>
        <description>SFDC-1763: Id of record that resulted in error</description>
        <inlineHelpText>Id of record that resulted in error</inlineHelpText>
        <label>Log Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordName__c</fullName>
        <description>SFDC-1763: Name of record that resulted in error</description>
        <label>Log Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4728: Create Auto Renewal field on Opportunity that will be updated from Contract.</description>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoesThisAutoRenewalHaveChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field includes renewal details of opportunity. (JIRA story SFDC1-556)</description>
        <inlineHelpText>Specify if Auto Renewal has any changes.</inlineHelpText>
        <label>Does this Auto Renewal Have Changes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1- 535 ;Checkbox fields on opportunity which is automatically populated from Account, SFDC1-959 : Added &apos;?&apos; to the Label.</description>
        <label>PO Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <description>SFDC1 -171; Describe source of the lead/opportunity
SFDC1-2219; Rename Source System to External Source System
SFDC1-8491: Updated picklist values
SFDC-2753: Added picklist value for PCM</description>
        <inlineHelpText>Please select a value</inlineHelpText>
        <label>External Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Manually Generated</fullName>
                    <default>true</default>
                    <label>Manually Generated</label>
                </value>
                <value>
                    <fullName>IHS CRM</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Lead Generated</fullName>
                </value>
                <value>
                    <fullName>Third Party System</fullName>
                </value>
                <value>
                    <fullName>Polk Salesforce</fullName>
                </value>
                <value>
                    <fullName>Markit Salesforce</fullName>
                </value>
                <value>
                    <fullName>PCM Salesforce</fullName>
                </value>
                <value>
                    <fullName>IHSM Salesforce</fullName>
                </value>
                <value>
                    <fullName>Market Scan (Dealer Instance)</fullName>
                </value>
                <value>
                    <fullName>Market Scan (API Customer Instance)</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                    <isActive>false</isActive>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>Markit SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Markit SFDC</label>
                </value>
                <value>
                    <fullName>Markit Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Markit Salesforce.com</label>
                </value>
                <value>
                    <fullName>Polk SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Polk SFDC</label>
                </value>
                <value>
                    <fullName>Polk Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Polk Salesforce.com</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityUpdateBatchJob.cls
//-----------------------------
// @author: Sushma Yadav
// @date: 24 Jan 2020
// @description: SFDC-2500 Auto Renewals with no change to go to 6WP when the have the External Source System = "SAP"
// -----------------------------

global class OpportunityUpdateBatchJob implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        string query;
        Id renewalRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        query = 'SELECT Id,StageName ' +
            'FROM Opportunity ' +
            'where StageName=\'6W-Renewal Won\' ' +
            ' AND AutoRenewal__c=true' +
            ' AND DoesThisAutoRenewalHaveChanges__c=false' + 
            ' AND SourceSystem__c=\'SAP\' ' +
            ' AND PORequired__c=false' +
            ' AND RecordTypeId =:renewalRecordTypeId';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        
        try {          
            for(Opportunity oppty : scope) {
                oppty.StageName = '6WP-Closed Won/Order Processed';
            }
            
            Database.SaveResult[] srList = Database.update(scope, false);
            List<ApexLogger__c> logRecList = new List<ApexLogger__c>();                
            Integer counter = 0;
            for (Database.SaveResult sr : srList) {                    
                if (!sr.isSuccess()) {                        
                    for(Database.Error err : sr.getErrors()) {                                
                        logRecList.add(new ApexLogger__c(ClassName__c='OpportunityUpdateBatchJob', FunctionName__c='Execute', LogRecordId__c=scope[counter].Id, LogRecordName__c=scope[counter].Name, ErrorDescription__c=err.getMessage()));
                    }
                }
                counter++;
            }
            if(logRecList.size() > 0) {
                insert logRecList;
            }
        }
        catch (Exception ex) {
            UtilityClass.createApexLogRecord(ex, 'OpportunityUpdateBatchJob', 'Execute');                
        }
    }
    
    global void finish(Database.BatchableContext bc) {
    }
}