objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Stores the Error Message which is either passed by developer  else derived from Exception.</description>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <description>Stores Type of Exception</description>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordId__c</fullName>
        <description>SFDC-1763: Id of record that resulted in error</description>
        <inlineHelpText>Id of record that resulted in error</inlineHelpText>
        <label>Log Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRecordJson__c</fullName>
        <description>Details about Object on which is passed to Exception Framework</description>
        <label>Log Record Json</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <description>Transaction ID of Salesforce  transaction</description>
        <label>Transaction Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Id of Logged in User.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Apex_Logger</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SetApexLoggerEvent__e.object
<CustomObject>
    <description>Platform Event to Captures Details about Apex Exception which will be saved to Apex Logger Object.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Class Name on which Exception Occurred.</description>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Error Message from Apex  Exception.</description>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <description>Type of Apex Exception.</description>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <description>Method Name on which Exception Occured.</description>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>SObject Record ID</description>
        <label>Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordJson__c</fullName>
        <description>Details about Object on which Exception Occurred.</description>
        <label>Record Json</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <description>Stack Trace of Apex Exception.</description>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <description>Transaction ID of Apex Transaction.</description>
        <label>Transaction Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>Logged In User&apos;s Id.</description>
        <label>User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SetApexLoggerEvent</label>
    <pluralLabel>SetApexLoggerEvents</pluralLabel>
</CustomObject>

classes/SetApexLoggerEventMethods.cls
//-----------------------------
// @author: Digvijay Singh
// @date: 11 Aug 2021
// @param: NA
// @description:  Class to hold SetApexLoggerEvent__e platform event trigger methods 
// @return: NA
//-----------------------------
public with sharing class SetApexLoggerEventMethods {
    /**
    * @author Digvijay Singh
    * @date 11 Aug 2021
    * @description Insert apex Logger records
    * @param TriggerParameters
    * @return void
    * @companyname IHS Markit
    */
    public static void insertApexLogEntries(List<SetApexLoggerEvent__e> eventList) {
        List<ApexLogger__c> apexlogEntries = new List<ApexLogger__c>();
        for (SetApexLoggerEvent__e apexlogEntryEvent : eventList) {
            ApexLogger__c apexlogEntry = new ApexLogger__c(
                exceptionType__c = apexlogEntryEvent.exceptionType__c,  
                errorMessage__c = apexlogEntryEvent.errorMessage__c,
                logRecordId__c = apexlogEntryEvent.recordId__c,
                LogRecordJson__c = apexlogEntryEvent.recordJson__c,
                errorDescription__c = apexlogEntryEvent.stackTrace__c,
                className__c=apexlogEntryEvent.className__c,
                functionName__c=apexlogEntryEvent.methodName__c,
                user__c=apexlogEntryEvent.UserId__c,
                transactionId__c=apexlogEntryEvent.transactionId__c
            );

            apexlogEntries.add(apexlogEntry);
        }

        if(!apexlogEntries.isEmpty()) {
            insert apexlogEntries;
        }
    }
    //-----------------------------
    // @author: Sathish Edla
    // @date: 30 Mar 2022
    // @description: SFDC-5375 Extend the trigger framework to handle platform events.
    //-----------------------------
    public static void insertApexLogEntries(TriggerParameters tp) {
        List<SetApexLoggerEvent__e> eventList = (List<SetApexLoggerEvent__e>)tp.newList;
        insertApexLogEntries(eventList);
    }
}