objects/ApprovedContractSummary__c.object
<CustomObject>
    <description>SFDC1-9063, created for account overview report, Provides summary of approved contracts (Not visible to end user, for internal purpose only)</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-9063 Created for account overview report, Master-Detail for accounts</description>
        <inlineHelpText>Master-Detail for accounts</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approved Contract Summaries</relationshipLabel>
        <relationshipName>ApprovedContractSummaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AnnualContractValue__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Annual Contract value in native currency.</description>
        <inlineHelpText>Annual Contract value in native currency</inlineHelpText>
        <label>Annual Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Frequency of billing (monthly / Quarterly / Annually).</description>
        <inlineHelpText>Frequency of billing (monthly / Quarterly / Annually)</inlineHelpText>
        <label>Billing Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <description>SFDC1-9063, Created for account overview report. This field is used to populate unique contract number.</description>
        <inlineHelpText>This field is used to populate unique contract number.</inlineHelpText>
        <label>Contract Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EarliestContractEndDate__c</fullName>
        <description>SFDC1-9063, Created for account overview report. End date of contract.</description>
        <inlineHelpText>End date of contract.</inlineHelpText>
        <label>Earliest Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>SFDC1-9063, Created for account overview report. (Not visible to end users, for internal purpose only)</description>
        <externalId>true</externalId>
        <inlineHelpText>Key Field</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Field to show product family.</description>
        <inlineHelpText>Field to show product family</inlineHelpText>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approved Contract Summary</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Approved Contract Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Contract Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CMRelationship__c.object
<CustomObject>
    <description>SFDC1-2455 CM Relationships is used to track the Live CM Brokers on the Account Additional fields object</description>
    <fields>
        <fullName>BrokerContract__c</fullName>
        <description>SFDC1-2455 CM Relationships&apos; Broker Contract</description>
        <label>Broker Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CM Clients</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CM Relationship</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CM #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>SFDC1-10131 New Contract field: &quot;Active&quot;</description>
        <formula>IF(
OR(text(ContractStatus__c)== &quot;Validated&quot;, text(ContractStatus__c)== &quot;Validated PO Pending&quot;, text(ContractStatus__c)== &quot;Invoiced&quot;, text(ContractStatus__c)== &quot;Executed&quot;, text(ContractStatus__c)== &quot;Delivered to Customer&quot;, text(ContractStatus__c)== &quot;Approved &amp; Processed&quot;,text(ContractStatus__c)== &quot;Validated-POD Pending&quot;),
True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>to quickly see which Contracts on an Account are &quot;Active&quot;</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>SFDC1-718;Only on Contract Type = Order Form</description>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Annually (First of the month)</fullName>
                </value>
                <value>
                    <fullName>Last day of the month</fullName>
                </value>
                <value>
                    <fullName>Last Day of the Quarter</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly on First of Month</fullName>
                </value>
                <value>
                    <fullName>Monthly on Last of Month</fullName>
                </value>
                <value>
                    <fullName>Multi Year</fullName>
                </value>
                <value>
                    <fullName>Multi Year for Prof. Srvcs</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Quarterly (First of the month)</fullName>
                </value>
                <value>
                    <fullName>Quarterly on Last of Month</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Two Year</fullName>
                </value>
                <value>
                    <fullName>Consulting Agreement</fullName>
                    <isActive>false</isActive>
                    <label>Consulting Agreement</label>
                </value>
                <value>
                    <fullName>Last day of the month,</fullName>
                    <isActive>false</isActive>
                    <label>Last day of the month,</label>
                </value>
                <value>
                    <fullName>Monthly on the First day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Monthly on the First day of the month</label>
                </value>
                <value>
                    <fullName>Monthly on the Last day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Monthly on the Last day of the month</label>
                </value>
                <value>
                    <fullName>Montly on the First day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Montly on the First day of the month</label>
                </value>
                <value>
                    <fullName>Montly on the Last Day of the Month</fullName>
                    <isActive>false</isActive>
                    <label>Montly on the Last Day of the Month</label>
                </value>
                <value>
                    <fullName>Multi Year for Prof Svcs</fullName>
                    <isActive>false</isActive>
                    <label>Multi Year for Prof Svcs</label>
                </value>
                <value>
                    <fullName>Non Billable</fullName>
                    <isActive>false</isActive>
                    <label>Non Billable</label>
                </value>
                <value>
                    <fullName>Quarterly last day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Quarterly last day of the month</label>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                    <isActive>false</isActive>
                    <label>Semi Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9301: Fetching value from Product Family on Opportunity
SFDC-887: change logic to have this value rolled up from Contract Line Item instead of copying from Opportunity</description>
        <inlineHelpText>Value rolled up from Contract line items</inlineHelpText>
        <label>Product Family</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RenewalDate__c</fullName>
        <description>SFDC1-9301 : Renewal Date</description>
        <inlineHelpText>Fill the Renewal Date</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>AssociatedProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4324 This field holds the product associated with &apos;Opportunity Line Item&apos;, to which contract line item is related.</description>
        <inlineHelpText>Product related to Opportunity Line Item</inlineHelpText>
        <label>Associated Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items (Associated Product)</relationshipLabel>
        <relationshipName>ContractLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>AssociatedProduct__r.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2298;Product Lookup field on Contract Line Item
SFDC-99 Duplicate for AssociatedProduct__c marking this as zz to delete in future</description>
        <label>zzzProduct</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ContractLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-905 This is a custom object, which will be related to contract line item.
SFDC1-10132: Updated object label name to Fixed Fee Schedule Line Item</description>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <description>SFDC1-380 This field holds the value of contract line item record to which contract line item schedule is related
SFDC1-10132 rename the label</description>
        <inlineHelpText>Contract Line Item</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Fixed Fee Schedule Line Item</relationshipLabel>
        <relationshipName>ContractLineItemSchedule</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-380 This is a lookup to Contract record, to which contract line item schedule is related</description>
        <inlineHelpText>Related Contract</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Item Schedules</relationshipLabel>
        <relationshipName>ContractLineItemSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fixed Fee Schedule Line Item</label>
    <nameField>
        <displayFormat>CLS-{0000000}</displayFormat>
        <label>Fixed Fee Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Fee Schedule Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchCreateContractSummary.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 12 July 2018
// @description: SFDC1-5228 This class creates Approved Contract Summary data for all accounts
// @Last Modified By : Uttam Arya
// @Last Modified Date : 7 March 2019
// @Last Modified Description- SFDC-899 - Products not appearing under the Contract Summary. Changed the contract selection filter to select from Renewal Date greater than today 
//                    instead of EndDate and added contractStatusIncludeList = {'Validated','Validated PO Pending','Invoiced'}
// @Last Modified By: Harshit Singhal
// @Last Modified Date: 23 Apr 2019
// @Last Modified Description: SFDC-900: Changes in calculation of Recurring and Non-recurring contracts schedules
// @Last Modified By : Uttam Arya
// @Last Modified Date : 1 May 2019
// @Last Modified Description- SFDC-1471 - In the Active Contract Summary section - instead of using the contract end date - using Renewal Date
// @LastModifiedBy: Paras Dhingra
// @LastModifiedDate: 6th Dec 2020
// @LastModifiedDescription: SFDC-1994 add exception for Lost Contract LineItem and Historical fixed fee line items
//-----------------------------
global class BatchCreateContractSummary implements Database.Batchable<sObject> {
    global String errorMsgs = '';
    public String fixedFeeHistoryStatus = GlobalConstants.FIXED_FEE_HISTORY_STATUS;
    public String contractLineItemLostStatus = GlobalConstants.CONTRACT_LINE_ITEM_LOST_STATUS;
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //return Database.getQueryLocator('SELECT Id FROM Account WHERE Number_of_Approved_Contracts__c >= 0');
        System.debug('@HS BATCH START()');
        return Database.getQueryLocator('SELECT Id FROM Account');
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('@HS BATCH EXECUTE() BEGINS');
        //PART 1 Variables
        Set<id> accountIDs = new Set<Id>();
        Map<String, ApprovedContractSummary__c> acsMap = new Map<String, ApprovedContractSummary__c>();
        List<ApprovedContractSummary__c> acsMapBillingSchedule = new List<ApprovedContractSummary__c>();
        List<String> recurringProductsAAGTypeList = new List<String>{'Subscription','SubscriptionVar'};
        
        //PART 1: Collect accounts, delete existing contract summaries and create dummy Approved Contract Summary records
        System.debug('@HS scope size='+scope.size());
        for(sObject acc: scope) {
            Account a = (Account) acc;
            accountIDs.add(a.id);
        }
        
        if(accountIDs != null && accountIDs.size() > 0) {
            //Pre clean all the Aproved Contract Summary data
            List<ApprovedContractSummary__c> acsToDeletePreClean = [SELECT id FROM ApprovedContractSummary__c WHERE Account__c in :accountIDs];            
            System.debug('@HS acsToDeletePreClean='+acsToDeletePreClean);
            if(acsToDeletePreClean != null && acsToDeletePreClean.size() > 0) {
                delete acsToDeletePreClean;
            }
            
            //Fetch active Contract records            
            List<Contract> contractsList = [SELECT Id, AccountId, EndDate, ContractNumber, BillingFrequency__c, RenewalDate__c,
                                            (SELECT ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name FROM ContractLineItemSchedules__r), 
                                            (Select Id From Contract_Line_Items__r)                                            
                                            FROM Contract 
                                            WHERE Account.Id in :accountIDs 
                                            AND Active__c=true
                                            ORDER BY RenewalDate__c DESC
                                           ];
            System.debug('@HS contractsList size='+contractsList.size());
            System.debug('@HS contractsList='+contractsList);
            
            Map<Id, Contract> mapContracts =  new Map <Id, Contract>();            
            //Prepare unique Approved Contract Summary records from CLI Schedules
            for (Contract con : contractsList) {
                if(con.Contract_Line_Items__r != null && con.Contract_Line_Items__r.size() > 0) {                           //Added a condition to check atleast one child line item to properly implement ContractAprroved=true condition in new org
                    mapContracts.put(con.Id,con);
                    for(ContractLineItemSchedule__c  cbs: con.ContractLineItemSchedules__r) {
                        String prodGroupName = cbs.ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name;       //?? Add null checkS
                        String Key = con.AccountId + prodGroupName;
                        System.debug('@HS Contract Id: ' + Con.Id + 'Product Group: ' + prodGroupName);
                        acsMap.put(key, new ApprovedContractSummary__c( Account__c = con.AccountId, AnnualContractValue__c = null, ProductFamily__c = prodGroupName
                                                                       , EarliestContractEndDate__c = con.RenewalDate__c, BillingFrequency__c = con.BillingFrequency__c
                                                                       , Key__c = Key,ContractNumber__c = con.ContractNumber));
                    }
                }
            }
            System.debug('@HS mapContracts size='+mapContracts.size());
            System.debug('@HS mapContracts='+mapContracts);
            System.debug('@HS acsMap size='+acsMap.size());
            System.debug('@HS acsMap='+acsMap);
            
            //Insert Approved Contract Summary records
            if(acsMap != null && acsMap.size() > 0) {
                Schema.SObjectField f = ApprovedContractSummary__c.Fields.Key__c;
                List<Database.UpsertResult> upsertResult = Database.upsert(acsMap.values(), f, false);
                for(Integer i=0;i< upsertResult.size();i++) {
                    if(!upsertResult.get(i).isSuccess()) {
                        Database.Error error = upsertResult.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        errorMsgs += 'ACS rec: '+', '+failedDML+'<\br>';
                        System.debug('@HS Error during acs record upsert. DML Error='+failedDML);
                    }
                }
                System.debug('@HS After acsMap upsert Error Messages='+errorMsgs);
                System.debug('@HS UPSERT1 complete.');                
            }
            
            //PART 2: Fetch current year Schedules using Instalment Year
            String CURRENTYEAR = String.valueOf(UtilityClass.calculateFYFromDate(System.today(), 12));
            Map<String,Id> toQueryRecurringCLIScheduleMap = new Map<String,Id>();
            
            List<ContractLineItemSchedule__c> recurringCLISchedulesPastList = [SELECT Id, Contract__c,ContractLineItem__c,ContractLineItem__r.AssociatedProduct__c
                                                                               FROM ContractLineItemSchedule__c
                                                                               WHERE Contract__r.AccountId = :accountIDs 
                                                                               AND Contract__r.Active__c=true
                                                                               AND ContractLineItem__c != null
                                                                               AND ContractLineItem__r.AssociatedProduct__r.AAG__c IN :recurringProductsAAGTypeList
                                                                               AND InstallmentYear__c <= :CURRENTYEAR 
                                                                               AND InstallmentYear__c!=null
                                                                               AND Status__c!=:fixedFeeHistoryStatus
                                                                               AND ContractLineItem__r.Status__c!=:contractLineItemLostStatus
                                                                               ORDER BY Contract__c,ContractLineItem__c, InstallmentYear__c DESC, CreatedDate DESC
                                                                              ];
            for(ContractLineItemSchedule__c clisRecurringPast: recurringCLISchedulesPastList) {
                String key = String.valueOf(clisRecurringPast.Contract__c) + String.valueOf(clisRecurringPast.ContractLineItem__r.AssociatedProduct__c);
                if(!toQueryRecurringCLIScheduleMap.containsKey(key)) {
                    toQueryRecurringCLIScheduleMap.put(key,clisRecurringPast.Id);
                }                
            }
            System.debug('recurringCLISchedulesPastList size='+recurringCLISchedulesPastList.size());
            System.debug('AFTER PAST:toQueryRecurringCLIScheduleMap size='+toQueryRecurringCLIScheduleMap.size());            
            
            List<ContractLineItemSchedule__c> recurringCLISchedulesFutureList = [SELECT Id, Contract__c,ContractLineItem__c,ContractLineItem__r.AssociatedProduct__c
                                                                                 FROM ContractLineItemSchedule__c
                                                                                 WHERE Contract__r.AccountId = :accountIDs 
                                                                                 AND Contract__r.Active__c=true
                                                                                 AND ContractLineItem__c != null
                                                                                 AND ContractLineItem__r.AssociatedProduct__r.AAG__c IN :recurringProductsAAGTypeList
                                                                                 AND InstallmentYear__c > :CURRENTYEAR
                                                                                 AND InstallmentYear__c!=null
                                                                                 AND Status__c!=:fixedFeeHistoryStatus
                                                                                 AND ContractLineItem__r.Status__c!=:contractLineItemLostStatus
                                                                                 ORDER BY Contract__c,ContractLineItem__c, InstallmentYear__c ASC, CreatedDate DESC
                                                                                ];
            for(ContractLineItemSchedule__c clisRecurringFuture: recurringCLISchedulesFutureList) {
                String key = String.valueOf(clisRecurringFuture.Contract__c) + String.valueOf(clisRecurringFuture.ContractLineItem__r.AssociatedProduct__c);
                if(!toQueryRecurringCLIScheduleMap.containsKey(key)) {
                    toQueryRecurringCLIScheduleMap.put(key,clisRecurringFuture.Id);
                }
            }
            System.debug('recurringCLISchedulesFutureList size='+recurringCLISchedulesFutureList.size());
            System.debug('AFTER FUTURE:toQueryRecurringCLIScheduleMap size='+toQueryRecurringCLIScheduleMap.size());            
                        
            /*
            //PART 2: Fetch current year Schedules using Billing Date
            Map<String,Date> billingDateMap = new Map<String,Date>();
            Set<Id> recurringCLIScheduleIds = new Set<Id>();
            AggregateResult[] groupedContractsCLIScheduleMaxDatePast = [SELECT MAX(BillingDate__c) maxBillingDate, Contract__c, ContractLineItem__r.AssociatedProduct__c productId
                                                                       FROM ContractLineItemSchedule__c
                                                                       WHERE Contract__r.AccountId = :accountIDs 
                                                                        AND Contract__r.Active__c=true
                                                                        AND ContractLineItem__c != null    
                                                                        AND ContractLineItem__r.AssociatedProduct__r.AAG__c IN :recurringProductsAAGTypeList
                                                                        AND BillingDate__c <= Today
                                                                       GROUP BY Contract__c,ContractLineItem__r.AssociatedProduct__c];
            
            AggregateResult[] groupedContractsCLIScheduleMinDateFuture = [SELECT MIN(BillingDate__c) minBillingDate, Contract__c, ContractLineItem__r.AssociatedProduct__c productId
                                                                       FROM ContractLineItemSchedule__c
                                                                       WHERE Contract__r.AccountId = :accountIDs 
                                                                        AND Contract__r.Active__c=true
                                                                        AND ContractLineItem__c != null    
                                                                        AND ContractLineItem__r.AssociatedProduct__r.AAG__c IN :recurringProductsAAGTypeList
                                                                        AND BillingDate__c > Today
                                                                       GROUP BY Contract__c,ContractLineItem__r.AssociatedProduct__c];
            
            for(AggregateResult ar: groupedContractsCLIScheduleMaxDatePast) {
                Date maxBillingDate = ar.get('maxBillingDate') != null? Date.valueOf(ar.get('maxBillingDate')) : null;
                String contractId = ar.get('Contract__c') != null ? String.valueOf(ar.get('Contract__c')) : '';
                String productId = ar.get('productId') != null ? String.valueOf(ar.get('productId')) : '';
                if(!billingDateMap.containsKey(contractId+productId)) {
                    billingDateMap.put(contractId+productId, maxBillingDate);
                    System.debug('Contract Id='+contractId+' ; maxBillingDate='+maxBillingDate);
                }
            }
            for(AggregateResult ar: groupedContractsCLIScheduleMinDateFuture) {
                Date minBillingDate = ar.get('minBillingDate') != null? Date.valueOf(ar.get('minBillingDate')) : null;
                String contractId = ar.get('Contract__c') != null ? String.valueOf(ar.get('Contract__c')) : '';
                String productId = ar.get('productId') != null ? String.valueOf(ar.get('productId')) : '';
                if(!billingDateMap.containsKey(contractId+productId)) {
                    billingDateMap.put(contractId+productId, minBillingDate);
                    System.debug('Contract Id='+contractId+' ; minBillingDate='+minBillingDate);
                }
            }            
            */
            
            //PART 3:
            //Fetch totals of Recurring and Non-Recurring CLIS records
            Map<String, ApprovedContractSummary__c> mapACSContractValue = new Map<String, ApprovedContractSummary__c>();
            AggregateResult[] groupedContractsBillingScheduleTotalsRecurring = [SELECT SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                                FROM ContractLineItemSchedule__c 
                                                                                WHERE Contract__r.AccountId = :accountIDs 
                                                                                AND Contract__r.Active__c=true
                                                                                AND ContractLineItem__c != null    
                                                                                AND ContractLineItem__r.AssociatedProduct__r.AAG__c IN :recurringProductsAAGTypeList
                                                                                AND Id IN :toQueryRecurringCLIScheduleMap.values()
                                                                                AND Status__c!=:fixedFeeHistoryStatus
                                                                                AND ContractLineItem__r.Status__c!=:contractLineItemLostStatus
                                                                                GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];
            
            AggregateResult[] groupedContractsBillingScheduleTotalsNonRecurring = [SELECT SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                                   FROM ContractLineItemSchedule__c 
                                                                                   WHERE Contract__r.AccountId = :accountIDs 
                                                                                   AND Contract__r.Active__c=true
                                                                                   AND ContractLineItem__c != null    
                                                                                   AND ContractLineItem__r.AssociatedProduct__r.AAG__c NOT IN :recurringProductsAAGTypeList
                                                                                   AND InstallmentYear__c = :CURRENTYEAR
                                                                                   GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];
            
            //Process Contracts that contain Subscription/Recurring type products
            for (AggregateResult ar : groupedContractsBillingScheduleTotalsRecurring) {
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');                 //?? Is this split on prod group name required?
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= 'Recurring', Account__c=AccountId,AnnualContractValue__c=SumAnnualRevenue,ProductFamily__c=pf, Key__c = Key));
                }                
                System.debug('@HS PF: ' + PFamlies + ' Recurring Amount: ' + SumAnnualRevenue);            
            }
            
            //Process Contracts that contain One off/Non-Recurring type products
            for(AggregateResult ar : groupedContractsBillingScheduleTotalsNonRecurring) { 
                
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    if(mapACSContractValue.get(Key) == null){
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= 'Non-recurring',Account__c=AccountId,AnnualContractValue__c=SumAnnualRevenue,ProductFamily__c=pf, Key__c = Key));
                    }
                    else {
                        String revenueTypeStr = mapACSContractValue.get(Key).RevenueType__c;
                        revenueTypeStr += ' & Non-recurring';
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= revenueTypeStr,Account__c=AccountId,AnnualContractValue__c= (SumAnnualRevenue + mapACSContractValue.get(Key).AnnualContractValue__c),ProductFamily__c=pf, Key__c = Key));
                    }
                }                
                System.debug('PF: ' + PFamlies + ' Non-recurring Amount: ' + SumAnnualRevenue);             
            }
            
            //Finally Update ACS records
            acsMapBillingSchedule.addAll(mapACSContractValue.values());
            
            if(acsMapBillingSchedule != null && acsMapBillingSchedule.size() > 0) {
                Schema.SObjectField f = ApprovedContractSummary__c.Fields.Key__c;
                List<Database.UpsertResult> upsertResult = Database.upsert(acsMapBillingSchedule, f, false);
                for(Integer i=0;i< upsertResult.size();i++) {
                    if(!upsertResult.get(i).isSuccess()) {
                        Database.Error error = upsertResult.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        errorMsgs += 'ACS rec: ' + acsMapBillingSchedule.get(i).Id+', '+failedDML+'<\br>';
                        System.debug('@HS Failure in acsMapBillingSchedule Map UPSERT2. Error='+failedDML);
                    }
                }
                System.debug('@HS UPSERT2 complete.');                
            }
        }
        System.debug('@HS BATCH EXECUTE() ENDS');
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('@HS BATCH FINISH()');
        //Call Support Overview Batch here in next phase
        //Database.executeBatch(new BatchCalCasesSummarySupportOverview(), 1);        
    }
}