objects/ArchivedEmailMessage__c.object
<CustomObject>
    <fields>
        <fullName>BccAddress__c</fullName>
        <label>BccAddress</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ArchivedEmailMessages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CcAddress__c</fullName>
        <label>CcAddress</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EmailMessage_CreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EmailMessage Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Archived_Email_Messages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailMessage_CreatedDate__c</fullName>
        <label>EmailMessage Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmailMessage_LastModifiedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EmailMessage Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Archived_Email_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailMessage_LastModifiedDate__c</fullName>
        <label>EmailMessage Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <label>EmailTemplateId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstOpenedDate__c</fullName>
        <label>FirstOpenedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FromAddress__c</fullName>
        <label>FromAddress</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FromName__c</fullName>
        <label>FromName</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HasAttachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasAttachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Headers__c</fullName>
        <label>Headers</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incoming__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Incoming</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBounced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsBounced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsClientManaged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClientManaged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsExternallyVisible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsExternallyVisible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsOpened__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsOpened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTracked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsTracked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastOpenedDate__c</fullName>
        <label>LastOpenedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <label>LegacyID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegacySystem__c</fullName>
        <label>LegacySystem</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageDate__c</fullName>
        <label>MessageDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MessageIdentifier__c</fullName>
        <label>MessageIdentifier</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PKIDEmailMessage__c</fullName>
        <label>PKIDEmailMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyToEmailMessageId__c</fullName>
        <label>ReplyToEmailMessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>New</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Read</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Replied</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Sent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Forwarded</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ThreadIdentifier__c</fullName>
        <label>ThreadIdentifier</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ToAddress__c</fullName>
        <label>ToAddress</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ValidatedFromAddress__c</fullName>
        <label>ValidatedFromAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Archived Email Message</label>
    <nameField>
        <label>ArchivedEmailMessages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Email Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <description>SFDC1-7046: Legacy ID Unique field is a concatenation of the source system name and a source system record id to ensure record is uniquely identified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Concatenation of the source system name and a source system record id to ensure the record is uniquely identified.</inlineHelpText>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <description>SFDC1-7046: Legacy ID field is the system id (unfriendly) referencing the source record.</description>
        <externalId>true</externalId>
        <inlineHelpText>System ID referencing the source record Populated at Migration</inlineHelpText>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegacySystem__c</fullName>
        <description>SFDC1-7046: Legacy System field is a picklist that represents the original system the record came from.</description>
        <inlineHelpText>Name of the CRM system the source record came from</inlineHelpText>
        <label>LegacySystem</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegacySystem</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <businessProcess>Implementation</businessProcess>
        <description>Used to track customer implementation projects.</description>
        <label>Implementation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmailMessage.object
<CustomObject>
    <fields>
        <fullName>LegacyIDUnique__c</fullName>
        <description>Created as part for migration exercise to store unique identifier for legacy records</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id for legacy records</inlineHelpText>
        <label>LegacyIDUnique</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LegacyID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-7046, MIG-521: Legacy ID field is the system id (unfriendly) referencing the source record.</description>
        <externalId>true</externalId>
        <inlineHelpText>System ID referencing the source record Populated at Migration</inlineHelpText>
        <label>LegacyID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LegacySystem__c</fullName>
        <description>Created as part of migration exercise to identify the system to which the legacy records relates with</description>
        <inlineHelpText>System from which the record was migrated</inlineHelpText>
        <label>LegacySystem</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegacySystem</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PKIDEmailMessage__c</fullName>
        <description>SFDC1-2445 : Creating PK field for Data Migration Support</description>
        <displayFormat>EMS{000000}</displayFormat>
        <externalId>true</externalId>
        <label>PKID EmailMessage</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

globalValueSets/LegacySystem.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agri_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>CDNEnergy_Ctele</fullName>
    </customValue>
    <customValue>
        <fullName>Fekete_MSCRM</fullName>
    </customValue>
    <customValue>
        <fullName>Goldfire_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>IHS_MSCRM</fullName>
    </customValue>
    <customValue>
        <fullName>IHS Markit_Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>IPREO_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>JOC_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Kingdom_MSCRM</fullName>
    </customValue>
    <customValue>
        <fullName>Markit_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>PCM_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Polk_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>SMT_MSCRM</fullName>
    </customValue>
    <customValue>
        <fullName>MEA_SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Cappitech_Hubspot</fullName>
    </customValue>
    <customValue>
        <fullName>Core_SFDC</fullName>
        <isActive>false</isActive>
        <label>Core_SFDC</label>
    </customValue>
    <description>SFDC1-6978: This is a global list of various legacy IHS Markit CRM system.</description>
    <masterLabel>Legacy System</masterLabel>
</GlobalValueSet>

classes/BatchToArchiveEmailMessages.cls
//-----------------------------
// @author: Amrender Singh
// @date: 12 oct 2021
// @description: SFDC-4755(Storing Email Message data against File Storage: implementation) This batch class will be used to archive email message records from case.
//------------------------------
public with sharing class BatchToArchiveEmailMessages implements Database.Batchable<sObject> {
    public final String whereClause;
    public final Boolean runNextBatch;
    public BatchToArchiveEmailMessages(String c, Boolean nb) {
        this.whereClause = c;
        this.runNextBatch = nb;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> caseCloseStatus = system.label.ClosedCaseStatusValues.split(',');
        List<String> toEmailAddresses = system.label.EmailAddressToNotifyArchival!=null ? system.label.EmailAddressToNotifyArchival.split(';'): new List<String>();
         String query = '';
        if(String.isEmpty(this.whereClause)) {
			String clause = 'Status IN '+caseCloseStatus;
            query = 'SELECT Id, ActivityId, BccAddress, CcAddress, CreatedById, CreatedDate, FromAddress, FromName, ' +
                                         'HasAttachment, Headers,Incoming, IsDeleted, LastModifiedById, LastModifiedDate, LegacyIDUnique__c,' +
                                         'LegacyID__c, Status, LegacySystem__c, MessageDate, MessageIdentifier, PKIDEmailMessage__c,ParentId, RelatedToId, ' +
                                         'ReplyToEmailMessageId, Subject, SystemModstamp, ThreadIdentifier, ToAddress, ValidatedFromAddress, HtmlBody, ' +
                                         'EmailTemplateId,FirstOpenedDate,IsBounced,IsExternallyVisible,IsOpened,IsTracked,LastOpenedDate,IsClientManaged ' +
                                         'FROM EmailMessage WHERE '+
                                         'ParentId IN(SELECT Id FROM Case WHERE isClosed=true OR Status IN:caseCloseStatus)';
        }
        else {
            query = 'SELECT Id, ActivityId, BccAddress, CcAddress, CreatedById, CreatedDate, FromAddress, FromName, ' +
                                         'HasAttachment, Headers,Incoming, IsDeleted, LastModifiedById, LastModifiedDate, LegacyIDUnique__c,' +
                                         'LegacyID__c, Status, LegacySystem__c, MessageDate, MessageIdentifier, PKIDEmailMessage__c,ParentId, RelatedToId, ' +
                                         'ReplyToEmailMessageId, Subject, SystemModstamp, ThreadIdentifier, ToAddress, ValidatedFromAddress, HtmlBody, ' +
                                         'EmailTemplateId,FirstOpenedDate,IsBounced,IsExternallyVisible,IsOpened,IsTracked,LastOpenedDate,IsClientManaged ' +
                                         'FROM EmailMessage WHERE '+ this.whereClause;       
        }
        
        if(!toEmailAddresses.isEmpty()) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.toAddresses = toEmailAddresses;
            Organization org =[SELECT Id FROM Organization];
            mail.subject = 'Archive Email Messages job started on org: '+org.Id;
            mail.plainTextBody= 'BatchToArchiveEmailMessages batch job started. JobId : '+bc.getJobId();
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage> {mail});
        }
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<EmailMessage> scope) {
        try 
        {
            Map<Id,ArchivedEmailMessage__c> mapOfEmailIdVsArchiveRcd = new Map<Id,ArchivedEmailMessage__c>();
            Map<Id,Attachment> mapOfEmailMIdVsAttachments = new Map<Id,Attachment>();
            List<Attachment> lstOfAttchmentToInsert = new List<Attachment>();
            List<Attachment> lstOfEmailMessageRelationRecordsCsv = new List<Attachment>();
            List<ContentDocumentLink> lstContDoclinks = new List<ContentDocumentLink>();
            Map<String,String> emailIdVsArchiveMessId = new Map<String, String>();
            List<String> emailMessageIds = new List<String>();
            for(EmailMessage em:scope){
                emailMessageIds.add(em.Id);
            }
            for(ArchivedEmailMessage__c aem:[Select Id,LegacyID__c from ArchivedEmailMessage__c where LegacyID__c IN:emailMessageIds ]){
                emailIdVsArchiveMessId.put(aem.LegacyID__c, aem.Id);
            }
            /**Creating ArchivedEmailMessage object record and from emailMessage**/
            if(!scope.isEmpty() && scope.size()>0) {
                for(EmailMessage em:scope)
                {
                    if(em != null && !emailIdVsArchiveMessId.containsKey(em.Id)) {
                        ArchivedEmailMessage__c archiveEmail = new ArchivedEmailMessage__c(
                            Name = String.isNotBlank(em.Subject)? em.Subject.Length()>80 ? em.Subject.substring(0, 80) : em.Subject : '',
                            Case__c = em.ParentId,
                            LegacyID__c = em.Id,
                            BccAddress__c = em.BccAddress,
                            CcAddress__c = em.CcAddress,
                            FirstOpenedDate__c = em.FirstOpenedDate,
                            FromAddress__c = em.FromAddress,
                            FromName__c = em.FromName,
                            HasAttachment__c = em.HasAttachment,
                            Headers__c = em.Headers,
                            Incoming__c = em.Incoming,
                            IsExternallyVisible__c = em.IsExternallyVisible,
                            MessageDate__c = em.messagedate.year()<1700?em.createddate:em.messagedate,
                            PKIDEmailMessage__c = em.PKIDEmailMessage__c,
                            Status__c = em.Status,
                            Subject__c =em.Subject,
                            ToAddress__c = em.ToAddress,
                            LegacyIDUnique__c = em.LegacyIDUnique__c,
                            LegacySystem__c = em.LegacySystem__c,
                            MessageIdentifier__c = em.MessageIdentifier,
                            ReplyToEmailMessageId__c = em.ReplyToEmailMessageId,
                            ValidatedFromAddress__c = em.ValidatedFromAddress,
                            EmailTemplateId__c = em.EmailTemplateId,
                            IsOpened__c = em.IsOpened,
                            IsTracked__c = em.IsTracked,
                            LastOpenedDate__c = em.LastOpenedDate,
                            IsClientManaged__c = em.IsClientManaged,
                            ThreadIdentifier__c = em.ThreadIdentifier,
                            IsBounced__c = em.IsBounced,
                            EmailMessage_CreatedBy__c = em.CreatedById,
                            EmailMessage_CreatedDate__c = em.CreatedDate,
                            EmailMessage_LastModifiedBy__c = em.LastModifiedById,
                            EmailMessage_LastModifiedDate__c = em.LastModifiedDate
                        );
                        Attachment htmlBody = new Attachment(Name= String.isNotBlank(em.Subject)? em.Subject.Length()>245 ? em.Subject.substring(0,245):em.Subject+'.html':'blank__.html',Body = em.HtmlBody!=null?Blob.valueOf(em.HtmlBody):Blob.valueOf('Html body is Empty.'));
                        mapOfEmailMIdVsAttachments.put(em.Id,htmlBody);
                        mapOfEmailIdVsArchiveRcd.put(em.Id, archiveEmail);
                    }
                }
            }
            //Inserting ArchivedEmailMessage__c object records.
            if(!mapOfEmailIdVsArchiveRcd.isEmpty()){
                database.insert(mapOfEmailIdVsArchiveRcd.values(),false);
            }
            /**Adding ParentId to Attachments. start **/
            for(ArchivedEmailMessage__c aem:mapOfEmailIdVsArchiveRcd.values()){
                if(mapOfEmailMIdVsAttachments.containsKey(aem.LegacyID__c) && aem.Id!=null){
                    Attachment attach =mapOfEmailMIdVsAttachments.get(aem.LegacyID__c);
                    attach.ParentId = aem.Id;
                    lstOfAttchmentToInsert.add(attach);
                } 
            }
            /**Adding ParentId to Attachments. end **/
            if(!mapOfEmailIdVsArchiveRcd.isEmpty()){
                lstContDoclinks              		=  cloneContentDocumentLinks(mapOfEmailIdVsArchiveRcd);
                lstOfEmailMessageRelationRecordsCsv = cloneEmailMessageRelationRecordsCsv(mapOfEmailIdVsArchiveRcd);
                if(!lstOfAttchmentToInsert.isEmpty()) {
                    database.insert(lstOfAttchmentToInsert,false);
                }               
                if(!lstContDoclinks.isEmpty()) {
                    database.insert(lstContDoclinks, false);
                }
                if(!lstOfEmailMessageRelationRecordsCsv.isEmpty()) {
                     database.insert(lstOfEmailMessageRelationRecordsCsv,false);
                }
            }
            
        } catch(Exception ex) {
            UtilityClass.createApexLogRecord(ex, 'BatchToArchiveEmailMessages', 'execute'); 
        } 
    }
    
    public void finish(Database.BatchableContext bc){
        
        List<String> toEmailAddresses = system.label.EmailAddressToNotifyArchival!=null ? system.label.EmailAddressToNotifyArchival.split(';'): new List<String>();
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                              TotalJobItems, CreatedBy.Email, ExtendedStatus
                              FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        if(!toEmailAddresses.isEmpty()) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.toAddresses = toEmailAddresses;
            Organization org =[SELECT Id FROM Organization];
            mail.subject = 'Archive Email Messages job ended on org: '+org.Id;
            mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +
                                       ' batches with '+ a.NumberOfErrors + ' failures. BatchToArchiveEmailMessages batch job ended. JobId : '+bc.getJobId());
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        }
        if(a.NumberOfErrors>0 && a.ExtendedStatus.contains('Apex heap size too large')){
            database.executeBatch(new BatchToArchiveEmailMessages( this.whereClause ,this.runNextBatch ),30);
        }
        if(a.NumberOfErrors == 0 && this.runNextBatch){
        	database.executeBatch(new BatchToCloneAttachments('',true),2);
        }
    }
    
    private static List<Attachment> cloneEmailMessageRelationRecordsCsv(Map<Id,ArchivedEmailMessage__c> mapOfEmailIdVsArchiveRcd ) {
        /**Cloning all EmailMessageRelation records csv to archival record. start**/
        List<Attachment> lstOfAttchmentToInsert = new  List<Attachment>();    
        Map<String, List<String>> mapOfEmailMIdVsLstOfERelationRcd = new Map<String, List<String>>();
        List<ContentDocumentLink> lstContDoclinks = new List<ContentDocumentLink>();
        for(EmailMessageRelation emr:[Select Id, CreatedById, CreatedDate, EmailMessageId, IsDeleted, RelationAddress, RelationId, 
                                      RelationObjectType, RelationType, SystemModstamp 
                                      From EmailMessageRelation 
                                      where EmailMessageId IN:mapOfEmailIdVsArchiveRcd.keyset()])
        {
            List<String> csvRowdata= new List<String>{emr.Id, emr.CreatedById, emr.CreatedDate.format('M/d/yyyy h:mm:ss a z'), emr.EmailMessageId,string.valueOf(emr.IsDeleted), emr.RelationAddress, emr.RelationId,
                emr.RelationObjectType, emr.RelationType, emr.SystemModstamp.format('M/d/yyyy h:mm:ss a z')};
                    String csvRcdString = String.join(csvRowdata,',');
            csvRcdString = csvRcdString.replace('\n',' ');
            if(mapOfEmailMIdVsLstOfERelationRcd.containsKey(emr.EmailMessageId)){
                mapOfEmailMIdVsLstOfERelationRcd.get(emr.EmailMessageId).add(csvRcdString);
            }else{
                mapOfEmailMIdVsLstOfERelationRcd.put(emr.EmailMessageId, new List<String>{csvRcdString});
            }
        }        
        for(String emailMessageId: mapOfEmailMIdVsLstOfERelationRcd.keySet()){
            if(mapOfEmailIdVsArchiveRcd.get(emailMessageId).Id!=null){
                List<String> emailRelationRcdLst = mapOfEmailMIdVsLstOfERelationRcd.get(emailMessageId);
                String csvHeader = 'Id, CreatedById, CreatedDate, EmailMessageId, IsDeleted, RelationAddress, RelationId, RelationObjectType, RelationType, SystemModstamp \n';
                String csvFileBody = csvHeader + String.join(emailRelationRcdLst,'\n');
                Attachment csvFile = new Attachment(ParentId=mapOfEmailIdVsArchiveRcd.get(emailMessageId).Id,Name ='EmailMessageRelation_'+emailMessageId+'.csv', Body = Blob.valueOf(csvFileBody));
                lstOfAttchmentToInsert.add(csvFile);
            }
        }
        return lstOfAttchmentToInsert; 
        /**Cloning all EmailMessageRelation records csv to archival record. end**/
    } 
    private static List<ContentDocumentLink> cloneContentDocumentLinks(Map<Id,ArchivedEmailMessage__c> mapOfEmailIdVsArchiveRcd ){
        /**Cloning all email messages ContentDocumentLink into arvhive email records. Start**/
        List<ContentDocumentLink> lstOfContentDocLinkToInsert = new List<ContentDocumentLink>();
        Map<String,List<String>> mapOfParentIdVsAttachmentCsvRcds = new Map<String,List<String>>();
        for(ContentDocumentLink doc:[SELECT Id, LinkedEntityId, ContentDocumentId, ShareType, Visibility 
                                     FROM 
                                     ContentDocumentLink 
                                     WHERE LinkedEntityId IN:mapOfEmailIdVsArchiveRcd.keyset()])
        {
            if(mapOfEmailIdVsArchiveRcd.get(doc.LinkedEntityId).Id!=null){
                ContentDocumentLink cloneDocLink = doc.clone(false, true, true, true);
                cloneDocLink.LinkedEntityId = mapOfEmailIdVsArchiveRcd.get(doc.LinkedEntityId).Id;
                lstOfContentDocLinkToInsert.add(cloneDocLink);
            }
        }
        return lstOfContentDocLinkToInsert;
        /**Cloning all email messages ContentDocumentLink into arvhive email records. end**/
    }
}