objects/ArchivedEmailMessage__c.object
<CustomObject>
    <label>Archived Email Message</label>
    <nameField>
        <label>ArchivedEmailMessages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Email Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ClosedReason__c</fullName>
        <description>SFDC1-251 Closed reason for when the case gets closed.</description>
        <inlineHelpText>Please populate the reason for case closure.</inlineHelpText>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completeness</fullName>
                </value>
                <value>
                    <fullName>Consistency</fullName>
                </value>
                <value>
                    <fullName>Correctness</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Customer Usage Error</fullName>
                </value>
                <value>
                    <fullName>Data Republished</fullName>
                </value>
                <value>
                    <fullName>Documentation Provided</fullName>
                </value>
                <value>
                    <fullName>Documentation Updated</fullName>
                </value>
                <value>
                    <fullName>Duplicates</fullName>
                </value>
                <value>
                    <fullName>Expected Behavior</fullName>
                </value>
                <value>
                    <fullName>Fixed in New Version</fullName>
                </value>
                <value>
                    <fullName>General Question</fullName>
                </value>
                <value>
                    <fullName>Incident Resolved</fullName>
                </value>
                <value>
                    <fullName>Issue on Client Side</fullName>
                </value>
                <value>
                    <fullName>Known Issue/Bug</fullName>
                </value>
                <value>
                    <fullName>No Action Required</fullName>
                </value>
                <value>
                    <fullName>Outage Resolved</fullName>
                </value>
                <value>
                    <fullName>Permissions Updated</fullName>
                </value>
                <value>
                    <fullName>Product Limitation</fullName>
                </value>
                <value>
                    <fullName>Query Answered</fullName>
                </value>
                <value>
                    <fullName>Referred to Sales</fullName>
                </value>
                <value>
                    <fullName>Resolution Steps Provided</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Training Provided</fullName>
                </value>
                <value>
                    <fullName>Workaround Provided</fullName>
                </value>
                <value>
                    <fullName>Referred to Training</fullName>
                </value>
                <value>
                    <fullName>Data Corrected</fullName>
                </value>
                <value>
                    <fullName>Data Corrected.</fullName>
                    <isActive>false</isActive>
                    <label>Data Corrected.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-251 A checkbox used to have the user confirm that the contact is an internal contact (contains @ihsmarkit.com email)
SFDC1- 7772 Checkbox should be unchecked</description>
        <inlineHelpText>Please tick this box if the associated contact is internal (Someone@IhsMarkit.com)</inlineHelpText>
        <label>Contact Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResolutionDescription__c</fullName>
        <description>SFDC1-251 A long description on how the case was resolved.</description>
        <inlineHelpText>Please populate a detailed description of how the case was resolved.</inlineHelpText>
        <label>Resolution Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SkillLevel__c</fullName>
        <description>SFDC1-251 Skill level that was required for case resolution.</description>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - General</fullName>
                </value>
                <value>
                    <fullName>2 - Technical</fullName>
                </value>
                <value>
                    <fullName>3 - Technical Expert</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchToArchiveEmailMessages.cls
@isTest
public class TestBatchToArchiveEmailMessages {
    
    @isTest
    private static void testBatchJob(){
        
        Account a = TestUtility.createTestAccount('Account ArchiveEmailMessages', true);
        
        Contact c = new Contact( firstname = 'Test', lastname = 'testArchiveEmailMessages', AccountId = a.Id, email='test@ishmarkit.com');
        insert c;       
        
        ProductGroup__c pg = new ProductGroup__c(Name = 'NRG');
        insert pg;
        
        Case testCase = new Case(subject = 'Test subject ArchiveEmailMessages',AccountId = a.Id,contactId = c.Id,ProductGroup__c = pg.Id, status='Closed - Canceled',
                                 ResolutionDescription__c='test email archive',SkillLevel__c='1 - General',ClosedReason__c='No Action Required',
                                Type='Access',ContactValidation__c=true,RecordTypeId='0120P000000tGrqQAE');
        insert testCase;
        
        EmailMessage emailMessage = new EmailMessage(status = '3',fromName = 'test archival',subject = 'This is the Subject!', htmlBody = '<html><body><b>Hello</b></body></html>',
                                                     ParentId=testCase.Id); 
        insert emailMessage; // insert 
         
         
        EmailMessageRelation emr = new EmailMessageRelation(emailMessageId = emailMessage.Id,relationId = c.Id, relationType = 'FromAddress'); 
        insert emr;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'testEmail',
            PathOnClient = 'emailAttach.jpg',
            VersionData = Blob.valueOf('Test email content.'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [
                                            SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                        ];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink(LinkedEntityId = emailMessage.Id,ContentDocumentId = documents[0].Id,shareType = 'V');
        insert cdl;
        
        Attachment attach=new Attachment(Name='Email Attachment',body=Blob.valueOf('Email Attachment Body'),parentId = emailMessage.Id);   	
        insert attach;
        
         Test.startTest();
        BatchToArchiveEmailMessagesScheduler sh1 = new BatchToArchiveEmailMessagesScheduler();
		String sch = '0 0 23 * * ?'; 
        system.schedule('Test Archive Email', sch, sh1);
        database.executeBatch(new BatchToArchiveEmailMessages('',true));
        database.executeBatch(new BatchToCloneAttachments('',true));
        database.executeBatch(new BatchToDeleteEmailMessages(''));
        Test.stopTest();
        
        List<ArchivedEmailMessage__c> aemLst = [Select id from ArchivedEmailMessage__c];
        system.assertEquals(true, aemLst.size()>0,'ArchivedEmailMessage records are not created');
        
    }

}