objects/AutomatedRenewalsConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SFDC-3186 Hierarchical custom setting to store config settings for Automated Renewals creation process.</description>
    <fields>
        <fullName>RenewalsBatchSize__c</fullName>
        <defaultValue>200</defaultValue>
        <description>SFDC-3186 Size of each batch when running renewals scheduled jobs.</description>
        <inlineHelpText>Set this only for org default record. User/Profile specific records should not use this.</inlineHelpText>
        <label>RenewalsBatchSize</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Automated Renewals Config</label>
</CustomObject>

classes/BatchAutoCreateRenewalOppsScheduler.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 24 Aug 2020
// @description: SFDC-3186 Scheduler class for BatchAutoCreateRenewalOpps batch class. 
// 					- Scope size for batch is derived from AutomatedRenewalsConfig__c org default custom setting record. Default is 200.
//-----------------------------
public class BatchAutoCreateRenewalOppsScheduler implements Schedulable {        
    public void execute(SchedulableContext ctx) {        
        //Get batch scope size
        AutomatedRenewalsConfig__c renewalsOrgDefaultConfig = AutomatedRenewalsConfig__c.getOrgDefaults();
        Integer scopeSize=renewalsOrgDefaultConfig!=null && renewalsOrgDefaultConfig.RenewalsBatchSize__c!=null && Integer.valueOf(renewalsOrgDefaultConfig.RenewalsBatchSize__c)>0 ? Integer.valueOf(renewalsOrgDefaultConfig.RenewalsBatchSize__c) : 200;
        //Run batch
        Database.executeBatch(new BatchAutoCreateRenewalOpps(),scopeSize);
    }
}