objects/BillingScheduleLineItem__c.object
<CustomObject>
    <description>SFDC1-4488 This object is used to create a billing schedule for variable billing products.This object will be a child object to Variable Billing Schedule Object.
SFDC1-10132: Updated object label name to Volume/Variable Billing Line Item</description>
    <fields>
        <fullName>AUMBPS__c</fullName>
        <description>SFDC1-4488 This field holds the AUM BPS</description>
        <inlineHelpText>AUM Basis Point (BPS)  value provided</inlineHelpText>
        <label>AUM BPS</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AUMValue__c</fullName>
        <description>SFDC-4488 This field holds the AUM Value</description>
        <inlineHelpText>AUM value provided</inlineHelpText>
        <label>AUM Value</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingStartDate__c</fullName>
        <description>SFDC1-7471 This field will hold the Billing Start Date</description>
        <inlineHelpText>Enter a date that falls within the ‘Invoicing Month’</inlineHelpText>
        <label>Invoicing Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7471 This field will hold Contract Line Item #
SFDC1-10132 rename the label</description>
        <inlineHelpText>System populated reference to the Contract Line Item being billed</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Volume/Variable Billing Line Item</relationshipLabel>
        <relationshipName>BillingScheduleLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-1725 Contract Link to Variable Billing Schedule Object</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Volume/Variable Billing Line Items</relationshipLabel>
        <relationshipName>VolumeVariableBillingLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCreatedfromQuickAction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7472 : This is an technical field only. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</description>
        <inlineHelpText>Only for DEV purpose. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</inlineHelpText>
        <label>Is Created from Quick Action?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>SFDC1-4488: This field will be user-filled and holds the quantity</description>
        <inlineHelpText>Enter quantity being billed</inlineHelpText>
        <label>Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalUpdated__c</fullName>
        <description>SFDC1-7471 This field hold the total</description>
        <inlineHelpText>Enter the total to invoice for the billing period</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Volume/Variable Billing Line Item</label>
    <nameField>
        <displayFormat>BSL{000000}</displayFormat>
        <label>Volume/Variable Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume/Variable Billing Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMRelationship__c.object
<CustomObject>
    <description>SFDC1-2455 CM Relationships is used to track the Live CM Brokers on the Account Additional fields object</description>
    <fields>
        <fullName>BillingStartDate__c</fullName>
        <description>SFDC1-2455 CM Relationships</description>
        <label>Billing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BrokerContract__c</fullName>
        <description>SFDC1-2455 CM Relationships&apos; Broker Contract</description>
        <label>Broker Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CM Clients</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CM Relationship</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CM #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>TEXT(Opportunity__r.CurrencyIsoCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>BillingPeriods__c</fullName>
        <description>SFDC1-7471 This field holds the Billing Period</description>
        <inlineHelpText>Please enter the Billing Period</inlineHelpText>
        <label>Billing Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingScheduleTotal__c</fullName>
        <description>SFDC1-9599: Sum of all Billing Schedule Line items</description>
        <inlineHelpText>Sum of all Billing Schedule Line items</inlineHelpText>
        <label>Billing Schedule Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BillingScheduleType__c</fullName>
        <description>SFDC-7471 This field holds the Billing Schedule Type</description>
        <inlineHelpText>Please select the Billing Schedule Type</inlineHelpText>
        <label>Billing Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Milestone</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>T &amp; M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>SFDC1-2298</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBillingScheduleLineItemMethods.cls
//-----------------------------
    // @author: Mohit Modi
    // @date: 16 April 2018
    // @description: SFDC1-7472 : Test method for BillingScheduleLineItemMethods Class
    // @return: None
    //------------------------------
@isTest
private class TestBillingScheduleLineItemMethods {
    
    //-----------------------------
    // @author: Mohit Modi
    // @date: 16 April 2018
    // @description: SFDC1-7472 : Test method for CreateCloneBillingScheduleLIFromCLIandPreventBSLICreation
    // @return: None
    //------------------------------
    @isTest
    static void testCreateCloneBillingScheduleLIFromCLIandPreventBSLICreation() {
    
        
        test.startTest();
        
        ContractLineItem__c  testCLI = [Select ID, BillingPeriods__c,BillingScheduleType__c, CurrencyIsoCode FROM ContractLineItem__c limit 1];
        // Creating the BSLI record with IsCreatedfromQuickAction__c = true as equal to be created by Quick Action
        BillingScheduleLineItem__c testBSLI = new BillingScheduleLineItem__c (CurrencyIsoCode = testCLI.CurrencyIsoCode,IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id,BillingStartDate__c = System.Today());
        insert testBSLI ;
        
        // Checking that the remaing BSLI record has to be created equal to CLI's Billing Period
        integer bSLIcreated = [select count() from BillingScheduleLineItem__c where ContractLineItem__c = : testCLI.id ];
        System.assertEquals(BSLIcreated ,testCLI.BillingPeriods__c,'Verify Billing period');
        
        // Updating Billing Period on CLI
        testCLI.BillingScheduleType__c = 'Quarterly';
        testCLI.BillingPeriods__c = 5;
        update testCLI;
        
        BillingScheduleLineItem__c testBSLI1 = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id,BillingStartDate__c = System.Today().addMonths(10));
        insert testBSLI1 ;
        
        // Checking that the remaing BSLI record has to be created equal to CLI's Billing Period
        BSLIcreated = [select count() from BillingScheduleLineItem__c where ContractLineItem__c = : testCLI.id ];
        System.assertEquals(BSLIcreated ,testCLI.BillingPeriods__c,'Verify Billing period');
        
        // Updating Billing Period on CLI
        testCLI.BillingScheduleType__c = 'Semi-annual';
        testCLI.BillingPeriods__c = 6;
        update testCLI;
        
        BillingScheduleLineItem__c testBSLI2 = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id,BillingStartDate__c = System.Today().addMonths(20));
        insert testBSLI2 ;
        
        // Checking that the remaing BSLI record has to be created equal to CLI's Billing Period
        BSLIcreated = [select count() from BillingScheduleLineItem__c where ContractLineItem__c = : testCLI.id ];
        System.assertEquals(BSLIcreated ,testCLI.BillingPeriods__c,'Verify Billing period');
        
        //Reducing the Billing Period on CLI
        testCLI.BillingPeriods__c = 1;
        update testCLI;
        
        try {
             //Trying to insert new BSLI using Quick action after reducing the CLI Billing Period, Error Should be thrown.
             BillingScheduleLineItem__c testBSLI3 = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id);
             insert testBSLI3 ;
        } catch (exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.BSLIErrorOnQuickActionOnCLI) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true,'Verify Billing period');
        }
    }
    
    //-----------------------------
    // @Author: Sruti Srivastava
    // @Date: 4 Sept 2018
    // @description: SFDC1-9599 : Test method for rollupValuesToContractLineItem
    // @return: None
    //------------------------------
    @isTest
    static void testRollupValuesToContractLineItemOnInsert() {    
        ContractLineItem__c testCLI = [Select Id,CurrencyIsoCode FROM ContractLineItem__c limit 1];
        
        //Creating the BSLI record, 4 BillingScheduleLineItem are created based on BillingPeriods on Contract Line item
        BillingScheduleLineItem__c testBSLI = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,
                                                                              AUMBPS__c = 'test',AUMValue__c = 'test',
                                                                              Quantity__c = 1,ContractLineItem__c = testCLI.id,CurrencyIsoCode = testCLI.CurrencyIsoCode,
                                                                             TotalUpdated__c = 90);
        test.startTest();
        insert testBSLI;
        // Checking if BillingScheduleTotal on ContractLineItem got rolled up correctly
        ContractLineItem__c objCLIUpdated = [select BillingScheduleTotal__c from ContractLineItem__c limit 1 ];
        system.assertEquals(objCLIUpdated.BillingScheduleTotal__c, 360,'Verify Billing schedule total');
        test.stopTest();
        
    }
    
    //-----------------------------
    // @Author: Sruti Srivastava
    // @Date: 4 Sept 2018
    // @description: SFDC1-9599 : Test method for rollupValuesToContractLineItem when records are updated
    // @return: None
    //------------------------------
    @isTest
    static void testRollupValuesToContractLineItemOnUpdate() {
        ContractLineItem__c testCLI = [Select Id,CurrencyIsoCode,Contract__r.CurrencyIsoCode,Contract__r.Currency__c FROM ContractLineItem__c limit 1];      
        //Creating the BSLI record, 4 BillingScheduleLineItem are created based on BillingPeriods on Contract Line item
        BillingScheduleLineItem__c testBSLI = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,
                                                                              AUMBPS__c = 'test',AUMValue__c = 'test',
                                                                              Quantity__c = 1,ContractLineItem__c = testCLI.id,CurrencyIsoCode = testCLI.CurrencyIsoCode,
                                                                             TotalUpdated__c = 90);
        
        insert testBSLI;
        
        // Checking if BillingScheduleTotal on ContractLineItem got rolled up correctly on insert
        ContractLineItem__c objCLIUpdated = [select BillingScheduleTotal__c from ContractLineItem__c limit 1 ];
        system.assertEquals(objCLIUpdated.BillingScheduleTotal__c, 360,'Verify Billing schedule total');
        
        test.startTest();
        
        testBSLI.TotalUpdated__c = 50;
        update testBSLI;
        
        test.stopTest();
        // Checking if BillingScheduleTotal on ContractLineItem got rolled up correctly on update
        ContractLineItem__c objCLIUpdated2 = [select BillingScheduleTotal__c from ContractLineItem__c limit 1 ];
        system.assertEquals(objCLIUpdated2.BillingScheduleTotal__c, 320,'Verify Billing schedule total');
    }

    //-----------------------------
    // @Author: Sruti Srivastava
    // @Date: 4 Sept 2018
    // @description: SFDC1-9599 : Test method for rollupValuesToContractLineItem which is caled 
    // @return: None
    //------------------------------
    @isTest
    static void testRollupValuesToContractLineItemOnDelete() {
        ContractLineItem__c testCLI = [Select Id, CurrencyIsoCode FROM ContractLineItem__c limit 1];
        //Creating the BSLI record, 4 BillingScheduleLineItem are created based on BillingPeriods on Contract Line item
        BillingScheduleLineItem__c testBSLI = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,
                                                                              AUMBPS__c = 'test',AUMValue__c = 'test',
                                                                              Quantity__c = 1,ContractLineItem__c = testCLI.id,CurrencyIsoCode = testCLI.CurrencyIsoCode,
                                                                             TotalUpdated__c = 90);
        
        insert testBSLI;
        
        // Checking if BillingScheduleTotal on ContractLineItem got rolled up correctly on insert
        ContractLineItem__c objCLIUpdated = [select BillingScheduleTotal__c from ContractLineItem__c limit 1 ];
        system.assertEquals(objCLIUpdated.BillingScheduleTotal__c, 360,'Verify Billing schedule total');
        
        test.startTest();
        // all records are deleted
        delete [select Id From BillingScheduleLineItem__c];
        
        test.stopTest();
        // Checking if BillingScheduleTotal on ContractLineItem showing correct value on delete
        ContractLineItem__c objCLIUpdated2 = [select BillingScheduleTotal__c from ContractLineItem__c limit 1 ];
        system.assertEquals(objCLIUpdated2.BillingScheduleTotal__c, 0,'Verify Billing schedule total');
    }
    
     //-----------------------------
    // @Author: Sruti Srivastava
    // @Date: 4 Sept 2018
    // @description: SFDC1-9599 : Testsetup method for creating test data for rollupValuesToContractLineItem which is caled 
    // @return: None
    //------------------------------
    @testSetup static void createTestData() {
        Account a = TestUtility.createTestAccount('Account testrollpu', true);
        Contact c = TestUtility.createContact(a.Id,'1testing@3test.com' ,true,'Test', 'testSetCaseAdditionalFieldsObject');
        
        //creating contract
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntityWithEligibleFields('testLegalEntity','USD',true,
                                                                  'No', 'No', 'Yes', 'No', 'No', 'No', 'No');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        
        Opportunity testOpportunity1 = TestUtility.createOpportunity(a.Id, 'test Opppy', false);
        testOpportunity1.CurrencyIsoCode = 'USD';
        insert testOpportunity1;
        
        /*OpportunityContactRole oppContactRole1 = new OpportunityContactRole ();
        oppContactRole1.OpportunityId = testOpportunity1.id;
        oppContactRole1.ContactId = c.id;
        oppContactRole1.IsPrimary = true;        
        insert new List<OpportunityContactRole> {oppContactRole,oppContactRole1};			
		*/
        
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id trailRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Trial').getRecordTypeId();
        
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,false);
        contract1.Opportunity__c = testOpportunity1.Id;
        insert contract1;
        
        // Creating the CLI record
        ContractLineItem__c  testCLI = TestUtility.createContractLineItem('TestCLI',contract1.id,testProd.id,false);
        testCLI.BillingPeriods__c = 4;
        testCLI.BillingScheduleType__c = 'Monthly';
        insert testCLI;
        
    }
}