objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesPlan__c.object
<CustomObject>
    <description>SFDC-5363 The object is created to store the Sales Plan details in Salesforce</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SFDC-5363 Field to store the plan amount for the product</description>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Businessline associated with the Plan</description>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <description>SFDC-5363 Field to store the plan start date</description>
        <label>Sales Plan Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroupName__c</fullName>
        <label>Product Group Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Product Group associated with the Plan</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5363 Field to store the Sub business line associated with the plan</description>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Sales Plans</relationshipLabel>
        <relationshipName>SalesPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Non-Recurring</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Lo</fullName>
                    <isActive>false</isActive>
                    <label>Lo</label>
                </value>
                <value>
                    <fullName>NR</fullName>
                    <isActive>false</isActive>
                    <label>NR</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <isActive>false</isActive>
                    <label>R</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Plan</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Sales Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubBusinessLine__c.object
<CustomObject>
    <description>SFDC1-2170 : This holds Sub Business Line related to Products</description>
    <label>Sub Business Line</label>
    <nameField>
        <label>Sub Business Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchCreateDailySalesPlan.cls
/*  @author: Akash Punera
*   @date: 15 Mar 2022
*   @description: Test class for BatchCreateDailySalesPlan
*/
@isTest(SeeAllData=false)
private class TestBatchCreateDailySalesPlan {
    @testSetup static void generateTestData() {
        Product2 objPro = TestUtility.createProduct('Test Product',false);
        BusinessLine__c objBl = TestUtility.createBusinessLine('Test Businessline', true);
        SubBusinessline__c objSbl= TestUtility.createSubBusinessLine('Test Sub-Businessline',true);
        productGroup__c objPg = TestUtility.createProductGroup('Test Product Group',true);
        objPro.subbusinessline__c = objSBl.id; 
        objPro.businessline2__c = objBl.id;
        objPro.productgroup__c = objPg.id;
        insert objPro;
    }
    @isTest
    static void testBatchExecute() {
        SalesPlan__c objSP = new SalesPlan__c(	Amount__c = 1200, productgroupname__c = 'Test Product Group', 
                             				 	Region__c = 'EMEA', type__c = 'Recurring', 
                                              	externalid__c = 'TestProductGroup_EMEA_Recurring_2022_1', 
                                              	period__c= date.parse('1/1/2022'));
        insert objSp;
        Test.startTest();
        BatchCreateDailySalesPlan batchCreatePlan = new BatchCreateDailySalesPlan();
        String batchId = Database.executeBatch(batchCreatePlan,200);
        System.assert(batchId!=null);
        BatchCreateDailySalesPlanScheduler createPlanSchedular = new BatchCreateDailySalesPlanScheduler();
        String cronExp = '0 0 23 * * ?'; 
        system.schedule('Test Create Plan', cronExp, createPlanSchedular); 
        List<AsyncApexJob> scheduledJob = [select ApexClassId, Id
                                           from AsyncApexJob  
                                           where JobType = 'ScheduledApex'];
        system.assert(scheduledJob.size() > 0);
        Test.stopTest();   
    }
    @isTest
    static void testUpsertWithError() {
        SalesPlan__c objSP = new SalesPlan__c(	Amount__c = 1200, productgroupname__c = 'Test Product Group', 
                             				 	Region__c = 'EMEAIncorrect', type__c = 'Incorrect', 
                                              	externalid__c = 'TestProductGroup_EMEA_R_2022_1', 
                                              	period__c= date.parse('1/1/2022'));
        List<SalesPLan__c> lstToUpsert = new List<SalesPlan__c>();
        lstToUpsert.add(objSp);
        Test.startTest();
        BatchCreateDailySalesPlan batchCreatePlan = new BatchCreateDailySalesPlan();
        batchCreatePlan.upsertSalesPlan(lstToUpsert);
        system.assert(batchCreatePlan.batchHasErrors);
        Test.stopTest();   
    }

}