objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <formula>TEXT(Contract__r.POAttached__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PO Attached</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <description>SFDC1-2060 Contract Status fields
SFDC1-7222: Adding picklist value &quot;Waiting on PO&quot;</description>
        <inlineHelpText>Please select from dropdown menu</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Signed By Customer</fullName>
                    <label>Signed by Customer</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validated PO Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-POD Pending</fullName>
                </value>
                <value>
                    <fullName>Validated-BSI Pending</fullName>
                </value>
                <value>
                    <fullName>Validated by ConsOps</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Sent to Delivery</fullName>
                </value>
                <value>
                    <fullName>Sent to OM/Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered to Customer</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved &amp; Processed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Unscheduled Termination</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <isActive>false</isActive>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                    <isActive>false</isActive>
                    <label>Received</label>
                </value>
                <value>
                    <fullName>Sent To OM</fullName>
                    <isActive>false</isActive>
                    <label>Sent To OM</label>
                </value>
                <value>
                    <fullName>Sent for Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Sent for Delivery</label>
                </value>
                <value>
                    <fullName>Waiting on PO</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on PO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NoInternalApprovalNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6282</description>
        <label>No Internal Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-6735: New Record Type Created for SOW/Consulting Usage</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-9507 : Created new RecordType for Consulting RecordType</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractAttachmentMethods.cls
/**
* @author: Ankita Singh
* @date: 18 June 2018
* @description: SFDC1-8559. After insert and After delete dispatcher event handler class that calls the functions in ContractAttachmentMethods.
* @companyname: VERTIBA
*/

public class ContractAttachmentMethods {
    
    //-----------------------------
    // @author: Ankita Singh
    // @date: 18 June 2018
    // @description: SFDC1-8559- Once the salesperson attaches the PO in custom attachments - and chooses the type 
    //              "Purchase Order" then a trigger will update  yes/no on field called "PO Attached" on the Contract and OM case
    // @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    // @companyname: VERTIBA
	// @lastmodifiedby : Mohit Modi
	// @Lastmodified description : SFDC1-9507 : adding Consulting RecordType for PO Attached Functionality. 
    //-----------------------------
    /* SFDC-2530 Commenting since PO Attached field on Contract is now dependent on the Attachment on Contract Attachment record.
    public static void updateFieldOnContract(TriggerParameters tp) {     
        if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert) {            
            try {
                Set<Id> contractIds = new Set<Id>();
                Boolean isChanged = FALSE;
                List<Contract> contractList = new List<Contract>();
                for(ContractAttachment__c c :(List<ContractAttachment__c>) tp.newList) {
                    if(c.AttachmentType__c == 'Purchase Order') {
                        // collecting associated contract id
                        contractIds.add(c.Contract__c); 
                    }
                }
                if(contractIds != null && contractIds.size() > 0) {
                    // fetching contract PO Attached Info for newly added attachment
                    Map<Id,Contract> contractMap = new Map<Id,Contract>([Select Id,POAttached__c from Contract where Id In:contractIds AND recordtype.Name IN ('Order Form','Consulting') AND POAttached__c !='Yes']);
                    if(contractMap != null && contractMap.size() > 0) {
                        for(Id c : contractMap.keySet()) {
                            // setting PO Attached to Yes since they have new attachment added
                            contractMap.get(c).POAttached__c = 'Yes';
                            isChanged = TRUE;       
                        }
                        if(isChanged == TRUE) {
                            update contractMap.values();    
                        }
                    }
                }   
            } catch (Exception e) {
                UtilityClass.createApexLogRecord(e,'ContractAttachmentMethods','updateFieldOnContract'); 
            }     
        }
        if(tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {   
            try {
                Set<Id> contractIds = new Set<Id>();
                Map<Id,ContractAttachment__c> mapOldContract =  (Map<Id,ContractAttachment__c>)tp.oldMap;
                List<Contract> contractList = new List<Contract>();
                for(ContractAttachment__c c : mapOldContract.values()) {
                    if(c.AttachmentType__c == 'Purchase Order') {
                        // collecting associated contract id
                        contractIds.add(c.Contract__c); 
                    }
                }
                if(contractIds != null && contractIds.size() > 0) {
                    // fetching contract PO Attached Info for deleted attachment
                    List<Contract> contractAttachmentList = [Select Id,POAttached__c,(Select Id from ContractAttachments__r where AttachmentType__c = 'Purchase Order' ) from Contract where Id In:contractIds AND recordtype.Name IN ('Order Form','Consulting') ];
                    if(contractAttachmentList != null && contractAttachmentList.size() > 0) {
                        for(Contract c : contractAttachmentList) {
                            if(c.ContractAttachments__r == null || c.ContractAttachments__r.size() == 0) {
                                // updating the field PO Attachment to no since they dont have any assciated attachment
                                c.POAttached__c = 'No';
                                contractList.add(c);
                            }
                        }
                        if(contractList != null && contractList.size()>0) {
                            update contractList;
                        }
                    }
                }   
            } catch (Exception e) {
                UtilityClass.createApexLogRecord(e,'ContractAttachmentMethods','updateFieldOnContract'); 
            }     
        } 
        
    }*/
    
    //-----------------------------
    // @author: Dev Aggarwal
    // @date: 07 November 2019
    // @description: SFDC-2037- Set the record type on Contract Attachment record same as the record type of the parent contract.
    // @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    //-----------------------------    
    public static void setRecordTypeFromContract(TriggerParameters tp) {                
        Set<Id> contractIds = new Set<Id>();        
        for(ContractAttachment__c conAttach : (List<ContractAttachment__c>) tp.newList) {
            System.debug('conAttach.RecordTypeId='+conAttach.RecordTypeId);
            contractIds.add(conAttach.contract__c);
        }
        if(contractIds.size() > 0) {
            Map<id, Contract> contractsMap = new Map<Id, Contract>([SELECT Id, RecordType.Name FROM Contract WHERE Id IN :contractIds]);            
            for(ContractAttachment__c conAttObj : (List<ContractAttachment__c>) tp.newList) {				
                if(contractsMap.containsKey(conAttObj.Contract__c) && String.isNotBlank(contractsMap.get(conAttObj.Contract__c).Recordtype.Name)) {
                    Id conAttRecordTypeId = Schema.SObjectType.ContractAttachment__c.getRecordTypeInfosByName().get(contractsMap.get(conAttObj.Contract__c).Recordtype.Name).getRecordTypeId();                    
                    if(conAttRecordTypeId != null) {
                        conAttObj.RecordTypeId = conAttRecordTypeId;
                    }
                }
            }
        }
    }
    //-----------------------------
    // @author: Dev Aggarwal
    // @date: 07 November 2019
    // @description: SFDC-2037- Update contract's status on the Contract Attachment AttachmentType picklist.
    // @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    //-----------------------------   	
    public static void updateContinuationContracts(TriggerParameters tp) {
        Map<Id,ContractAttachment__c> oldMap = (Map<Id,ContractAttachment__c>)tp.oldMap;
        Set<Id> contractIds = new Set<Id>();
        List<ContractAttachment__c> conAttToProcess = new List<ContractAttachment__c>(); 
        List<Contract> contractsUpdateList = new List<Contract>();
        
        for(ContractAttachment__c conAttach : (List<ContractAttachment__c>)tp.newList) {
            ContractAttachment__c oldConAttach = (oldMap!=null && oldMap.size()>0) ? oldMap.get(conAttach.Id) : null;
            if(conAttach.Contract__c != null && 
               (oldConAttach == null || (conAttach.AttachmentType__c!=oldConAttach.AttachmentType__c && (conAttach.AttachmentType__c == 'Continuation Letter' || conAttach.AttachmentType__c == 'Signed Continuation Letter')))) {
                   conAttToProcess.add(conAttach);
                   contractIds.add(conAttach.Contract__c);    
               }            
        }
        if(contractIds.size() > 0) {
        	Map<Id,Contract> contractMap = new Map<Id,contract>([SELECT Id, RecordTypeId, ContractStatus__c, Status, NoInternalApprovalNeeded__c FROM Contract 
                                                                 WHERE Id IN :contractIds AND RecordTypeId =:ContractMethods.continuationLetterRecordTypeId]);
            for(ContractAttachment__c conAttachObj: conAttToProcess) {
                Contract conObj = contractMap.get(conAttachObj.Contract__c);
                if(conAttachObj.AttachmentType__c == 'Continuation Letter' && conObj != null && conObj.ContractStatus__c!='Sent to Customer' && conObj.ContractStatus__c!='Signed By Customer') {
                    conObj.ContractStatus__c = 'Sent to Customer';
                    contractsUpdateList.add(conObj);
                }
                if(conAttachObj.AttachmentType__c == 'Signed Continuation Letter' && conObj != null && conObj.ContractStatus__c!='Signed By Customer') {
                    conObj.ContractStatus__c = 'Signed By Customer';
                    contractsUpdateList.add(conObj);
                }
            }
        }
        
        if(contractsUpdateList.size() > 0) {
            update contractsUpdateList;
        }
    }
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 05 Oct 2021
    // @description: SFDC-4568- When Contract is at stage 11, only Admins/OM/CM users can edit Contract Attachment records.
    // @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    //-----------------------------   	
    public static void updateRestrictionOnContractStage11(TriggerParameters tp) {
        Map<Id,ContractAttachment__c> oldMap = (Map<Id,ContractAttachment__c>)tp.oldMap;

		if (tp.tEvent == TriggerParameters.TriggerEvent.beforeUpdate) {
            Profile prof = [Select Id, Name from Profile where Id=:UserInfo.getProfileId() limit 1];
            String profileName = prof.Name;
			System.debug('@PD--Profilename--'+profileName);
			//check if user is admin then do not process further
			if(GlobalVariables.allowContactAttchToUpdate || profileName.containsIgnoreCase('System Admin') || profileName.containsIgnoreCase('User Support') || profileName.containsIgnoreCase('Contract Management') || profileName.containsIgnoreCase('Order Management')
			  ) {
				//no validation checks are required for system admins/CM/OM 
				System.debug('$$ Checked bypassed');
				return;
			}
			
			validateContractAttachment ((List<ContractAttachment__c>)tp.newList, tp.tEvent);
		}

    }
     
    /*
    * @author: Sharique Iqbal
    * @date: 06 Oct 2021
    * @description: SFDC-4568 Restrict users to delete Contract Attachment records when Contract Stage is at 11
    * @param TriggerParameters
    * @return void
    * @companyname IHS Markit
    */
    public static void deletionRestrictedWhenContractStage11(TriggerParameters tp) {
        Map<Id,ContractAttachment__c> oldMap = (Map<Id,ContractAttachment__c>)tp.oldMap;
        List<ContractAttachment__c> conAttToProcess = new List<ContractAttachment__c>(); 
        if (tp.tEvent == TriggerParameters.TriggerEvent.beforeDelete) {
            Profile prof = [Select Id, Name from Profile where Id=:UserInfo.getProfileId() limit 1];
            String profileName = prof.Name;
            System.debug('@PD--Profilename--'+profileName);
            //check if user is admin then do not process further
            if(profileName.containsIgnoreCase('System Admin')|| profileName.containsIgnoreCase('User Support') || profileName.containsIgnoreCase('Order Management')) {
                //no validation checks are required for system admins
                System.debug('$$ Checked bypassed');
                return; 
            }
			validateContractAttachment ((List<ContractAttachment__c>)tp.oldList,tp.tEvent);
		}
	}
	
	   /*
    * @author: Sharique Iqbal
    * @date: 06 Oct 2021
    * @description: SFDC-4568 Restrict users to create Contract Attachment records when Contract Stage is at 11
    * @param TriggerParameters
    * @return void
    * @companyname IHS Markit
    */
    public static void creationRestrictionOnContractStage11(TriggerParameters tp) {
        
        if (tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert) {
            Profile prof = [Select Id, Name from Profile where Id=:UserInfo.getProfileId() limit 1];
            String profileName = prof.Name;
            System.debug('@PD--Profilename--'+profileName);
            //check if user is admin then do not process further
            if(profileName.containsIgnoreCase('System Admin') || profileName.containsIgnoreCase('Contract Management') || profileName.containsIgnoreCase('Order Management')
               || profileName.containsIgnoreCase('General') || profileName.containsIgnoreCase('Sales Coordinator') || profileName.containsIgnoreCase('User Support') || profileName.containsIgnoreCase('Sales Ops')) {
                //no validation checks are required for system admins
                System.debug('$$Checked bypassed');
                return; 
            }
			validateContractAttachment ((List<ContractAttachment__c>)tp.newList,tp.tEvent);
		}
	}	
              
	
	public static void validateContractAttachment(List<ContractAttachment__c> conAttList, TriggerParameters.TriggerEvent evt) {
		
        Set<Id> contractIds = new Set<Id>();
        List<ContractAttachment__c> conAttToProcess = new List<ContractAttachment__c>(); 
		String ErrorMsg = (evt == TriggerParameters.TriggerEvent.beforeInsert) ? System.Label.ContractAttachmentCreationRestrictionError : System.Label.ContractAttachmentRestrictionError;
		
		for (ContractAttachment__c conAtt : conAttList) {
           if(conAtt.Contract__c != null) {
              conAttToProcess.add(conAtt);
              contractIds.add(conAtt.Contract__c);  
           }
        }
        if(contractIds.size() > 0) {
            Map<Id,Contract> contractMap = new Map<Id,contract>([SELECT Id, Status FROM Contract WHERE Id IN :contractIds]);
            for(ContractAttachment__c conAttachObj: conAttToProcess) {
                Contract conObj = contractMap.get(conAttachObj.Contract__c);
                if(conObj != null && conObj.Status == 'Complete') {
                    conAttachObj.addError(ErrorMsg);
                }    
            }  
        } 
	}	
 
}