objects/ChangeLog__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all Work Request change log data.</description>
    <fields>
        <fullName>ChangeDescription__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Change Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ChangeDocumentedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Change Documented By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <description>Formula field for Owner so that end user can&apos;t change owner manually</description>
        <formula>If( BEGINS(Owner:User.Id, &apos;005&apos;)  ,HYPERLINK(&quot;/&quot; &amp;OwnerId, Owner:User.FirstName +&apos; &apos;+ Owner:User.LastName,&apos;_self&apos;),
HYPERLINK(&quot;/lightning/setup/Queues/page?address=%2Fp%2Fown%2FQueue%2Fd%3Fid%3D&quot; &amp;  Owner:Queue.Id  ,  Owner:Queue.QueueName ,&apos;_self&apos;))</formula>
        <label>Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <description>Picklist value of Status for Work request form</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved without Job</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WRStatus__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>text(WorkRequestForm__r.RequestStatus__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WR Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Change Logs</relationshipLabel>
        <relationshipName>ChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>OrderRequestStatus__c</fullName>
        <label>Order Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved without Job</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderRequestedDate__c</fullName>
        <label>Order Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <formula>If( BEGINS(Owner:User.Id, &apos;005&apos;) ,HYPERLINK(&quot;/&quot; &amp;OwnerId, Owner:User.FirstName +&apos; &apos;+ Owner:User.LastName,&apos;_self&apos;),
HYPERLINK(&quot;/lightning/setup/Queues/page?address=%2Fp%2Fown%2FQueue%2Fd%3Fid%3D&quot; &amp; Owner:Queue.Id , Owner:Queue.QueueName,&apos;_self&apos; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Queues__mdt.object
<CustomObject>
    <label>Queue</label>
    <pluralLabel>Queues</pluralLabel>
</CustomObject>

classes/OperationsQueue.cls
//-----------------------------
// @author: Anjali
// @date: 27th May 2021
// @description: Class for passing data in operation queue related lwc components.
// @return: None
//------------------------------
public with sharing class OperationsQueue {
    
    @AuraEnabled(cacheable=true)
    public static List<Queues__mdt> queueValues(){
        return [SELECT Id, MasterLabel FROM Queues__mdt ORDER BY MasterLabel ASC];
    }
    
    @AuraEnabled(cacheable=true)
    public static list<WorkRequestForm__c> getWRFRecords(String selectedQueue) {
        list<WorkRequestForm__c> lstofWRF = new list<WorkRequestForm__c>();
        String searchID = returnQueue(selectedQueue);
        if(selectedQueue != 'All') {
        lstofWRF =[select id, name, ownerId,owner.Name, SubmittedDateTime__c, PrimarySalesContact__c,PrimarySalesContact__r.Name, RequestedDueDate__c, RequestStatus__c,
                            JobNumber__c, FormType__c from WorkRequestForm__c where ownerid =: searchID order by SubmittedDateTime__c ASC LIMIT :(Limits.getLimitQueryRows())];
        }
         else {
                lstofWRF=[select id, name, ownerId,owner.Name, SubmittedDateTime__c, PrimarySalesContact__c,PrimarySalesContact__r.Name, RequestedDueDate__c, RequestStatus__c,
                            JobNumber__c, FormType__c from WorkRequestForm__C where RequestStatus__c = 'Submitted' order by SubmittedDateTime__c asc LIMIT :(Limits.getLimitQueryRows())];
        }
        return lstofWRF;
        
    }
    
    @AuraEnabled(cacheable=true)
    public static list<changelog__c> getchangeLogRecords(String selectedQueue) {
        list<changelog__c> clResults = new list<changelog__c>();
        String searchID = returnQueue(selectedQueue);       
        if(selectedQueue != 'All') {
            clResults = [select Id, Name, OwnerId,Owner.Name,Owner__c, changedescription__c, ChangeDocumentedBy__c,ChangeDocumentedBy__r.Name, SubmittedDateTime__c,
                         WorkRequestForm__c,WorkRequestForm__r.Name, RequestStatus__c, wrstatus__c from changelog__c where ownerid =: searchID order by SubmittedDateTime__c LIMIT :(Limits.getLimitQueryRows())];
        }
        else {
            clResults = [select Id, Name, OwnerId,Owner.Name,Owner__c, changedescription__c, ChangeDocumentedBy__c,ChangeDocumentedBy__r.Name, SubmittedDateTime__c,
                         WorkRequestForm__c,WorkRequestForm__r.Name, RequestStatus__c, wrstatus__c from changelog__c where RequestStatus__c = 'Submitted' order by SubmittedDateTime__c LIMIT :(Limits.getLimitQueryRows())];
        }
        return clResults;
        
    }
    
    @AuraEnabled(cacheable=true)
    public static list<OrderRequest__c> getOrderReqRecords(String selectedQueue) {
        list<OrderRequest__c> orResults = new list<OrderRequest__c>();
        String searchID = returnQueue(selectedQueue);       
        if(selectedQueue != 'All') {
            orResults = [select id, name, ownerid,owner.Name, SubmittedDateTime__c,
                         workrequestform__c,workrequestform__r.Name, OrderRequestStatus__c,OrderRequestedDate__c from OrderRequest__c where ownerid =:searchID order by SubmittedDateTime__c LIMIT :(Limits.getLimitQueryRows()) ];//Added OrderRequestedDate__c for SFDC-4664 
        }        
        else {
            orResults = [select id, name, ownerid,owner.Name, SubmittedDateTime__c,
                         workrequestform__c,workrequestform__r.Name, OrderRequestStatus__c,OrderRequestedDate__c from OrderRequest__c where OrderRequestStatus__c = 'Submitted' order by SubmittedDateTime__c LIMIT :(Limits.getLimitQueryRows())];//Added OrderRequestedDate__c for SFDC-4664
        }
        return orResults;
        
    }
    
    public static String returnQueue(String selectedQueue) {
        String searchID;
        if (selectedQueue != 'All') {
            List<Group> queues = [Select id From Group where Type='Queue' and name =: selectedQueue LIMIT 1 ];
            if(queues.size() > 0) {
                searchID = queues[0].id;
            } else {
                searchID = null;
            }
        }
        return searchID;
    }

}