objects/ChangeLog__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all Work Request change log data.</description>
    <fields>
        <fullName>PLCJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>PLC Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>Change Logs</relationshipLabel>
        <relationshipName>ChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Change Logs</relationshipLabel>
        <relationshipName>ChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>PLCJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>PLC Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>OrderRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CreatePeerReviewTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Peer Review Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CycleStart__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Week Days</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Semi-Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Six Week Cycle</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeliverableEstimate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Deliverable Estimate</label>
        <summarizedField>JobTask__c.EstimatedHours__c</summarizedField>
        <summaryFilterItems>
            <field>JobTask__c.TaskName__c</field>
            <operation>equals</operation>
            <value>Deliverable</value>
        </summaryFilterItems>
        <summaryForeignKey>JobTask__c.PLCJob__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>EncryptionKey__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Encryption Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EncryptionRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Encryption Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPInformationInWRF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Information In WRF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPPassword__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTPPath__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Path</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTPRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPUserID__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP User ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobEstimatedHours__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Estimated Hours</label>
        <summarizedField>JobTask__c.EstimatedHours__c</summarizedField>
        <summaryForeignKey>JobTask__c.PLCJob__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobNumber__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
                <value>
                    <fullName>Ad-Hoc (non-cyclical)</fullName>
                </value>
                <value>
                    <fullName>Cyclical</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Estimate only</fullName>
                </value>
                <value>
                    <fullName>Internal Ad-Hoc</fullName>
                </value>
                <value>
                    <fullName>Internal Cyclical</fullName>
                </value>
                <value>
                    <fullName>Lights Out Process</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfCycles__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>MAX Number of Cycles = 50. You can repeat creating cyclical jobs if you need to add more than 50.</inlineHelpText>
        <label>Number Of Cycles</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityValue__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>Opportunity__r.Amount</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Order Request</label>
        <referenceTo>OrderRequest__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OtherCostEstimate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>Royalties and other data cost</inlineHelpText>
        <label>Other Cost Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeerReviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Peer Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PLCJobs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessToUse__c</fullName>
        <description>POLK-WRF: This field is used for WRF related feature on PLC Job object.</description>
        <label>Process To Use</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analytics Custom Solution</fullName>
                </value>
                <value>
                    <fullName>Analytics Loyalty</fullName>
                </value>
                <value>
                    <fullName>Analytics Loyalty Compilation</fullName>
                </value>
                <value>
                    <fullName>Analytics Mapping</fullName>
                </value>
                <value>
                    <fullName>Analytics Modeling</fullName>
                </value>
                <value>
                    <fullName>Analytics Profile</fullName>
                </value>
                <value>
                    <fullName>China data-CV</fullName>
                </value>
                <value>
                    <fullName>China data-Polkinsight</fullName>
                </value>
                <value>
                    <fullName>Commercial Account File</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-OEM List</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-OEM Stat</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-Other</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Global NewReg</fullName>
                </value>
                <value>
                    <fullName>Global PARC</fullName>
                </value>
                <value>
                    <fullName>IFOF</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>NVPP</fullName>
                </value>
                <value>
                    <fullName>NVPP Online</fullName>
                </value>
                <value>
                    <fullName>PMC</fullName>
                </value>
                <value>
                    <fullName>PolkInsight</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>RSD</fullName>
                </value>
                <value>
                    <fullName>TIP</fullName>
                </value>
                <value>
                    <fullName>TIPNet System</fullName>
                </value>
                <value>
                    <fullName>TLAS</fullName>
                </value>
                <value>
                    <fullName>VIN Decoding Products Cyclical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TotalJobEstimate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Programming Hours Estimate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PLCJobCyclicalUtility.cls
// @author: Madhusudhan karna
    // @date: 06 May 2021
    // @param:
    // @description: This is used to create the cloned Cyclical jobs/ Multipart Jobs from parent PLC job record
    // @return: None
public class PLCJobCyclicalUtility {
    // @author: Madhusudhan karna
    // @date: 06 May 2021
    // @param:
    // @description: This is used to create the cloned Cyclical jobs from Parent PLC Job record
    // @return: List<plcjob__c>
    @AuraEnabled(cacheable=false)
    public static List<plcjob__c> getPlcJobRecords(String masterPLCId) {
        plcjob__c clonedPLC = [select 
                CreatePeerReviewTask__c, id, OwnerId,Owner.Name,jobname__c, 
                JobType__c, NumberOfCycles__c, cyclestart__c, cycle__c, opportunity__c, OpportunityValue__c, 
                processtouse__c, totaljobestimate__c, othercostestimate__c, currencyisocode, 
                peerreviewer__c, encryptionrequired__c, encryptionkey__c, ftprequired__c, 
                ftpinformationinwrf__c, ftppath__c, ftpuserid__c, ftppassword__c, jobnumber__c, 
                JobEstimatedHours__c, workrequestform__c, DeliverableEstimate__c, 
                OrderRequest__c, SubmittedDate__c, StartDate__c, NegotiatedDate__c,RequestedDate__c,ChangeLog__c,
                Team1__c
                from plcjob__c where id =: masterPLCId];
        id cloneID = clonedPLC.ID;
        date nextDate = clonedPLC.StartDate__c;
        date negDate =  clonedPLC.NegotiatedDate__c ;
        date reqDate =  clonedPLC.RequestedDate__c ;
    
        //use cyclestart__c date if StartDate__c is not populated
        if (clonedPLC.StartDate__c == null ){
            nextDate = clonedPLC.cyclestart__c;
        }
        //use cyclestart__c date if NegotiatedDate__c is not populated
        if (clonedPLC.NegotiatedDate__c == null ){
            negDate = clonedPLC.cyclestart__c;
        }
        //use cyclestart__c date if RequestedDate__c is not populated
        if (clonedPLC.RequestedDate__c == null ){
            reqDate = clonedPLC.cyclestart__c;
        }
        double estimatedHours = clonedPLC.DeliverableEstimate__c;
        string nextDateDOW;
        string negDateDOW;
        string reqDateDOW;
        list<plcjob__c> newJobs = new list<plcjob__c>();
        
        //Here we iterate through the number of cycles based on the # put in the PLC Job
        //First thing that happens to set the date of the cycle based on the cycle type.
        
        for (integer i = 1; i <= clonedPLC.NumberOfCycles__c - 1; i++) {
            plcjob__c tempPLC = clonedPLC.clone(false);
            if (tempPLC.Cycle__c == 'Week Days' ){ //&& i <> 1) {
                    nextDate = nextDate.addDays(1);
                    negDate = negDate.addDays(1);
                    reqDate = reqDate.addDays(1);
            }
            else if (tempPLC.Cycle__c == 'Weekly'  ){ //&& i <> 1) {
                    nextDate = nextDate.addDays(7);
                    negDate =  negDate.addDays(7);
                    reqDate =  reqDate.addDays(7);
            }
            else if (tempPLC.Cycle__c == 'Semi-Monthly'  ){ //&& i <> 1) {
                    nextDate = nextDate.addDays(15);
                    negDate =  negDate.addDays(15);
                    reqDate =  reqDate.addDays(15);
            }
            else if (tempPLC.Cycle__c == 'Monthly'  ){ //&& i <> 1) {
                    nextDate = nextDate.addMonths(1);
                    negDate =  negDate.addMonths(1);
                    reqDate =  reqDate.addMonths(1);
            }
            else if (tempPLC.Cycle__c == 'Six Week Cycle'  ){ //&& i <> 1) {
                    nextDate = nextDate.addDays(42);
                    negDate =  negDate.addDays(42);
                    reqDate =  reqDate.addDays(42);
            }
            else if (tempPLC.Cycle__c == 'Quarterly'  ){ //&& i <> 1) {
                    nextDate = nextDate.addMonths(3);
                    negDate =  negDate.addMonths(3);
                    reqDate =  reqDate.addMonths(3);
            }
            else if (tempPLC.Cycle__c == 'Semi-Annually'  ){ //&& i <> 1) {
                    nextDate = nextDate.addMonths(6);
                    negDate =  negDate.addMonths(6);
                    reqDate =  reqDate.addMonths(6);
            }
            else if (tempPLC.Cycle__c == 'Annually'  ){ //&& i <> 1) {
                    nextDate = nextDate.addYears(1);
                    negDate =  negDate.addYears(1);
                    reqDate =  reqDate.addYears(1);
            }
            else if (tempPLC.Cycle__c == 'Other' ){ //&& i <> 1 ) {
                    nextDate = nextDate.addDays(0);
                    negDate =  negDate.addDays(0);
                    reqDate =  reqDate.addDays(0);
            }
            datetime nextDateTime = datetime.newInstance(nextDate.year(), nextDate.month(),nextDate.day());
            datetime negDateTime = datetime.newInstance(negDate.year(), negDate.month(),negDate.day());
            datetime reqDateTime = datetime.newInstance(reqDate.year(), reqDate.month(),reqDate.day());
            
            nextDateDOW = nextDateTime.format('EEEE');
            negDateDOW  = negDateTime.format('EEEE');
            reqDateDOW = reqDateTime.format('EEEE');
            
            //Backdate if Saturday or Sunday                       
            if (nextDateDOW == 'Saturday') {
                    nextDate = nextDate.addDays(-1);
            }
            if (nextDateDOW == 'Sunday') {
                    nextDate = nextDate.addDays(-2);
            }
            // Same backdate for negotiated date
            if (negDateDOW == 'Saturday') {
                    negDate = negDate.addDays(-1);
            }
            
            if (negDateDOW == 'Sunday') {
                    negDate = negDate.addDays(-2);
            }
            // Same backdate for RequestedDate__c 
            if (reqDateDOW == 'Saturday') {
                    reqDate = reqDate.addDays(-1);
            }
            if (reqDateDOW == 'Sunday') {
                    reqDate = reqDate.addDays(-2);
            }
            tempPLC.cycleoccurance__c = i;
            tempPLC.StartDate__c = nextDate;
            tempPLC.NegotiatedDate__c = negDate;
            tempPLC.RequestedDate__c = reqDate;
            //tempPLC.OwnerID = tempPLC.OwnerID;
            tempPLC.WRFQuality__c = 'No Set-up Required';
            tempPLC.ParentJob__c = cloneID;
            tempPLC.totaljobestimate__c = estimatedHours;

            newJobs.add (tempPLC);
            //Since we want the next date to be based on the standard, not backdated next date, we'll reverse what we did
            //For the next loop
            
            if (nextDateDOW == 'Saturday') {
                    nextDate = nextDate.addDays(1);
            }
            
            if (nextDateDOW == 'Sunday') {
                    nextDate = nextDate.addDays(2);
            }
        }
        return newJobs;
    }
    // @author: Madhusudhan karna
    // @date: 06 May 2021
    // @param:
    // @description: This is used to create the cloned Multipart jobs from Parent PLC Job record
    // @return: List<plcjob__c>
    @AuraEnabled
    public static List<plcjob__c> PLCJobCloneMultipartUtility(String masterPLCId) {

        plcjob__c clonedPLC = [select id, ownerid, jobname__c, JobType__c, NumberofCycles__c, 
                cyclestart__c, cycle__c, opportunity__c, opportunityvalue__c, processtouse__c,
                currencyisocode, peerreviewer__c, encryptionrequired__c,
                encryptionkey__c, ftprequired__c, ftpinformationinwrf__c, ftppath__c, 
                ftpuserid__c, ftppassword__c, workrequestform__c, jobnumber__c, NumberOfParts__c,
                //ELS added 7/17/12
                StartDate__c, NegotiatedDate__c,RequestedDate__c,ChangeLog__c, submitteddate__c
                from plcjob__c where id = :masterPLCId]; 
                
        id cloneID = clonedPLC.ID;
        
        date nextDate = clonedPLC.StartDate__c;
        date negDate =  clonedPLC.NegotiatedDate__c ;
        date reqDate =  clonedPLC.RequestedDate__c ;        
        
        
        string nextDateDOW;
        list<plcjob__c> newJobs = new list<plcjob__c>();
        integer totalJobs; 
        totalJobs = integer.valueOf(clonedPLC.NumberofParts__c);
                        
        for (integer i = 2; i <= totalJobs; i++) {
            plcjob__c tempPLC = clonedPLC.clone(false);
            tempPLC.multipartnum__c = i;
            tempPLC.StartDate__c = nextDate;
            tempPLC.NegotiatedDate__c = negDate;
            tempPLC.RequestedDate__c = reqDate;
            tempPLC.OwnerID = tempPLC.OwnerID;
            tempPLC.WRFQuality__c = 'No Set-up Required';
            tempPLC.ParentJob__c = cloneID;        
            tempPLC.isMultipart__c = True;                  
            newJobs.add (tempPLC);              
        }
        return newJobs;
    }

    //--------------------------------------------------------------------
    // @author: Uday Bikkumalla
    // @date: 30 June 2021
    // @param:
    // @description: Save PLC Jobs
    // @return:  List<PLCJob__C>
    //--------------------------------------------------------------------
    @AuraEnabled
    public static String saveCyclicPLCJobs(List<PLCJob__C> plcJobs) {
        String status = 'Failed';
        System.debug('List of PLC Jobs to be inserted: '+plcJobs);
        try {
            insert plcJobs;
            status = 'Success';
        }
        catch(AuraHandledException ex) {

            throw new AuraHandledException('Error: Unable to create cyclic jobs. '+ex.getMessage());
        }
        return status;
    }
}