objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>AssociatedProduct__r.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ContractProductAlliancePartner__c.object
<CustomObject>
    <description>SFDC-4235: Alliances Validation Tracking - to check whether the customer has a license or not to use IHS data via partners</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Product Alliance Partners</relationshipLabel>
        <relationshipName>ContractProductAlliancePartners</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroupText__c</fullName>
        <description>SFDC-4235: Alliances Validation Tracking</description>
        <label>Product Group</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contract Product Alliance Partner</label>
    <nameField>
        <displayFormat>CPAP-{000000}</displayFormat>
        <label>Contract Product Alliance Partner Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Alliance Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/multiSelectPicklist.cls
//-----------------------------
// @author: Akshay Dogra
// @date: 29 Aug 2021
// @description: SFDC-4235: Alliance Validation
// @companyname : IHS Markit
//-----------------------------
public class multiSelectPicklist {
    
    @AuraEnabled(cacheable=true)
    public static List<String> getProductGroup(String contractId) {
        List<String> ProductGroupName = new List<String>();
        Set<String> mySet = new Set<String>();
        List<ContractLineItem__c> productGroupValue = [SELECT ProductGroup__c from ContractLineItem__c Where Contract__c =: contractId ];
        for(ContractLineItem__c CLI : productGroupValue) {
            if(String.isNotBlank(CLI.ProductGroup__c)) {
                mySet.add(CLI.ProductGroup__c);
            }
        }
        ProductGroupName.addAll(myset);
        ProductGroupName.sort();
        return ProductGroupName;
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getProductGroupAlliance(String Id) {
        
        List<String> ProductGroupName = new List<String>();
        
        List<ContractProductAlliancePartner__c> productGroupValue = [SELECT ProductGroupText__c from ContractProductAlliancePartner__c Where Id =: Id ];
        for(String str : productGroupValue[0].ProductGroupText__c.split(',')) {
            ProductGroupName.add(str);
        }
        ProductGroupName.sort();
        return ProductGroupName;
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getProductGroupAll(String allianceId) {
        List<String> ProductGroupName = new List<String>(); 
        List<String> Contract = new List<String>();
        
        List<ContractProductAlliancePartner__c> contractId = [SELECT contract__c from ContractProductAlliancePartner__c Where Id =: allianceId ];
        for(ContractProductAlliancePartner__c CPAId : contractId) {
            Contract.add(CPAId.contract__c);
        }
        
        List<ContractLineItem__c> productGroupValue = [SELECT ProductGroup__c from ContractLineItem__c Where Contract__c =: Contract ];
        
        for(ContractLineItem__c CLI : productGroupValue) {
            if(String.isNotBlank(CLI.ProductGroup__c)) {
                ProductGroupName.add(CLI.ProductGroup__c);
            }
        }
        ProductGroupName.sort();
        return ProductGroupName;
    }
    @AuraEnabled
    public static Boolean getProfile() {
        Boolean profileBoolean = false;
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        system.debug('ProfileName'+profileName);
        if ( profileName.contains('Admin') ) { 
            profileBoolean = true;
        }
        else if (profileName.contains('General') ) {
            profileBoolean = true;
        }
        else if (profileName.contains('IHSMarkit Customer Care') ) {
            profileBoolean = true;
        }
        else {
            profileBoolean = false;
        }
        system.debug('ProfileName'+profileBoolean);
        return profileBoolean;
    }
}