objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning layout</description>
        <formula>Owner.FirstName + &apos; &apos; + Owner.LastName</formula>
        <inlineHelpText>Contract Owner</inlineHelpText>
        <label>Contract Owner</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/InternalApproval__c.object
<CustomObject>
    <description>SFDC1-6282: New custom junction object to provide many-to-many relationship between Contracts and Contacts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-6282: Contact
SFDC1-9701: Only emailing to internal IHSMarkit Users when using the internal approvals
SFDC1-9979: Filter Inactive user with IHMarkit mail ID
SFDC1-10610: update Internal Approval&apos;s Contact Lookup filter message
SFDC-3911: Skip filter for batch admin</description>
        <inlineHelpText>The person contact who this Internal Approval request will be sent to.</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Please select an internal IHS Markit user contact (email address ends with &quot;@ihsmarkit.com&quot;).</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>ihsmarkit.com</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>$User.FullName__c</field>
                <operation>equals</operation>
                <value>Batch Admin</value>
            </filterItems>
            <infoMessage>Only internal contact is allowed for Internal Approvals.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Internal Approvals</relationshipLabel>
        <relationshipName>Internal_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6282: Contract Owner</description>
        <inlineHelpText>Contract Created By</inlineHelpText>
        <label>Contract Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Internal_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-6282: Contract</description>
        <inlineHelpText>Contract Number</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Internal Approvals</relationshipLabel>
        <relationshipName>Internal_Approvals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-6282: Status</description>
        <inlineHelpText>Requested or Approved?</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Internal Approval</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Internal Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InternalApprovalMethods.cls
//-----------------------------
// @author: Jagadesh Kumar
// @date: 06 June 2018
// @param: NA
// @description: Class to hold trigger methods 
// @return: NA
//-----------------------------
public class InternalApprovalMethods {
    //-----------------------------
    // @author: Jagadesh Kumar
    // @date: 06 June 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-8542,SFDC1-6282: Populate the Contract Owner field of the new Internal Approval record with 
    // the Owner of the Contract on which it is created and send notification.
    // @return: NA
    //------------------------------
    public static void populateContractOwner(TriggerParameters tp) {
        Set<Id> contractIds = new Set<Id>();
        if(tp.tEvent==TriggerParameters.TriggerEvent.beforeInsert) {
            for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                contractIds.add(inApproval.Contract__c);
            }
            if(contractIds.size() > 0) {
                Map<Id,Contract> contractUserIdMap = new Map<Id,Contract>([SELECT Id,OwnerId FROM Contract 
                                                                           WHERE Id IN : contractIds]);
                for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                    if(contractUserIdMap.get(inApproval.Contract__c) != null) {
                    	inApproval.ContractOwner__c = contractUserIdMap.get(inApproval.Contract__c).OwnerId;    
                    }
                }
            }
        }
    }
    //-----------------------------
    // @author: Akshay Dogra
    // @date: 02 July 2021
    // @param: TriggerParameters tp
    // @description: SFDC-3222: Notification of the contract movement when internal approval is provided
    // @return: NA
    //------------------------------
    public static void notifyContractOwner(TriggerParameters tp) {
        Set<Id> contactIds = new Set<Id>();
        Set<Id> contractIds = new Set<Id>();
        Map<Id,InternalApproval__c> mapOldInternalApproval = (Map<Id,InternalApproval__c>)tp.oldMap;
        List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        
        List<FeedItem> FeedItemList = New List<FeedItem>();
        if(tp.tEvent==TriggerParameters.TriggerEvent.afterUpdate) {
            for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                contractIds.add(inApproval.Contract__c);
                contactIds.add(inApproval.Contact__c);
            }
            
			Map<Id,Contract> contractIdMap = new Map<Id,Contract>([SELECT Id,OwnerId FROM Contract WHERE Id IN : contractIds]);
            Map<Id,Contact> contactUserIdMap = new Map<Id,Contact>([SELECT Id,Name FROM Contact WHERE Id IN : contactIds]); 
            
            for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                if(inApproval.status__c != mapOldInternalApproval.get(inApproval.id).Status__c && (inApproval.status__c == 'Approved')) {   
                    
                    String message = 'Internal Approval has been provided by user '+ contactUserIdMap.get(inApproval.Contact__c).Name + ' ';
                    ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(UtilityClass.getChatterFeedItemInput(inApproval.contract__c,new List<String>{contractIdMap.get(inApproval.Contract__c).OwnerId},message));
                    batchInputs.add(batchInput);
                } 
            }
            if(!batchInputs.isEmpty()) {
                if(!Test.isRunningTest()) {
                    ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);
                }
            }
        }
    } 

}