objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>SFDC1-718;Only on Contract Type = Order Form</description>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Annually (First of the month)</fullName>
                </value>
                <value>
                    <fullName>Last day of the month</fullName>
                </value>
                <value>
                    <fullName>Last Day of the Quarter</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly on First of Month</fullName>
                </value>
                <value>
                    <fullName>Monthly on Last of Month</fullName>
                </value>
                <value>
                    <fullName>Multi Year</fullName>
                </value>
                <value>
                    <fullName>Multi Year for Prof. Srvcs</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Quarterly (First of the month)</fullName>
                </value>
                <value>
                    <fullName>Quarterly on Last of Month</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Two Year</fullName>
                </value>
                <value>
                    <fullName>Consulting Agreement</fullName>
                    <isActive>false</isActive>
                    <label>Consulting Agreement</label>
                </value>
                <value>
                    <fullName>Last day of the month,</fullName>
                    <isActive>false</isActive>
                    <label>Last day of the month,</label>
                </value>
                <value>
                    <fullName>Monthly on the First day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Monthly on the First day of the month</label>
                </value>
                <value>
                    <fullName>Monthly on the Last day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Monthly on the Last day of the month</label>
                </value>
                <value>
                    <fullName>Montly on the First day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Montly on the First day of the month</label>
                </value>
                <value>
                    <fullName>Montly on the Last Day of the Month</fullName>
                    <isActive>false</isActive>
                    <label>Montly on the Last Day of the Month</label>
                </value>
                <value>
                    <fullName>Multi Year for Prof Svcs</fullName>
                    <isActive>false</isActive>
                    <label>Multi Year for Prof Svcs</label>
                </value>
                <value>
                    <fullName>Non Billable</fullName>
                    <isActive>false</isActive>
                    <label>Non Billable</label>
                </value>
                <value>
                    <fullName>Quarterly last day of the month</fullName>
                    <isActive>false</isActive>
                    <label>Quarterly last day of the month</label>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                    <isActive>false</isActive>
                    <label>Semi Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fastrack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5851 Checkbox on &quot;Order From&quot; contracts
SFDC1-10429:Update Fastrack to Fast Track</description>
        <inlineHelpText>Use Fast Track terms and conditions if under $100k</inlineHelpText>
        <label>Fast Track</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GeneralAgreementType__c</fullName>
        <description>SFDC1-2209 This field helps user select the current Agreement Type that the customer has signed that is the overarching agreement the order is falling under.
SFDC1-7189- Renaming &apos;General Agreement&apos; to &apos;Master Agreemant&apos;</description>
        <inlineHelpText>The Master Agreement Type must match the title of the signed agreement to bind Client.</inlineHelpText>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IHS Markit Master Agreement</fullName>
                </value>
                <value>
                    <fullName>IHS General Agreement</fullName>
                </value>
                <value>
                    <fullName>IHS Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Markit Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>IHS Markit General Agreement</fullName>
                    <isActive>false</isActive>
                    <label>IHS Markit General Agreement</label>
                </value>
                <value>
                    <fullName>Markit General Agreement</fullName>
                    <isActive>false</isActive>
                    <label>Markit General Agreement</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IHSMarkitLegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2405 IHS Markit Legal Entity</description>
        <inlineHelpText>IHS Markit Legal Entity</inlineHelpText>
        <label>IHS Markit Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>IHSMarkitLegalEntity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <description>SFDC1-7588 hidden field to be passed in as a filter parameter to Drawloop URL</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hidden field to be passed in as a filter parameter to Drawloop URL</inlineHelpText>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContractGenerateDocumentClass.cls
/*  @author: Neha Gupta
*   @date: 20 Jan 2021
*   @description: SFDC-3096 Class to get the contract detail associated to a contract
*/
public class ContractGenerateDocumentClass {
    @AuraEnabled
    public static wrapperClass getContractInfo(String conId){
        wrapperClass wrpCon = new wrapperClass();
        //SFDC-4575 - Added IHS Markit Legal Entity Name in SOQL
        Contract con=[select id,AccountId,Opportunity__c,RecordTypeName__c,BillingFrequency__c,
                      GeneralAgreementType__c,Fastrack__c, IHSMarkitLegalEntity__r.Name 
                      from Contract where id=:conId limit 1];
        //return con;
        wrpCon.con=con;
        wrpCon.sessionid=System.UserInfo.getSessionId();
        return wrpCon;
    }
	
    public class wrapperClass{
    	 @AuraEnabled public Contract con{ get; set;}
         @AuraEnabled public String sessionid{ get; set;}
    }
}