objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/VoiceofCustomer__c.object
<CustomObject>
    <fields>
        <fullName>CustomerAccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer/ Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Voice of Customers</relationshipLabel>
        <relationshipName>Voice_of_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FileAttached__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>File Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Voice of Customer</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice of Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestContentDocumentMethods.cls
// @author: Sharique Iqbal
// @date: 23 Aug 2021
// @param: NA
// @description: Test class for ContentDocument trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestContentDocumentMethods {
      
     //-----------------------------
    // @author: Sharique
    // @date: 23 Auguest 2021
    // @param: NA
    // @description: SFDC-4182 Test Method for delete operations
    // @return: NA
    //-----------------------------
    
    @isTest  private static void testMethodDeleteFile() { 
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        Id stdPricebookId = Test.getStandardPricebookId();
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHSM test legalEntity', 'USD'); 
        Contract testContract = TestUtility.createContractWithInsertOptional(acct.Id, testLegalEntity.Id, null, stdPricebookId,true );

        ContractAttachment__c ctrtAtt = new ContractAttachment__c(AttachmentType__c = 'Purchase Order',Contract__c =testContract.id);
        insert ctrtAtt ;
        
        string before = 'Testing base 64 encode';            
        Blob beforeblob = Blob.valueOf(before);
        
        //Insert contentdocument data
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        newFileShare.contentdocumentid = testcontent.contentdocumentid;
        newFileShare.LinkedEntityId = ctrtAtt.Id;
        newFileShare.ShareType= 'V';
             
        insert new List<ContentDocumentLink>{newFileShare};
        ContractAttachment__c contrtAttach = [select Id, Contract__c, (Select Id From ContentDocumentLinks) from ContractAttachment__c limit 1];
        system.assertEquals(1, contrtAttach.ContentDocumentLinks.size());  
        
        delete [Select id from ContentDocument];
        
    }
    
     //-----------------------------
    // @author: Digvijay
    // @date: 9 Nov 2022
    // @param: NA
    // @description:  Test Method for VOC attachement operations
    // @return: NA
    //-----------------------------
    
    @isTest  private static void testMethodDeleteVOCFile() { 
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        VoiceofCustomer__c voc=new VoiceofCustomer__c(CustomerAccountName__c=acct.Id);
        insert voc;

        string before = 'Testing base 64 encode';            
        Blob beforeblob = Blob.valueOf(before);
        
        //Insert contentdocument data
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        newFileShare.contentdocumentid = testcontent.contentdocumentid;
        newFileShare.LinkedEntityId = voc.Id;
        newFileShare.ShareType= 'V';
             
        insert new List<ContentDocumentLink>{newFileShare};
        voc=[Select Id,FileAttached__c from VoiceofCustomer__c where id=:voc.id];
        system.assertEquals('Yes', voc.FileAttached__c);       
        delete [Select id from ContentDocument];
        voc=[Select Id,FileAttached__c from VoiceofCustomer__c where id=:voc.id];
        system.assertEquals('No', voc.FileAttached__c); 
        
    }
    
}