objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC-5711 : field created for better reporting.</description>
        <label>AAG</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Businessline__c</fullName>
        <description>SFDC-1346 field to store comma separated values of business lines derived from contract line items</description>
        <inlineHelpText>Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GlobalSegments__c</fullName>
        <description>SFDC-1346 field to store comma separated values of global segment derived from contract line items</description>
        <inlineHelpText>Global segments rolled up from contract line items into one single field</inlineHelpText>
        <label>Global Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2969 field to store comma separated values of Internal Business segment derived from contract line items</description>
        <inlineHelpText>Internal Business segments rolled up from contract line items into one single field</inlineHelpText>
        <label>Internal Business Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9301: Fetching value from Product Family on Opportunity
SFDC-887: change logic to have this value rolled up from Contract Line Item instead of copying from Opportunity</description>
        <inlineHelpText>Value rolled up from Contract line items</inlineHelpText>
        <label>Product Family</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <description>SFDC-1346 Roll up text field to store comma separated values of sub business line from contract line item</description>
        <inlineHelpText>Sub Business lines rolled up from contract line items into one single field</inlineHelpText>
        <label>Sub Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule
SFDC1-10060 change data type from Percentage(16, 0) to Percentage(3, 2)</description>
    <fields>
        <fullName>AssociatedProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4324 This field holds the product associated with &apos;Opportunity Line Item&apos;, to which contract line item is related.</description>
        <inlineHelpText>Product related to Opportunity Line Item</inlineHelpText>
        <label>Associated Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items (Associated Product)</relationshipLabel>
        <relationshipName>ContractLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <formula>AssociatedProduct__r.ProductGroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2298;Product Lookup field on Contract Line Item
SFDC-99 Duplicate for AssociatedProduct__c marking this as zz to delete in future</description>
        <label>zzzProduct</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <description>SFDC1-9374 calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</description>
        <inlineHelpText>This is a calculated field to list all the business lines for all the Opportunity Productswhere the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Business Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GlobalSegments__c</fullName>
        <description>SFDC-1346 Comma separated field to capure all global segments related to the opportunity product</description>
        <inlineHelpText>This is a calculated field to list all the Global segments for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Global Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2969 Comma separated field to capure all Internal Business segments related to the opportunity product</description>
        <inlineHelpText>This is a calculated field to list all the Internal Business segments for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Internal Business Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-7525 product family calculated from related products
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Product family of related products automatically populated by system</inlineHelpText>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <description>SFDC - 1346 field to capture sub business line related to the products</description>
        <inlineHelpText>This is a calculated field to list all the sub business lines for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Sub Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>SFDC1-6958: Global Segment field will be populated from the SAP Product Master and incorporated with the load to keep products in sync.</description>
        <inlineHelpText>Reporting Global Segment</inlineHelpText>
        <label>Global Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Product Family</inlineHelpText>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2624 Internal Business Segment field for Sales Product Reporting</description>
        <inlineHelpText>For Sales Product Reporting</inlineHelpText>
        <label>Internal Business Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractLineItemMethods.cls
//@Author : Jagadesh Kumar
//@Date : 20th Dec 2018
//@Description : SFDC1-10588 Trigger helper method class for ContractLineItem__c object 
//@company : Vertiba
// 
// @ModifiedBy: Tran-Vu Tran
// @ModifiedDate: 20 Feb 2019
// @Modification: SFDC-887 refactored rollupProductInfoToContract method to handle the roll-up update
// 				and resolve "invalid query locator" error when adding more than 30 products,
// 				also added logic to roll up Product Family from Contract Line Item to Contract record
// @ModifiedBy: Paras Dhingra
// @ModifiedDate: 15/07/2019
// @ModifiedDescription: SFDC-1346 Addinge new rollup fields on contract and opportunity
// @ModifiedBy: Sushma Yadav
// @ModifiedDate: 4th Jun 2020
// @ModifiedDescription: SFDC-2969 Adding new rollup field on contract and opportunity

public class ContractLineItemMethods {
    
    //@author : Jagadesh Kumar
    //@date : 20th Dec 2018
    //@description : SFDC1-10588 Rollup product group from ContractLineItem to contract level 
    //@modifiedBy: Tran-Vu Tran
    //@modifiedDate: 20 Feb 2019
    //@modifiedDescription: SFDC-887 refactored rollupProductInfoToContract method to handle the roll-up update
    // 						and resolve "invalid query locator" error when adding more than 30 products,
    // 						also added logic to roll up Product Family from Contract Line Item to Contract record
    //@param : TriggerParameters
    //@return : void
    //@companyname : Vertiba
	// @ModifiedBy: Paras Dhingra
	// @ModifiedDate: 15/07/2019
	// @ModifiedDescription: SFDC-1346 Addinge new rollup fields on contract and opportunity
    public static void rollupProductInfoToContract(TriggerParameters tp) {  
        try {
            Set<Id> contractIds = new Set<Id>();

            if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert 
                || tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate
                || tp.tEvent == TriggerParameters.TriggerEvent.afterUndelete) {
                for (ContractLineItem__c cli: (List<ContractLineItem__c>) tp.newList) {
                    contractIds.add(cli.Contract__c);
                }
            }
            
            if (tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {
                for (ContractLineItem__c cli: (List<ContractLineItem__c>) tp.oldList) {
                    contractIds.add(cli.Contract__c);
                }           
            }
            
            if (!contractIds.isEmpty()) {
                rollupProductInfoToContract(contractIds);
            }
            
        } catch(Exception ex) {
			String errMessage = ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')?
                ex.getMessage().substringAfterLast('FIELD_CUSTOM_VALIDATION_EXCEPTION,'):ex.getMessage();
            System.debug('Exception occured while rollupProductInfoToContract :' + ex.getMessage());
            UtilityClass.createApexLogRecord(ex, 'ContractLineItemMethods', 'rollupProductInfoToContract');
			tp.newList[0].addError('Error: ' + errMessage);
        }
    }
    
    //@author: Tran-Vu Tran
    //@date: 25 Feb 2019
    //@description: SFDC-887 refactored rollupProductInfoToContract method above to handle the roll-up update
    // 						and resolve "invalid query locator" error when adding too many products,
    // 						also added logic to roll up Product Family from Contract Line Item to Contract record
	// @modifiedBy: Paras Dhingra
	// @modifiedDate: 10th June 2020
	// @modifiedDescription: SFDC-99 Replacing Product__c with AssociatedProduct__c as it is a duplicate field
	// @date: 28 Feb 2022
    // @description: SFDC-5557,updated logic to use AutoCalculateRollupValueHelper class  
    public static void rollupProductInfoToContract(Set<Id> contractIds) {
		System.Savepoint sp = Database.setSavepoint();
        try {
            List<Contract> contractList = [Select Id, BusinessLine__c,SubBusinessLine__c,GlobalSegments__c,InternalBusinessSegment__c,ProductGroup__c, ProductFamily__c,AAG__c from Contract where Id in : contractIds];
            
            List<Contract> contractToBeUpdatedList = new List<Contract>();
            
            //Map<Id, List<ContractLineItem__c>> mapContract_LineItems = new Map<Id, List<ContractLineItem__c>>();
            //SFDC-1346 adding new rollup fields at contract level
            List<ContractLineItem__c> lineItemList = [Select Id, AssociatedProduct__r.ProductGroup__r.Name, AssociatedProduct__r.Family__r.Name,AssociatedProduct__r.AAG__c,Contract__c,
                                                 AssociatedProduct__r.SubBusinessLine__r.name, AssociatedProduct__r.BusinessLine2__r.Name, AssociatedProduct__r.Division__c, AssociatedProduct__r.InternalBusinessSegment__c            
                                                 FROM ContractLineItem__c where Contract__c in: contractIds and Status__c != 'Lost'];
            contractToBeUpdatedList=AutoCalculateRollupValueHelper.rollupProductInfoToParent(contractList,lineItemList,'Contract__c',Null);
            /*SFDC- 5557 Commenting this logic , AutoCalculateRollupValueHelper class will be used to calculate logic
            {
                List<ContractLineItem__c> contractLineItems = mapContract_LineItems.get(lineItem.Contract__c);
                if (contractLineItems == null) {
                    contractLineItems = new List<ContractLineItem__c>();
                }
                contractLineItems.add(lineItem);
                mapContract_LineItems.put(lineItem.Contract__c, contractLineItems);
            } 
            
            for (Contract contract : contractList) {
                List<ContractLineItem__c> contractLineItems = mapContract_LineItems.get(contract.Id);
                if (contractLineItems != null) {
                    //initialize sets and add values from related child ContractLineItems
                    Set<String> productGroups = new Set<String>();
                    Set<String> productFamilies = new Set<String>();
                    //SFDC-1346 adding string sets for business line, sub business line and global segment(division__c) #start
                    Set<String> productBusinessLine = new Set<String>();
                    Set<String> productSubBusinessLine = new Set<String>();
                    Set<String> productGlobalSegment = new Set<String>();
                    //SFDC-1346 #end
                    //SFDC-2969 adding string set for internal business segment
                    Set<String> productInternalBusinessSegment = new Set<String>();
                    for (ContractLineItem__c lineItem : contractLineItems) {
                        // getting the Product Group Name from the Contract Line Item's Product
                        if (lineItem.AssociatedProduct__r.ProductGroup__r.Name != null) {
                            productGroups.add(lineItem.AssociatedProduct__r.ProductGroup__r.Name.trim());                                                                      
                        }
                        
                        // getting the Product Family Name from the Contract Line Item's Product
                        if (lineItem.AssociatedProduct__r.Family__r.Name != null) {
                            productFamilies.add(lineItem.AssociatedProduct__r.Family__r.Name.trim());                                                                      
                        }
                        //SFDC-1346 #start
                        // getting the Business line from the Contract line item's product
                        if (lineItem.AssociatedProduct__r.BusinessLine2__r.Name!=null) {
                            productBusinessLine.add(lineItem.AssociatedProduct__r.BusinessLine2__r.Name.trim());
                        }
                        if (lineItem.AssociatedProduct__r.SubBusinessLine__r.Name!=null) {
                            productSubBusinessLine.add(lineItem.AssociatedProduct__r.SubBusinessLine__r.Name.trim());
                        }
                        if (lineItem.AssociatedProduct__r.Division__c!=null) {
                            productGlobalSegment.add(lineItem.AssociatedProduct__r.Division__c);
                        }
                        //SFDC-1346 #end
                        //SFDC-2969
                        if (lineItem.AssociatedProduct__r.InternalBusinessSegment__c!=null) {
                            productInternalBusinessSegment.add(lineItem.AssociatedProduct__r.InternalBusinessSegment__c);
                        }
                    }
                    
                    contract.ProductGroup__c = '';
                    //process product groups and create comma separated values
                    if (productGroups.size() > 0) { 
                        List<String> productGroupList = new List<String>(productGroups);
                        productGroupList.sort();
                        contract.ProductGroup__c = String.join(productGroupList, ',');     
                    }
                    System.debug('rollupProductInfoToContract - productGroups: ' + productGroups);
                    
                    contract.ProductFamily__c = '';
                    //process product families and create comma separated values
                    if (productFamilies.size() > 0) { 
                        List<String> productFamilyList = new List<String>(productFamilies);
                        productFamilyList.sort();
                        contract.ProductFamily__c = String.join(productFamilyList, ',');     
                    }
                    System.debug('rollupProductInfoToContract - productFamilies: ' + productFamilies);
    				//SFDC-1346 #start
    				// adding business lines
                    if (productBusinessLine.size()>0) {
                        List<String> productBusinessList = new List<String>(productBusinessLine);
                        productBusinessList.sort();
                        contract.BusinessLine__c = String.join(productBusinessList, ',');     
                    }
                    // adding product sub business lines
                    if (productBusinessLine.size()>0) {
                        List<String> productBusinessList = new List<String>(productBusinessLine);
                        productBusinessList.sort();
                        contract.BusinessLine__c = String.join(productBusinessList, ',');     
                    }
                    if (productSubBusinessLine.size()>0) {
                        List<String> productSubBusinessList = new List<String>(productSubBusinessLine);
                        productSubBusinessList.sort();
                        contract.SubBusinessLine__c = String.join(productSubBusinessList, ',');     
                    }
                    // adding product global segment
                    if (productGlobalSegment.size()>0) {
                        List<String> productGlobalSegmenList = new List<String>(productGlobalSegment);
                        productGlobalSegmenList.sort();
                        contract.GlobalSegments__c = String.join(productGlobalSegmenList, ',');     
                    }
    				//SFDC-1346 #end
    				//SFDC-2969
    				if (productInternalBusinessSegment.size()>0) {
                        List<String> productInternalBusinessSegmenList = new List<String>(productInternalBusinessSegment);
                        productInternalBusinessSegmenList.sort();
                        contract.InternalBusinessSegment__c = String.join(productInternalBusinessSegmenList, ',');     
                    }
                    contractToBeUpdatedList.add(contract);
                }
            }
            */
            if (!contractToBeUpdatedList.isEmpty()) {
                update contractToBeUpdatedList;
            }
            
        }
        catch(Exception ex) {
			Database.rollback(sp);
            throw(ex);
        }
    }
        
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 05 Oct 2020
    // @description: SFDC-3403: Moved "LockContractLineItem" validation rule to code. This method stops users from updating contract line items if the parent Contract is marked as Complete.
    // @param: TriggerParameters
    // @return: None
    // @modified by: Paras Dhingra
    // @date: 10th May 2021
    // @description: SFDC-4066 Giving access to custom permission ContractLineItemEditAccessFinancialServicesteam to allow users to 
    //                  add billing info and create volume billing records
    //-----------------------------
    public static void lockCLIForCompletedContracts(TriggerParameters tp) {        
        if(GlobalVariables.shouldCLIValidationBypass) {
            return;
        }
        Set<String> setProfilesAllowed = new Set<String>{'System Administrator', 'IHSMarkit System Admin', 'IHSMarkit System Admin: API', 'IHSMarkit Contract Management', 'IHSMarkit Sales: User Support', 'IHSMarkit Sales: Sales Coordinator'};        
        String profileName = UtilityClass.LoggedInUserProfileName;        
        Boolean isPermAssigned = FeatureManagement.checkPermission('RevenueAssuranceForBSLI');
        if(!isPermAssigned) {//if user does not have elevated access. check for another permission set
            isPermAssigned = FeatureManagement.checkPermission('ContractLineItemEditAccessFinancialServicesteam');
            if(isPermAssigned) {
                GlobalVariables.shouldContractValidationBypass = true;
            }
        }
        if (!setProfilesAllowed.contains(profileName) && !isPermAssigned) {
            Map <String, Schema.SobjectField > cliFields = ContractLineItem__c.sObjectType.getDescribe().fields.getMap();
            Map<Id,ContractLineItem__c> newCLIMap = new Map<Id,ContractLineItem__c>([SELECT Id,Contract__c,Contract__r.Status FROM ContractLineItem__c WHERE Id IN :tp.newList]);
            for(ContractLineItem__c newCLI: (List<ContractLineItem__c>)tp.newList) {
                Boolean hasError = false;
                ContractLineItem__c oldCLI = (ContractLineItem__c)tp.oldMap.get(newCLI.Id);
                ContractLineItem__c newCLIWithContractInfo = newCLIMap.get(newCLI.Id);
                if(newCLIWithContractInfo.Contract__c!=null && newCLIWithContractInfo.Contract__r.Status=='Complete') {
                    for(string fieldName : cliFields.keySet()) {
                        Schema.DescribeFieldResult dfr = cliFields.get(fieldName).getDescribe();
                        if(oldCLI.get(fieldName)!=newCLI.get(fieldName) && !dfr.IsCalculated()) {
                            hasError = true;
                            break;
                        }
                    }
                    if(hasError) {
                        newCLI.addError('Contract Line Items are locked for editing after stage is completed');
                    }
                }                
            }
        }        
    }

    /** 
    * @author: Digvijay
    * @date: 3 May 2021
    * @description: SFDC-4069- Do not allow  users with "ContractLineItemEditAccessFinancialServicesteam" permission set  to delete contract Line Items.
    * @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got deleted.
    * @return: void
    */
    public static void preventContractLineItemDeletion(TriggerParameters tp) {
        List<PermissionSetAssignment> lstpermset=[SELECT Id, AssigneeId, Assignee.Name FROM PermissionSetAssignment WHERE 
                            PermissionSet.Name =: System.Label.ContractLineItemEditAccessPermissionSet and AssigneeId =: Userinfo.getUserId() limit 1];
        List<ContractLineItem__c> listContractlineItems = (List<ContractLineItem__c>) tp.oldList;
        for(ContractLineItem__c cliObj : listContractlineItems ) {
            if(!lstpermset.IsEmpty()){
                cliObj.addError('You are not authorized to Delete a Contract Line Item.');
            }
        }               
    }
}