objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalFilesAttached__c</fullName>
        <description>SFDC-4182 Count total number of files under all Contract Attachment records</description>
        <label>Total Files Attached</label>
        <summarizedField>ContractAttachment__c.TotalFilesAttached__c</summarizedField>
        <summaryForeignKey>ContractAttachment__c.Contract__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentPO__c</fullName>
        <description>SFDC-2530-This represents the Contract Attachment (Type=PO) which is valid under a contract for the current period.</description>
        <inlineHelpText>This represents the Contract Attachment(PO) which is valid under a contract for the current period.</inlineHelpText>
        <label>Current PO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalFilesAttached__c</fullName>
        <description>SFDC-4182 Count total files attached under each Contract Attachment Record</description>
        <label>Total Files Attached</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MISAttachmentAdded__c</fullName>
        <description>SFDC1-2243 Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</description>
        <inlineHelpText>System Managed Field. This field is used for MIS pipeline reporting. Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</inlineHelpText>
        <label>MIS Attachment Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityAttachment__c.object
<CustomObject>
    <description>SFDC1-661 Object to define what kind of attachment users are adding to an Opportunity</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-661 to define what kind of attachment users are adding to an Opportunity</description>
        <inlineHelpText>Please select the kind of attachment you are adding to an Opportunity</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discount Approval</fullName>
                </value>
                <value>
                    <fullName>End User Certificate</fullName>
                </value>
                <value>
                    <fullName>Final Proposal</fullName>
                </value>
                <value>
                    <fullName>Pricing Sheet</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Quote Created</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-661 Opportunity to which this contact attachment is associated</description>
        <inlineHelpText>Please select an opportunity to which this contact attachment is associated</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Attachments</relationshipLabel>
        <relationshipName>OpportunityAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Attachment</label>
    <nameField>
        <label>Opportunity Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Attachments</pluralLabel>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <description>Opportunity Attachment Recordtype for Renewal Opportunities only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VoiceofCustomer__c.object
<CustomObject>
    <fields>
        <fullName>FileAttached__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>File Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Voice of Customers</relationshipLabel>
        <relationshipName>Voice_of_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Voice of Customer</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice of Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentLinkMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 29 Aug 2017
// @param: NA
// @description: SFDC1-2243 Class to hold ContentDocumentLink trigger methods 
// @return: NA
//-----------------------------
public class ContentDocumentLinkMethods {

   public static Set <Id> setContractAttId = new Set <Id>();
//-----------------------------
// @author: Uttam Arya
// @date: 22 Aug 2017
// @param: TriggerParameters tp
// @description: SFDC1-2243 Whenever an ContentDocumentLink is added to an opportunity,  
//                  MISContentDocumentLinkAdded field is auto populated with the current timestamp. 
//                  This is used for MIS pipeline reporting.
//
// @return: None
// @Modifiedby: Mohit Modi
// @Modified Description: 06 Nov 2017 : Added the logic to capture the attahment added on Opportunity Attachment as well.
// @Modified by: Paras Dhingra
// @Modified date: 16 July 2019
// @Modified description: Adding bypass to avoid firing auto-renewal validations on insert of opportunity attachment
//------------------------------
    public static void populateMISAttachmentAddedInOpportunityWhenAttachmentIsInsertedInLightning(TriggerParameters tp) {
    
        //List of Opportunity that needs to be updated    
        list <Opportunity > OpportunityToUpdate = new list<Opportunity>(); 
        set<id> setOpportunityAttId = new set<id>();
        
        String OppAttachmentkeyPrefix = UtilityClass.getObjectKeyPrefix('OpportunityAttachment__c');
        set<id> setOpportunityId = new set<id>();
        
        for(ContentDocumentLink ContentDocumentLink: (List <ContentDocumentLink>) tp.newList) {
            if(ContentDocumentLink.LinkedEntityId != null && String.valueOf(ContentDocumentLink.LinkedEntityId).startsWith('006')) {
                setOpportunityId.add(ContentDocumentLink.LinkedEntityId);
            }
            // Checking if attachment is added to Opportunity Attachment Record.
            if(ContentDocumentLink.LinkedEntityId != null && OppAttachmentkeyPrefix != NULL && String.valueOf(ContentDocumentLink.LinkedEntityId).startsWith(OppAttachmentkeyPrefix)) {
                setOpportunityAttId.add(ContentDocumentLink.LinkedEntityId);
            }
        }
        
        if(!setOpportunityAttId.isEmpty()) {
            for(OpportunityAttachment__c tempOppAttach : [select id,Opportunity__c from OpportunityAttachment__c where id in : setOpportunityAttId]) {
                setOpportunityId.add(tempOppAttach.Opportunity__c);
            }
        }
        
        for(id oppid : setOpportunityId) {
            OpportunityToUpdate.add(new Opportunity(Id = oppid , MISAttachmentAdded__c = Datetime.now()));
        }
        
        //update if list has any records
        if(OpportunityToUpdate != null && OpportunityToUpdate.size() > 0) {
            //adding bypass for uploading opportunity attachments such that validations are not fired SFDC-1710 #start
            GlobalConstants.hasTriggeredFromOpportunityProduct = true;
            update OpportunityToUpdate;
            GlobalConstants.hasTriggeredFromOpportunityProduct = false;
            // SFDC-1710 #stop
        }
    }
    
    // @return: None
    // @Modifiedby: Sharique Iqbal
    // @Modified Description: Added the logic Mark PO Attached as Yes when an attahment added on Contract Attachment Record.
    // @ Story: SFDC-2530 
    public static void updateContractOncePOIsAttached(TriggerParameters tp) {
        
        String ContractAttachmentPrefix = UtilityClass.getObjectKeyPrefix('ContractAttachment__c');
        set<id> setContractAttId = new set<id>();
        List <sObject> updateSobject = new List <sObject>();
        String profileName = UtilityClass.LoggedInUserProfileName;
        Boolean profileCheck =  (profileName.containsIgnoreCase('System Admin') || profileName.containsIgnoreCase('Contract Management') || profileName.containsIgnoreCase('Order Management')
               				  || profileName.containsIgnoreCase('General') || profileName.containsIgnoreCase('Sales Coordinator') || profileName.containsIgnoreCase('User Support') || profileName.containsIgnoreCase('Sales Ops')) ? True : False;
        for(ContentDocumentLink ContentDocumentLink: (List <ContentDocumentLink>) tp.newList) {
           // Checking if attachment is added to Contract Attachment Record.
           if(ContentDocumentLink.LinkedEntityId != null && ContractAttachmentPrefix != NULL && String.valueOf(ContentDocumentLink.LinkedEntityId).startsWith(ContractAttachmentPrefix)) {
               setContractAttId.add(ContentDocumentLink.LinkedEntityId);
           }
        }
                
        if(!setContractAttId.isEmpty()) {
            for(ContractAttachment__c contrtAttach : [select Id, Contract__c, CurrentPO__c, AttachmentType__c, (Select Id From ContentDocumentLinks) from ContractAttachment__c where id in : setContractAttId]) {
                contrtAttach.TotalFilesAttached__c = contrtAttach.ContentDocumentLinks.size(); 
                if (contrtAttach.AttachmentType__c == 'Purchase Order') {
                    contrtAttach.POAttached__c = 'Yes';
                    if (contrtAttach.CurrentPO__c == 'Yes') {
                        Contract ctrt = new Contract (Id = contrtAttach.Contract__c, POAttached__c = 'Yes');
                        updateSobject.add(ctrt);
                    }
                }
                updateSobject.add(contrtAttach);
            }
        }

        if (!updateSobject.isEmpty()) {
            if (profileCheck) {
             GlobalVariables.allowContactAttchToUpdate = True;
            }    
            update updateSobject;  
            GlobalVariables.allowContactAttchToUpdate = False;
        }
    }
    
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 18 Aug 2021
    // @param: TriggerParameters
    // @description: Hold the Parent Ids before Removing(delinking) the File from parent 
    // @return: NA
    //-----------------------------
    public static void beforeDeleteOperations(TriggerParameters tp) {
        
      String ContractAttachmentPrefix = UtilityClass.getObjectKeyPrefix('ContractAttachment__c');
 
      for(ContentDocumentLink ContentDocumentLink: (List <ContentDocumentLink>) tp.oldList) {
           // Checking if attachment is added to Contract Attachment Record.
           if(ContentDocumentLink.LinkedEntityId != null && ContractAttachmentPrefix != NULL && String.valueOf(ContentDocumentLink.LinkedEntityId).startsWith(ContractAttachmentPrefix)) {
               setContractAttId.add(ContentDocumentLink.LinkedEntityId);
           }
      } 
    }
    
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 18 Aug 2021
    // @param: TriggerParameters
    // @description: Count the no of files after a file has been delinked. 
    // @return: NA
    //-----------------------------
    public static void afterDeleteOperations(TriggerParameters tp) {
      List <sObject> updateSobject = new List <sObject>();
      try {
           if(!setContractAttId.isEmpty()) {
             for(ContractAttachment__c contrtAttach : [select Id, Contract__c, (Select Id From ContentDocumentLinks) from ContractAttachment__c where Id IN : setContractAttId]) {
                contrtAttach.TotalFilesAttached__c = contrtAttach.ContentDocumentLinks.size(); 
                updateSobject.add(contrtAttach);
             }
           }
           if (!updateSobject.isEmpty()) {
              GlobalVariables.shouldContractValidationBypass = True;
              update updateSobject;  
              GlobalVariables.shouldContractValidationBypass = False;
           }
      } catch (Exception e) {
               if(e.getMessage().contains(System.Label.ContractShouldHaveAtLeastOneFile)) {    
                ((List<ContentDocumentLink>) tp.oldList).get(0).addError(System.Label.ContractShouldHaveAtLeastOneFile);
               } else if(e.getMessage().contains(System.Label.ContractAttachmentRestrictionError)) {    
                ((List<ContentDocumentLink>) tp.oldList).get(0).addError(System.Label.ContractAttachmentRestrictionError);
               } else ((List<ContentDocumentLink>) tp.oldList).get(0).addError(System.Label.ContractShouldHaveAtLeastOneFile);     
        }
    }  
    
    // @return: None
    // @Modifiedby: Digvijay Singh
    // @Modified Description: Added the logic Mark File Attached as Yes when an attahment added on VOC.
    // @ Story: US-5320681 
    public static void updateVOCOnceFileIsAttached(TriggerParameters tp) {

        String vocAttachmentPrefix = UtilityClass.getObjectKeyPrefix('VoiceofCustomer__c');
        System.debug('VOC..pref'+vocAttachmentPrefix);
        set<id> setVOCAttId = new set<id>();
        List <sObject> updateSobject = new List <sObject>();

         for(ContentDocumentLink ContentDocumentLink: (List <ContentDocumentLink>) tp.newList) {
           // Checking if attachment is added to VOC Record.
           if(ContentDocumentLink.LinkedEntityId != null && vocAttachmentPrefix != NULL && String.valueOf(ContentDocumentLink.LinkedEntityId).startsWith(vocAttachmentPrefix)) {
               setVOCAttId.add(ContentDocumentLink.LinkedEntityId);
           }
         }
        
        System.debug('VOC..pref'+setVOCAttId);

          if(!setVOCAttId.isEmpty()) {
            for(VoiceofCustomer__c vocobj  : [select Id, FileAttached__c from VoiceofCustomer__c where id in : setVOCAttId]) {
                if(vocobj.FileAttached__c=='No' || String.isBlank(vocobj.FileAttached__c)) {
                    vocobj.FileAttached__c='Yes';
                    updateSobject.add(vocobj);
                }
            }

            if(!updateSobject.isEmpty()) {
                update updateSobject;
            }
          }
    }
    
   
}