objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalFilesAttached__c</fullName>
        <description>SFDC-4182 Count total files attached under each Contract Attachment Record</description>
        <label>Total Files Attached</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VoiceofCustomer__c.object
<CustomObject>
    <fields>
        <fullName>FileAttached__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>File Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Voice of Customer</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice of Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentMethods.cls
//-----------------------------
// @author: Sharique Iqbal
// @date: 18 Aug 2021
// @param: TriggerParameters
// @description:  In Lightning, when a file is deleted, ContentDocument Trigger is fired.
// @return: NA
//-----------------------------
public class ContentDocumentMethods {
    
    public static Set <Id> setContractAttId = new Set <Id>();
    public static Set<Id> setVOCAttdelId = new Set<Id>();
    
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 18 Aug 2021
    // @param: TriggerParameters
    // @description: Hold the Parent Ids before deleting the Files
    // @return: NA
    //-----------------------------
    public static void beforeDeleteOperations(TriggerParameters tp) {
        
      String ContractAttachmentPrefix = UtilityClass.getObjectKeyPrefix('ContractAttachment__c');
       String vocAttachmentPrefix = UtilityClass.getObjectKeyPrefix('VoiceofCustomer__c');
      set<id> ConDocIds = new set<id>();
 
      for(ContentDocument ConDoc: (List<ContentDocument>) tp.oldList) {
          ConDocIds.add(ConDoc.Id);
      }    
      for(ContentDocument ConDoc: [Select Id, (Select Id, LinkedEntityId from ContentDocumentLinks) from ContentDocument Where ID IN :ConDocIds ]) {
          for (ContentDocumentLink conDocLink : ConDoc.ContentDocumentLinks) {
            if(conDocLink.LinkedEntityId != null && ContractAttachmentPrefix != NULL && String.valueOf(conDocLink.LinkedEntityId).startsWith(ContractAttachmentPrefix)) {
               setContractAttId.add(conDocLink.LinkedEntityId);  
            }  
            
            // Checking if attachment is added to VOC Attachment Record.
           if(conDocLink.LinkedEntityId != null && vocAttachmentPrefix != NULL && String.valueOf(conDocLink.LinkedEntityId).startsWith(vocAttachmentPrefix)) {
               setVOCAttdelId.add(conDocLink.LinkedEntityId);
               System.debug('here..'+setVOCAttdelId);
           }
          }  
      }
    }
    
    //-----------------------------
    // @author: Sharique Iqbal
    // @date: 18 Aug 2021
    // @param: TriggerParameters
    // @description: Count the no of files after a file has been deleted. 
    // @return: NA
    //-----------------------------
    public static void afterDeleteOperations(TriggerParameters tp) {
      List <sObject> updateSobject = new List <sObject>();
      try {
           if(!setContractAttId.isEmpty()) {
             for(ContractAttachment__c contrtAttach : [select Id, Contract__c, (Select Id From ContentDocumentLinks) from ContractAttachment__c where Id IN : setContractAttId]) {
                contrtAttach.TotalFilesAttached__c = contrtAttach.ContentDocumentLinks.size(); 
                updateSobject.add(contrtAttach);
             }
           }
           if (!updateSobject.isEmpty()) {
              GlobalVariables.shouldContractValidationBypass = True;
              update updateSobject;  
              GlobalVariables.shouldContractValidationBypass = False;
           }
      } catch (Exception e) {
               if(e.getMessage().contains(System.Label.ContractShouldHaveAtLeastOneFile)) {    
                ((List<ContentDocument>) tp.oldList).get(0).addError(System.Label.ContractShouldHaveAtLeastOneFile);
               } else if(e.getMessage().contains(System.Label.ContractAttachmentRestrictionError)) {    
                ((List<ContentDocument>) tp.oldList).get(0).addError(System.Label.ContractAttachmentRestrictionError);
               } else ((List<ContentDocument>) tp.oldList).get(0).addError(System.Label.ContractShouldHaveAtLeastOneFile);     
        }
    }    
    
    //-----------------------------
    // @author: Digvijay Singh
    // @date: Nov 09 2022
    // @param: TriggerParameters
    // @description: reset flag on VOC once all attachements are deleted.
    // @return: NA
    //-----------------------------
    public static void afterVOCattachementDeleteOperations(TriggerParameters tp) {
      List <sObject> updateSobject = new List <sObject>();
         System.debug('setVOCAttdelId..'+setVOCAttdelId);
        if(setVOCAttdelId!=null && !setVOCAttdelId.IsEmpty()) {
              for(ContentDocumentLink cdobj:[Select Id ,LinkedEntityId from ContentDocumentLink where LinkedEntityId IN :setVOCAttdelId]) {
                    if(setVOCAttdelId!=null && setVOCAttdelId.contains(cdobj.LinkedEntityId)) {
                        setVOCAttdelId.remove(cdobj.LinkedEntityId);
                    }
              }
        }

      if(setVOCAttdelId!=null && !setVOCAttdelId.isEmpty()) {
         for(Id vocId:setVOCAttdelId) {
            updateSobject.add(new VoiceofCustomer__c(Id=vocId,FileAttached__c='No'));
         }
      }

      if(!updateSobject.isEmpty()) {
         update updateSobject;
      }
	}
}