objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>SFDC1-10131 New Contract field: &quot;Active&quot;</description>
        <formula>IF(
OR(text(ContractStatus__c)== &quot;Validated&quot;, text(ContractStatus__c)== &quot;Validated PO Pending&quot;, text(ContractStatus__c)== &quot;Invoiced&quot;, text(ContractStatus__c)== &quot;Executed&quot;, text(ContractStatus__c)== &quot;Delivered to Customer&quot;, text(ContractStatus__c)== &quot;Approved &amp; Processed&quot;,text(ContractStatus__c)== &quot;Validated-POD Pending&quot;),
True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>to quickly see which Contracts on an Account are &quot;Active&quot;</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CACreationDate__c</fullName>
        <description>SFDC-2530 This field indicates when the batch will run to create Contract Attachment record</description>
        <inlineHelpText>This field indicates when the batch will run to create Contract Attachment record</inlineHelpText>
        <label>CA Creation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-718;Only on Contract Type = Order Form</description>
        <label>PO Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenewalDate__c</fullName>
        <description>SFDC1-9301 : Renewal Date</description>
        <inlineHelpText>Fill the Renewal Date</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-6735: New Record Type Created for SOW/Consulting Usage</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentPO__c</fullName>
        <description>SFDC-2530-This represents the Contract Attachment (Type=PO) which is valid under a contract for the current period.</description>
        <inlineHelpText>This represents the Contract Attachment(PO) which is valid under a contract for the current period.</inlineHelpText>
        <label>Current PO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-9507 : Created new RecordType for Consulting RecordType</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1- 535 ;Checkbox fields on opportunity which is automatically populated from Account, SFDC1-959 : Added &apos;?&apos; to the Label.</description>
        <label>PO Required?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchToCreateContractAttachment.cls
//-----------------------------
// @author: Sharique Iqbal
// @date: 18 May 2021
// @description: SFDC-2530 This batch class is to use to create Contract Attachment record year on year
//------------------------------

global class BatchToCreateContractAttachment implements Database.Batchable<sObject>,schedulable {

    public String query;
    List<ContractAttachment__c> upsertContractAtt = new List<ContractAttachment__c>();
    List<Contract> contractsToBeUpdated = new List<Contract>();

    global Database.QueryLocator start(Database.BatchableContext BC) {
        if (String.isBlank(query)) {
            query = 'Select Id From Contract ' 
                    +'Where Active__c = True AND PORequired__c = true AND '
                    +'Recordtype.Name IN (\'Order Form\',\'Consulting\') AND ' 
                    +'Renewaldate__c > today';
        }  
        system.debug('@@query--'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
        try {
            for (Contract ctrt: [Select Id, ContractNumber, StartDate, EndDate, Renewaldate__c, CACreationDate__c, POAttached__c, Active__c,Account.Name,(Select Id from ContractAttachments__r Where AttachmentType__c = 'Purchase Order') 
                                 From Contract Where Id IN :scope]) {
               
               //Scenario 1- If Contract Start date is in next 30days 
               if (ctrt.StartDate.addMonths(-1) == System.today() && ctrt.CACreationDate__c == null) {
                    
                    // If contract duration is more than 1 yr, then batch will run again as per CACreationDate__c
                    if (System.today().addMonths(13) < ctrt.Renewaldate__c) {
                        ctrt.CACreationDate__c = System.today().addYears(1);
                        contractsToBeUpdated.add(ctrt);
                    }
                    /*1st time no need to create Contract Attachment record since they will 
                      be created along with Contract creation*/
                    //createContractAttachment (ctrt);
               }    
                                     
               //Scenario 2- If CSD is in past, CED is today/future 
               else if (ctrt.StartDate < System.today() && ctrt.EndDate > System.today() && ctrt.CACreationDate__c == null) {
                    Date thisYearstartdate = date.newInstance(System.today().year(), ctrt.StartDate.Month(), ctrt.StartDate.day());
                    Date thisYearEnddate = date.newInstance(System.today().year(), ctrt.EndDate.Month(), ctrt.Enddate.day());

                    if (thisYearstartdate.addMonths(-1) == System.today() && ctrt.RenewalDate__c >= System.today().addMonths(2)) {
                        if (System.today().addMonths(13) < ctrt.RenewalDate__c) {
                            ctrt.CACreationDate__c = System.today().addYears(1); 
                        }
                        createContractAttachment (ctrt);   
                    }  
                }
                
                // Scenario-3: If CSD & CED both are at past.
                else if (ctrt.StartDate < System.today() && ctrt.EndDate < System.today() && ctrt.CACreationDate__c == null) {
                       Date thisYearEnddate = date.newInstance(System.today().year(), ctrt.EndDate.Month(), ctrt.Enddate.day());
                       if (thisYearEnddate.addMonths(-1) == System.today() && ctrt.RenewalDate__c >= System.today().addMonths(2) ) {
                           // if Enddate is less then 1 yr from today's date
                           if (System.today().addMonths(13) < ctrt.RenewalDate__c) {
                              ctrt.CACreationDate__c = System.today().addYears(1); 
                           }
                           createContractAttachment (ctrt);   
                       }  
                }
                
                //Scenario 4- If Contract Creation Date is today
                else if (ctrt.CACreationDate__c != null && ctrt.CACreationDate__c == System.today()) {
                         if (ctrt.CACreationDate__c < ctrt.EndDate && System.today().addYears(1) > ctrt.EndDate) {
                              ctrt.CACreationDate__c = ctrt.EndDate.addMonths(-1);
                         } else if (System.today().addMonths(13) < ctrt.Renewaldate__c) {
                              ctrt.CACreationDate__c = System.today().addYears(1);
                         }
                    createContractAttachment (ctrt);   
                }                  
            }
            
            for (Contract cont : contractsToBeUpdated) {
                for (ContractAttachment__c conAtt : cont.ContractAttachments__r) {
                    conAtt.CurrentPO__c = 'No';
                    upsertContractAtt.add(conAtt);
                }
            }
            
            if (upsertContractAtt.size() > 0) {
                database.upsert(upsertContractAtt);
            }
            
            if (contractsToBeUpdated.size() > 0) {
                database.update(contractsToBeUpdated);
            } 
            
        } catch(Exception ex) {
            System.debug('Exception when executing BatchToCreatePOContractAttachment: ' + ex.getMessage());
            UtilityClass.createApexLogRecord(ex, 'BatchToCreatePOContractAttachment', 'execute'); 
        }
    }
    
    public void createContractAttachment (Contract ctrt) { 
        ContractAttachment__c ctrtAtt = new ContractAttachment__c();
        ctrtAtt.Name = 'PO -'+ctrt.Account.Name+' '+System.today().format();
        ctrtAtt.Contract__c = ctrt.Id;
        ctrtAtt.AttachmentType__c = 'Purchase Order';
        ctrtAtt.CurrentPO__c = 'Yes';
        ctrtAtt.POAttached__c = 'No';
        ctrt.POAttached__c = 'No'; // Marking PO Attached as 'No' on Contract.
        upsertContractAtt.add(ctrtAtt);
        contractsToBeUpdated.add(ctrt);
                
    }    
    
    global void finish(Database.BatchableContext BC) {
      // Workflow is fired to send an Email Notifications to Contract, Opportunity, Renewal Owner for recently created Contract Attachment Records.
    }
    
    global void execute(SchedulableContext SC) {
 	  database.executebatch(new BatchToCreateContractAttachment());
    }
    
}