objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-1178 Creating this field to track auto renewal of a Contract on Opportunity</description>
        <inlineHelpText>Customer can sign one agreement which will automatically renew year after year</inlineHelpText>
        <label>AutoRenewal</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4728: Create Auto Renewal field on Opportunity that will be updated from Contract.</description>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.
SFDC-1896 Updated filter criteria for Consulting record type</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DoesThisAutoRenewalHaveChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field includes renewal details of opportunity. (JIRA story SFDC1-556)</description>
        <inlineHelpText>Specify if Auto Renewal has any changes.</inlineHelpText>
        <label>Does this Auto Renewal Have Changes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriceChangeOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-3187 This checkbox when checked will allow user to update pricing on Auto renewal opportunity without changes</description>
        <inlineHelpText>Please use the Manual Price Increase button to select this</inlineHelpText>
        <label>Price Change Only</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestProductSelectorController.cls
/**
* @Author : Mohit Modi
* @Date : 14 Nov 2017
* @Description : Test Class for accessCheckController
* @company : Vertiba
*/
    @isTest
    private class TestProductSelectorController {
    
        @testSetup static void setup() {
            Account acc = TestUtility.createTestAccount('Account testAccountforOpp', true);
            
            Contact c = new Contact();
        	c.firstname = 'Test';
        	c.lastname = 'testSetCaseAdditionalFieldsObject';
        	c.AccountId = acc.Id;
        	c.Phone = '12345';
        	c.EmailUnknown__c = true;
            insert c;
     
            Product2 testProd = TestUtility.createProduct('Test Product', true);
            Id standardId = Test.getStandardPricebookId();
            LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
            List<Country__c> lstCountry = TestUtility.loadCountryData();
            Country__c country = lstCountry.get(0);
            Contract contract = TestUtility.createContractWithInsertOptional(acc.Id, legalEntity.Id, country.Id, standardId,FALSE);
            Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
            contract.recordtypeid = orderFormRecordTypeId;
            insert contract;
    		
            List<Opportunity> oppyList = new List<Opportunity>();
            Opportunity testOpportunity1 = TestUtility.createOpportunity(acc.Id,'first test Oppy', false);
            testOpportunity1.Amount = 1000;
        	oppyList.add(testOpportunity1);
        	User u = TestUtility.createTestUser('IHSMarkit Sales: General','standardrollupuser@testorg.com',true);
            User u2 = TestUtility.createTestUser('IHSMarkit Sales: User Support','usersupport@testorg.com',true);
            
        	Id RecordTypeIdOppty = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Inner Year').getRecordTypeId();
            Id renRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
            Opportunity testOpportunity2 = TestUtility.createOpportunity(acc.Id,'Rollup test Oppy', false);
            testOpportunity2.recordtypeid = RecordTypeIdOppty;
            testOpportunity2.StageName = '6WP-Closed Won/Order Processed';
        	testOpportunity2.ContractBeingRenewed__c = contract.Id;
        	testOpportunity2.AutoRenewal__c = true;
            testOpportunity2.DoesThisAutoRenewalHaveChanges__c = false;
            testOpportunity2.OwnerId = u.Id;
        	oppyList.add(testOpportunity2);   
          
            Opportunity testRenewalOpp = TestUtility.createOpportunity(acc.id,'Test Opp Renewal', false);
            testRenewalOpp.StageName= '3-Renewal Pending';
            testRenewalOpp.RecordTypeId = renRecordTypeId;
        	testRenewalOpp.AutoRenewal__c = true;
            testRenewalOpp.PriceChangeOnly__c = false;
            testRenewalOpp.DoesThisAutoRenewalHaveChanges__c = false;
        	oppyList.add(testRenewalOpp);

            Opportunity testOpportunity4 = TestUtility.createOpportunity(acc.Id,'Inner Year test Oppy', false);
            testOpportunity4.recordtypeid = RecordTypeIdOppty;
            testOpportunity4.StageName = '1-Sales Qualified';
            testOpportunity4.ContractBeingRenewed__c = contract.Id;
        	testOpportunity4.AutoRenewal__c = true;
            testOpportunity4.DoesThisAutoRenewalHaveChanges__c = false;
            testOpportunity4.OwnerId = u.Id;
            oppyList.add(testOpportunity4);

        	insert oppyList;
            
            OpportunityContactRole oppContactRole = new OpportunityContactRole();
            oppContactRole.OpportunityID = testRenewalOpp.id;
            oppContactRole.ContactId = c.id;
            oppContactRole.IsPrimary = true;
            insert oppContactRole;
        }    
        
        @isTest
        private static void testCommunityCheck () {
                   	
            test.startTest();
            Boolean isCommunity = ProductSelectorController.isCommunity();
            System.assertEquals(false, isCommunity, 'Community Portal');
            test.stopTest();
        }
        
         @isTest
        private static void testcheckRecordAccessforUser () {
                   	
            test.startTest();
            Opportunity testOpportunity1 = [Select id from Opportunity where Name = 'first test Oppy' LIMIT 1];
            Opportunity testOpportunity3 = [Select id from Opportunity where Name = 'Test Opp Renewal' LIMIT 1];
            ProductSelectorController.ProductSelectorValidatorWrapper assertAccess = ProductSelectorController.checkRecordAccessforUser (userinfo.getuserID(),testOpportunity1.id,'Add Products');
            System.assertEquals(true, assertAccess.isSuccess,'Check access is true' );
            User u = [select Id from User where Email = 'usersupport@testorg.com' LIMIT 1];
            System.runAs(u) {
                ProductSelectorController.ProductSelectorValidatorWrapper assertAccess2 = ProductSelectorController.checkRecordAccessforUser (u.Id,testOpportunity3.id,'Edit Products');
                System.assertEquals(false, assertAccess2.isSuccess,'Check access is false' );
            }
            test.stopTest();
        }
        
         @isTest
        private static void testcheckRecordAccessforGeneral () {
                   	
            test.startTest();
            Opportunity testOpportunity3 = [Select id from Opportunity where Name = 'Test Opp Renewal' LIMIT 1];
            Opportunity testOpportunity2 = [Select id from Opportunity where Name = 'Rollup test Oppy' LIMIT 1];
            Opportunity testOpportunity4 = [Select id from Opportunity where Name = 'Inner Year test Oppy' LIMIT 1];
            
            ProductSelectorController.ProductSelectorValidatorWrapper assertAccess = ProductSelectorController.checkRecordAccessforUser (userinfo.getuserID(),testOpportunity3.id,'Add Products');
            System.assertEquals(false, assertAccess.isSuccess,'Check access is true' );
            User u = [select Id from User where Email = 'standardrollupuser@testorg.com'];
            System.runAs(u) {
                ProductSelectorController.ProductSelectorValidatorWrapper assertAccess2 = ProductSelectorController.checkRecordAccessforUser (u.Id,testOpportunity2.id,'Add Products');
                System.assertEquals(false, assertAccess2.isSuccess,'Check access is false' );
                ProductSelectorController.ProductSelectorValidatorWrapper assertAccess3 = ProductSelectorController.checkRecordAccessforUser (u.Id,testOpportunity4.id,'Add Products');
                System.assertEquals(false, assertAccess3.isSuccess,'Check access is false' );
            }
            test.stopTest();
        }
         @isTest
        private static void testExceptionRequestStatus () {
                   	
            test.startTest();
            Opportunity testOpty = [Select id, Amount from Opportunity where Name = 'first test Oppy' LIMIT 1];
            System.assertEquals(1000, testOpty.Amount, 'Amount should be 1000');
            String exceptionStatus = ProductSelectorController.exceptionRequestCheck(testOpty.Id);
            System.assertEquals(Null, exceptionStatus, 'Exception Status should be Blank');
            test.stopTest();
        }
    }