objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Renewal Notice</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contract attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contract attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC-2530- This indicates if a file has been attached under the Contract Attachment record</description>
        <inlineHelpText>This indicates if a file has been attached under the Contract Attachment record</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MISAttachmentAdded__c</fullName>
        <description>SFDC1-2243 Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</description>
        <inlineHelpText>System Managed Field. This field is used for MIS pipeline reporting. Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</inlineHelpText>
        <label>MIS Attachment Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityAttachment__c.object
<CustomObject>
    <description>SFDC1-661 Object to define what kind of attachment users are adding to an Opportunity</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-661 to define what kind of attachment users are adding to an Opportunity</description>
        <inlineHelpText>Please select the kind of attachment you are adding to an Opportunity</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discount Approval</fullName>
                </value>
                <value>
                    <fullName>End User Certificate</fullName>
                </value>
                <value>
                    <fullName>Final Proposal</fullName>
                </value>
                <value>
                    <fullName>Pricing Sheet</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Quote Created</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-661 Opportunity to which this contact attachment is associated</description>
        <inlineHelpText>Please select an opportunity to which this contact attachment is associated</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Attachments</relationshipLabel>
        <relationshipName>OpportunityAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Attachment</label>
    <nameField>
        <label>Opportunity Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestContentDocumentLinkMethods.cls
// @author: Uttam Arya
// @date: 31 Aug 2017
// @param: NA
// @description: Test class for ContentDocumentLink trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestContentDocumentLinkMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 31 Aug 2017
    // @param: NA
    // @description: SFDC1-2243 Test method for ContentDocumentLink trigger methods populateMISAttachmentAddedInOpportunityWhenAttachmentIsInsertedInLightning on insert
    // @return: NA
    // @Modifiedby: Mohit Modi
    // @Modified Description: 06 Nov 2017 : Updated Test Method logic to capture the attahment added on Opportunity Attachment as well.
    //-----------------------------
    @isTest private static void testpopulateMISAttachmentAddedInOpportunityWhenAttachmentIsInsertedInLightning() {
        
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        Opportunity oppt = TestUtility.createOpportunity(acct.Id, 'Test Oppy Attachment', true);
        
        OpportunityAttachment__c oppAtt = new OpportunityAttachment__c(AttachmentType__c = 'Final Proposal',Opportunity__c =oppt.id );
        insert oppAtt ;
        
        string before = 'Testing base 64 encode';            
        Blob beforeblob = Blob.valueOf(before);
        
        //Insert contentdocument data
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        newFileShare.contentdocumentid = testcontent.contentdocumentid;
        newFileShare.LinkedEntityId = oppt.Id;
        newFileShare.ShareType= 'V';
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShareOppAtt = new ContentDocumentLink();
        newFileShareOppAtt.contentdocumentid = testcontent.contentdocumentid;
        newFileShareOppAtt.LinkedEntityId = oppAtt.Id;
        newFileShareOppAtt.ShareType= 'V';
        
        insert new List<ContentDocumentLink>{newFileShare,newFileShareOppAtt};
        
        //Assert if MIS field is inserted
        Opportunity opp = [select MISAttachmentAdded__c from Opportunity where Id =: oppt.Id];
        
        System.assertNotEquals(opp.MISAttachmentAdded__c, null, 'MISAttachmentAdded field should not be null');
        
    }
    
    //-----------------------------
    // @author: Sharique
    // @date: 26 May 2021
    // @param: NA
    // @description: SFDC1-2530 Test method for ContentDocumentLink trigger methods updateContractOncePOIsAttached on insert
    // @return: NA
    //-----------------------------
    @isTest private static void testMethodupdateContractOncePOIsAttached() {
        
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        Id stdPricebookId = Test.getStandardPricebookId();
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHSM test legalEntity', 'USD'); 
        Contract testContract = TestUtility.createContractWithInsertOptional(acct.Id, testLegalEntity.Id, null, stdPricebookId,true );

        ContractAttachment__c ctrtAtt = new ContractAttachment__c(AttachmentType__c = 'Purchase Order',Contract__c =testContract.id);
        insert ctrtAtt ;
        
        string before = 'Testing base 64 encode';            
        Blob beforeblob = Blob.valueOf(before);
        
        //Insert contentdocument data
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        newFileShare.contentdocumentid = testcontent.contentdocumentid;
        newFileShare.LinkedEntityId = ctrtAtt.Id;
        newFileShare.ShareType= 'V';
        
        /*insert new ContentDocumentLink
        ContentDocumentLink newFileShareOppAtt = new ContentDocumentLink();
        newFileShareOppAtt.contentdocumentid = testcontent.contentdocumentid;
        newFileShareOppAtt.LinkedEntityId = ctrtAtt.Id;
        newFileShareOppAtt.ShareType= 'V';*/
        
        insert new List<ContentDocumentLink>{newFileShare};
        
        ContractAttachment__c conAtt = [select Id,POAttached__c from ContractAttachment__c where Id =: ctrtAtt.Id];
        System.assertEquals(conAtt.POAttached__c, 'Yes','File attached was failed');
        
    }
    
     //-----------------------------
    // @author: Sharique
    // @date: 23 Auguest 2021
    // @param: NA
    // @description: SFDCfor C-4182 Test method for delete operations
    // @return: NA
    //-----------------------------
    @isTest private static void testMethodDeleteFile() {
        
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        Id stdPricebookId = Test.getStandardPricebookId();
        LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('IHSM test legalEntity', 'USD'); 
        Contract testContract = TestUtility.createContractWithInsertOptional(acct.Id, testLegalEntity.Id, null, stdPricebookId,true );

        ContractAttachment__c ctrtAtt = new ContractAttachment__c(AttachmentType__c = 'Purchase Order',Contract__c =testContract.id);
        insert ctrtAtt ;
        
        string before = 'Testing base 64 encode';            
        Blob beforeblob = Blob.valueOf(before);
        
        //Insert contentdocument data
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //insert new ContentDocumentLink
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        newFileShare.contentdocumentid = testcontent.contentdocumentid;
        newFileShare.LinkedEntityId = ctrtAtt.Id;
        newFileShare.ShareType= 'V';
             
        insert new List<ContentDocumentLink>{newFileShare};
        
        delete newFileShare;
        List<ContentDocumentLink> cdl = [Select id, ShareType from ContentDocumentLink where LinkedEntityId = :ctrtAtt.Id and ShareType = 'V' LIMIT 1];
        System.assertEquals(0, cdl.size(), 'Checking if ContentDocumentLink delete was successful');
    }
    
}