objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country/Territory Code</inlineHelpText>
        <label>Country/Territory Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>SFDC1-620 Specify Country&apos;s geography</description>
        <inlineHelpText>Please select Country&apos;s geography</inlineHelpText>
        <label>Geography</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia &amp; NZ</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Eastern Europe</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany/Austria/Switzerland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; Africa</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Southern Europe</fullName>
                </value>
                <value>
                    <fullName>UK &amp; Ireland</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExceptionStatus__c</fullName>
        <description>SFDC-4731: Field for exception process status</description>
        <label>Exception Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception Requested</fullName>
                </value>
                <value>
                    <fullName>Exception Request Approved</fullName>
                </value>
                <value>
                    <fullName>Exception Request Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-616 Lookup to Country object</description>
        <label>Opportunity Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedLegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4731: To store the requested legal entity for offline exception process</description>
        <label>Requested Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities (Requested Legal Entity)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestUpdateExceptionStatusFromEmail.cls
/**
 * @CreatedBy: Manish Kumar
 * @CreatedDate : 31st March 2022
 * @Description: SFDC-5500 Test Class for UpdateExceptionStatusFromEmail
 */
@istest
public class TestUpdateExceptionStatusFromEmail {
    
   @isTest static void TestinBoundEmail() {
       test.startTest();
       Account acc = TestUtility.createTestAccount('Test Account for Product Selection', true);
       LegalEntity__c leUS = TestUtility.createLegalEntity('Markit Group Limited US', 'USD');
       Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
       Country__c countryUS = New Country__c();
       countryUS.Name = 'United States';
       countryUS.CountryCode__c = 'US';
       countryUS.Geography__c = 'United States';
       countryUS.Region__c = 'Americas';
       insert countryUS;
       
       id newBusinessRecTypeId = UtilityClass.getObjectRecordTypeId('Opportunity','New Business');
       Opportunity oppyUS1 = TestUtility.createOpportunity(acc.Id, 'Test Opportunity for US', false);
       oppyUS1.RecordTypeId = newBusinessRecTypeId;
       oppyUS1.ExceptionStatus__c = 'Exception Requested';
       oppyUS1.RequestedLegalEntity__c = leUS.Id;
       oppyUS1.CurrencyIsoCode = 'USD';
       oppyUS1.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
       oppyUS1.OpportunityCountry__c = countryUS.Id;
       insert oppyUS1;
       
       Opportunity oppyUS2 = TestUtility.createOpportunity(acc.Id, 'Test Opportunity for US', false);
       oppyUS2.RecordTypeId = newBusinessRecTypeId;
       oppyUS2.ExceptionStatus__c = 'Exception Requested';
       oppyUS2.RequestedLegalEntity__c = leUS.Id;
       oppyUS2.CurrencyIsoCode = 'USD';
       oppyUS2.ContractStartDate__c = date.newinstance(currentFY, 03,21 );
       oppyUS2.OpportunityCountry__c = countryUS.Id;
       insert oppyUS2;
       
       Messaging.InboundEmail email1 = new Messaging.InboundEmail() ;
       Messaging.InboundEnvelope env1 = new Messaging.InboundEnvelope();
       email1.subject = 'Opportunity ' + oppyUS1.Id + ' has been Approved';
       email1.fromAddress = 'someaddress@email.com';
       email1.plainTextBody = 'Approved';
       UpdateExceptionStatusFromEmail emailObj1 = New UpdateExceptionStatusFromEmail();
       Messaging.InboundEmailResult result1 = emailObj1.handleInboundEmail(email1, env1);
       System.assertEquals(true, result1.success, 'result should be true');
       
       Messaging.InboundEmail email2 = new Messaging.InboundEmail() ;
       Messaging.InboundEnvelope env2 = new Messaging.InboundEnvelope();
       email2.subject = 'Opportunity ' + oppyUS2.Id + ' has been Rejected';
       email2.fromAddress = 'someaddress@email.com';
       email2.plainTextBody = 'Rejected';
       UpdateExceptionStatusFromEmail emailObj2 = New UpdateExceptionStatusFromEmail();
       Messaging.InboundEmailResult result2 = emailObj2.handleInboundEmail(email2, env2);
       System.assertEquals(true, result2.success, 'result should be true');
       test.stopTest();
   }
}