objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country/Territory</label>
    <nameField>
        <label>Country/Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries/Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country/Territory</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4728: Create Auto Renewal field on Opportunity that will be updated from Contract.</description>
        <label>Auto-Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContinuationEndDate__c</fullName>
        <description>SFDC1-8989 &quot;Continuation End Date&quot; on the &apos;Renewal&apos; opportunity record type.</description>
        <inlineHelpText>Continuation End Date</inlineHelpText>
        <label>Continuation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.
SFDC-1896 Updated filter criteria for Consulting record type</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoesThisAutoRenewalHaveChanges__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field includes renewal details of opportunity. (JIRA story SFDC1-556)</description>
        <inlineHelpText>Specify if Auto Renewal has any changes.</inlineHelpText>
        <label>Does this Auto Renewal Have Changes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store primary contact name at Opportunity record level.</description>
        <inlineHelpText>To store primary contact name at Opportunity record level.</inlineHelpText>
        <label>Primary Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <description>SFDC1 -171; Describe source of the lead/opportunity
SFDC1-2219; Rename Source System to External Source System
SFDC1-8491: Updated picklist values
SFDC-2753: Added picklist value for PCM</description>
        <inlineHelpText>Please select a value</inlineHelpText>
        <label>External Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Manually Generated</fullName>
                    <default>true</default>
                    <label>Manually Generated</label>
                </value>
                <value>
                    <fullName>IHS CRM</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Lead Generated</fullName>
                </value>
                <value>
                    <fullName>Third Party System</fullName>
                </value>
                <value>
                    <fullName>Polk Salesforce</fullName>
                </value>
                <value>
                    <fullName>Markit Salesforce</fullName>
                </value>
                <value>
                    <fullName>PCM Salesforce</fullName>
                </value>
                <value>
                    <fullName>IHSM Salesforce</fullName>
                </value>
                <value>
                    <fullName>Market Scan (Dealer Instance)</fullName>
                </value>
                <value>
                    <fullName>Market Scan (API Customer Instance)</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                    <isActive>false</isActive>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>Markit SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Markit SFDC</label>
                </value>
                <value>
                    <fullName>Markit Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Markit Salesforce.com</label>
                </value>
                <value>
                    <fullName>Polk SFDC</fullName>
                    <isActive>false</isActive>
                    <label>Polk SFDC</label>
                </value>
                <value>
                    <fullName>Polk Salesforce.com</fullName>
                    <isActive>false</isActive>
                    <label>Polk Salesforce.com</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestScheduleAutoRenewalAutoClose.cls
//-----------------------------
// @author: Paras Dhingra
// @date: 24 Apr 2020
// @description: SFDC-2877 test class for ScheduleAutoRenewalAutoClose batch
//------------------------------
@isTest
private  class TestScheduleAutoRenewalAutoClose {
    @isTest
    private static void TestScheduleAutoRenewalAutoClose() {
        //create test data
        Account testAccount = TestUtility.createTestAccount('Test UpdateContractContinuationEndDate Account ', true);
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('Test Legal Entity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);

        Id renewalRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        List<Opportunity> lstOpportunityToInsert = new List<Opportunity>();
        Opportunity opp1 = new Opportunity();
        opp1.RecordTypeId = renewalRecordTypeId;
        opp1.AccountId = testAccount.Id;
        opp1.Name = 'Test Renewal Opp 1';
        opp1.StageName= '3-Renewal Pending';
        opp1.ContractStartDate__c = System.Today() + 12;
        opp1.ContractEndDate__c = System.Today() + 60;
        opp1.CloseDate = System.Today() + 2;
        opp1.ContinuationEndDate__c = System.Today() + 60;
        opp1.AutoRenewal__c = true;
        opp1.SourceSystem__c = 'Manually Generated';
        opp1.DoesThisAutoRenewalHaveChanges__c = false;
        opp1.Amount = 3000;
        opp1.PrimaryContact__c = 'Test Contact';
        lstOpportunityToInsert.add(opp1);

        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'test1';
        c.AccountId = testAccount.Id;
        c.Email = 'a@tst123example.com';
        insert c;
        Opportunity opp2 = new Opportunity();
        opp2.RecordTypeId = renewalRecordTypeId;
        opp2.AccountId = testAccount.Id;
        opp2.Name = 'Test Renewal Opp 2';
        opp2.StageName= '3-Renewal Pending';
        opp2.ContractStartDate__c = System.Today() + 31;
        opp2.ContractEndDate__c = System.Today() + 60;
        opp2.CloseDate = System.Today() + 31;
        opp2.ContinuationEndDate__c = System.Today() + 60;
        opp2.AutoRenewal__c = true;
        opp2.SourceSystem__c = 'SAP';
        opp2.DoesThisAutoRenewalHaveChanges__c = false;
        opp2.Amount = 3000;
        //opp2.ContractBeingRenewed__c = testContract.Id;
        opp2.PrimaryContact__c = 'Test Contact 2';
        lstOpportunityToInsert.add(opp2);
        insert lstOpportunityToInsert;
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = c.Id;
        ocr.OpportunityId = opp1.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;  
        Test.startTest();
        ScheduleBatchAutoRenewalAutoClose ba = new ScheduleBatchAutoRenewalAutoClose(); //Schedule apex class name
        String sch = '0 0 8 13 2 ?'; //schedule interval time
        String jobId = System.schedule('Run Job for BatchAutoRenewalAutoClose', sch, ba); //system method to schedule apex class
        System.assert(jobId!=null);
        Database.executeBatch(new BatchAutoRenewalAutoClose(), 200);
        try{
        BatchAutoRenewalAutoClose BARAC = new BatchAutoRenewalAutoClose();
        BARAC.query = 'SELECT Id, StageName, Name,CloseDate  FROM Opportunity WHERE Id =\''+opp2.Id+'\'';
        Database.executeBatch(BARAC, 200);
        }catch(exception e){
            UtilityClass.createApexLogRecord(e, 'BatchAutoRenewalAutoClose', 'Finish');
        }
        Test.stopTest();
        //assert oppy
        Opportunity assertOppy1 = [Select Id, StageName from Opportunity where ID=:opp1.Id];
        System.assertEquals('6W-Renewal Won', assertOppy1.StageName,'Opportunity stage name is not correct');
        Opportunity assertOppy2 = [Select Id, StageName from Opportunity where ID=:opp2.Id];
        System.assertNotEquals('6W-Renewal Won', assertOppy2.StageName,'Opportunity stage name is not correct');
    }
}