objects/CustomLink__c.object
<CustomObject>
    <description>SFDC1-5622 to Store the Custom Links, easily find things like clicktools, forms or user request forms.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5622 To check the URL is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomLinkName__c</fullName>
        <description>SFDC1-5622 Custom Link Name</description>
        <inlineHelpText>Please Enter Name of the Custom Link</inlineHelpText>
        <label>Custom Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>SFDC-2564: Created a new field that determines the type of Custom Link.</description>
        <inlineHelpText>Type of Custom Link.</inlineHelpText>
        <label>Domain</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InternalLink__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC-2564 To identify if the URL is an internal link.</description>
        <label>Internal Link?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RelatedField__c</fullName>
        <description>SFDC-2564 Created to add API name(s) of the field(s) that has to be used in the URL field.</description>
        <inlineHelpText>To add API name of the field. This will replace &apos;{FieldValue0}&apos; string in the URL.
In case of multiple fields to be used in the URL, add comma separated API names, in the same sequence as {FieldValue(i)} in the URL field.</inlineHelpText>
        <label>Related Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>SFDC-2564: This field determines the order in which the Custom Links would appear</description>
        <inlineHelpText>Add order number of the custom link.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>SFDC1-5622 - Custom Link&apos;s URL</description>
        <inlineHelpText>Please enter the URL. 
To add a field value as a parameter, use &apos;{FieldValue0}&apos;. In case of multiple parameters, use &apos;{FieldValue0}&apos;, &apos;{FieldValue1}&apos;, &apos;{FieldValue2}&apos; and so on. Eg: www.example.com?p0={FieldValue0}&amp;p1={FieldValue1}&amp;p2={FieldValue2}.</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Custom Link</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Custom Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomLinkController.cls
//-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  SFDC1-5622 Custom Links, to have a list of useful links on lightning home page.
// @return: NA
// @Company: Vertiba
//-----------------------------
public without sharing  class CustomLinkController {
  
//-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  Method to check logged in user is System Admin
// @return: Boolean
// @Company: Vertiba
//-----------------------------
/* //admin check is not required as functionality is desired for all the users
    @AuraEnabled
    public static boolean checkUserIsAdmin() {
        system.debug('Admin Test'+UserInfo.getUserName());
        Id profileId = userInfo.getProfileId();
        system.debug('profileId----'+profileId);
        List<Profile> p = [select id, name from Profile where id=:profileId and name='System Administrator'];
        if(!p.isempty()) {
            system.debug('true');
            return true;
        }
        else {
            system.debug('false');
            return false;
        }
    }
*/
 //-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  SFDC1-5622 Custom Links, to have a list of useful links on lightning home page.
// @return: List of Custom Links
// @Company: Vertiba
//-----------------------------
    @AuraEnabled
    public static list<customLink__c> loadCustomLinks(String domain) {
        system.debug('custom Links');
        System.Debug('Domain Value--->'+domain);
        List<customLink__c> cl = [select CustomLinkName__c,url__c,Domain__c,RelatedField__c, active__c, InternalLink__c from customLink__c where active__c = true AND Domain__c=:domain
                                  order by SortOrder__c asc];
        system.debug('custom Links'+cl);
        return cl;
    }
    //-----------------------------
	// @author: Priyanka Vyas
	// @date: 28 Mar 2020
	// @description:  SFDC1-2564 Custom Links, to fetch the fields of the parent Object
	// @return: Record field values
	//-----------------------------
    @AuraEnabled
    public static sobject fetchSObjectfields(String recordString){
        SObject record;
        if(recordString!=null){  
        	ID recordId = recordString;
            DescribeSObjectResult describeResult = recordId.getSObjectType().getDescribe();	
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            String query =
                ' SELECT ' +
                 String.join( fieldNames, ',' ) +
                ' FROM ' +
                 describeResult.getName() +
                ' WHERE ' +
                ' id = :recordId ' +
                ' LIMIT 1 ';
    
            record = Database.query( query );
            System.debug( record );
       }
       return record; 
    }
}