objects/CustomLink__c.object
<CustomObject>
    <description>SFDC1-5622 to Store the Custom Links, easily find things like clicktools, forms or user request forms.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5622 To check the URL is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomLinkName__c</fullName>
        <description>SFDC1-5622 Custom Link Name</description>
        <inlineHelpText>Please Enter Name of the Custom Link</inlineHelpText>
        <label>Custom Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>SFDC-2564: Created a new field that determines the type of Custom Link.</description>
        <inlineHelpText>Type of Custom Link.</inlineHelpText>
        <label>Domain</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>SFDC1-5622 - Custom Link&apos;s URL</description>
        <inlineHelpText>Please enter the URL. 
To add a field value as a parameter, use &apos;{FieldValue0}&apos;. In case of multiple parameters, use &apos;{FieldValue0}&apos;, &apos;{FieldValue1}&apos;, &apos;{FieldValue2}&apos; and so on. Eg: www.example.com?p0={FieldValue0}&amp;p1={FieldValue1}&amp;p2={FieldValue2}.</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Custom Link</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Custom Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCustomLinkController.cls
//-----------------------------
// @author: Vinod Merwade
// @date: 6 Nov 2017
// @description:  Test class for the CustomLinkController
// @return: NA
// @Company: Vertiba
//-----------------------------

@isTest
public class TestCustomLinkController {
    
    //-----------------------------
    // @author: Vinod Merwade
    // @date: 6 Nov 2017
    // @description:  Test Setup for the loading the custom links
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    
    @testSetup public static void setup() {
        CustomLink__c cLink1 = new CustomLink__c(
            CustomLinkName__c = 'Opportunity List',
            Domain__c='Global',
            URL__c = '/006/o',
            Active__c = true
        );
        insert cLink1;
        CustomLink__c cLink2 = new CustomLink__c(
            CustomLinkName__c = 'Opportunity List',
            Domain__c='Global',
            URL__c = 'https://www.google.com',
            Active__c = true
        );
        insert cLink2;
    }
    //-----------------------------
    // @author: Vinod Merwade
    // @date: 6 Nov 2017
    // @description:  Test Setup for the loading the custom links
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    public static testmethod void customLinkControllerTest() {
        List<CustomLink__c> cl = new List<CustomLink__c>();
        String domain='Global';
        cl= CustomLinkController.loadCustomLinks(domain);
        Account a=TestUtility.createTestAccount('TestAccount', true);
        SObject accRecord=CustomLinkController.fetchSObjectfields(a.id);
        system.assertNotEquals(a.id, null);
        system.assertEquals(2, cl.size());
    }
    
}