objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipName>Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2969 Comma separated field to capure all Internal Business segments related to the opportunity product</description>
        <inlineHelpText>This is a calculated field to list all the Internal Business segments for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Internal Business Segments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <description>SFDC - 1346 field to capture sub business line related to the products</description>
        <inlineHelpText>This is a calculated field to list all the sub business lines for all the Opportunity Products where the status on the Opportunity Product is &quot;New&quot; or &quot;Existing&quot;.</inlineHelpText>
        <label>Sub Business Lines</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>IPJurisdiction__c</fullName>
        <description>SFDC1-215. Contains the Tax Country field pulled in from the product. Complies with the US Supreme Court Wayfair Decision and Tax Reform Act effective Jan. 1, 2019. 
SFDC-723. Renamed and replaced the fields.</description>
        <formula>PricebookEntry.Product2.IPJurisdiction__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Complies with the US Supreme Court Wayfair Decision and Tax Reform Act effective Jan. 1, 2019.</inlineHelpText>
        <label>IP Jurisdiction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AAG__c</fullName>
        <description>SFDC1-2086;Product picklist value</description>
        <inlineHelpText>Account Assignment Group</inlineHelpText>
        <label>AAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Transaction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software/Services</fullName>
                </value>
                <value>
                    <fullName>SubscriptionVar</fullName>
                </value>
                <value>
                    <fullName>Subscript Maint RAR</fullName>
                </value>
                <value>
                    <fullName>Subscript Licenc RAR</fullName>
                </value>
                <value>
                    <fullName>Credit/Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Credit/Deposit</label>
                </value>
                <value>
                    <fullName>Prod Design Deposits</fullName>
                    <isActive>false</isActive>
                    <label>Prod Design Deposits</label>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                    <isActive>false</isActive>
                    <label>Rebates</label>
                </value>
                <value>
                    <fullName>Withholding Tax</fullName>
                    <isActive>false</isActive>
                    <label>Withholding Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Product Family</inlineHelpText>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPJurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-215. Field required for compliance with the US Supreme Court Wayfair Decision and Tax Reform Act effective Jan. 1, 2019. 
SFDC-723 Renamed the Label and API Name</description>
        <inlineHelpText>Field required for compliance with the US Supreme Court Wayfair Decision and Tax Reform Act effective Jan. 1, 2019.</inlineHelpText>
        <label>IP Jurisdiction</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Products (IP Jurisdiction)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalBusinessSegment__c</fullName>
        <description>SFDC-2624 Internal Business Segment field for Sales Product Reporting</description>
        <inlineHelpText>For Sales Product Reporting</inlineHelpText>
        <label>Internal Business Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalProductName__c</fullName>
        <inlineHelpText>Extended Name, Internal-Facing Only</inlineHelpText>
        <label>Internal Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MediaType__c</fullName>
        <inlineHelpText>Format of Deliverable</inlineHelpText>
        <label>Media Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines Availability/Sellability</inlineHelpText>
        <label>Product Status</label>
        <referenceTo>CrossPlantStatus__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCrossPlantStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductExtensions__c.object
<CustomObject>
    <description>SFDC1-134 : This Object will be used to Track the Product Extensions between Product and Legal Entities</description>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-134 : This field will be used to store the value of Legal Entity</description>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Product Extensions</relationshipLabel>
        <relationshipName>Product_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Extensions</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Product Extensions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProductSearchControllerLWC.cls
//@Createdby : Pankhuri Jain
//@date: 28 Feb 2022
/*@description : SFDC-2964 Clone from productSearchController,Changes modified for new LWC components.Removed unused code/methods previous in use.
               : New class referenced in Add/Edit LWC components (SearchProductList and LegalEntitySelection)*/

public without sharing class ProductSearchControllerLWC {
   
    //@last modified: Pankhuri Jain
    //@modifiedDate: 28 Feb 2022  
    //@modifiedDecription : SFDC-2964  Updates done for New Add/Edit Screens. Removed unused code previous in use in Aura components
    
    //@modified: Manish Kumar
    //@modifiedDate: 18th Oct 2021
    //@modifiedDecription: SFDC-4730 Changes for Search products screen to include new fields in the filter criteria
    
    //@modified: Tran-Vu Tran
    //@modifiedDate: 4th April 2019
    //@modifiedDecription: SFDC-1278 allow "Renewal Only" products to be added to Renewal opportunity
    
    //@Author : Paras Dhingra
    //@date: 17th Aug 2017
    //@description : SFDC1-2043 fetch search products based on user filters
    
    @auraEnabled 
    public static List<productSelectorWrapperClass> getProducts(String familyName, String productName,String materialNumber, String businessLine, String subBusinessLine, String profitCenter, String mediaType, String internalProductName,String productGroup,String internalBusinessSegment, String aag) {
                                 
        List<productSelectorWrapperClass> lstProductsToReturn = new List<productSelectorWrapperClass>();
        System.debug('--familyName--'+ familyName);
        List<Product2> lstProductsLegal = new List<Product2>();
        Map<Id,Product2> mapProductIds = new Map<Id,Product2>();
        Set<Id> setExtensionProductIds = new Set<Id>();
        Set<id> setProductIds = new Set<id>();
      
        String availableForSale = '04';
        String renewalOnly = '09'; //SFDC-1278
        String queryBase = 'Select id, name, family__c, family__r.Name, MaterialCode__c, BusinessLine2__r.name, SubBusinessLine__r.name, ProfitCenters__r.Name, InternalProductName__c, MediaType__c, LegalEntity__c,ProductGroup__r.Name, AAG__c, InternalBusinessSegment__c, IPJurisdiction__r.Name from Product2 where';
    
        String queryCommonFilter = ' isActive=true AND (ProductStatus__r.SAPCode__c=:availableForSale OR ProductStatus__r.SAPCode__c=:renewalOnly)';
        if(familyName!=null && !String.IsBlank(familyName)) {
            queryCommonFilter += ' AND family__r.Name like \'%'+familyName+'%\'';
        }
        if(productName!=null && !String.IsBlank(productName)) {                                                                         
            queryCommonFilter+= ' AND Name like \'%'+productName+'%\'';
        }
        if(materialNumber!=null && !String.IsBlank(materialNumber)) {
            queryCommonFilter+= ' AND  MaterialCode__c like \'%'+materialNumber+'%\'';
        }
        if(businessLine!= '--None--' && !String.IsBlank(businessLine)) {
            queryCommonFilter += ' AND BusinessLine2__r.name = \''+businessLine+'\'';
        }
        if(subBusinessLine!= '--None--' && !String.IsBlank(subBusinessLine)) {
            queryCommonFilter += ' AND SubBusinessLine__r.name = \''+subBusinessLine+'\'';
        }
        if(profitCenter!=null && !String.IsBlank(profitCenter)) {
            queryCommonFilter += ' AND ProfitCenters__r.name like \'%'+profitCenter+'%\'';
        }
        if(mediaType!=null && !String.IsBlank(mediaType)) {
            queryCommonFilter += ' AND MediaType__c like \'%'+mediaType+'%\'';
        }
        if(internalProductName!=null && !String.IsBlank(internalProductName)) {
            queryCommonFilter += ' AND internalProductName__c like \'%'+internalProductName+'%\'';
        }
        if(productGroup!=null && !String.IsBlank(productGroup)) {
            queryCommonFilter += ' AND ProductGroup__r.Name like \'%'+productGroup+'%\'';
        }
        //SFDC-4730 Change start
        if(internalBusinessSegment!= '--None--' && !String.IsBlank(internalBusinessSegment)) {
            queryCommonFilter += ' AND internalBusinessSegment__c = \''+internalBusinessSegment+'\'';
        }
        if(aag!= '--None--' && !String.IsBlank(aag)) {
            queryCommonFilter += ' AND AAG__c = \''+aag+'\'';
        }
        String queryFinalLegal = queryBase + queryCommonFilter + ' ORDER BY MaterialCode__c ASC LIMIT 100' ;
        System.debug('--queryFinalLegal--'+ queryFinalLegal);

        mapProductIds = new Map<Id,Product2>((List<Product2>)Database.query(queryFinalLegal)); 
        
        
        //check if products are extended in product extensions
        //query the product extenstions and fetch related extensions only
        if(mapProductIds!=null && !mapProductIds.isEmpty()) {
            
            for(ProductExtensions__c pe : [Select Product__c from ProductExtensions__c where Product__r.isActive=true
                                    AND Status__c='Active' AND Product__c IN: mapProductIds.keySet() ] ) {
            //SFDC-4730 Change end
            setExtensionProductIds.add(pe.Product__c);
        }
            //SFDC-4730 Change start
            for(Product2 prd : mapProductIds.values()){
                setProductIds.add(prd.id);
            }
            //SFDC-4730 Change end
            for(Product2 prod : mapProductIds.values()) {
                productSelectorWrapperClass pswc = new productSelectorWrapperClass();
                                                                                            
                if(setProductIds.contains(prod.id) || setExtensionProductIds.contains(prod.Id)) {
                //SFDC-4730 Change end
                    pswc.isSelected = false;
                    pswc.product = prod;
                    pswc.ProductName = prod.Name;
                    pswc.productId = prod.Id;                  
                    lstProductsToReturn.add(pswc);                   
                }            
            }
        }
        System.debug('--getQueries--'+Limits.getQueries());

        System.debug('--lstProductsToReturn.size before recursion--'+lstProductsToReturn.size());
        
        return lstProductsToReturn;
    }


    //@Author : Paras Dhingra
    //@date: 17th Aug 2017
    //@description : SFDC1-2043 fetch productIds already on opportunity
    @auraEnabled
    public static List<String> getProductsAlreadyInOppy(String oppyId) {
        List<String> lstProductId = new List<String>();
        List<OpportunityLineItem> lstOppyProduct = [Select Product2Id from OpportunityLineItem where OpportunityId=:oppyId];
        if(lstOppyProduct!=null && !lstOppyProduct.isEmpty()) {
            for(OpportunityLineItem oli : lstOppyProduct) {
                lstProductId.add(oli.Product2Id);
            }
        }
        return lstProductId;
    }

    //@Author : Pankhuri Jain
    //@date : 28 Feb 2022
    //@description : Fetch map of all InternalBusiness, related Business and related SubBusiness Lines in sorted order
    @auraEnabled 
    public static Map<String, Map<String, List<String>>> getIbsBsSubBsLines() {
        
        Map<String, Map<String, List<String>>> mapIbsBs = new Map<String, Map<String, List<String>>>();
        
        List<AggregateResult> lstProduct = [Select count(id),InternalBusinessSegment__c ibsName,BusinessLine2__r.Name blName,SubBusinessLine__r.Name sblName from product2 where NOT (InternalBusinessSegment__c LIKE 'zzz%' OR isActive = false OR InternalBusinessSegment__c = '') group by InternalBusinessSegment__c,BusinessLine2__r.Name,SubBusinessLine__r.Name order by InternalBusinessSegment__c,BusinessLine2__r.Name,SubBusinessLine__r.Name];
        
        Map<String, List<String>> mapBsSbs = new Map<String, List<String>>(); 
        List<String> sbsList = new List<String>();
        
        for(AggregateResult prd : lstProduct) {
            mapBsSbs = new Map<String, List<String>>();
            sbsList = new List<String>();
            if(mapIbsBs.containsKey((String)prd.get('ibsName'))) {
                mapBsSbs = mapIbsBs.get((String)prd.get('ibsName'));                
                if(mapBsSbs.containsKey((String)prd.get('blName'))) {
                    sbsList = mapBsSbs.get((String)prd.get('blName'));                      
                }
            }
            sbsList.add((String)prd.get('sblName'));
            mapBsSbs.put((String)prd.get('blName'), sbsList);
            mapIbsBs.put((String)prd.get('ibsName'), mapBsSbs);
        }
        
        return mapIbsBs;

    }
   
}