objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipName>Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <description>SFDC1-7525 Profit center to be rolled up from opportunity product&apos;s related product
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Profit center for related products automatically populated by system</inlineHelpText>
        <label>Profit Center</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SynergyTheme__c</fullName>
        <label>Synergy Theme</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SynergyType__c</fullName>
        <label>Synergy Type</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynergyTheme__c</fullName>
        <label>Synergy Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1. Expand MI Desktop</fullName>
                </value>
                <value>
                    <fullName>2. Data Distribution</fullName>
                </value>
                <value>
                    <fullName>3. Private Markets</fullName>
                </value>
                <value>
                    <fullName>4. Corporates</fullName>
                </value>
                <value>
                    <fullName>5. Risk &amp; Compliance</fullName>
                </value>
                <value>
                    <fullName>6. Research and Advisory</fullName>
                </value>
                <value>
                    <fullName>9. Wealth Management and Retail Investing</fullName>
                </value>
                <value>
                    <fullName>PD - Expand EWB</fullName>
                </value>
                <value>
                    <fullName>PD - Other</fullName>
                </value>
                <value>
                    <fullName>TRANS - pending 1</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Energy Transition</fullName>
                </value>
                <value>
                    <fullName>Financials Expansion</fullName>
                </value>
                <value>
                    <fullName>Insights to Pricing Solution</fullName>
                </value>
                <value>
                    <fullName>Non Energy Commodities Penetration</fullName>
                </value>
                <value>
                    <fullName>Technology, Data &amp; Platforms</fullName>
                </value>
                <value>
                    <fullName>Auto Data Expansion</fullName>
                </value>
                <value>
                    <fullName>10. M&amp;T</fullName>
                </value>
                <value>
                    <fullName>8. APAC Other</fullName>
                </value>
                <value>
                    <fullName>6. Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>7. ESG &amp; Climate</fullName>
                </value>
                <value>
                    <fullName>12. Digital</fullName>
                </value>
                <value>
                    <fullName>11. Investment Management</fullName>
                </value>
                <value>
                    <fullName>10. EDM</fullName>
                </value>
                <value>
                    <fullName>11.Unassigned</fullName>
                    <isActive>false</isActive>
                    <label>11.Unassigned</label>
                </value>
                <value>
                    <fullName>8. APAC</fullName>
                    <isActive>false</isActive>
                    <label>8. APAC</label>
                </value>
                <value>
                    <fullName>99.Unassigned</fullName>
                    <isActive>false</isActive>
                    <label>99.Unassigned</label>
                </value>
                <value>
                    <fullName>Non-Energy Commodities Penetration</fullName>
                    <isActive>false</isActive>
                    <label>Non-Energy Commodities Penetration</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SynergyType__c</fullName>
        <label>Synergy Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SynergyTheme__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1.1 Cross sell FS Issuance solutions Book Building products</fullName>
                </value>
                <value>
                    <fullName>1.2 Cross sell FS BRST data to MI clients</fullName>
                </value>
                <value>
                    <fullName>1.3 FS Issuance to MI clients</fullName>
                </value>
                <value>
                    <fullName>3 FS PVR, Equities Info and Private Vals to MI clients</fullName>
                </value>
                <value>
                    <fullName>7.1 FS Notice Manager, Private Markets, WSO, and Debt Domain to MI clients</fullName>
                </value>
                <value>
                    <fullName>7.2 FS Notice Manager, Private Markets, WSO, and Debt Domain to MI clients</fullName>
                </value>
                <value>
                    <fullName>7.3 FS Notice Manager, Private Markets, WSO, and Debt Domain to MI clients</fullName>
                </value>
                <value>
                    <fullName>10.1 FS Issuer services solutions to MI clients</fullName>
                </value>
                <value>
                    <fullName>10.2 FS Issuer services solutions to MI clients</fullName>
                </value>
                <value>
                    <fullName>13. FS KYC to MI IB, IM, and CB clients</fullName>
                </value>
                <value>
                    <fullName>14. FS KY3P to MI clients</fullName>
                </value>
                <value>
                    <fullName>19.2 Cross sell ECR Supply Chain data to MI clients</fullName>
                </value>
                <value>
                    <fullName>20. FS cross sell ECR PMI to MI clients</fullName>
                </value>
                <value>
                    <fullName>21. FS ECR content to MI clients</fullName>
                </value>
                <value>
                    <fullName>24. FS Markit Digital to MI DMS customers</fullName>
                </value>
                <value>
                    <fullName>Engineering Workbench to Platts Customers</fullName>
                </value>
                <value>
                    <fullName>PD - Other</fullName>
                </value>
                <value>
                    <fullName>P/R Cons Chemicals - Cross Sell #75</fullName>
                </value>
                <value>
                    <fullName>P/R Cons Power consulting - Cross Sell #76</fullName>
                </value>
                <value>
                    <fullName>P/R Cons Agri &amp; OMD consulting - Cross Sell #77</fullName>
                </value>
                <value>
                    <fullName>P/R Cons Financials - Cross Sell #80</fullName>
                </value>
                <value>
                    <fullName>P/R ET CSM &amp; Climate Scenarios - Cross Sell #11</fullName>
                </value>
                <value>
                    <fullName>P/R ET Mobility &amp; energy futures - Cross Sell #45</fullName>
                </value>
                <value>
                    <fullName>P/R ET Clean Energy Tech &amp; hydrogen - Cross Sell #70</fullName>
                </value>
                <value>
                    <fullName>P/R ET Corporate Emissions Solutions - Cross Sell #70.2</fullName>
                </value>
                <value>
                    <fullName>P/R ET EnergyView Climate/Energy Adv - Cross Sell #71</fullName>
                </value>
                <value>
                    <fullName>P/R FE Upstream to financials - Cross Sell #23</fullName>
                </value>
                <value>
                    <fullName>P/R ITP Crude News &amp;  Analytics - Cross Sell #22</fullName>
                </value>
                <value>
                    <fullName>P/R ITP Waterborne LPG - Cross Sell #41</fullName>
                </value>
                <value>
                    <fullName>P/R ITP Carve out R&amp;M Market Profiles - Cross Sell #44</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <description>SFDC1-6958: Global Segment field will be populated from the SAP Product Master and incorporated with the load to keep products in sync.</description>
        <inlineHelpText>Reporting Global Segment</inlineHelpText>
        <label>Global Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RuleDefinition__c.object
<CustomObject>
    <fields>
        <fullName>BusinessFunctionality__c</fullName>
        <label>Business Functionality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleObject__c</fullName>
        <label>Rule Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Definition</label>
    <nameField>
        <label>Rule Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RuleEntry__c.object
<CustomObject>
    <fields>
        <fullName>CriteriaCondition__c</fullName>
        <label>Criteria Condition</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OutputColumns__c</fullName>
        <label>Output Columns</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RuleDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Definition</label>
        <referenceTo>RuleDefinition__c</referenceTo>
        <relationshipLabel>Rule Entries</relationshipLabel>
        <relationshipName>Rule_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rule Entry</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Rule Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestRuleEngineLogic.cls
//-----------------------------
// @author: Digvijay Singh
// @date: 25 Jan 2022
// @param: NA
// @description: Test class for RuleEngineLogic methods 
// @return: NA 
//                                      T
//-----------------------------

@isTest
private class TestRuleEngineLogic  {

    //-----------------------------
    // @author: Digvijay Singh
    // @date: 25 Jan 2022
    // @description: Test Setup
    // @return: NA 
    //                                      
    //-----------------------------
     @testSetup static void setup() {
         
        RuleDefinition__c robj=new RuleDefinition__c();
        robj.BusinessFunctionality__c='OpportunityLineItemSynergyRules';
        robj.RuleObject__c='OpportunityLineItem';
        robj.Name='OpportunityLineItemSynergyRules';
        insert robj;
        
        List<RuleEntry__c> listruleEntry=new List<RuleEntry__c >();
        RuleEntry__c rentryObj1= new RuleEntry__c(RuleDefinition__c=robj.Id,CriteriaCondition__c='Product2.Division__c=Resources|Product2.MaterialCode__c = 2000028208',
        OutputColumns__c='SynergyType__c=P/R ET Mobility & energy futures - Cross Sell #45| SynergyTheme__c=Energy Transition');
        listruleEntry.add(rentryObj1);
        RuleEntry__c rentryObj2= new RuleEntry__c(RuleDefinition__c=robj.Id,CriteriaCondition__c='Product2.Division__c=Resources|ProductGroup__c.Name IN: Agri Consulting, Agri Multi-Client Studies,Coal Consulting, Crop Forecasting Consulting,EWP Consulting, Expert Connect-UPS',
        OutputColumns__c='SynergyType__c=P/R Cons Financials - Cross Sell #80| SynergyTheme__c=Consulting');
        RuleEntry__c rentryObj3= new RuleEntry__c(RuleDefinition__c=robj.Id,CriteriaCondition__c='Product2.Division__c=Resources|ProductGroup__c.Name = Commodities & Food |Product2.Name Contains: Sugar',
        OutputColumns__c='SynergyType__c=P/R NEC Sugar Economics / Analytics - Cross Sell #4| SynergyTheme__c=Non-Energy Commodities Penetration');
        listruleEntry.add(rentryObj2);
        listruleEntry.add(rentryObj3);
        
        insert listruleEntry;
        //adding more atttributes to product
        ProfitCenter__c testProfitCenter = new ProfitCenter__c(Name='UP - Energy', Active__c=true, ProfitCenterCode__c='187');
        insert testProfitCenter;
        Family__c testProdFam = new Family__c(Name='ETC-C&A',Status__c ='Active');
        insert testProdFam;
        ProductGroup__c pg = TestUtility.createProductGroup('Agri Consulting',false,false);//SFDC1-5228 JK- New
        //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', false);
        testProd.FormerIpOwner__c = 'IHS Markit Global Inc.';
        testProd.Division__c='Resources';
        testProd.MaterialCode__c = '2000028208';
        testProd.Family__c = testProdFam.Id;
        testProd.ProfitCenters__c = testProfitCenter.Id;
        testProd.ProductGroup__c = pg.Id;//SFDC1-5228 JK- New
        insert testProd;
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        Integer currentFY = UtilityClass.calculateFyFromDate(Date.Today(), UtilityClass.FiscalStartMonth);
        Integer nextFY = currentFY+1;
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;

        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', false);
        testOpportunity.ContractStartDate__c =  date.newinstance(currentFY, 03,21 );
        testOpportunity.ContractEndDate__c = date.newinstance(currentFY+2, 10, 21);
        testOpportunity.Synergy1__c='Yes';
        insert testOpportunity;
         
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, false);
        testOLI.IsProductatRisk__c = 'No';
        testOLI.RiskStatus__c = 'Closed - Downgraded';
        insert testOLI;
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(2223.23, String.valueof(currentFY), '3 Years', String.valueof(currentFY), testProd.Id, false);
        ProductSchedule__c ps2 = TestUtility.createProductSchedule(2323.23, String.valueof(currentFY), '3 Years', String.valueof(currentFY+1), testProd.Id, false);
        ProductSchedule__c ps3 = TestUtility.createProductSchedule(2423.23, String.valueof(currentFY), '3 Years', String.valueof(currentFY+2), testProd.Id, false);
        //insert product schedule for 2018 financial year
        ProductSchedule__c ps4 = TestUtility.createProductSchedule(2223.23, String.valueof(nextFY), '3 Years', String.valueof(nextFY), testProd.Id, false);
        ProductSchedule__c ps5 = TestUtility.createProductSchedule(2223.23, String.valueof(nextFY), '3 Years', String.valueof(nextFY+1), testProd.Id, false);
        ProductSchedule__c ps6 = TestUtility.createProductSchedule(2223.23, String.valueof(nextFY), '3 Years', String.valueof(nextFY+2), testProd.Id, false);
        insert new List<ProductSchedule__c>{ps1,ps2,ps3,ps4,ps5,ps6};
        OpportunityLineItemSchedule__c ops1 = TestUtility.createOpportunityProductSchedule(testOpportunity.Id,ps1.Id,2223.23,2000,
                                                                                            'Amount', 223.23, 0.0, testProd.Id, '2017', 1, 
                                                                                            testOLI.Id,false);
        OpportunityLineItemSchedule__c ops2 = TestUtility.createOpportunityProductSchedule(testOpportunity.Id,ps2.Id,2323.23,2000,
                                                                                            'Amount', 323.23, 0.0, testProd.Id, '2018', 1, 
                                                                                            testOLI.Id,false);
        OpportunityLineItemSchedule__c ops3 = TestUtility.createOpportunityProductSchedule(testOpportunity.Id,ps3.Id,2323.23,2000,
                                                                                            'Amount', 423.23, 0.0, testProd.Id, '2019', 1, 
                                                                                            testOLI.Id,false);
        insert new List<OpportunityLineItemSchedule__c>{ops1,ops2,ops3};
        
    }

    //-----------------------------
    // @author: Digvijay Singh
    // @date: 25 Jan 2022
    // @description: Test method for runtheBusinessLogic
    // @return: NA 
    //                                      
    //-----------------------------
     private static testMethod void testruntheBusinessLogic() {
     
        OpportunityLineItem testOLI = [Select Id,Product2Id, OpportunityId from OpportunityLineItem limit 1];
        Product2 testProd=new Product2(Id=testOLI.Product2Id );
        testOLI.Description= 'Test';
        
        Test.startTest();
        update testOLI;
        testOLI = [Select Id,SynergyTheme__c,SynergyType__c,Product2Id, OpportunityId from OpportunityLineItem limit 1];
        System.assertEquals(testOLI.SynergyTheme__c, 'Energy Transition');
        System.assertEquals(testOLI.SynergyType__c, 'P/R ET Mobility & energy futures - Cross Sell #45');
        testProd.MaterialCode__c ='87676';
        update testProd;
        testOLI.Description= 'Test2';
        update testOLI;
        Opportunity testoppy=[Select Id,Synergy1__c,SynergyTheme__c,SynergyType__c from Opportunity Limit 1];
        testoppy.Synergy1__c='No';
        update testoppy;
        testoppy.Synergy1__c='Yes';
        update testoppy;
        testOLI = [Select Id,SynergyTheme__c,SynergyType__c,Product2Id, OpportunityId from OpportunityLineItem limit 1];
        System.assertEquals(testOLI.SynergyTheme__c, 'Consulting');
        System.assertEquals(testOLI.SynergyType__c, 'P/R Cons Financials - Cross Sell #80');
        Test.stopTest();       
     }
     
}