objects/Feedback__c.object
<CustomObject>
    <description>SDFC-4199- The sales team wants to capture the feedback of the end customer (decision-makers) at the time or after negotiating an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4199 Link opportunity with the feedback</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestOppyContactRolesController.cls
//-----------------------------
// @author: Sharique Iqbal
// @date: 7th Dec 2021
// @description: Test class for LWC Controller-OppyContactRolesController 
// @company: IHS Markit
//-----------------------------
@isTest
public class TestOppyContactRolesController{
	@isTest
    public static void TestMethod1() {
        
        Account testAccount  = testUtility.createTestAccount('test Account', True );
        Contact con = testUtility.createContact(testAccount.Id, 'mark@test.com', true, 'Mark', 'Wood');
        Opportunity testOpportunity = testUtility.createOpportunity(testAccount.Id, 'test Opportunity', true);
        OpportunityContactRole ocr = new OpportunityContactRole();
         ocr.ContactId = con.Id;
         ocr.IsPrimary = True;
         ocr.Role = 'Business User';
         ocr.OpportunityID = testOpportunity.Id;
        insert ocr;
        
        Feedback__c fdbk =  new Feedback__c();
        fdbk.Opportunity__c = testOpportunity.Id;
        insert fdbk;
        List <OpportunityContactRole> conRolesList = OppyContactRolesController.getOppyContactRoles(fdbk.Id);
        System.assertEquals(conRolesList.size()>0,True, 'Unable to fetch Opportunity ContactRoles');
    }
}