objects/Feedback__c.object
<CustomObject>
    <description>SDFC-4199- The sales team wants to capture the feedback of the end customer (decision-makers) at the time or after negotiating an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-4199 Link opportunity with the feedback</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OppyContactRolesController.cls
/**
 * @author: Sharique Iqbal
 * @date : 2nd Dec 2021
 * @description: SFDC-4199 Controller for lightning component to fetch related
 * 				Opportunity Contact Roles
*/

public class OppyContactRolesController {
	@AuraEnabled(cacheable=true)
    public static List<OpportunityContactRole> getOppyContactRoles(String recId){
        System.debug('$$$ getOppyContactRoles Called');
        Id oppyId = [Select id, Opportunity__c from Feedback__c where Id = :recId].Opportunity__c;
        List<OpportunityContactRole> lstOppyContctRoles = [Select id, ContactId,Contact.Name,IsPrimary,Role,Contact.Email,
                                          Contact.Account.Name, Contact.AccountId, Contact.Phone FROM OpportunityContactRole where OpportunityId=:oppyId ];
      
        return lstOppyContctRoles;
    }
}