objects/FieldServiceActivityAttendee__c.object
<CustomObject>
    <description>SFDC1-166.
Tracks attendees for the Field Service Activities.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-1052.
Main contact associated with the field Service Activity.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Service Activity Attendees</relationshipLabel>
        <relationshipName>FieldServiceActivityAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-1052.
Reference to the Field Service Activity.</description>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Attendees</relationshipLabel>
        <relationshipName>FSAAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Field Service Activity Attendee</label>
    <nameField>
        <displayFormat>FSATND-{00000}</displayFormat>
        <label>FSA Attendee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FieldServiceActivityProduct__c.object
<CustomObject>
    <description>SFDC1-166.
Tracks products behind the Field Service Activities.</description>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-166.
Reference to the field service activity.</description>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6381: Changing the lookup from Product to Product group</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Service Activity Product</label>
    <nameField>
        <displayFormat>FSAPRD-{00000}</displayFormat>
        <label>Field Service Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestFSAProductMethods.cls
//-----------------------------
// @author: Manish Kumar
// @date: 5th Aug 2021
// @param: NA
// @description: Test class for FSA Products methods 
// @return: NA
//-----------------------------

@isTest
private class TestFSAProductMethods {
    
	//-----------------------------
	// @author: Manish Kumar
	// @date: 5th Aug 2021
	// @param: NA
	// @description: Test Method for FSA Products creation
	// @return: NA
	//-----------------------------
	@isTest
    	static void createFSAProducts() {
        
        //Create a test Account
        Account acct = TestUtility.createTestAccount('Test Account For Survey Response', true);
		
        //Create a Contact
        Contact con = TestUtility.createContact(acct.id,'testemail@test.com',true,'TestFirstName','TestLastName');
		
        //Create a Work Order
        WorkOrder workOrderObj = TestUtility.createFieldServiceActivity(con.id, true);
        //update workOrderObj;
        //workOrderDispatcher.isAfterUpdateProcessing = true;
        //update workOrderObj;
		
        //Create a Product Group
		ProductGroup__c productGroupObj = TestUtility.createProductGroup('Test Product Group 1', true);
        ProductGroup__c productGroupObj2 = TestUtility.createProductGroup('Test Product Group 2', true);
            
            //Create FSA Product
            FieldServiceActivityProduct__c fsaProductObj = TestUtility.createFSAProduct(workOrderObj.id, productGroupObj.id, true); 
            FieldServiceActivityAttendee__c fsaAttendee = New FieldServiceActivityAttendee__c();
        	fsaAttendee.FieldServiceActivity__c = workOrderObj.id;
        	fsaAttendee.Contact__c = con.id;
        	insert fsaAttendee;
        	workOrderObj.status = 'Delivered';
            update workOrderObj;
        	workOrderDispatcher.isAfterUpdateProcessing = true;
        	update workOrderObj;
            fsaProductObj.ProductGroup__c = productGroupObj2.Id;
            test.startTest();
            update fsaProductObj;
            List<FieldServiceActivityProduct__c> fsapList = new list<FieldServiceActivityProduct__c>();
            fsapList.add(fsaProductObj);
            for(FieldServiceActivityProduct__c fsap: fsapList) {
                System.assertEquals(productGroupObj2.Id, fsap.ProductGroup__c, 'Product group mathes after update');
            }
            test.stopTest();
        }
}