objects/FieldServiceActivityProduct__c.object
<CustomObject>
    <description>SFDC1-166.
Tracks products behind the Field Service Activities.</description>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-166.
Reference to the field service activity.</description>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6381: Changing the lookup from Product to Product group</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Field Service Activity Products</relationshipLabel>
        <relationshipName>FieldServiceActivityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Service Activity Product</label>
    <nameField>
        <displayFormat>FSAPRD-{00000}</displayFormat>
        <label>Field Service Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>ProductGroups__c</fullName>
        <label>Product Groups</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSAProductMethods.cls
//*********************************************************************************************************************
// @author Vaishali Jain
// @date 4th June 2021
// @description Class created to add common methods to be used by FSA Product trigger handler classes
//*********************************************************************************************************************

public class FSAProductMethods {
    
    /**
     * @author Vaishali Jain
     * @date 4th June 2021
     * @description when the FSA Product is updated,
     * Concatenate FSA Product name to ProductGroup on FSA when FSA Product is inserted or updated
     */
    public static void updateFSAProductGroups(TriggerParameters tp) {
    
        //create a set to store the product Group record Ids
        Set<Id> FSAIdSet = new Set<Id>();
        List<String> ProductNameList = new List<String> ();
        List<WorkOrder> fsaListUpdate = new List<WorkOrder> ();
        if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert) {
            for(FieldServiceActivityProduct__c fsaProd: (List<FieldServiceActivityProduct__c>)tp.newList) {
                if(fsaProd.FieldServiceActivity__c != null) {
                    FSAIdSet.add(fsaProd.FieldServiceActivity__c);
                }
            }
            List<WorkOrder> fsaList = [Select id, ProductGroups__c,(Select name,ProductGroup__r.Name from FieldServiceActivityProducts__r) FROM WorkOrder Where Id IN :FSAIdSet];
            System.debug(' ===fsaList 28 == '+fsaList);
            for(WorkOrder wo : fsaList) {
                for(FieldServiceActivityProduct__c fsaProd : wo.FieldServiceActivityProducts__r) {
                    ProductNameList.add(fsaProd.ProductGroup__r.Name);
                    System.debug(' ===ProductNameList 32 == '+ProductNameList);
                }
                wo.ProductGroups__c = String.join(ProductNameList,',');
                System.debug(' ===ProductGroups__c 35 == '+wo.ProductGroups__c);
                fsaListUpdate.add(wo);
            }
            
            if(fsaListUpdate.size() > 0) {
                update fsaListUpdate;
            }
        }
    }    

}