objects/FieldServiceActivityOpportunity__c.object
<CustomObject>
    <description>SFDC1-10104 : Tracks Opportunity for the Field Service Activities.</description>
    <fields>
        <fullName>FieldServiceActivity__c</fullName>
        <description>SFDC1-10104 : This field will hold the value of Field Service Activity</description>
        <inlineHelpText>Please enter Field Service Activity.</inlineHelpText>
        <label>Field Service Activity</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Field Service Activity Opportunities</relationshipLabel>
        <relationshipName>FieldServiceActivityOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-10104 : This field will hold the value of Opportunity</description>
        <inlineHelpText>Please enter Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Field Service Activity Opportunities</relationshipLabel>
        <relationshipName>FieldServiceActivityOpportunities1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Field Service Activity Opportunity</label>
    <nameField>
        <displayFormat>FSAOPP-{00000}</displayFormat>
        <label>Field Service Activity Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Activity Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FirstYearValue__c</fullName>
        <description>SFDC1-4275 First year total price value rolled up from Opportunity Products</description>
        <inlineHelpText>First Year Contract Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/TriggerFrameworkExtension__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDC-5786 In case the dispatcher class name exceeds character limit. Shorten it to work with Trigger Factory logic</description>
    <fields>
        <fullName>ModifiedObjectName__c</fullName>
        <label>Modified Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TriggerFrameworkExtension</label>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-166.
Associated opportunity for this Field Service Activity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryOpportunityName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC-5786 Add Primary Opportunity Name to FSA Records</description>
        <inlineHelpText>It reflects the highest value opportunity (using first year value converted) from the list of opportunities added in the related section under field service activity opportunities</inlineHelpText>
        <label>Primary Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Field Service Activities (Primary Opportunity Name)</relationshipLabel>
        <relationshipName>FieldServiceActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestFieldServiceActivityOppyMethods.cls
// @author: Shikhar Singh
// // @date: 06 June 2022
// @param: NA
// @description: Test class for FSAO methods 
// @return: NA
//-----------------------------

@isTest
private class TestFieldServiceActivityOppyMethods {
    
    //-----------------------------
    // @author: Shikhar Singh
    // @date: 06 June 2022
    // @param: NA
    // @description: SFDC-5786 Test method for FSAOMethods to update Primary Opportunity on insert, update and Delete
    // @return: NA
    //-----------------------------

    @isTest
    private static void testPrimaryOpportunityUpdateAndDeleteOnFsa() {
        Account acc = TestUtility.createTestAccount('Test Acc 1',true);
        Contact con = TestUtility.createContact(acc.Id, 'test@test.com.ibnvalid', true, 'Test', 'Contact FSA');
        WorkOrder FSA = TestUtility.createFieldServiceActivity(con.Id,true);
        test.startTest();
        Opportunity oppy1 = TestUtility.createOpportunity(acc.Id,'Test Oppy FSA',true);
        Opportunity oppy2 = TestUtility.createOpportunity(acc.Id,'Test Oppy FSA',true);
        oppy1.FirstYearValue__c = 1000;
        update oppy1;
        oppy2.FirstYearValue__c = 2000;
        update oppy2;
        
        TriggerFrameworkExtension__c setting = new TriggerFrameworkExtension__c();
		setting.Name = 'FieldServiceActivityOpportunity__c';
		setting.ModifiedObjectName__c = 'FieldServiceActivityOppy__c';
		insert setting;
        
        FieldServiceActivityOpportunity__c FSAO1 = new FieldServiceActivityOpportunity__c(FieldServiceActivity__c = FSA.Id, Opportunity__c= oppy1.Id);
        insert FSAO1;
        
        List<WorkOrder> listOfWorkOrder1 = [Select Id,PrimaryOpportunityName__c FROM WorkOrder WHERE ID=: FSA.ID];
        
        for(WorkOrder wo: listOfWorkOrder1) {
            System.assertEquals(oppy1.Id, wo.PrimaryOpportunityName__c, 'The Oppy does not match 1');
        }
        
        FieldServiceActivityOpportunity__c FSAO2 = new FieldServiceActivityOpportunity__c(FieldServiceActivity__c = FSA.Id, Opportunity__c= oppy2.Id);
        insert FSAO2;
        
        List<WorkOrder> listOfWorkOrder2 = [Select Id,PrimaryOpportunityName__c FROM WorkOrder WHERE ID=: FSA.ID];
        
        for(WorkOrder wo: listOfWorkOrder2) {
            System.assertEquals(oppy2.Id, wo.PrimaryOpportunityName__c, 'The Oppy does not match 2');
        }
     
        
        delete FSAO2;
        List<WorkOrder> listOfWorkOrder3 = [Select Id,PrimaryOpportunityName__c FROM WorkOrder WHERE ID=: FSA.ID];
        
        for(WorkOrder wo: listOfWorkOrder3) {
            System.assertEquals(oppy1.Id, wo.PrimaryOpportunityName__c, 'The Oppy does not match 3');
        }
        
        test.stopTest();    
    }
    
}