objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ExceptionStatus__c</fullName>
        <description>SFDC-4731: Field for exception process status</description>
        <label>Exception Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception Requested</fullName>
                </value>
                <value>
                    <fullName>Exception Request Approved</fullName>
                </value>
                <value>
                    <fullName>Exception Request Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CreateQuoteController.cls
/*
* @author : Manish Kumar
* @date : 23 Nov 2021
* @description : SFDC-4969 Method to get the Opportunity details and Session Id
* @param : String
* @return : Wrapper Class
* @companyname : IHS Markit
*/
public class CreateQuoteController {
    @auraEnabled
    public static wrapperClass getOptyAndSessionId (string oppyId) {
        wrapperClass wrpCon = new wrapperClass();
        Opportunity oppy = [Select legalEntity__c, ExceptionStatus__c, AccountId from Opportunity where id = :oppyId];
        wrpCon.oppy=oppy;
        wrpCon.sessionid=System.UserInfo.getSessionId();
        return wrpCon; 
    }
    
    public class wrapperClass{
    	 @AuraEnabled public Opportunity oppy{ get; set;}
         @AuraEnabled public String sessionid{ get; set;}
    }
}