objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalContactLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Add non-salesforce users</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>You can only send meeting notes to internal customers.</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>@ihsmarkit.com, @markit.com, @markitserv.com, @ihs.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MeetingNotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedEventId__c</fullName>
        <description>SFDC-2748 Store related event id in a text field. This is a backend field created to save recursive trigger invocation.</description>
        <label>Related Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Only open opportunities can be linked to a meeting.</errorMessage>
            <filterItems>
                <field>Opportunity.IsClosed</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestRelatedOpportunityMethods.cls
//-----------------------------
// @author: Priyanka Vyas
// @date: 24 June 2020
// @param: NA
// @description: SFDC-3115 Test Class for RelatedOpportunityMethods
// @return: NA
//-----------------------------
@isTest
public class TestRelatedOpportunityMethods {
    @isTest public static void checkRelatedOpportunityMethods() {
        Set<ID> oppIDSet=new Set<ID>();
        Account acc1 = TestUtility.createTestAccount('TestAcc1',false);
        Account acc2 = TestUtility.createTestAccount('TestAcc2',false);
        Account acc3 = TestUtility.createTestAccount('TestAcc3',false);
        List<Account> accList=new List<Account>{acc1, acc2, acc3};
        test.startTest();
        insert accList;
        Opportunity testOpp1 = TestUtility.createOpportunity(acc1.id, 'Test Opp1', false);
        Opportunity testOpp2 = TestUtility.createOpportunity(acc2.id, 'Test Opp2', false);
        Opportunity testOpp3 = TestUtility.createOpportunity(acc3.id, 'Test Opp3', false);
        Opportunity testOpp4 = TestUtility.createOpportunity(acc3.id, 'Test Opp4', false);
        Opportunity testOpp5 = TestUtility.createOpportunity(acc3.id, 'Test Opp5', false);
        testOpp5.ActivityCreated__c=true;
        List<Opportunity> oppList = new List<Opportunity> {testOpp1, testOpp2, testOpp3, testOpp4,testOpp5};
            insert oppList;
        for(Opportunity opp:oppList){
            oppIDSet.add(opp.id);
        }
        Event testEvt1 = new Event(Subject='Test1', WhatId=testOpp1.id,StartDateTime=System.now(),EndDateTime=System.now()+1);
        insert testEvt1;
        Task t = new Task(WhatId=testOpp2.id, subject='test', Priority='Normal', Status='Open');
        insert t;
        RelatedOpportunity__c rlObj1=new RelatedOpportunity__c();
        rlObj1 = [SELECT Id, Opportunity__c FROM RelatedOpportunity__c WHERE MeetingNote__r.RelatedEventId__c=:testEvt1.id];
        if(rlObj1!=null){
            rlObj1.Opportunity__c=testOpp3.id;
        }
        update rlObj1;
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        Contact markitContact = TestUtility.createContact(acc3.Id,uniqueName + '@test' + orgId + '.org',true, 'FirstName', 'LastName');
        MeetingNote__c mn = new MeetingNote__c(Account__c = acc3.Id, Name = 'test1243', Opportunity__c = testOpp4.Id,InternalContactLookup__c = markitContact.Id);
        insert mn;
        RelatedOpportunity__c testRO1 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp3.Id);
        RelatedOpportunity__c testRO2 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp5.Id);
        RelatedOpportunity__c testRO3 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp1.Id);
        RelatedOpportunity__c testRO4 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp2.Id);
        List<RelatedOpportunity__c> ROList=new List<RelatedOpportunity__c>{testRO1,testRO2,testRO3,testRO4};
            insert ROList;
        List<RelatedOpportunity__c> ROListDeletion=new List<RelatedOpportunity__c>{testRO1,testRO2, rlObj1, testRO4};
            delete ROListDeletion;
        test.stopTest(); 	
        List<Opportunity> oppyListFinal=[Select id,name,ActivityCreated__c from Opportunity where id in:oppIDSet];
        For(Opportunity O: oppyListFinal){
            if(o.id==testOpp1.id){
                System.assertEquals(o.ActivityCreated__c,true,'opp should be active.');
            }
            if(o.id==testOpp2.id){
                System.assertEquals(o.ActivityCreated__c,true,'opp should be active.');
            }
            if(o.id==testOpp3.Id){
                System.assertEquals(o.ActivityCreated__c,false,'opp should be active.');
            }
            if(o.id==testOpp4.Id){
                System.assertEquals(o.ActivityCreated__c,true,'opp should be active.');
            }
            if(o.id==testOpp5.Id){
                System.assertEquals(o.ActivityCreated__c,false,'opp should be active.');
            }
        }
    }
    //-----------------------------
    // @author: Anjali
    // @date: 17 Feb 2021
    // @param: Trigger events
    // @description: SFDC-3135 : Test method for checkDuplicateRelatedOpportunityRec
    // @return: NA
    //------------------------------
    @isTest public static void testCheckDuplicateRelatedOpportunityRec() {
        Set<ID> oppIDSet=new Set<ID>();
        Account acc = TestUtility.createTestAccount('TestAcc1',false);
        Account acc2 = TestUtility.createTestAccount('TestAcc2',false);
        List<Account> accList=new List<Account>{acc, acc2};
        insert accList;
        Opportunity testOpp1 = TestUtility.createOpportunity(acc.id, 'Test Opp1', false);  
        Opportunity testOpp2 = TestUtility.createOpportunity(acc2.id, 'Test Opp2', false);
        testOpp1.ActivityCreated__c=true;  
        List<Opportunity> oppList = new List<Opportunity> {testOpp1, testOpp2};
        insert oppList;
        Event testEvt1 = new Event(Subject='Test1', WhatId=testOpp1.id,StartDateTime=System.now(),EndDateTime=System.now()+1);
        insert testEvt1;
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        Contact markitContact = TestUtility.createContact(acc.Id,uniqueName + '@test' + orgId + '.org',true, 'FirstName', 'LastName');        
        MeetingNote__c mn = new MeetingNote__c(Account__c = acc.Id, Name = 'test1243',Opportunity__c = testOpp1.Id, InternalContactLookup__c = markitContact.Id);
        insert mn;
        RelatedOpportunity__c testRO1 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp2.Id);
        insert testRO1;        
        RelatedOpportunity__c testRO2;
        try{
        Test.startTest();
         testRO2 = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=testOpp2.Id);
        insert testRO2;
        }catch(exception e) {
            system.assertEquals(true,e.getMessage().contains(System.Label.DuplicateRelatedOpportunity), 'exception message match with label');
        }
        System.assertEquals(testRO2.Id,null,'related opp is null.'); 
        Test.stopTest();
    }
}