objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>MeetingOutcome__c</fullName>
        <inlineHelpText>Please enter the notes for this meeting, things to consider including - Agenda, Achieved/Meeting Outcome, Next Steps</inlineHelpText>
        <label>Meeting Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RelatedEventId__c</fullName>
        <description>SFDC-2748 Store related event id in a text field. This is a backend field created to save recursive trigger invocation.</description>
        <label>Related Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>SFDC-2748 Stores the subject of related event.</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestActivitiesEmailTemplateWrapper.cls
@isTest
public class TestActivitiesEmailTemplateWrapper {
	
    //-----------------------------
    // @author: Shikhar Singh
    // @date: 14th March 2022
    // @description: Org Assessment 2022 Test class coverage
    // @param: None
    // @return: None
    //-----------------------------
    private static testMethod void ActivitiesEmailTemplateWrapper() {
        // create Account
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        // create contact
        Contact testContact = TestUtility.createContact(testAccount.id,'test@test.com', true, 'Test','Contact');
        // create an event record
        Event testEvent = TestUtility.createEventWithWhoId('Test Event meetingNote',testContact.id,true);
        test.startTest();
        List<MeetingNote__c> mtngNote = [SELECT Id, MeetingOutCome__c, Subject__c
                                         FROM MeetingNote__c WHERE RelatedEventId__c= 'testEvent.Id' LIMIT 1];
        for(MeetingNote__c mn: mtngNote) {
            System.assertEquals('testEvent.Subject', 'mtngNote.Subject__c' , 'event subject matches the meeting note subject');
        }
        
        test.stopTest();
        
        ActivitiesEmailTemplateWrapper templatewrapper = new ActivitiesEmailTemplateWrapper(testEvent.Id);
    }
}