objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>EstimatedValueatRisk__c</fullName>
        <inlineHelpText>Holds the estimated value at risk</inlineHelpText>
        <label>Estimated Value at Risk</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsProductatRisk__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>Is Product at Risk?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RiskStatus__c</fullName>
        <inlineHelpText>Holds the status of the product risk</inlineHelpText>
        <label>Risk Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Pending Resolution</fullName>
                </value>
                <value>
                    <fullName>Closed - Risk Mitigated</fullName>
                </value>
                <value>
                    <fullName>Closed - Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Closed - Downgraded</fullName>
                </value>
                <value>
                    <fullName>Closed – Downgraded</fullName>
                    <isActive>false</isActive>
                    <label>Closed – Downgraded</label>
                </value>
                <value>
                    <fullName>Closed – Non-Renewal</fullName>
                    <isActive>false</isActive>
                    <label>Closed – Non-Renewal</label>
                </value>
                <value>
                    <fullName>Closed – Risk Mitigated</fullName>
                    <isActive>false</isActive>
                    <label>Closed – Risk Mitigated</label>
                </value>
                <value>
                    <fullName>Open – Pending Resolution</fullName>
                    <isActive>false</isActive>
                    <label>Open – Pending Resolution</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                    <label>Add On</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                    <label>Removal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/OpportunityProductRiskController.cls
//@author : Sharique Iqbal
//@date: 25 Feb 2021
//@description : SFDC- 3918- Fetch the opportunity Products which are at Risk
//@company : IHS Markit
//@param : String
//@return : String

public with sharing class OpportunityProductRiskController  {

 @AuraEnabled(cacheable=true)
 public static String getRiskProductName (String oppyId) {
      
      Integer count = 0;
      String riskyProductNames = '';  
      for (OpportunityLineItem oli : [SELECT Id, Product2.Name 
                                      FROM OpportunityLineItem
                                      WHERE OpportunityId = :oppyId AND IsProductatRisk__c = 'Yes' AND Status__c = 'Existing' AND RiskStatus__c = 'Open - Pending Resolution'
                                      ORDER By EstimatedValueatRisk__c desc]) {
          if (count < 3) {
            riskyProductNames = riskyProductNames +', '+ oli.Product2.Name;
          }
          count++;          
      } 
      
      if (count > 3) {
         riskyProductNames = riskyProductNames.substring(1) +' and +'+ (count-3)+' are';
      } else {      
         riskyProductNames = count != 0 ? (count == 1 ? riskyProductNames.substring(1)+' is' : riskyProductNames.substring(1)+' are') : '';      
      }
      system.debug('@@ return value--'+riskyProductNames);
      return riskyProductNames;
    }
}