objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContinuationEndDate__c</fullName>
        <description>SFDC1-8989 &quot;Continuation End Date&quot; on the &apos;Renewal&apos; opportunity record type.</description>
        <inlineHelpText>Continuation End Date</inlineHelpText>
        <label>Continuation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LostReasonCode__c</fullName>
        <description>SFDC1 -171 ; if the contract is Closed Lost then the Lost Reason Code from the Contract Should display. Otherwise the list of Lost Reason Codes for the Opportunity are listed here.
SFDC1-769 : Updated the Picklist Values and removed old Values.
SFDC1-6704 : Updated the Picklist Values and removed old Values.</description>
        <inlineHelpText>Choose a valid reason from the dropdown list</inlineHelpText>
        <label>Lost Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bankruptcy/Out of Business</fullName>
                </value>
                <value>
                    <fullName>Company Too Small/Retail/Commerce</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Contact Non Responsive/Wrong Contact</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                    <label>Created in Error (Sales Ops Team Only)</label>
                </value>
                <value>
                    <fullName>Customer exiting business</fullName>
                    <label>Customer Exiting Business</label>
                </value>
                <value>
                    <fullName>Customer Lost Bid</fullName>
                </value>
                <value>
                    <fullName>Cutting Costs/Lost Budget</fullName>
                </value>
                <value>
                    <fullName>Decided to do it Themselves</fullName>
                </value>
                <value>
                    <fullName>IHSM Decision to Pass/No Bid</fullName>
                    <label>Decision to Pass / No Bid</label>
                </value>
                <value>
                    <fullName>Duplicate/Existing Opp</fullName>
                </value>
                <value>
                    <fullName>Key contact left company</fullName>
                </value>
                <value>
                    <fullName>Customer has merged / restructured</fullName>
                    <label>Merger &amp; Acquisition Activity</label>
                </value>
                <value>
                    <fullName>No/low usage</fullName>
                </value>
                <value>
                    <fullName>No further interest, has all information needed</fullName>
                </value>
                <value>
                    <fullName>Non Payment</fullName>
                </value>
                <value>
                    <fullName>Product/Solution does not match need</fullName>
                </value>
                <value>
                    <fullName>Product Code Changed</fullName>
                </value>
                <value>
                    <fullName>Product discontinued</fullName>
                    <label>Product Discontinued</label>
                </value>
                <value>
                    <fullName>Product Quality Issue</fullName>
                </value>
                <value>
                    <fullName>Project completed/cancelled</fullName>
                    <label>Project Completed/Cancelled</label>
                </value>
                <value>
                    <fullName>Systematically Closed Lost - Past Due</fullName>
                </value>
                <value>
                    <fullName>Terms &amp; Conditions Issues</fullName>
                </value>
                <value>
                    <fullName>Unfavorable Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesLostBus__c</fullName>
        <description>SFDC1-10166 : Rollup Field for Opportunity Product : Sales - Lost Bus</description>
        <inlineHelpText>Rollup Field for Opportunity Product : Sales - Lost Bus</inlineHelpText>
        <label>Sales - Lost Bus</label>
        <summarizedField>OpportunityLineItem.RCLostBiz__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SalesRenewalUSD__c</fullName>
        <description>SFDC-1610: To store USD equivalent of SalesRenewal__c amount field.</description>
        <formula>SalesRenewal__c/CURRENCYRATE(TEXT(CurrencyIsoCode))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>USD equivalent amount of Sales Renewal</inlineHelpText>
        <label>Sales - Renewal(USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesRenewal__c</fullName>
        <description>SFDC1-10166 : Rollup Field for Opportunity Product : Sales - Renewal</description>
        <inlineHelpText>Sum of first year value in USD of all existing products</inlineHelpText>
        <label>Sales - Renewal</label>
        <summarizedField>OpportunityLineItem.RCRenewal__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quota__c.object
<CustomObject>
    <description>SFDC-4105:  Quota Import &amp; Assignment</description>
    <fields>
        <fullName>AllocateQuota__c</fullName>
        <label>Allocate Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DirectQuota__c</fullName>
        <label>Direct Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GlobalVertical__c</fullName>
        <label>Global Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CMS</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IndividualQuota__c</fullName>
        <label>Individual Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfferingType__c</fullName>
        <label>Offering Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allocate Consulting</fullName>
                </value>
                <value>
                    <fullName>Allocate New Subscription</fullName>
                </value>
                <value>
                    <fullName>Allocate Onetime</fullName>
                </value>
                <value>
                    <fullName>Allocate Renewal</fullName>
                </value>
                <value>
                    <fullName>Analytics License Revenue</fullName>
                </value>
                <value>
                    <fullName>Analytics Upfront</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>New Subscription</fullName>
                </value>
                <value>
                    <fullName>Onetime</fullName>
                </value>
                <value>
                    <fullName>Overlay</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Allocate New Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpenPositionCount__c</fullName>
        <label>Open Position Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpenPositionQuota__c</fullName>
        <label>Open Position Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverlayQuota__c</fullName>
        <label>Overlay Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QuotaAmount__c</fullName>
        <label>Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QuotaPeriod__c</fullName>
        <label>Quota Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quota Database</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamQuota__c</fullName>
        <label>Team Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchCreateRenewalQuota.cls
//-------------------------------------
// @author: Mohit Parnami
// @date: 14 June 2021
// @description: SFDC-4123 This class upserts Quota records of Renewal Opportunities. 
// @Last Modified By : Akash Punera
// @Last Modified Date : 20 June 2022
// @Last Modified Description : SFDC-5841 Updated filter logic to include account managers and remove error oppies
// -------------------------------------------------
global class BatchCreateRenewalQuota implements Database.Batchable<sObject>, Database.Stateful {
    global  Map<String, Decimal> mapSplitOwnerToRenewalQuota;

    global BatchCreateRenewalQuota() {
        mapSplitOwnerToRenewalQuota = new Map<String, Decimal>();
    }
	public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, SplitOwnerId, SplitPercentage, OpportunityId, convertcurrency(Opportunity.SalesRenewal__c), convertcurrency(Opportunity.SalesLostBus__c), Opportunity.ContinuationEndDate__c,'; 
        query += ' Opportunity.ContractStartDate__c,Opportunity.SalesRenewalUSD__c, SplitOwner.EmployeeNumber__c';
        query += ' From OpportunitySplit';
        query += ' WHERE Opportunity.RecordType.Name = \'Renewal\'';
        
        //SFDC-5841 added filters for renewal quota
        query += 'AND Opportunity.lostReasonCode__c not in (\'Created in Error\',\'Duplicate/Existing Opp\')';
        query += ' AND (not opportunity.account.type like \'Place Holder -%\')';
            
        query += ' AND (SplitOwner.GlobalVertical__c = \'Financial Markets\' OR SplitOwner.GlobalVertical__c = \'Financial Services: Financial Market Technologies\' OR SplitOwner.GlobalVertical__c = \'Financial Services: Financial Markets\')';
        //query += ' AND SplitType.MasterLabel = \'Sales Specialists\''; SFDC-5841 Commenting the Sales Specialists filter 
        query += ' AND Opportunity.ContractStartDate__c != null';
        query += ' AND ((Opportunity.ContractStartDate__c <=  NEXT_N_YEARS:2';
        query += ' AND Opportunity.ContractStartDate__c >=  LAST_N_YEARS:2)';
        query += '  OR (Opportunity.ContinuationEndDate__c <= NEXT_N_YEARS:2 AND Opportunity.ContinuationEndDate__c >=  LAST_N_YEARS:2))';

        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<OpportunitySplit> lstOppSplit) {
        List<Quota__c> listQuotaToUpsert = new List<Quota__c>();
        Map<String, OpportunitySplit> mapKeyToOppSplit = new Map<String, OpportunitySplit>();
        Map<String, Date> mapKeyToDate = new Map<String, Date>();

        for(OpportunitySplit oppSplit : lstOppSplit) {
            if(oppSplit.SplitOwner != null && oppSplit.SplitOwner.EmployeeNumber__c != null) {
                String key = '';
                //If extended opportunity, use ContinuationEndDate__c field to calculate quota
                if(oppSplit.Opportunity.ContinuationEndDate__c != null) {
                    key = oppSplit.SplitOwner.EmployeeNumber__c + '_' + oppSplit.Opportunity.ContinuationEndDate__c.Year() + '_' + oppSplit.Opportunity.ContinuationEndDate__c.Month() + '_011';
                    //+ oppSplit.SplitOwner.QuotaManager__r.EmployeeNumber__c + '_'
                    mapKeyToDate.put(key, oppSplit.Opportunity.ContinuationEndDate__c);
                } else {
                    key = oppSplit.SplitOwner.EmployeeNumber__c + '_' + oppSplit.Opportunity.ContractStartDate__c.Year() + '_' + oppSplit.Opportunity.ContractStartDate__c.Month() + '_011';
                    //+ oppSplit.SplitOwner.QuotaManager__r.EmployeeNumber__c + '_'
                    mapKeyToDate.put(key, oppSplit.Opportunity.ContractStartDate__c);
                }
                
                Decimal renewalQuota =  ((oppSplit.Opportunity.SalesRenewalUSD__c + oppSplit.Opportunity.SalesLostBus__c) * oppSplit.SplitPercentage)/100;
                if(renewalQuota != null) {
                    if(!mapSplitOwnerToRenewalQuota.containsKey(key)) {
                        mapSplitOwnerToRenewalQuota.put(key, renewalQuota);
                    } else {
                        Decimal totalRenewalOpp = mapSplitOwnerToRenewalQuota.get(key) + renewalQuota;
                        mapSplitOwnerToRenewalQuota.put(key, totalRenewalOpp);
                    }
                }
                
                mapKeyToOppSplit.put(key, oppSplit);
            }
        }
        //system.debug('===mapSplitOwnerToRenewalQuota size===' + mapSplitOwnerToRenewalQuota.size());
        //system.debug('===mapSplitOwnerToRenewalQuota===' + mapSplitOwnerToRenewalQuota);
        for(String key : mapSplitOwnerToRenewalQuota.keySet()) {
            if(mapKeyToOppSplit.containsKey(key)) {
                Quota__c renQuota = new Quota__c(OverlayQuota__c = 0, DirectQuota__c = 0, TeamQuota__c = 0, AllocateQuota__c = 0, OpenPositionQuota__c = 0, IndividualQuota__c = 0, OpenPositionCount__c =0);
                renQuota.ExternalId__c = key+'_024_R';//Create quota with businessline as other
                renQuota.OwnerId = mapKeyToOppSplit.get(key).SplitOwnerId != null ? mapKeyToOppSplit.get(key).SplitOwnerId : null;
                //renQuota.Manager__c = mapKeyToOppSplit.get(key).SplitOwnerId != null && mapKeyToOppSplit.get(key).SplitOwner.QuotaManager__c != null ? mapKeyToOppSplit.get(key).SplitOwner.QuotaManager__c : null;
                renQuota.QuotaAmount__c = mapSplitOwnerToRenewalQuota.get(key);
                renQuota.OfferingType__c = 'Renewal';
                renQuota.Source__c = 'Salesforce';
                renQuota.GlobalVertical__c = 'Financial Markets';
                if(mapKeyToDate.get(key) != null) {
                    renQuota.QuotaPeriod__c = mapKeyToDate.get(key) != null ? mapKeyToDate.get(key).toStartOfMonth() : null;
                }
                
                //renQuota.QuotaPeriod__c = mapKeyToOppSplit.get(key).Opportunity.ContractStartDate__c != null ? mapKeyToOppSplit.get(key).Opportunity.ContractStartDate__c.toStartOfMonth() : null;
                
                listQuotaToUpsert.add(renQuota);
            }
        }
        //system.debug('===listQuotaToUpsert size===' + listQuotaToUpsert.size());
        //system.debug('===listQuotaToUpsert===' + listQuotaToUpsert);
        if(!listQuotaToUpsert.isEmpty()) {
            upsert listQuotaToUpsert ExternalId__c;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('@HS BATCH FINISH()');
        //Call Support Overview Batch here in next phase
        //Database.executeBatch(new BatchCalCasesSummarySupportOverview(), 1);        
    }
}