objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CreatePeerReviewTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Peer Review Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CycleStart__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Week Days</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Semi-Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Six Week Cycle</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NegotiatedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>If no Negotiated Date was provided, use the date from Requested Due Date to populate this required field</inlineHelpText>
        <label>Negotiated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberOfCycles__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>MAX Number of Cycles = 50. You can repeat creating cyclical jobs if you need to add more than 50.</inlineHelpText>
        <label>Number Of Cycles</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfParts__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Number Of Parts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPLCJobCyclicalUtility.cls
//-----------------------------
// @author: Madhusudhan
// @date: 12 July 2021
// @param: 
// @description: Test class for PLCJob trigger methods 
// @return: NA
//----------------------------- 
@isTest
private class TestPLCJobCyclicalUtility  {
    //-----------------------------
    // @author: Madhusudhan
    // @date: 12 July 2021
    // @param: 
    // @description: This method is used for to create the cyclical jobs 
    // @return: NA
    //----------------------------- 
    @isTest
    public static void testgetPlcJobRecords() {  
        PLCJob__c plc = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Week Days', CreatePeerReviewTask__c=true);
        insert plc;
        List<plcjob__c> plcList=PLCJobCyclicalUtility.getPlcJobRecords(plc.id);
        system.assert(plcList.size()==9,'Check PLC List is 9');
        PLCJob__c plcWeekly = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Weekly', CreatePeerReviewTask__c=true);
        insert plcWeekly;
        List<plcjob__c> plcWeeklyList=PLCJobCyclicalUtility.getPlcJobRecords(plcWeekly.id);
        system.assert(plcWeeklyList.size()==9,'Check PLC List is 9');
        PLCJob__c plcMonthly = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Semi-Monthly', CreatePeerReviewTask__c=true);
        insert plcMonthly;
        List<plcjob__c> plcMonthlyList=PLCJobCyclicalUtility.getPlcJobRecords(plcMonthly.id);
        system.assert(plcMonthlyList.size()==9,'Check PLC List is 9');
        PLCJob__c plcQuarterly = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Quarterly', CreatePeerReviewTask__c=true);
        insert plcQuarterly;
        List<plcjob__c> plcQuarterlyList=PLCJobCyclicalUtility.getPlcJobRecords(plcQuarterly.id);
        system.assert(plcQuarterlyList.size()==9,'Check PLC List is 9');
        PLCJob__c plcAnnually = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Annually', CreatePeerReviewTask__c=true);
        insert plcAnnually;
        List<plcjob__c> plcAnnuallyList=PLCJobCyclicalUtility.getPlcJobRecords(plcAnnually.id);
        system.assert(plcAnnuallyList.size()==9,'Check PLC List is 9');
        PLCJob__c Otherplc = new PLCJob__c(NumberofCycles__c = 10, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Other', CreatePeerReviewTask__c=true);
        insert Otherplc;
        List<plcjob__c> OtherplcList=PLCJobCyclicalUtility.getPlcJobRecords(Otherplc.id);
        system.assert(OtherplcList.size()==9,'Check PLC List is 9');
        
    }
    //-----------------------------
    // @author: Madhusudhan
    // @date: 12 July 2021
    // @param: 
    // @description: This method is used for to create the Multipart jobs 
    // @return: NA
    //----------------------------- 
    @isTest
    public static void testPLCJobCloneMultipartUtility() {  
        PLCJob__c plc = new PLCJob__c(NumberofCycles__c = 5, CycleStart__c = date.newInstance(2000,1,1), Cycle__c = 'Week Days', CreatePeerReviewTask__c=true,NumberofParts__c=5);
        insert plc;
         List<plcjob__c> plcList=PLCJobCyclicalUtility.PLCJobCloneMultipartUtility(plc.id);
        system.debug('plcList.size()----------- '+plcList.size());
        system.assert(plcList.size()==4,'Check PLC size is 4');        
    }
    //-----------------------------
    // @author: Madhusudhan
    // @date: 12 July 2021
    // @param: 
    // @description: This method is used to save the PLC records
    // @return: NA
    //----------------------------- 
    @isTest
    public static void testsaveCyclicPLCJobs() {  
        List<PLCJob__c> bulkPLCs = new List<PLCJob__c>();
        for(Integer i = 0; i < 10; i++) {
            bulkPLCs.add(new PLCJob__c(StartDate__c = System.today(), NegotiatedDate__c=System.today()));
        }
        PLCJobCyclicalUtility.saveCyclicPLCJobs(bulkPLCs);
        system.assert(bulkPLCs.size()>0, 'Check size greater than 0');
    }
 
}