objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductLoginContactAssociation__c.object
<CustomObject>
    <description>SFDC1-7972 This object links the Product Login to the related contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-4386 Contact related to this Product Login</description>
        <inlineHelpText>Link the related Contact to this Product Login</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-4386 Product Login related to this Contact</description>
        <inlineHelpText>Link the related to Product Login to this Contact</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UniqueProductContactId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-10703: Id to Store Product +  Contact Id so that there are no duplicates</description>
        <inlineHelpText>Id to Store Product +  Contact Id so that there are no duplicates</inlineHelpText>
        <label>Unique Product Contact Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Login Contact Association</label>
    <nameField>
        <displayFormat>PLContact-{000000}</displayFormat>
        <label>Product Login Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Login Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProductLoginContactAssociationMethods.cls
//-----------------------------
// @author: Vishnu Vardhan Chowdary
// @date: 17 Dec 2018
// @description: Class to hold Product Login Contact Association trigger methods 
//-----------------------------
public class ProductLoginContactAssociationMethods {
    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 17 Dec 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-10703 Whenever there is an insert or update on this record then populate unique key field.
    // @return: None
    //------------------------------
    public static void populateUniqueProductLoginContactId(TriggerParameters tp) {
        // Map of old values and new values
        Map<Id,ProductLoginContactAssociation__c> mapOldPLCA = (Map<Id,ProductLoginContactAssociation__c>) tp.oldMap;
        
        for(ProductLoginContactAssociation__c newPLCA : (List <ProductLoginContactAssociation__c>) tp.newList) {
            ProductLoginContactAssociation__c oldPLCA = new ProductLoginContactAssociation__c();
            if(tp.tEvent == TriggerParameters.TriggerEvent.beforeUpdate) {
                oldPLCA = mapOldPLCA.get(newPLCA.Id);
            }
            if(newPLCA.Contact__c != oldPLCA.Contact__c) {
                newPLCA.UniqueProductContactId__c = newPLCA.ProductLogin__c + '' + newPLCA.Contact__c;
            }
        }
    }
}