objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-6785 Email of the user used for Product Login.</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user used for Product Login.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductLoginContactAssociation__c.object
<CustomObject>
    <description>SFDC1-7972 This object links the Product Login to the related contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-4386 Contact related to this Product Login</description>
        <inlineHelpText>Link the related Contact to this Product Login</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-4386 Product Login related to this Contact</description>
        <inlineHelpText>Link the related to Product Login to this Contact</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UniqueProductContactId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC1-10703: Id to Store Product +  Contact Id so that there are no duplicates</description>
        <inlineHelpText>Id to Store Product +  Contact Id so that there are no duplicates</inlineHelpText>
        <label>Unique Product Contact Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Login Contact Association</label>
    <nameField>
        <displayFormat>PLContact-{000000}</displayFormat>
        <label>Product Login Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Login Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPLCAMethods.cls
// @author: Vishnu Vardhan Chowdary
// @date: 17 Dec 2018
// @param: NA
// @description: Test class for Product Login Contact Association trigger methods 
// @return: NA
//-----------------------------
@isTest
public class TestPLCAMethods {

    //-----------------------------
    // @author: Vishnu Vardhan Chowdary
    // @date: 17 Dec 2018
    // @param: NA
    // @description: SFDC1-10703 Test method for populateUniqueProductLoginContactId
    // @return: NA
    //-----------------------------
    private static testMethod void testPopulateUniqueProductLoginContactId() {
        Account a = TestUtility.createTestAccount(System.Label.CaseUnknownAccountName, true);

        Contact con = new Contact();
        con.firstname = 'Test1';
        con.lastname = 'Test1';
        con.Email = 'pl.contactExists@ihsmarkit.com';
        con.AccountId = a.Id;
        insert con;
        Test.startTest();
        
        ProductLogin__c testProductLogin = TestUtility.createProductLogin('testPopulateUniqueProductLoginContactId@test.com', false);
        testProductLogin.Email__c = con.Email;
        insert testProductLogin;
        list <ProductLogin__c> testProductLoginResult = [SELECT Id,
                                             (SELECT UniqueProductContactId__c, Contact__c FROM ProductLoginContactAssociations1__r) 
                                             FROM ProductLogin__c];
        //Assert if Product Login is inserted
        System.assertEquals(1, testProductLoginResult.size());
        System.assert(testProductLoginResult[0].ProductLoginContactAssociations1__r != null);
        ProductLoginContactAssociation__c pLCA = testProductLoginResult[0].ProductLoginContactAssociations1__r.get(0);
        System.assertEquals(pLCA.Contact__c, con.Id);
        System.assertEquals(pLCA.UniqueProductContactId__c, testProductLogin.Id + '' + con.Id);

        Test.stopTest();
    }
}