objects/Quota__c.object
<CustomObject>
    <description>SFDC-4105:  Quota Import &amp; Assignment</description>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quota Database</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SharedQuota__c.object
<CustomObject>
    <description>SFDC-4930 Share managers quota outside of quota hierarchy</description>
    <fields>
        <fullName>ShareWithUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who will be able to see the additional quota and actual records</description>
        <label>Share with User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SharedQuotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserQuota</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shared Quota</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Shared Quota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestBatchUpdateQuotaHierarchy.cls
//-----------------------------
// @author: 
// @date: 05 July 2021
// @param: NA
// @description: Test Class for BatchUpdateQuotaHierarchy
// @return: NA
//----------------------------
@isTest(SeeAllData=false)
private class TestBatchUpdateQuotaHierarchy {
    @isTest
    static void testCreateRenewalQuota() {
        User testUser1 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.testuser123@ihsmarkit.com.user',true);
        User testUser2 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.test22343@ihsmarkit.com.usertest',true);
        User testUser3 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.test10@ihsmarkit.com.usertest',true);
        List<Quota__c> quotaList= new List<Quota__c>();
        for(User uObj : [SELECT employeeNumber__c, Name 
                         FROM User
                         WHERE username like '%CreateRenewalQuota%' ]) {
                             Quota__c quota=new Quota__c(hierarchy__c=uObj.EmployeeNumber__c,source__c = 'Quota Database');
                             quotaList.add(quota);
                         }
        insert quotaList;
        SharedQuota__c sharedQuota = new SharedQuota__c(user__c = testUser1.id, sharewithuser__c = testUser3.id);
        insert sharedQuota;
        Test.startTest();
        String batchId = Database.executeBatch(new BatchUpdateQuotaHierarchy(),200);
        System.assert(batchId!=null);
        Test.stopTest();   
        
        
    }
    @isTest
    static void testScheduler() {
        User testUser1 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.testuser123@ihsmarkit.com.user',true);
        User testUser2 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.test22343@ihsmarkit.com.usertest',true);
        User testUser3 = TestUtility.createTestUser('IHSMarkit Data Governance', 'CreateRenewalQuota.test10@ihsmarkit.com.usertest',true);
        List<Quota__c> quotaList= new List<Quota__c>();
        for(User uObj : [SELECT employeeNumber__c, Name 
                         FROM User
                         WHERE username like '%CreateRenewalQuota%' ]) {
                             Quota__c quota=new Quota__c(hierarchy__c=uObj.EmployeeNumber__c);
                             quotaList.add(quota);
                         }
        insert quotaList;
        Test.startTest();
        BatchUpdateQuotaHierarchyScheduler UpdateHierarchySchedular = new BatchUpdateQuotaHierarchyScheduler();
        String cronExp = '0 0 23 * * ?'; 
        system.schedule('Test Update Hierarchy', cronExp, UpdateHierarchySchedular); 
        List<AsyncApexJob> scheduledJob = [select ApexClassId, Id
                                           from AsyncApexJob  
                                           where JobType = 'ScheduledApex'];
        system.assert(scheduledJob.size() > 0);
        Test.stopTest();   
        
        
    }
    
}