objects/S1_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client Activity (External)</fullName>
                </value>
                <value>
                    <fullName>Education (Internal)</fullName>
                </value>
                <value>
                    <fullName>Expert Insights &amp; Idea Generation (Internal)</fullName>
                </value>
                <value>
                    <fullName>Marketing Events</fullName>
                </value>
                <value>
                    <fullName>Resource/Materials (External)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <description>US 5450464: store the close date of S1 request</description>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <inlineHelpText>Please select the division for which the request is being created.</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                </value>
                <value>
                    <fullName>Engineering Solutions</fullName>
                </value>
                <value>
                    <fullName>Commodity Insights</fullName>
                    <isActive>false</isActive>
                    <label>Commodity Insights</label>
                </value>
                <value>
                    <fullName>MI</fullName>
                    <isActive>false</isActive>
                    <label>MI</label>
                </value>
                <value>
                    <fullName>Ratings</fullName>
                    <isActive>false</isActive>
                    <label>Ratings</label>
                </value>
                <value>
                    <fullName>SPDJI</fullName>
                    <isActive>false</isActive>
                    <label>SPDJI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>S1 Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/S1_Response__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>User Story 5306779: External Id to map records from Hub and divisions</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>S1_Request__c</fullName>
        <label>S1 Request</label>
        <referenceTo>S1_Request__c</referenceTo>
        <relationshipName>S1_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Response</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>S1 Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RfaPullRecordsMockTest.cls
/*  @author: Pankhuri Jain
 *  @date: 21 Dec 2022
 *  @description: Mock Response Test Class for RfaPullRecords
*/

@isTest
public class RfaPullRecordsMockTest implements HttpCalloutMock{
	public HTTPResponse respond(HTTPRequest request) {   
        s1_request__c s1Req = [SELECT id,External_Id__c FROM s1_Request__c limit 1];
        s1_response__c s1Res = [SELECT id,External_Id__c FROM s1_response__c limit 1];
        HttpResponse response = new HttpResponse();        
        response.setHeader('Content-Type', 'application/json');  
        response.setBody('[[{"Id":"'+s1Req?.id+'","External_Id__c":"'+s1Req?.id+'","Account_Name__c":"","Completed_Date__c":"2022-12-08","Opportunity_Name__c":"test2","Record_Type_Id__c":"","Description__c":"test for screen flow","Status__c":"In Progress","OwnerId":"0054x0000062aP1AAI","Division__c":"Mobility","Division_Sent_From__c":"MI","Category__c":"Education (Internal)","S1Response":{"records":[{"Id":"'+s1Res?.id+'","External_Id__c":"'+s1Res?.external_Id__c+'","S1_Request__c":"'+s1Req?.id+'","Description__c":"test for screen flow","Status__c":"New","Owner":"DonnaORourke","OwnerEmail":"donna.orourke@spglobal.com.invalid","Type":"Outgoing"}]}}]]');        
        response.setStatusCode(200);
        return response; 
    }
}