objects/S1_Request__c.object
<CustomObject>
    <label>S1 Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>S1 Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/S1_Response__c.object
<CustomObject>
    <fields>
        <fullName>S1_Request__c</fullName>
        <label>S1 Request</label>
        <referenceTo>S1_Request__c</referenceTo>
        <relationshipName>S1_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>S1 Response</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>S1 Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RfaPushUpdatesMockTest.cls
/*  @author: Akash Punera
 *   @date: 15 Dec 2022
 *   @description: Mock Class for RfaPushUpdates test callouts
 */
@isTest
public class RfaPushUpdatesMockTest implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest request) {
        s1_request__c s1Req = [SELECT id FROM s1_Request__c limit 1];
        s1_response__c s1Res = [SELECT id FROM s1_response__c limit 1];
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('[[{"type":"S1_Request__c","status":"Success","recordId":"'+s1Req?.id+'","message":"Record Upserted"},{"type":"S1_Response__c","status":"Success","recordId":"'+s1Res?.id+'","message":"Record Upserted"}]]');
        response.setStatusCode(200);
        return response; 
    }
}