objects/S1_Request__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Push_Updates__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Push Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>S1 Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/S1_Response__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>User Story 5306779: External Id to map records from Hub and divisions</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Push_Updates__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Push Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S1_Request__c</fullName>
        <label>S1 Request</label>
        <referenceTo>S1_Request__c</referenceTo>
        <relationshipName>S1_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>S1 Response</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>S1 Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S1 Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/S1_RFA_Configurations__mdt.object
<CustomObject>
    <description>US 5496291: Custom Metadata to Store Configurational Changes for RFA apex classes</description>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>Field to store the name of the division i.e. division sent from field</description>
        <label>Division Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body_Prefix__c</fullName>
        <description>Define the email body to be appended before response</description>
        <label>Email Body Prefix</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <description>define the subject of email to be sent</description>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_String__c</fullName>
        <description>Filter applied to Request and response objects when querying the data to sync</description>
        <label>Filter String</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Fields__c</fullName>
        <description>Field to store all the fields to be synced with hub (existing fields can be removed but to add new fields wrapper needs to be updated)</description>
        <label>Request Fields</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Object_API__c</fullName>
        <description>Field to store the API name for request Object</description>
        <label>Request Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Child_API__c</fullName>
        <description>Field to store the API name of the child relationship response</description>
        <label>Response Child API</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response_Fields__c</fullName>
        <description>Field to store all the fields to be synced with the hub (existing fields can be removed but to add new fields wrapper needs to be updated)</description>
        <label>Response Fields</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Object_API__c</fullName>
        <description>Field to store Response object API name</description>
        <label>Response Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, Email notifications will be sent on Rest API execution</description>
        <label>Send Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <description>Email address to send the notifications in case of success and failure</description>
        <label>To Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S1 RFA Configuration</label>
    <pluralLabel>S1 RFA Configurations</pluralLabel>
</CustomObject>

classes/RfaPushUpdates.cls
/*  @author: Akash Punera
*   @date: 25 Oct 2022
*   @description: Class to push request/response from source org to hub org
*/
public with Sharing class RfaPushUpdates implements Queueable, Database.AllowsCallouts{
    
    string reqFields;
    string resFields;
    string reqObjectName;
    string resObjectName;
    string resRelationName;
    string recFilter;
    string sourceDivision;
    static string[] toAddresses = new string[]{};
    boolean sendStatusEmails = false;
    String emailSubject;
    String emailBody;
    public map<String,String> mapExternalIdToId = new map<String,String>();

    /*  @author: Akash Punera
    *   @date: 28 Oct 2022
    *   @description: Method to populate variables from custom metadata
    */
    public void setConfigurations() {
        //Adding query instead of get instance method as the later has a limit of 255 char on fields queried
        S1_RFA_Configurations__mdt config = [SELECT    id, Request_Fields__c, Response_Fields__c, Request_Object_API__c, Response_Object_API__c,
                                                    Response_Child_API__c, Filter_String__c, Division_Name__c, To_Email_Address__c, Send_Email_Notification__c, 
                                                    Email_Body_Prefix__c, Email_Subject__c
                                            FROM    S1_RFA_Configurations__mdt WHERE DeveloperName  = 'Default'];
        reqFields = config.Request_Fields__c;
        resFields = config.Response_Fields__c;
        reqObjectName = config.Request_Object_API__c;
        resObjectName = config.Response_Object_API__c;
        resRelationName = config.Response_Child_API__c;
        recFilter = config.Filter_String__c;
        sourceDivision = config.Division_Name__c;
        toAddresses.addAll(config?.To_Email_Address__c?.split(','));
        sendStatusEmails = config.Send_Email_Notification__c;
        emailBody = config.Email_Body_Prefix__c;
        emailSubject = config.Email_Subject__c;
    }
        
    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Method to make callout to push changes to the Hub
    */
    public void pushUpdatesToHub() {
        try{
            setConfigurations();
            string response;
            string reqBody = createRequestBody();
            response = makeCallout('upsertRecords',reqBody);
            updateRecords(response);
        }catch (Exception ex) {
            System.debug('Exception '+Ex.getMessage()+'--'+ex.getStackTraceString());
            if(sendStatusEmails) {
                sendNotification(Ex.getMessage()+'--'+ex.getStackTraceString());
            }
        }
    }
    
    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Send a notification email to notify about the job status (failure/success)
    *   @param: Additional description to be sent 
    */
    public void sendNotification(string description) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);
        mail.setSubject(emailSubject);
        emailBody = emailBody.replace('{{mailContent}}', description);
        emailBody = emailBody.replace('{{jobname}}', 'PushUpdatesToHub');
        mail.setPlainTextBody(emailBody);
        Messaging.sendEmail(new Messaging.Email[] { mail });

    }

    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Update Request and response records based on Rest Callout response (only records successfully added to hub are updated)
    *   @param: Rest Callout response
    */
    public void updateRecords(String response) {
        schema.sObjectType sObjType = Schema.getGlobalDescribe().get(reqObjectName);
        String requestObjPrefix = sObjType.getDescribe().getKeyPrefix();
        List<sObject> recToUpdate = new List<sObject>();
        String decodedStr = EncodingUtil.urlDecode(response, 'UTF-8');
        decodedStr = decodedStr.substring(1, decodedStr.length()-1);
        List<RfaWrapper.RfaRestResponse> responses = (List<RfaWrapper.RfaRestResponse>)JSON.deserialize(decodedStr, List<RfaWrapper.RfaRestResponse>.Class);
        prepareIdMap(responses);
        for(RfaWrapper.RfaRestResponse res: responses) {
            string idToUpdate = mapExternalIdToId.containsKey(res.recordID) ? mapExternalIdToId.get(res.recordID) : res.recordID; 
            system.debug(res);
            if(res.status.equalsIgnoreCase('success')) {
                if(res.type.equalsIgnoreCase(resObjectName)) {
                    recToUpdate.add(new S1_Response__c(id = idToUpdate, push_updates__c = false, status__c = 'Sent'));
                }else if(res.type.equalsIgnoreCase(reqObjectName)) {
                    recToUpdate.add(new S1_Request__c(id = idToUpdate, push_updates__c = false));
                    //for MI make both the Divisional and the S1 request as false
                    if(sourceDivision.equalsIgnoreCase('mi') && idToUpdate != res.recordId && String.valueOf(res.recordId).startsWith(requestObjPrefix)) {
                        recToUpdate.add(new S1_Request__c(id = res.recordID, push_updates__c = false));
                    }
                }
            }
        }
        update recToUpdate;
    }

    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Method to creat a map of externalIdToId this map is used to identify records for update
    *   @param: List of Rest responsed from Hub
    */
    public void prepareIdMap(List<RfaWrapper.RfaRestResponse> listRes) {
        set<id> externalIdsToQuery = new Set<Id>();
        for(RfaWrapper.RfaRestResponse res: listRes) {
            externalIdsToQuery.add(res.recordID);
        }
        for(S1_request__c req : [SELECT id, external_id__c FROM S1_Request__c WHERE external_id__c IN: externalIdsToQuery]) {
            mapExternalIdToId.put(req.external_id__c,req.id);
        }
        for(S1_response__c res : [SELECT id, external_id__c FROM S1_Response__c WHERE external_id__c IN: externalIdsToQuery]) {
            mapExternalIdToId.put(res.external_id__c,res.id);
        }
        system.debug(mapExternalIdToId);
    }

    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Method to create body for HTTP request to the hub org, this method also URL encodes the request body
    */
    public string createRequestBody() {
        List<sObject> listRecordsToPush = new List<sObject>();
        string reqBody;
        
        string queryStr = generateQueryString();        
        listRecordsToPush = database.query(queryStr);
        reqBody = EncodingUtil.urlEncode(JSON.serialize(listRecordsToPush),'UTF-8');
        return reqBody;
    }
    
    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: generate the query sting based on fields and object names specified in the custom settings
    */
    public string generateQueryString() {
        string childQueryStr = ', (SELECT '+ resFields + ' FROM '+ resRelationName +' WHERE '+ recFilter +')';
        string queryStr = 'SELECT '+ reqFields + childQueryStr + ' FROM '+ reqObjectName +' WHERE '+ recFilter +' order by Status__c desc';
        system.debug('Generated Query: '+queryStr);
        return queryStr;
    }
    
    /*  @author: Akash Punera
    *   @date: 25 Oct 2022
    *   @description: Method to make callout to the Hub org with encoded Request body
    *   @param: Rest Webservice Method to call, Request body for the webservice method
    */
    public string makeCallout(string serviceMethod, string reqBody) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:RFAHubConnect/services/apexrest/rfa/'+serviceMethod);
        req.setMethod('PUT');
        req.setHeader('Content-Type', 'application/json');
        req.setBody('{"reqBody" : "'+reqBody+'","sourceDivision" : "'+ sourceDivision+'" }');
        req.setTimeout(120000);
        Http http = new Http();
        HTTPResponse res = http.send(req);
        system.debug(res);
        return res.getBody();
    }

    /*  @author: Akash Punera
    *   @date: 29 Nov 2022
    *   @description: Method to queue push updates in a async call
    *   @param: Rest Callout response
    */
    public void execute(QueueableContext context) {
        pushUpdatesToHub();
    }
}