objects/SetApexLoggerEvent__e.object
<CustomObject>
    <description>Platform Event to Captures Details about Apex Exception which will be saved to Apex Logger Object.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Class Name on which Exception Occurred.</description>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Error Message from Apex  Exception.</description>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <description>Type of Apex Exception.</description>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <description>Method Name on which Exception Occured.</description>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>Logged In User&apos;s Id.</description>
        <label>User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SetApexLoggerEvent</label>
    <pluralLabel>SetApexLoggerEvents</pluralLabel>
</CustomObject>

classes/TestSetApexLoggerEventMethods.cls
//-----------------------------
// @author: Sathish Edla
// @date: 30 Mar 2022
// @description: SFDC-5375 Extend the trigger framework to handle platform events.
//-----------------------------
@isTest
private class TestSetApexLoggerEventMethods {
    @isTest static void SetApexLoggerEventMethods() {
        // Create a test event instance
        SetApexLoggerEvent__e objPlatformEvent = new SetApexLoggerEvent__e(ClassName__c = 'TestClass',
                                                                           ErrorMessage__c = 'Test Error', 
                                                                           ExceptionType__c = 'Apex', 
                                                                           MethodName__c = 'Test Method', 
                                                                           UserId__c = system.UserInfo.getUserId());
        Test.startTest();
        // Publish test event
        Database.SaveResult sr = EventBus.publish(objPlatformEvent);
        Test.stopTest();
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
    }
}